### PR TITLE
[CMAKE][ARM] USE_SSE option to govern USE_SSE in mshadow and -msse2 compil…

### PR DESCRIPTION
**Pull request by larroy**
…er flags

Updated mshadow.

## Description ##
This fixes Cmake build on ARM. (NO SSE  support nor X86 specific includes like emmintrin.h)

### CODE REVIEW

**Comment by cjolivier01** [comment]
Just curious what the use-case is for not wanting sse

**Comment by cjolivier01** [comment]
Doesn’t the SUPPORT_SSE test fail for platform which doesn’t support it?

**Comment by larroy** [comment]
non intel processors. Mshadow fails to compile since it includes a specific i386 header when sse is enabled.

No point in checking if you have it disabled. Just for completeness, since we have to expose the flag anyways.

**Comment by larroy** [comment]
https://github.com/dmlc/mshadow/pull/302

**Comment by cjolivier01** [comment]
Still not sure I understand -- currently it has an automatic detection system via checking for compiler support for that platform.  Why are we also adding a manual switch?  Is there a use-case where the compiler would pass the check-for-sse-support test but we wouldn't want ot use SSE anyway?

**Comment by cjolivier01** [comment]
Also, what about visual C++? /arch:SSE flag?  Is this currently supported? Will that flag disable it?

**Comment by larroy** [comment]
Wheres the visual C++ flag set?

**Comment by larroy** [comment]
I added the switch for consistency. I think it would be better to change this sse to -march=native eventually. Do you propose using SUPPORT_MSSE2 in ARM instead? the previous PR is already merged, and depends on USE_SSE flag.

**Comment by larroy** [comment]
Can you be more specific in what's your alternative proposal?

**Comment by cjolivier01** [comment]
I just think it doesn't make logical sense. If @piiswrong likes it, then I am fine, but why t bothers me is:
1) if SSE is supported, there's no reason not to use it, right? Why would anyone set USE_SSE to off?
2) SUPPORTS_SSE check is automatic. Why expose to the user/developer?   
3) The check will still occur, so USE_SSE doesn't seem to actually say whether SSE will be used. Settin gthe flag is superfluous, and per #1, you'd never turn it off manually anyway
4) Other PR can be changed. Why can;t it check the compiler flag in mshadow so that it doesn't require mshadow consumers to know that they must set this flag?

**Comment by larroy** [comment]
Ok, you convinced me. I will close this PR and fix mshadow to use SUPPORTS_SSE. I think it's better not to expose this additional flag as you say. Thanks for your review.

**Pull request closed without merging**
