### PR TITLE
Revert #15842 and #15894. These PRs should not modify CI timeouts.

### PR DESCRIPTION
**Pull request by larroy**
## Description ##

These PRs introduced an unrelated increase of the CI time limit. This should be in a separate PR and discussed with the community and CI maintainers before.

@haojin2 Please reintroduce your PRs without unrelated changes to the CI infrastructure and tag @marcoabreu and me on changes to CI.

Thanks.

### CODE REVIEW

**Comment by haojin2** [comment]
Please let me know why #15842 also has to be reverted, seems like it has nothing to do with CI?

**Comment by larroy** [comment]
I couldn't revert just one, as the other builds on top and creates a conflict while reverting. Feel free to revert yourself and close this PR if you so prefer.

**Comment by larroy** [comment]
Is not really a duplicate as the PR you linked has an empty patch.

**Comment by haojin2** [comment]
I'll revert the CI time limit in a separate PR myself, closing this one now.

**Pull request closed without merging**
