### PR TITLE
Add NaiveEngine tests in CI

### PR DESCRIPTION
**Pull request by xinyu-intel**
## Description ##
NaiveEngine Test for #15089.
@pengzhao-intel @TaoLv @ZhennanQin @juliusshufan 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
@szha @eric-haibin-lin

**Comment by piyushghai** [comment]
Thanks for your contributions @xinyu-intel . 
I agree with Marco, if we want to run NaiveEngine tests in CI, nightly might be the more appropriate place for them as the normal unit test suite runs on every PR and thus speed is of essence. 

@mxnet-label-bot Add [CI]

**Comment by pengzhao-intel** [comment]
@marcoabreu I heard some people are using the naive engine for the better performance but the naive engine can't work very well. I think at least we need to add 1 or 2 tests on CI for the naive engine. 

Let's use this PR to fix the bugs in the naive engine first and then see how much time from threaded and naive engine :)

**Comment by Roshrini** [comment]
@xinyu-intel Thanks for working on this. I agree with Marco that naive engine is slower. So, its better to have these as nightly tests. But how much extra time will these tests add to our CI pipeline? If it's not too much, maybe its worthwhile to have them on CI.
Could you please add approx time which these tests will take on CI?

**Comment by roywei** [comment]
gentle ping for update on this PR

**Comment by pengzhao-intel** [comment]
Closing this PR. We're not urgent to enable naive engine test. 
Let's wait if someone requests this in the future.

**Pull request closed without merging**
