### PR TITLE
Make output of multi input hybrid block unique

### PR DESCRIPTION
**Pull request by sandeep-krishnamurthy**
## Description ##
* fixes issue - https://github.com/apache/incubator-mxnet/issues/12795
* Problem: If we have multiple inputs passed to the same block, then output symbol will have same name leading to conflicts. 
* Solution: append input symbol name to the block prefix, making output names to be unique per input symbol.

Example code of having 2 inputs to same block. The same Dense block is applied twice (2 inputs). Without this change, both a and b will have same name.

```python
class MyBlock(mx.gluon.HybridBlock):
    def __init__(self):
        super().__init__()
        with self.name_scope():
            self.model = mx.gluon.nn.Dense(units=5)

    def hybrid_forward(self, F, x, y):
        a = self.model(x)
        b = self.model(y)
        return a + b
```
Before:
```json
{
      "op": "FullyConnected", 
      "name": "myblock0_dense0_fwd", 
      "attrs": {
        "flatten": "True", 
        "no_bias": "False", 
        "num_hidden": "5"
      }, 
      "inputs": [[0, 0, 0], [1, 0, 0], [2, 0, 0]]
    }, 
    {
      "op": "null", 
      "name": "data1", 
      "inputs": []
    }, 
    {
      "op": "FullyConnected", 
      "name": "myblock0_dense0_fwd", 
      "attrs": {
        "flatten": "True", 
        "no_bias": "False", 
        "num_hidden": "5"
      }, 
      "inputs": [[4, 0, 0], [1, 0, 0], [2, 0, 0]]
    },
```
After
```json
{
      "op": "FullyConnected", 
      "name": "myblock0_dense0_data0_fwd", 
      "attrs": {
        "flatten": "True", 
        "no_bias": "False", 
        "num_hidden": "5"
      }, 
      "inputs": [[0, 0, 0], [1, 0, 0], [2, 0, 0]]
    }, 
    {
      "op": "null", 
      "name": "data1", 
      "inputs": []
    }, 
    {
      "op": "FullyConnected", 
      "name": "myblock0_dense0_data1_fwd", 
      "attrs": {
        "flatten": "True", 
        "no_bias": "False", 
        "num_hidden": "5"
      }, 
      "inputs": [[4, 0, 0], [1, 0, 0], [2, 0, 0]]
    },
```
Created this PR for initial feedback.
@zhreshold @safrooze @szha

### CODE REVIEW

**Comment by piyushghai** [comment]
Will this also fix #12783 ?

**Comment by sandeep-krishnamurthy** [comment]
> Will this also fix #12783 ?

No. That requires separate fix using F.broadcast_* operations like Sheng and lostella are working on other PR.

**Comment by zhreshold** [comment]
LGTM, but a small concern is if this affect the save/load of existing models

**Comment by Roshrini** [comment]
@sandeep-krishnamurthy Thanks for making this change. Can you please fix build?

**Comment by safrooze** [comment]
Change the code above to
```
class MyBlock(mx.gluon.HybridBlock):
    def __init__(self):
        super().__init__()
        with self.name_scope():
            self.model = mx.gluon.nn.Dense(units=5)

    def hybrid_forward(self, F, x, y):
        return self.model(self.model(x))
```
and you get these symbol names:
```
data0
myblock0_dense0_weight
myblock0_dense0_bias
myblock0_dense0_data0_fwd
myblock0_dense0_myblock0_dense0_data0_fwd_fwd
myblock0_dense0_myblock0_dense0_myblock0_dense0_data0_fwd_fwd_fwd
```
Something doesn't sit right with these names.

**Comment by roywei** [comment]
@sandeep-krishnamurthy ping, please try to rebase on latest master and see if CI pass.

**Comment by roywei** [comment]
@sandeep-krishnamurthy could you take a look at gluon rnn unit tests failing?

**Comment by sandeep-krishnamurthy** [comment]
This fix is wrong as pointed by sina. Closing for now as I try to work on the fix.

**Pull request closed without merging**
