### PR TITLE
Update packages and tests in the straight dope nightly

### PR DESCRIPTION
**Pull request by vishaalkapoor**
## Description ##
This PR enables two tutorial tests that were previously running too long. Both of those notebooks have since been updated in the Straight Dope repository to run faster. This addresses https://github.com/apache/incubator-mxnet/issues/12345.
This PR also updates a missing python dependency in the tutorial runner and adds a check so that future breakages will trigger an error: Addresses  https://github.com/apache/incubator-mxnet/issues/12743)

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented:

### CODE REVIEW

**Comment by ThomasDelteil** [comment]
LGTM

**Comment by vrakesh** [comment]
mxnet-label-bot [pr-awaiting-merge]

**Comment by vishaalkapoor** [comment]
> mxnet-label-bot [pr-awaiting-merge]
@vrakesh  thanks! adding the at sign: @mxnet-label-bot [pr-awaiting-merge]

**Comment by vishaalkapoor** [comment]
> mxnet-label-bot [pr-awaiting-merge]
@vrakesh  thanks! adding the at sign: 
@mxnet-label-bot [pr-awaiting-merge]

**Comment by vishaalkapoor** [comment]
Thanks for reviews and merge.

**Pull request merged**
