### PR TITLE
Fix CD

### PR DESCRIPTION
**Pull request by leezu**
- Fix NCCL versions in Cuda 10 docker containers.
- Fix missing dependency specification in dynamic CD pipeline
- Fix use of cpu image for gpu builds in static CD pipeline
- Fix gcc7 not on PATH in dynamic CD pipeline build step

### CODE REVIEW

**Comment by marcoabreu** [comment]
How is this tested?

**Comment by leezu** [comment]
The parts that can be tested locally are tested locally. Other parts are untested.

**Comment by leezu** [comment]
@mxnet-bot run ci [centos-cpu, unix-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
