### PR TITLE
 [v1.7.x] backport Invoke mkldnn and cudnn BatchNorm when axis != 1 to v1.7.x

### PR DESCRIPTION
**Pull request by stu1130**
Backport [Improvement] Invoke mkldnn and cudnn BatchNorm when axis != 1 v1.7x
The PR could be part of 1.7.1 release.

### CODE REVIEW

**Comment by wkcn** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by stu1130** [comment]
@wkcn could you take a look at the nan test failure?

**Comment by stu1130** [comment]
My bad I saw you fixed it Great work

**Comment by wkcn** [comment]
HI @stu1130 , the flaky test is `test_symbol.test_load_000800`.

`test_symbol.test_load_000800` initializes the weights of the model randomly, and the output's values are abnormally large, which leads to a abnormal output when invoking MKLDNN.

In the latest version of MXNet, the test `test_symbol.test_load_000800` has been removed in other PR.

**Comment by stu1130** [comment]
@wkcn thanks for the explanation. Let me retrigger the ci again. 
@mxnet-bot run ci [unix-cpu]

**Comment by wkcn** [comment]
Hi @stu1130 , the unittest test_symbol.test_load_000800 should be removed.
Meanwhile the test case of test_numpy_op.test_npx_batch_norm should be updated.
https://github.com/apache/incubator-mxnet/pull/18688

**Comment by stu1130** [comment]
> Hi @stu1130 , the unittest test_symbol.test_load_000800 should be removed.
> Meanwhile the test case of test_numpy_op.test_npx_batch_norm should be updated.
> #18688
> 
> I do not have the permission to update this PR.
Could you check again? I enable `Allow edits and access to secrets by maintainers`
If that doesn't work out, you can create another cherry-pick PR. I can drop this.

**Comment by wkcn** [comment]
Hi @stu1130 ,  I could not push the commit.
```bash
➜  incubator-mxnet git:(a273dc903) ✗ git push stu1130 stu1130/v1.7.x 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:stu1130/incubator-mxnet
 ! [remote rejected]     stu1130/v1.7.x -> stu1130/v1.7.x (permission denied)
error: failed to push some refs to 'github.com:stu1130/incubator-mxnet'
```

**Comment by stu1130** [comment]
Thanks @wkcn I will ping my colleague to merge it

**Comment by pengzhao-intel** [comment]
Merging now.

**Comment by pengzhao-intel** [comment]
@bgawrych could you take a review for this change, especially for MKLDNN BN

**Comment by bgawrych** [comment]
@pengzhao-intel LGTM, all tests are executed by MKLDNN primitive

**Comment by stu1130** [comment]
@ciyongch if we need to rework on 1.7 source code for addressing license issue, could we include this commit? If it would block 1.7 release or affect the process, I am ok to make it release on 1.7.1 or 1.8

**Comment by ciyongch** [comment]
Hi @stu1130 , currently, 1.7.0rc1 vote on dev@ was completed, and I didn't see any hard requirement to rework/updated the 1.7.0rc1 code base, the release process was hold on (vote on general@) to address some legal issues like (IP clearance of mshadow and some branding/trademark issue in external/3rd party usage). So I would suggest to include this in the next release, what do you think?

**Comment by stu1130** [comment]
@ciyongch alright, I think we can do it on next release.

**Pull request merged**
