### PR TITLE
Fix windows flakiness

### PR DESCRIPTION
**Pull request by reminisce**
## Description ##
Reverts PR Numpy det and slogdet operators https://github.com/apache/incubator-mxnet/pull/15861 which causes flakiness on windows platforms.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by DickJC123** [comment]
Thanks for this effort to get the CI passing again!  Looks promising!  Sorry to see the unix-cpu pipeline had a network issue and will need a retrigger.

**Comment by junrushao1994** [comment]
Curious why this could cause flakiness. Could you kindly provide some information? Many thanks!

**Comment by reminisce** [comment]
@junrushao1994 I'm puzzled by the flakiness too. Need to dive deep later to figure out the root cause. It's not obvious from the code displayed here.

**Comment by nickguletskii** [comment]
Possibly related: https://github.com/apache/incubator-mxnet/issues/15975

The test for `mx.symbol.slogdet` is currently disabled.

**Pull request merged**
