### PR TITLE
Add Java API docs generation

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
This PR splits out the Java API from the Scala API docs.

## Preview

From CI:
Java API docs: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13071/8/api/java/docs/index.html#org.apache.mxnet.javaapi.package

Scala API docs: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13071/8/api/scala/docs/index.html#org.apache.mxnet.package

If we upgraded Scala they'd look like this:
Java API docs: http://34.201.8.176/versions/javadocs/api/java/docs/org/apache/mxnet/javaapi/index.html
Scala API docs: http://34.201.8.176/versions/javadocs/api/scala/docs/org/apache/mxnet/index.html

Note that they look better because I upgraded Scala on my dev server. AFAIK we're not doing that for production... yet. I added an 'exit 0' to the copy command to avoid failing with newer versions of scala. This fixes https://github.com/apache/incubator-mxnet/issues/10858 as a workaround.

### CODE REVIEW

**Comment by ddavydenko** [comment]
Even though URLs are different - they both seems to render javadoc documentation for Java API. I think Scala URL should render existing Scala API documentation but exclude Java API from it.

**Comment by aaronmarkham** [comment]
@ddavydenko Thanks for the check. I updated the preview urls for Scala. It doesn't seem to have the javaapi in it... in the index or search...

**Comment by ddavydenko** [comment]
Yup, looks good now. And yes, I don't see Java API mixed in with Scala API in either docs, which is desired behavior.

**Comment by ankkhedia** [comment]
@aaronmarkham Thanks for your contribution!
@mxnet-label-bot [pr-work-in-progress, java]

**Comment by aaronmarkham** [comment]
When https://github.com/apache/incubator-mxnet/pull/13081 gets merged we can try running this through CI again.

**Comment by ankkhedia** [comment]
@aaronmarkham #13081 has been merged now.

**Comment by aaronmarkham** [comment]
Preview: http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13071/5/api/java/docs/index.html#org.apache.mxnet.javaapi.package

**Comment by aaronmarkham** [comment]
@lanking520 @zachgk - please review

**Comment by aaronmarkham** [comment]
@mxnet-label-bot remove [pr-work-in-progress]
@zachgk ok, we'll address that in another PR since this change is fine and I don't think this should go through CI again just for that.

**Comment by aaronmarkham** [comment]
@mxnet-label-bot add [Doc]

**Pull request merged**
