### PR TITLE
Add two bit compression operator

### PR DESCRIPTION
**Pull request by aksnzhy**
This is the implementation of two-bit compression.

Usage:

```
> import mxnet as mx
>
> grad = mx.nd.array([-6, -2, 3, 1, 10, 5, -3, 2, -8, 0])
> residual = mx.nd.array([-3, 1, -1, 5, -2, 2, 3, -7, -2, -100])
> neg_threshold = mx.nd.array([-4.0])
> pos_threshold = mx.nd.array([4.0])
> out = mx.contrib.nd.quantize_2bit(grad, residual, neg_threshold, pos_threshold)
> mx.contrib.nd.dequantize_2bit(out, grad)
>
> out
[ -4.00000000e+00   4.00000000e+00   7.40468810e-39]
<NDArray 3 @cpu(0)>
>
> residual
[ -5.  -1.   2.   2.   4.   3.   0.  -1.  -6. -96.]
<NDArray 10 @cpu(0)>
>
> grad
[-4.  0.  0.  4.  4.  4.  0. -4. -4. -4.]
<NDArray 10 @cpu(0)>
```

### CODE REVIEW

**Comment by piiswrong** [comment]
Is the output actually compressed? Looks like it's still float?

**Comment by aksnzhy** [comment]
It is actually compressed. The float data is just a hold, in which 16 float  will be compressed into one float data

**Comment by aksnzhy** [comment]
For now, this method can only support to compress the float data.

**Comment by piiswrong** [comment]
We may want to consider adding a data type like int2

**Comment by piiswrong** [comment]
How is this going to be used by kvstore and ps-lite? How does it recognize a compressed array?

**Comment by aksnzhy** [comment]
For multi-GPU, we can directly invoke quantize_bit() before copying data to other gpu, and invoke dequantize_2bit() when receiving the data block. But in distributed training  I'm not sure if we need to hack the ps-lite code, to invoke a dequantize function before updating the model ?

**Comment by piiswrong** [comment]
How are gradients from different gpus aggregated?

**Comment by aksnzhy** [comment]
Example:

Compress:

`>>> arr = np.random.randint(-10,10,(5, 16))
>>> array = mx.nd.array(arr)
>>> array

[[  5.  -1.  -7.   0.  -7.   9.  -4.   8.  -3.  -7.  -4.   9.  -7.   6.  1.   1.]
 [  2.   1.  -5.  -3.   5.   3.   0.   1.   6.   9.  -1.  -3.   7.  -6. 5.   4.]
 [  5.  -7.   0.   2.   0.   9.   6.   5.   8.   8.  -7.  -2.  -1.   3. 3.  -8.]
 [  1.   2.  -3.  -9.  -9.   2.   0.   0.  -5.   3.   6.  -8.   7. -10. 2.   4.]
 [ -5.   2.   2.   1.   6.  -6. -10.  -9.  -4.  -4.  -3. -10.  -7.   1. -5.   0.]]
<NDArray 5x16 @cpu(0)>
>>> min = mx.nd.array([-5.0])
>>> max = mx.nd.array([5.0])
>>> out = mx.contrib.ndarray.quantize_2bit(array, min, max)
>>> out

[ -5.00000000e+00   5.00000000e+00   4.21925537e+19  -4.14882934e-24
   6.03051597e-38  -3.96895673e-29   5.18332031e+02]
<NDArray 7 @cpu(0)>`

Decompress:

`>>> mx.contrib.ndarray.dequantize_2bit(out, array)
>>> array

[[ 5.  0. -5.  0. -5.  5.  0.  5.  0. -5.  0.  5. -5.  5.  0.  0.]
 [ 0.  0. -5.  0.  5.  0.  0.  0.  5.  5.  0.  0.  5. -5.  5.  0.]
 [ 5. -5.  0.  0.  0.  5.  5.  5.  5.  5. -5.  0.  0.  0.  0. -5.]
 [ 0.  0.  0. -5. -5.  0.  0.  0. -5.  0.  5. -5.  5. -5.  0.  0.]
 [-5.  0.  0.  0.  5. -5. -5. -5.  0.  0.  0. -5. -5.  0. -5.  0.]]
<NDArray 5x16 @cpu(0)>`

**Comment by aksnzhy** [comment]
Before aggregate the gradient, we first need to decompress them into a new array with same size of the original gradient array, but the value  new array is changed, only consist of two threshold.

**Comment by piiswrong** [comment]
quantize also need to output the residual right?

**Comment by aksnzhy** [comment]
Yes, before compressing we need to add the residual. I think it will be better to let user do this task. This operator is just a very low-level operator. We can build higher level python wrapper for that.

**Comment by aksnzhy** [comment]
The residual is stored in each local device

**Comment by piiswrong** [comment]
You can calculate compression and residual in one operator to make it faster

**Comment by aksnzhy** [comment]
I will do that .

**Comment by aksnzhy** [comment]
@piiswrong I add the calculation of residual in this operator and add test case in test file.

**Comment by piiswrong** [comment]
Where are the tests? I don't see any

**Comment by aksnzhy** [comment]
I removed the test file just to verify if it can be built successfully. I will add them later.

**Comment by aksnzhy** [comment]
@piiswrong  I'm considering add a new feature in gluon to make user use the low-bit compression more easily.

**Comment by aksnzhy** [comment]
Update the Usage:

>>> array = mx.nd.array([-6, -2, 3, 1, 10, 5, -3, 2, -8, 0])
>>> residual = mx.nd.array([-3, 1, -1, 5, -2, 2, 3, -7, -2, -100])
>>> min = mx.nd.array([-4.0])
>>> max = mx.nd.array([4.0])
>>> out = mx.contrib.ndarray.create_2bit(array)
>>> mx.contrib.ndarray.quantize_2bit(array, residual, min, max, out)

[ -4.00000000e+00   4.00000000e+00   7.40468810e-39]
<NDArray 3 @cpu(0)>

>>> mx.contrib.ndarray.dequantize_2bit(out, array)
>>> array

[-4.  0.  0.  4.  4.  4.  0. -4. -4. -4.]
<NDArray 10 @cpu(0)>

**Pull request closed without merging**
