### PR TITLE
[1.x] Backport #17772

### PR DESCRIPTION
**Pull request by mseth10**
## Description ##
Backport #17772 to branch v1.x

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mseth10** [comment]
@samskalicky @leezu please review

**Comment by mseth10** [comment]
@ciyongch @PatricZhao please help merge! thanks!

**Comment by mseth10** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by ciyongch** [comment]
@pengzhao-intel Please take a look and help merge.
@mseth10 can you backport this PR to v1.7.x release branch as well (as the code rebase was already done)? Thanks.

**Comment by ciyongch** [comment]
@mseth10 please check the failed CI, and backport this PR to v1.7.x branch as well. :)

**Comment by mseth10** [comment]
Hi @ciyongch , the CI got re-triggered automatically on this PR. It was passing earlier.

I have created another PR for v1.7.x #18122

**Comment by ciyongch** [comment]
Thanks @mseth10 , I will track that PR before code freeze.

**Comment by mseth10** [comment]
@leezu @pengzhao-intel @ciyongch please help merge this PR

**Comment by ciyongch** [comment]
@TaoLv @pengzhao-intel please help to merge this PR, which is already merged in both master and v1.7.x.

**Comment by rondogency** [comment]
@szha @leezu @eric-haibin-lin Can you help to merge this PR?

**Pull request merged**
