### PR TITLE
Revert "Disable OpenMP offloading support for 3rdparty/openmp"

### PR DESCRIPTION
**Pull request by haojin2**
Reverts apache/incubator-mxnet#17098, trying to alleviate the current CI issue.

### CODE REVIEW

**Comment by haojin2** [comment]
Trying to solve the current CI issue by reverting #17160 since #17133 passed all its post-merge check as per https://github.com/apache/incubator-mxnet/commits/master. Let's see if this PR passes CI smoothly.

**Comment by leezu** [comment]
Closing as the failure is due to Numpy 1.18 release and unrelated to #17098

**Comment by TaoLv** [comment]
> Closing as the failure is due to Numpy 1.18 release and unrelated to #17098

I thought ci is dockernized and pined to a certain version of each dependency. Why a new release of numpy can crash mxnet ci? Is it upgraded explicitly by PR?

**Comment by leezu** [comment]
Numpy is not pinned. We may want to pin it. CI just installs the latest stable numpy version.

**Pull request closed without merging**
