### PR TITLE
set_lower_bound(1) so that stride is not zero

### LINKED ISSUE #18942: Floating point exception in mxnet.ndarray.Correlation
## Description
(A clear and concise description of what the bug is.)
`mxnet.ndarray.Correlation` has floating point exception when given `stride2=0`. Please see the provided code for example.
### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=10` before running your script.)
>Floating point exception (core dumped)
## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
```python
import mxnet
import numpy as np
data1 = mxnet.nd.array(np.random.rand(1,1,1,1))
data2 = mxnet.nd.array(np.random.rand(1,1,1,1))
mxnet.ndarray.Correlation(data1=data1, data2=data2, stride2=0)
```
### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. run the provided code in python interpreter or as a script
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```
Got 404 when trying to get the script.

Some environment information:

* OS: ubuntu 18.04
* Python: 3.7.6
* pip: 20.0.2
* numpy: 1.18.5
* mxnet: 1.6.0

### LINKED ISSUE #18994: Documentation bug: mxnet.test_utils.check_consistency  Inconsistent parameter
## Description
This is a documentation bug. There is an inconsistency of parameter name between the function signature and **Parameter** section. 

It is `use_uniform ` in the signature, but `use_unifrom ` in the Parameter section.

Link to the document: https://mxnet.apache.org/versions/1.6/api/python/docs/api/mxnet/test_utils/index.html#mxnet.test_utils.check_consistency

image

### Error Message
None
## To Reproduce
None
## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```
OS: ubuntu 18.04
Python: 3.7.6
pip: 20.0.2
numpy: 1.18.5
mxnet: 1.6.0

### PR DESCRIPTION
**Pull request by ekdnam**
in issue: https://github.com/apache/incubator-mxnet/issues/18942, an error was occurring where strides became zero. to solve the issue, the lower bounds of stride1 and stride2 have been set to 1.

in issue: https://github.com/apache/incubator-mxnet/issues/18994, a typo was mentioned. that has also been cleared.

fix #18942 
fix #18994 

## Description ##
(Brief description on what this PR is about)
When the correlation function is called on two arrays when the stride is zero, it results in a floating point exception as a division by zero is carried out. Thus, the lower bounds of stride1 and stride2 have been set to 1.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ekdnam** [comment]
What changes can I make to the source code so that the `unix-cpu` job succeeds?

**Comment by szha** [comment]
@ekdnam I think the test failed due to a network issue that's unrelated to the change. You can use the command as described by the mxnet ci bot in this comment: https://github.com/apache/incubator-mxnet/pull/18997#issuecomment-679052386

**Comment by szha** [comment]
Thanks for the fix, @ekdnam! Could you add a test here and assert that proper error will happen when the parameter is out of bound? https://github.com/apache/incubator-mxnet/blob/3c4ac19daa3e645d918692b864ea19640f7e0314/tests/python/unittest/test_operator.py#L3200-L3233

**Comment by ekdnam** [comment]
Thanks for triggering the test! I will add the required unit tests.

**Comment by ekdnam** [comment]
What should be the value of the strides when they will go out of bounds?

**Comment by ekdnam** [comment]
@szha can you give someone guidelines on the tests? I am sorta new to testing

**Comment by szha** [comment]
@ekdnam yes happy to help. As documented [here](https://mxnet.apache.org/community/code_guide), mxnet uses pytest as the python testing tool for development. Here's pytest's guide on [how to write tests for expected exception](https://docs.pytest.org/en/stable/assert.html#assertions-about-expected-exceptions). With that, you can write the statements to check whether an exception (and in this case the expected error should be `MXNetError`) is raised when input argument doesn't meet the lower bound.

To test this out locally, you need to:
- follow the [build from source guide](https://mxnet.apache.org/get_started/build_from_source) (we use cmake for this, configs are in [/config](https://github.com/apache/incubator-mxnet/tree/master/config), choose the one that's right for your platform) and build the change locally.
- cd into `/python` folder, and you can use `python setup.py develop` to link your local copy to your python site packages, which will enable your python to find the mxnet package you built.
- if you haven't yet, install pytest. you may also choose to install the development and testing dependencies that are exactly the same as mxnet CI. you can achieve this with
```
python -m pip install -r https://raw.githubusercontent.com/apache/incubator-mxnet/master/ci/docker/install/requirement
```
- finally, run the test and make sure it passes. the complete test suite of mxnet is quite large so instead you may choose to run a specific test. see pytest's guide on [selecting the test to run](https://docs.pytest.org/en/stable/usage.html#specifying-tests-selecting-tests)

**Comment by ekdnam** [comment]
Thanks a lot for such an in-depth answer!!

**Comment by ekdnam** [comment]
@szha I am currently having some issues while building mxnet from source. It may take some more time to resolve them. So I can't test myself the changes made. Hope the changes made to `test_operator.py` are enough. Thanks

**Comment by ekdnam** [comment]
@szha thanks for making the changes! :))

**Comment by ekdnam** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by ekdnam** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by szha** [comment]
@ekdnam thanks for the fix!

**Comment by ekdnam** [comment]
@szha sure! Thank you for the help!

**Pull request merged**
