### PR TITLE
Change CUB submodule to track Nvidia CUB project.

### PR DESCRIPTION
**Pull request by frankfliu**
## Description ##

Current cub submodule is pointing to DLMC's cub repo, the repo doesn't have customization of nvidia's cub project. The historic reason to use DLMC's cub is:
1. check out of nvidia's cub project takes long time
2. There was force push in nvidia's cub project broke mxnet submodule link.

Since both above issue has been resolved on Nvidia side, we should move back to Nvidia's cub project to reduce upgrade/merge effort.

The proposal has been discussed on: https://lists.apache.org/thread.html/6c10ab4746ac15b08fb5ac7281abdfdfcd5b534fd3838200941cd2ca@%3Cdev.mxnet.apache.org%3E. 

Directly change submodule URL will impact every developer.
"git submodule update" won't work, developer has to use
"git submodule sync" first.

To avoid impact every developer, remove CUB and add a new
"nvidia_cub" to workaround this issue.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [X] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-work-in-progress]

**Comment by kalyc** [comment]
@frankfliu please take a look at the failed CI build and update PR accordingly

**Comment by stu1130** [comment]
@mxnet-label-bot update [pr-awaiting-review]

**Comment by lupesko** [comment]
@frankfliu did you do some sanity perf tests on GPU? we probably should for operators using cub.
Pulling in @anirudh2290 @apeforest and @nswamy to review.

**Comment by KellenSunderland** [comment]
@frankfliu Thanks for the contribution.  Your description indicates why we're using the name '3rdparty/nvidia_cub' but not why we're switching submodules, which in my opinion is the more important piece of information.  Can you give some details around why we're switching back to the NVIDIA repo?

If I remember correctly the reason we switched away from using the NVIDIA cub repo was because we had a bunch of force pushes and history re-writes in that repo that were causing us issues.  Looking at the current repo it seems like it's in really good shape now.  They describe their release process clearly and are making use of release branches.  Given they're using release branching, I'd suggest we track a specific stable branch using git 1.8 (and higher) submodule branch feature.  I hope this will help to protect us against future force-pushes.

**Comment by KellenSunderland** [comment]
I've looked into this a little further and I suspect that tracking a branch is still not going to get us any protection against our submodules force pushing.  I've opened a question on StackOverflow to see if anyone knows the details around what happens in this case: https://stackoverflow.com/questions/53438716/does-tracking-a-branch-with-a-submodule-protect-you-against-force-pushes

**Comment by KellenSunderland** [comment]
Looks like adding a branch ref to the submodule isn't necessary / won't alleviate the problem I have in mind.  Pending questions for this PR are only
* What problems does it solve / feature does it provide?
* What testing has been done?

**Comment by KellenSunderland** [comment]
@mxnet-label-bot update [pr-awaiting-response]

**Comment by lanking520** [comment]
@lebeg Any idea how to conduct a test on this? It seemed to be an improvement on the performance.

**Comment by sandeep-krishnamurthy** [comment]
@frankfliu - Can you please provide next steps here? and few open questions from Kellen.

**Comment by KellenSunderland** [comment]
This PR is looking good to me, and I don't want to be a blocker.  Consider me approving modulo short testing description.  I think my "What problems does it solve / feature does it provide" has been answered well in the edited PR description.

**Comment by anirudhacharya** [comment]
@frankfliu ping for update :)

**Comment by stu1130** [comment]
@mxnet-label-bot update [pr-awaiting-response]
@frankfliu could you address the LICENSE conflict? Thanks

**Comment by frankfliu** [comment]
@mxnet-label-bot add [pr-awaiting-merge] remove [pr-awaiting-response]

**Comment by frankfliu** [comment]
@mxnet-label-bot remove [pr-awaiting-response]

**Comment by ankkhedia** [comment]
@KellenSunderland Could you please review/merge this PR after the latest changes?

**Comment by vandanavk** [comment]
@frankfliu could you have a look at the incomplete CI? may be it needs to be re-triggered

**Comment by karan6181** [comment]
@frankfliu Could you please look at the incomplete CI? It seems no updates from last couple of weeks. Can you please look into it? Thanks!

**Comment by wkcn** [comment]
The PR has been merged. Thank you!

**Pull request merged**
