### PR TITLE
Implement some ONNX exports, needed for SSD

### PR DESCRIPTION
**Pull request by RuRo**
## Description ##
This is a WIP pull request for implementing exports for some `ONNX` operators, which are needed to successfully export the `SSD` model from `gluocv`. The only 2 operators, which are not yet implemented are `_contrib_box_decode`, which can be sidestepped by using `SSD(minimal_opset=True)` and `_contrib_box_nms`, which could be potentially implemented with the `NonMaxSuppression` `ONNX` operator, but this is a big enough undertaking to be its own separate PR.

This PR assumes that #18054 is merged (ruro/onnx_version_bump), since it uses some `ONNX` operators only available in `v1.5.0`. (The first commit is a squashed version of that PR and will be dropped after it gets merged into master)

If you actually want to try exporting `SSD`, you should also merge #17827 (QueensGambit/onnx_export_slice_fix or ruro/onnx_export_slice_fix).

## Changes ##
- `eagerly check onnx conversion availability in verbose mode`
  The `export_model` method now warns about *all* nodes, that don't have a registered conversion **before** trying to export the model, if `verbose=True`. This is a simple quality of life change, which helps potential contributors to estimate, how many layers are missing until a model can be exported.
- implement `_arange` op
  (doesn't support the `repeat` attribute for now)
- implement `ones_like` and `zeros_like` ops
- implement `_lesser_scalar`, `_greater_scalar` and `_equal_scalar` ops
  also fixes the issue, where the `scalar_op_helper` would fail, if the input is a non-1D initializer
- implement `slice_like` op
  (doesn't support the implicit `axes` variation right now)
- implement `where` op

### CODE REVIEW

**Comment by RuRo** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by VisionZQ** [comment]
Hi, 
Thanks for you kindness.
We have converted the mxnet to onnx 1.5,  and the 'slice_like' is work.
But, When I from onnx convert to TensorRT6.0, the program crash. can you give me any suggestion? 
`While parsing node number 205 [Gather -> "yolov30__mulscalar0__shape__gathered"]:
ERROR: /home/jakin/songzq/onnx-tensorrt/onnx2trt_utils.hpp:412 In function convert_axis:
[8] Assertion failed: axis >= 0 && axis < nbDims
`
Thanks a lot.

**Comment by RuRo** [comment]
@VisionZQ This PR currently has WIP status (it's not ready) and it's main purpose was to implement the needed ops to convert `SSD` models from `mxnet` to `ONNX`. There's been a lot of breakage recently with `onnx2mx`, so some further work may be required. I am not sure, I can help you with converting `yolov3`. I don't currently have the free time to even finish this PR.

I would recommend, that you open an issue, describing, which layers needed for `yolov3` don't have a conversion in `mxnet 1.6.0` and which conversion functions are currently missing in `mxnet 2.0.0`, but I wouldn't get your hopes up, that somebody will implement the conversions for you. Afaik, most `mxnet` contributors are currently **very** busy with `mxnet 2` API changes.

**Comment by chinakook** [comment]
It's a great job!

**Comment by Aktcob** [comment]
Really good job！ 

When I convert yolov3 model in gluoncv to ONNX, I'm faced with the same problem.

**Pull request closed without merging**
