### PR TITLE
[MXNET-70] Update tensorboard.py

### PR DESCRIPTION
**Pull request by arundasan91**
Adding `step` to Tensorboard. Currently only horizontal axis setting of `Relative` or `Wall` are available without any info about the epoch.

## Description ##
Current Tensorboard integration with `dmlc/tensorboard` allows good visualizations for MXNET training/eval procedure. However, visualizations are limited to horizontal axis setting of `Relative` or `Wall` and do not include any information about current epoch OR relation between the plots and epoch. 

After spending some time on the code at `dmlc/tensorboard`, I found that the [add_scalar](https://github.com/dmlc/tensorboard/blob/master/python/tensorboard/writer.py#L264) function have an argument named `global_step` to log `step` or `epoch` information. I added a simple fix to the [tensorboard.py](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/contrib/tensorboard.py) in MXNET to address this lost information. Kindly take a look at the figures below:

Tensorboard plots BEFORE FIX:
1. Horizontal axis: `step`
screen shot 2018-03-04 at 8 27 12 pm
2. Horizontal axis: `Relative`
screen shot 2018-03-04 at 8 27 22 pm

Tensorboard plot AFTER FIX:
Horizontal axis: `step`
screen shot 2018-03-04 at 8 35 39 pm

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
None: No major changes.

## Comments ##
I am getting discontinuous tensorboard plots while plotting training graph on Tensorboard w/ my own dataset as you can see in the figure. I am pretty sure it has to do with the data and not the fix.

### CODE REVIEW

**Comment by piiswrong** [comment]
@zihaolucky

**Comment by CodingCat** [comment]
Hi, the community has passed to vote about associating the code changes with JIRA (https://lists.apache.org/thread.html/ab22cf0e35f1bce2c3bf3bec2bc5b85a9583a3fe7fd56ba1bbade55f@%3Cdev.mxnet.apache.org%3E)

We have updated the guidelines for contributors in https://cwiki.apache.org/confluence/display/MXNET/Development+Process, please ensure that you have created a JIRA at https://issues.apache.org/jira/projects/MXNET/issues/ to describe your work in this pull request and include the JIRA title in your PR as [MXNET-xxxx] your title where MXNET-xxxx is the JIRA id

Thanks!

**Comment by arundasan91** [comment]
@CodingCat , Thanks for the comments. I've updated the title.

**Comment by arundasan91** [comment]
All thanks to you @zihaolucky !

**Pull request merged**
