### PR TITLE
[BUGFIX] update ci/build_windows.py MKLROOT and readme

### PR DESCRIPTION
**Pull request by sfraczek**
## Description ##
My colleague pointed out to me that I missed occurrences of MKL_ROOT in other files.
Related Issue link https://github.com/apache/incubator-mxnet/issues/19151

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] Code is well-documented

### CODE REVIEW

**Review by leezu — APPROVED** [review]

**Comment by leezu** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by sfraczek** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by sfraczek** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
