### PR TITLE
update issue template

### PR DESCRIPTION
**Pull request by szha**

### CODE REVIEW

**Comment by szha** [comment]
I included the automatic diagnosis script in the issue template (thanks to @zhreshold).
@thirdwing @javelinjs are changes needed for R and scala?

**Comment by javelinjs** [comment]
For Scala package, please also list
- Java version (`java -version`)
- Maven version (`mvn -version`)
- Scala runtime (if it is used, `scala -version`)

**Comment by szha** [comment]
Updated.

**Comment by thirdwing** [comment]
@szha `sessionInfo()` should be enough.

**Comment by szha** [comment]
Thanks. cc @apache/mxnet-committers

**Pull request merged**
