### PR TITLE
Fix symbolic example for rand_zipfian function

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
`mx.sym.contrib.rand_zipfian` function example fixed
It contained NDArray specific example for a Symbolic API

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by KellenSunderland** [comment]
LGTM but I can't tell what's fixed.  Were the values reported in the docs wrong?

**Comment by ChaiBapchya** [comment]
The example before had NDArray. I replaced it with a corresponding Symbolic example

**Comment by stu1130** [comment]
@mxnet-label-bot update [pr-awaiting-merge]
@KellenSunderland I think what he fixed is just doc. The symbol API should use smybol for demonstration rather than NDArray. And we won't get intermediate result with Symbol.

**Pull request closed without merging**
