### PR TITLE
[DOC] Fix a typo in dataset.py

### PR DESCRIPTION
**Pull request by leeesangwon**
## Description ##
Fix a typo in dataset.py `elemtn -> element`

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Fix a typo in dataset.py

### CODE REVIEW

**Review by wkcn — APPROVED** [review]
LGTM. Thank you!

**Comment by szha** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by wkcn** [comment]
The PR has been merged. Thank you!

**Pull request merged**
