### PR TITLE
Fix example/module folder and remove duplicate examples

### PR DESCRIPTION
**Pull request by yuruofeifei**
## Description ##
This PR is to fix example/module folder's scripts.
(1) fix python_loss.py script
(2) lstm_bucketing.py already exists in rnn folder, remove from module folder
(3) train_cifar10.py already exists in image-classification folder, remove from module folder

### Essentials ###
- [:white_check_mark: ] Passed code style checking (`make lint`)
- [:white_check_mark: ] Changes are complete (i.e. I finished coding on this PR)
- [N/A ] All changes have test coverage
- [N/A ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [:white_check_mark: ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by piiswrong** [comment]
could you rebase?

**Comment by yuruofeifei** [comment]
Rebased...

**Comment by yuruofeifei** [comment]
Added readme file and rebased.

**Comment by yuruofeifei** [comment]
ping for review

**Comment by yuruofeifei** [comment]
@piiswrong @aaronmarkham can you please review?
Remove some redundant tutorial files.

**Pull request merged**
