### PR TITLE
[WIP] Gluon object detection

### PR DESCRIPTION
**Pull request by zhreshold**
## Description ##
Pure gluon object detection baselines.
A standalone c++ operators PR was submitted as #8603 

### Targeted object algorithms

By stage
- Single stage: SSD,YOLO, RetinaNet
- Two stage: Faster-RCNN, RFCN, MaskRCNN

By data shape
- Immutable data_shape: SSD, YOLO
- Mutable data_shape: Faster-RCNN, RFCN, RetinaNet, MaskRCNN

Status:
`trainer/train_xxx.py`

- [x] SSD
- [x] YOLO v2(experimental)
- [ ] Faster RCNN
- [ ] MaskRCNN
- [ ] RetinaNet
- [ ] RFCN

### Dataset
`dataset/xxx.py`

- [x] Pascal VOC
- [x] COCO
- [ ] Imagenet
- [ ] Custom dataset Wrapper

### Shared network blocks(Basic, Hybrid)
`block/xxx.py`

- [ ] (not complete)Anchor generator(CustomOp/function): SSD,YOLO, Faster-RCNN, RFCN, RetinaNet: `block/anchor.py`
- [x] Feature extractor/expander: `block/feature.py`
- [x] Box predictor(Conv2D, Dense, Complex): predict box class/location: `block/predictor.py`
- [ ] (not complete) Target generator(CustomOp/function calling nd internally): SSD,YOLO, Faster-RCNN, RFCN, RetinaNet: `block/target.py`
- [x] (Modified, can be merged to gluon.loss once finished) Loss(gluon.loss): L1, L2, SmoothL1, CE loss, Focal loss: `block/loss.py`
- [x] Bounding box encoder/decoder: `block/coder.py`
- [x] Matcher wrapper: `block/matcher.py`
- [x] Sampler for select/discard matched results: `block/sampler.py`
- [x] registry for blocks `block/registry.py`

### Perf critical components
`src/operator/contrib/xxx`

- [x]  IOU: overlap between anchors and labels. 
- [x] (may not complete) Sampler: generating positive/negative/other samples
- [x] Bipartite matching
- [x] Argmax matching
- [x] OHEM sampler: Hard negative mining(only dynamic block provided now, need to convert to c++)
- [x] Non-maximum-suppression
- [ ] More

### Iterator
`dataset/`

- [x] Normal iterator(python iterator): SSD/YOLO iterator
- [ ] Mutable iterator(wrapper for c++ iter?): batch_size=1, take arbitrary data shape. Usually don't need augmentation.
- [ ] Mini-batch iterator: for rcnn variations.

### Others
- [ ] Object detection Model Zoo
- [ ] Dataset downloader/loader
- [ ] Configuration loader/saver(yaml)

# Note
Feel free to add/comment/contribute, as I am still working on it, any help is appreciated.
Sorry about the missing docs, the APIs will change frequently in this period.

### CODE REVIEW

**Comment by Jing-Luo** [comment]
@zhreshold Sorry for troubling but I noticed in [target.py](https://github.com/zhreshold/mxnet/blob/gluon-det-pr/example/object-detection/block/target.py#L30) there is a line:
`ious = nd.transpose(nd.contrib.box_iou(anchors, gt_boxes), (1, 0, 2))`

But when I run train.py, here is the error message:

> module 'mxnet.ndarray.contrib' has no attribute 'box_iou'

And I truly could not see this attribute from the mxnet repository. So do you implement it by yourself so that I could run the code successfully?

**Comment by ZiyueHuang** [comment]
@Jing-Luo This operator is in https://github.com/apache/incubator-mxnet/pull/8603, not merged yet.

**Comment by Jing-Luo** [comment]
@ZiyueHuang Thanks!!! 👍

**Comment by piiswrong** [comment]
any updates?

**Comment by piiswrong** [comment]
Moved to separate repo. Closing

**Comment by indhub** [comment]
Which separate repo was this moved to?

**Pull request closed without merging**
