### PR TITLE
fix type mismatch bugs

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
## Description ##

Fix type mismatch when building mxnet1.3.1 on windows, please check this [post ](https://qtandopencv.blogspot.com/2019/03/build-mxnet-131-on-windows.html)for more details.

### CODE REVIEW

**Comment by stereomatchingkiss** [comment]
> And I think you could merge the PR into the master branch, thank you!

There are two problems stopping me to do that

1. Since mxnet 1.4.0, mxnet got even more bugs when you try to compile it on windows, I can't specify those bugs are caused by this pull request or not because of the new bugs exist in master branch(please check #14203)
2. Could you tell me why jenkins complain?

Thanks

**Comment by stereomatchingkiss** [comment]
> Can you explain what were the errors you found and why this is the right fix.

Build it by vc2015 then you will know what am I talking about.

**Comment by anirudh2290** [comment]
@stereomatchingkiss there is currently a ci check for windows build and the latest commit on 1.3.x has a windows build test passing: http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-14469/runs/2/nodes/113/steps/567/log/?start=0  which runs on visual studio 2015. Would you be able to check how this build steps are different from what you are doing ?

**Comment by stereomatchingkiss** [comment]
> Would you be able to check how this build steps are different from what you are doing ?

Not sure, maybe we are using different version of vc2015, mine is "C/C++ Optimizing Compiler Version 19.00.24234.1 for x86"

I am using openBLAS build my myself, not the openBLAS you used, that one has incompatible abi with the compiler I am using.

**Comment by apeforest** [comment]
> Build it by vc2015 then you will know what am I talking about.

If our Windows CI could not catch the error you encountered, we cannot verify this fix either.

**Comment by apeforest** [comment]
> then you will see "error C2672: 'std::min': no matching overloaded function found".

This error is not unique to Windows VC2015. Linux should report the same error.

**Comment by apeforest** [comment]
It seems the mismatch you reported has been fixed in master. Please rebase the latest master and verify. Thanks.

**Comment by stereomatchingkiss** [comment]
> It seems the mismatch you reported has been fixed in master. Please rebase the latest master and verify.

Since it is fixed, please close this issue, I kept it only for my blog.

ps : Really hope mxnet could become much easier to compile on windows in the future. [v1.5 still got lots of issues](https://zhuanlan.zhihu.com/p/58918998)

**Comment by abhinavs95** [comment]
@stereomatchingkiss Could you please close this PR if your issue is already fixed? Thanks!

**Comment by stereomatchingkiss** [comment]
> 
> 
> @stereomatchingkiss Could you please close this PR if your issue is already fixed? Thanks!

No problem

**Pull request closed without merging**
