### PR TITLE
[MXNET-1359] Adds a multiclass-MCC metric derived from Pearson

### PR DESCRIPTION
**Pull request by tlby**
## Description ##
A multiclass metric equivalent to `mxnet.metric.MCC` can be derived from `mxnet.metric.PearsonCorrelation` with the addition of an `.argmax()` on preds.  I'd like to document this use case of Pearson and provide it behind a metric named "PCC" to simplify extending examples from F1 and MCC to multiclass predictions.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by tlby** [comment]
hmm, actually `numpy.corrcoef()` may not be working how I need for the multiclass class.  This work is based on the [formulas here](http://rk.kvl.dk/introduction/index.html) which relate Matthews to Pearson, but I may need to calculate the covariance myself.

And of course this PR should have some tests added.  I'll work through both these issues.

**Comment by pinaraws** [comment]
Thank you for your contribution @tlby!
Some tests are failing, please have a look.

@mxnet-label-bot [pr-work-in-progress]

**Comment by tlby** [comment]
```diff
diff --git a/python/mxnet/metric.py b/python/mxnet/metric.py
index 2a33cf4d9..6de76cc64 100644
--- a/python/mxnet/metric.py
+++ b/python/mxnet/metric.py
@@ -1576,9 +1576,8 @@ class PCC(EvalMetric):
             n = max(pred.max(), label.max())
             if n >= self.k:
                 self._grow(n + 1 - self.k)
-            bcm = numpy.zeros((self.k, self.k))
-            for i, j in zip(pred, label):
-                bcm[i, j] += 1
+            ident = numpy.identity(self.k)
+            bcm = numpy.tensordot(ident[label], ident[pred].T, axes=(0,1))
             self.lcm += bcm
             self.gcm += bcm
```
seems more efficient for constructing the confusion matrix, but benchmarks worse.  I'm new to NumPy though, anyone see a better approach?

**Comment by tlby** [comment]
I think this PR is ready now, sorry for posting the PR prematurely. I am happy with test coverage at this point, and happy with the metric scaling out to a large number of classes. The `.update()` method duration doubles when there are about 500 classes.

**Comment by pinaraws** [comment]
@mxnet-label-bot update[pr-awaiting-review]

**Comment by tlby** [comment]
```diff
diff --git a/python/mxnet/metric.py b/python/mxnet/metric.py
index 2a33cf4d9..7bc090a0a 100644
--- a/python/mxnet/metric.py
+++ b/python/mxnet/metric.py
@@ -1576,9 +1576,8 @@ class PCC(EvalMetric):
             n = max(pred.max(), label.max())
             if n >= self.k:
                 self._grow(n + 1 - self.k)
-            bcm = numpy.zeros((self.k, self.k))
-            for i, j in zip(pred, label):
-                bcm[i, j] += 1
+            k = self.k
+            bcm = numpy.bincount(label * k + pred, minlength=k*k).reshape((k, k))
             self.lcm += bcm
             self.gcm += bcm
```
is a bit faster when k is small, but scales to larger k poorly.

**Comment by tlby** [comment]
It turned out building the confusion matrix wasn't the hotspot in `.update()` anyway.  Once I cleaned up the actual hotspots this code became comparable in speed to binary mcc.

**Comment by piyushghai** [comment]
@szha Can you help with the review of this PR ?

**Comment by szha** [comment]
@tlby thanks for the contribution. Great job.

**Pull request merged**
