### PR TITLE
[COMMUNITY] add Chaitanya Bapat as a new committer

### PR DESCRIPTION
**Pull request by szha**
## Description ##
Please join me in welcoming Chaitanya Bapat @ChaiBapchya) as a new committer of Apache MXNet!
Chai has been of great help in the community development and the stability of our
CI infrastructure. He also contributed to the OpPerf feature in MXNet. Recently, Chai worked on an infrastructure feature that automatically labels the pull requests
to reflect their status: https://github.com/apache/incubator-mxnet-ci/pull/27. It simplifies how
committers can find PRs that pass CI and need review, and will help mxnet receive code review
contribution more easily.

Congratulations to @ChaiBapchya!

PRs: https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AChaiBapchya+
Issues he participated: https://github.com/apache/incubator-mxnet/issues?utf8=%E2%9C%93&q=is%3Aissue+involves%3AChaiBapchya
PR reviews: https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3AChaiBapchya

### Changes ###
- [x] add Chaitanya Bapat as a new committer

### CODE REVIEW

**Comment by szha** [comment]
Congratulations Chaitanya!!!!

**Comment by szha** [comment]
Congrats Chai! Great work!

Sheng Zha <notifications@github.com.invalid> 于2020年11月10日周二 上午9:26写道：

**Comment by szha** [comment]
Congratulations Chai! Well deserved. Cheers!!

- Karan

**Comment by szha** [comment]
Congrats and welcome!

On Tue, Nov 10, 2020 at 1:27 PM Sheng Zha <notifications@github.com.invalid>
wrote:

> Congratulations Chai! Well deserved. Cheers!!
>
> - Karan
>
> On Tue, Nov 10, 2020 at 10:25 AM Zhu Zhaoqi <zhaoqizhu96@gmail.com> wrote:
>
> > Congrats Chai! Great work!
> >
> > Sheng Zha <notifications@github.com.invalid> 于2020年11月10日周二 上午9:26写道：
> >
> > > Congratulations Chaitanya!!!!
> > >
> > > On Tue, Nov 10, 2020 at 8:34 AM Sheng Zha <notifications@github.com
> > > .invalid>
> > > wrote:
> > >
> > > > ## Description ##
> > > > Please join me in welcoming Chaitanya Bapat @ChaiBapchya) as a new
> > > > committer of Apache MXNet!
> > > > Chai has been of great help in the community development and the
> > > stability
> > > > of our
> > > > CI infrastructure. He also contributed to the OpPerf feature in
> MXNet.
> > > > Recently, Chai worked on an infrastructure feature that automatically
> > > > labels the pull requests
> > > > to reflect their status:
> > > > https://github.com/apache/incubator-mxnet-ci/pull/27. It simplifies
> > how
> > > > committers can find PRs that pass CI and need review, and will help
> > mxnet
> > > > receive code review
> > > > contribution more easily.
> > > >
> > > > Congratulations to @ChaiBapchya!
> > > >
> > > > PRs:
> > > >
> > >
> >
> https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&amp;q=is%3Apr+author%3AChaiBapchya+
> > > > Issues he participated:
> > > >
> > >
> >
> https://github.com/apache/incubator-mxnet/issues?utf8=%E2%9C%93&amp;q=is%3Aissue+involves%3AChaiBapchya
> > > > PR reviews:
> > > >
> > >
> >
> https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&amp;q=is%3Apr+reviewed-by%3AChaiBapchya
> > > >
> > > > ### Changes ###
> > > > - [x] add Chaitanya Bapat as a new committer
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > >   https://github.com/apache/incubator-mxnet/pull/19512
> > > >
> > > > -- Commit Summary --
> > > >
> > > >   * Update CONTRIBUTORS.md
> > > >
> > > > -- File Changes --
> > > >
> > > >     M CONTRIBUTORS.md (2)
> > > >
> > > > -- Patch Links --
> > > >
> > > > https://github.com/apache/incubator-mxnet/pull/19512.patch
> > > > https://github.com/apache/incubator-mxnet/pull/19512.diff
> > > >
> > > > --
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/apache/incubator-mxnet/pull/19512
> > > >
> > >
> > >
> > > --
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub:
> > >
> >
> https://github.com/apache/incubator-mxnet/pull/19512#issuecomment-724849483
> >
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/apache/incubator-mxnet/pull/19512#issuecomment-724883230



-- 
Yuan Tang
https://terrytangyuan.github.io/about/
<https://terrytangyuan.github.io/about/>

**Comment by szha** [comment]
Congrats Chai! Well deserved!

**Comment by apeforest** [comment]
Congratulations, Chai! Great work.

Lin

**Review by terrytangyuan — APPROVED** [review]

**Comment by ChaiBapchya** [comment]
Thanks a lot everyone 🙏🏽

**Pull request merged**
