### PR TITLE
[1.x] Backport of #19078

### PR DESCRIPTION
**Pull request by r3stl355**
## Description ##
Backport of https://github.com/apache/incubator-mxnet/pull/19078 to v1.x (solves https://github.com/apache/incubator-mxnet/issues/18886)

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### CODE REVIEW

**Comment by szha** [comment]
@r3stl355 thanks for backporting! remember to add back the part for text processing as it's still available in contrib on 1.x

**Comment by r3stl355** [comment]
@szha thanks, yes, I realised that at some point after submitting the PR. I still need to figure out how to run all the tests locally, doing `nosetests tests/python/unittest/` segfaults and crashes Python on my Mac

**Comment by szha** [comment]
> @szha thanks, yes, I realised that at some point after submitting the PR. I still need to figure out how to run all the tests locally, doing `nosetests tests/python/unittest/` segfaults and crashes Python on my Mac

This seems to be a common request. I recently shared some of it in https://github.com/apache/incubator-mxnet/pull/18997#issuecomment-683217771, though I think we likely need to expand a bit more and add in https://github.com/apache/incubator-mxnet/blob/master/docs/static_site/src/pages/community/code_guide.md#testing

**Comment by r3stl355** [comment]
Great, I'll try to make it run on my machine and update the docs

**Comment by r3stl355** [comment]
@szha - do you want to merge this before the 1.8 release?

**Comment by leezu** [comment]
You can suggest the inclusion in https://github.com/apache/incubator-mxnet/issues/18800

**Pull request merged**
