### PR TITLE
R Metrics

### PR DESCRIPTION
**Pull request by jeremiedb**
- Port metrics calculation to NDArrays and let the calculations on the devices (rather than after copying on cpu). Performance is similar for general cases, but significant for Perplexity on large dictionnary. 
- Fix top_k bug. 
- Add logloss and accurancy for logistic regression.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Hi, could you provide your benchmark values for this change?

**Comment by jeremiedb** [comment]
Benchmark performed on AWS K80.

Going to NDArray has no significant speed modification on MNIST:

Original: 
```
> source("../NLP/model_rnn_old.R")
> source("../NLP/metrics_old.R")
> tic("model training")
> model <- mx.model.buckets(symbol = convnet,
+                           train.data = train.iter,
+                           eval.data = eval.iter,
+                           num.round = 5, ctx = ctx, verbose = TRUE,
+                           metric = mx.metric.accuracy,
+                           optimizer = optimizer,  initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = epoch.end.callback)
Start training with 1 devices
Batch [25] Speed: 17512.6201754097 samples/sec Train-accuracy=0.378203125
[1] Train-accuracy=0.500131967905405
[1] Validation-accuracy=0.8005859375
Batch [25] Speed: 19089.099867642 samples/sec Train-accuracy=0.84328125
[2] Train-accuracy=0.855600717905405
[2] Validation-accuracy=0.8712890625
Batch [25] Speed: 19066.4264974117 samples/sec Train-accuracy=0.8941015625
[3] Train-accuracy=0.898701435810811
[3] Validation-accuracy=0.8982421875
Batch [25] Speed: 19019.28342411 samples/sec Train-accuracy=0.9138671875
[4] Train-accuracy=0.916807432432432
[4] Validation-accuracy=0.9126953125
Batch [25] Speed: 19028.9402301531 samples/sec Train-accuracy=0.924453125
[5] Train-accuracy=0.926889780405405
[5] Validation-accuracy=0.9203125
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 11.227 sec elapsed
```

With NDArray:

```
> source("../NLP/model_rnn_old.R")
> source("../NLP/metrics.R")
> tic("model training")
> model <- mx.model.buckets(symbol = convnet,
+                           train.data = train.iter,
+                           eval.data = eval.iter,
+                           num.round = 5, ctx = ctx, verbose = TRUE,
+                           metric = mx.metric.accuracy,
+                           optimizer = optimizer,  initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = epoch.end.callback)
Start training with 1 devices
Batch [25] Speed: 19127.6006208524 samples/sec Train-accuracy=0.360625
[1] Train-accuracy=0.479386613175676
[1] Validation-accuracy=0.784765625
Batch [25] Speed: 19106.7837383884 samples/sec Train-accuracy=0.82609375
[2] Train-accuracy=0.839817356418919
[2] Validation-accuracy=0.874609375
Batch [25] Speed: 19091.8084094211 samples/sec Train-accuracy=0.8843359375
[3] Train-accuracy=0.889490076013513
[3] Validation-accuracy=0.901953125
Batch [25] Speed: 19122.3887433588 samples/sec Train-accuracy=0.9060546875
[4] Train-accuracy=0.909311655405405
[4] Validation-accuracy=0.91171875
Batch [25] Speed: 19023.3337071591 samples/sec Train-accuracy=0.9182421875
[5] Train-accuracy=0.920792863175676
[5] Validation-accuracy=0.9203125
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 11.113 sec elapsed
```

However, the on device (GPU) calculation on device brings some overhead in this case. Seems in the range of 2-5%. 

```
> source("../NLP/model_rnn.R")
> source("../NLP/metrics.R")
> tic("model training")
> model <- mx.model.buckets(symbol = convnet,
+                           train.data = train.iter,
+                           eval.data = eval.iter,
+                           num.round = 5, 
+                           ctx = ctx, 
+                           verbose = TRUE,
+                           metric = mx.metric.accuracy,
+                           optimizer = optimizer,  initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = epoch.end.callback)
Start training with 1 devices
Batch [25] Speed: 18690.2377642633 samples/sec Train-accuracy=0.4166796875
[1] Train-accuracy=0.517868454391892
[1] Validation-accuracy=0.7767578125
Batch [25] Speed: 18716.4802325446 samples/sec Train-accuracy=0.819609375
[2] Train-accuracy=0.833588471283784
[2] Validation-accuracy=0.8595703125
Batch [25] Speed: 18732.0356273382 samples/sec Train-accuracy=0.8775390625
[3] Train-accuracy=0.883155616554054
[3] Validation-accuracy=0.8888671875
Batch [25] Speed: 18680.6843297833 samples/sec Train-accuracy=0.900234375
[4] Train-accuracy=0.904244087837838
[4] Validation-accuracy=0.90546875
Batch [25] Speed: 18706.2253398244 samples/sec Train-accuracy=0.9145703125
[5] Train-accuracy=0.917361697635135
[5] Validation-accuracy=0.9189453125
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 11.262 sec elapsed
```

Differences are more dramatic on a translation task: 

Original: 
```
> source("model_rnn_old.R")
> source("metrics_old.R")
> tic("model training")
> model <- mx.model.buckets(symbol = decode,
+                           train.data = iter_train,
+                           eval.data = NULL,
+                           num.round = 1, ctx = ctx, verbose = TRUE,
+                           metric = mx.metric.Perplexity,
+                           optimizer = optimizer,  initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = NULL)
Start training with 1 devices
Batch [20] Speed: 215.456704571082 samples/sec Train-Perplexity=10599.8404743246
Batch [40] Speed: 207.486600740186 samples/sec Train-Perplexity=6673.25650384215
Batch [60] Speed: 210.566703784213 samples/sec Train-Perplexity=5481.96414418588
Batch [80] Speed: 205.564767054434 samples/sec Train-Perplexity=4922.55990169088
Batch [100] Speed: 207.716705645805 samples/sec Train-Perplexity=4639.57757078004
[1] Train-Perplexity=4622.90027048472
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 187.623 sec elapsed
```

NDArray metrics on cpu (~4 times faster):
```
> source("model_rnn_old.R")
> source("metrics.R")
> tic("model training")
> model <- mx.model.buckets(symbol = decode,
+                           train.data = iter_train, 
+                           eval.data = NULL,
+                           num.round = 1, ctx = ctx, verbose = TRUE,
+                           metric = mx.metric.Perplexity,
+                           optimizer = optimizer,  
+                           initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = NULL)
Start training with 1 devices
Batch [20] Speed: 836.457053325741 samples/sec Train-Perplexity=16897.5107666016
Batch [40] Speed: 866.499773437333 samples/sec Train-Perplexity=10473.8368347168
Batch [60] Speed: 863.315608505923 samples/sec Train-Perplexity=7621.48778483073
Batch [80] Speed: 870.988032823973 samples/sec Train-Perplexity=6163.53143768311
Batch [100] Speed: 868.541533143258 samples/sec Train-Perplexity=5321.95678344727
[1] Train-Perplexity=5286.70074160736
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 45.998 sec elapsed
```

NDArray metrics calculated on device (~8 times faster): 
```
> model <- mx.model.buckets(symbol = decode,
+                           train.data = iter_train, 
+                           eval.data = NULL,
+                           num.round = 1, ctx = ctx, verbose = TRUE,
+                           metric = mx.metric.Perplexity,
+                           optimizer = optimizer,  
+                           initializer = initializer,
+                           batch.end.callback = batch.end.callback,
+                           epoch.end.callback = NULL)
Start training with 1 devices
Batch [20] Speed: 1846.40915580585 samples/sec Train-Perplexity=10282.578125
Batch [40] Speed: 1687.93908208322 samples/sec Train-Perplexity=5992.89606018066
Batch [60] Speed: 1691.51875464203 samples/sec Train-Perplexity=4422.54621988932
Batch [80] Speed: 1693.66507496428 samples/sec Train-Perplexity=3635.94312591553
Batch [100] Speed: 1695.72445295657 samples/sec Train-Perplexity=3180.84664916992
[1] Train-Perplexity=3161.07460067296
> mx.model.save(model = model, prefix = "models/model_en_fr_conv_4", iteration = 0)
> toc()
model training: 23.355 sec elapsed
```

Note that computing Perplexity on NDArray cause some memory leak that is adressed through a garbage collection call in the training loop, though it's essential to get decent training speed. 

There may be a tradeoff for the general cases with 2-4% vs. the large speedup for peplexity. Maybe revert the `model.R` to cpu computation and let the `model.rnn.R` with on device computation?

**Comment by marcoabreu** [comment]
@piiswrong what do you think?

**Comment by jeremiedb** [comment]
Added a metric_cpu option defaulting to TRUE to have metrics computed on CPU, but allowing computation on GPU when needed. There's now no performance tradeoff. 

An option has been added to perdiodically calll gc() in model.rnn. There's clearly a memory leak (both with FeedforwardCreate and model.rnn) but I cannot see how to fix this at root.

**Comment by marcoabreu** [comment]
I'd like to refrain from calling gc() manually as much as possible. In my opinion it would be better if we really track down the root cause.

**Comment by CodingCat** [comment]
Hi, the community has passed to vote about associating the code changes with JIRA (https://lists.apache.org/thread.html/ab22cf0e35f1bce2c3bf3bec2bc5b85a9583a3fe7fd56ba1bbade55f@%3Cdev.mxnet.apache.org%3E)

We have updated the guidelines for contributors in https://cwiki.apache.org/confluence/display/MXNET/Development+Process, please ensure that you have created a JIRA at https://issues.apache.org/jira/projects/MXNET/issues/ to describe your work in this pull request and include the JIRA title in your PR as [MXNET-xxxx] your title where MXNET-xxxx is the JIRA id

Thanks!

**Comment by jeremiedb** [comment]
Sure, solving the root cause is definitely preferable. Help would however be welcomed to track the memory leak; I'm lacking resources to do so. 
Given there seems to be little dev effort on the R package right now, I thought it would still be preferable to have an easy option to circumvent the issue that can impair package usability, as patchy it may be.

**Comment by marcoabreu** [comment]
I understand. In that case I'm fine with merging as long as the problem is tracked somewhere.

**Pull request merged**
