### PR TITLE
Migrate from private jetpack files to public

### LINKED ISSUE #18637: [Nvidia][CI] Jetson toolchain files public acess
## Description
Currently, CI for Jetson builds uses aarch64 cross depedencies package based on Jetpack 4.3

However, it needs to be manually downloaded using SDK Manager tool and placed in a private S3 bucket because we don't have license to redistribute them.

Fix would be to make it publicly available under nvidia machine learning apt repository http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/

For reference
https://github.com/apache/incubator-mxnet/blob/master/ci/docker/Dockerfile.build.jetson#L61-L65

@leezu @ptrendx @tristonc

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
Fixes #18637 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

@leezu @ptrendx

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Once this is merged in master, I'll subsequently cherry-pick it into other branches which use private S3 buckets for Jetpack files

**Comment by ptrendx** [comment]
The error in the Jetson pipeline is due to what I believe is a bug in CMake 3.17.3 (https://gitlab.kitware.com/cmake/cmake/-/issues/20826), which results in not setting the host compiler for CUDA. Set the version of CMake to 3.17.1 or 3.17.2 (3.17.1 was the version in the previously cached docker container, which is why you did not see this failure earlier).

That said, please wait with merging this PR - those packages do not include cuDNN and TRT, which we would also like to have in order to enable proper cross compilation support for Jetson that includes every feature. I will be working with @tristonc to get those other packages too.

**Comment by leezu** [comment]
@ptrendx could you help get a reproducible example to cmake so that the bug can be fixed upstream?

**Comment by ptrendx** [comment]
@leezu I'm not a CMake expert unfortunately - the only thing I could give them is this Jetson build (you can take this Dockerfile, see that it does not produce `--ccbin` option for Ninja, and then install CMake 3.17.1 on top of it and redo cmake to see that this version does produce the correct option). I don't think this counts as minimal example :-(.

**Comment by ChaiBapchya** [comment]
> I will be working with @TristonC to get those other packages too.
@ptrendx any ETA on the same? thanks.

**Comment by ChaiBapchya** [comment]
Thanks @ptrendx @leezu 
I can confirm that pinning the cmake version resolves the issue: https://github.com/ChaiBapchya/incubator-mxnet/commit/18595b39418582697485b1eca55f83659bec3ed4

And running
```
ci/build.py --docker-registry mxnetci --platform jetson --docker-build-retries 3 --shm-size 500m /work/runtime_functions.sh build_jetson
```
Resolved the issue and it build perfectly.
Commented this on the Triston's cmake [upstream] issue : https://gitlab.kitware.com/cmake/cmake/-/issues/20826

**Comment by ChaiBapchya** [comment]
Jetson pipeline error should be resolved by https://github.com/apache/incubator-mxnet/pull/18713

**Comment by ChaiBapchya** [comment]
@mxnet-bot add [pr-awaiting-review]

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot  add [pr-awaiting-review]

**Pull request merged**
