### PR TITLE
review require() usages to add meaningful messages.

### PR DESCRIPTION
**Pull request by mdespriee**
## Description ##
The motivation of this PR is to add & improve error messages raised by failed requirements.
In relation to https://github.com/apache/incubator-mxnet/issues/12565.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)

### Changes ###
No feature change.

## Comment ##
Unfortunately, i'm not sure to really improve the error messages regarding shape inference. Real improvement would come from backend error messages. Any suggestions ?

### CODE REVIEW

**Comment by kalyc** [comment]
Thanks for your contribution @mdespriee 
@mxnet-label-bot[pr-work-in-progress]

**Comment by nswamy** [comment]
@mdespriee thanks a lot for taking the time to improve the messages. there are a few scalastyle errors, could you please fix them, test locally(at least the unit tests) and then push. I can merge the code later

**Comment by mdespriee** [comment]
Removing [WIP]. The failing test is probably a flaky test (clojure).

**Comment by lanking520** [comment]
@mdespriee please fix this line:
```
error file=/work/mxnet/scala-package/core/src/main/scala/org/apache/mxnet/Symbol.scala message=File line length exceeds 100 characters line=1099

```
You should be able to pass them afterwards

**Comment by andrewfayres** [comment]
Mostly just commenting so I can easily watch this but I really like this improvement!

**Comment by mdespriee** [comment]
@lanking520 fixed. Any existing JIRA to mention ?

**Pull request merged**
