### PR TITLE
Fix broken links for symbol and params

### PR DESCRIPTION
**Pull request by cloudhan**
http://data.dmlc.ml is inaccessible, use http://data.mxnet.io instead

## Description ##
Fix broken links in docs.

### Essentials ###
No code change involved.

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by vandanavk** [comment]
LGTM.

@cloudhan could you check the CI failure?

**Comment by cloudhan** [comment]
Only document is changed. So it shouldn't trigger a build failure.

**Comment by cloudhan** [comment]
wont bother with this PR

**Pull request closed without merging**
