### PR TITLE
Fix CI in master

### PR DESCRIPTION
**Pull request by josephevans**
Update minor versions of nvidia cuda containers to use that have the latest keys pre-installed, which prevents the error:

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
```

Also update TensorRT to 8.x, because the previous version we were building with is no longer available. 

@TristonC

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by TristonC** [comment]
@DickJC123

**Comment by bgawrych** [comment]
@josephevans @DickJC123 @TristonC Can we merge this fix? It blocks other changes

**Comment by bgawrych** [comment]
Link check can be fixed by removing all link occurences: https://crl.ucsd.edu/~elman/Papers/fsit.pdf
or by replacing it with e.g.: https://axon.cs.byu.edu/~martinez/classes/678/Papers/Elman_time.pdf
(Reference paper: Finding structure in time - Elman, 1988.)

**Comment by josephevans** [comment]
> Link check can be fixed by removing all link occurences: https://crl.ucsd.edu/~elman/Papers/fsit.pdf or by replacing it with e.g.: https://axon.cs.byu.edu/~martinez/classes/678/Papers/Elman_time.pdf (Reference paper: Finding structure in time - Elman, 1988.)

I can fix the broken links in another PR I have open: https://github.com/apache/incubator-mxnet/pull/21015

**Comment by TristonC** [comment]
LGTM, thanks!

**Pull request merged**
