### PR TITLE
[1.x] Add test case for oneDNN RNN

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
This PR enables test case which produces seg faults with oneDNN < 1.6.5
https://github.com/apache/incubator-mxnet/pull/19308
https://github.com/apache/incubator-mxnet/pull/19451

Problem should be fixed with: https://github.com/apache/incubator-mxnet/pull/19449

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by samskalicky** [comment]
Hi @bgawrych, the centos-cpu failure can be fixed by https://github.com/apache/incubator-mxnet/pull/19456/commits/655d81f987b45498204252e4762246999efc6c78

You can either pull it in yourself, or wait until after my PR adds this #19456

**Comment by samskalicky** [comment]
> Hi @bgawrych, the centos-cpu failure can be fixed by [655d81f](https://github.com/apache/incubator-mxnet/commit/655d81f987b45498204252e4762246999efc6c78)
> 
> You can either pull it in yourself, or wait until after my PR adds this #19456

should be fixed now from #19476 can you rebase/merge?

**Review by pengzhao-intel — APPROVED** [review]
LGTM and will merge after CI pass.

**Comment by bgawrych** [comment]
@szha @samskalicky @pengzhao-intel  This codecov/project job must be passed to merge?

**Pull request merged**
