### PR TITLE
MXNET-308 [Perl] added missing license

### PR DESCRIPTION
**Pull request by sergeykolychev**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by sergeykolychev** [comment]
@eric-haibin-lin @mbaijal @anirudh2290 
I've added missing license to four files from the list.
Other 9 are Changes, MANIFEST and META.yml (for 3 modules that comprise the perl-package) are autogenerated files that perl modules aggregator CPAN uses for indexing purposes and can't have comments in them.
Changes - list of changes to the module
MANIFEST - list of files in the module
META.yml - meta information about the module (version, external dependencies, etc).
I'd like to request kindly add these to the list of excepted files.

**Comment by mbaijal** [comment]
@sergeykolychev 
Sergey, Thanks for updating the licenses. 
you just need to add the names of the file to the .rat-excludes file here - https://github.com/apache/incubator-mxnet/blob/master/tests/nightly/apache_rat_license_check/.rat-excludes

However, this file does not accept full file paths for some reason and only the name of the file. Hence to avoid excluding all files with the same name, I had added the whole perl-package to this excluded list. You can handle this in any way you want. 

@anirudh2290 Do make sure RAT check passes after these changes are included!

**Comment by anirudh2290** [comment]
@mbaijal sounds like the only option we have right now is to add the names Changes, Manifest and META.yml to .rat-excludes and hope that we remember to check the licenses if the same named files are used elsewhere in MXNet (I checked that currently the file names are being used only inside perl-package).

**Comment by eric-haibin-lin** [comment]
Thank you @sergeykolychev !

**Pull request merged**
