### PR TITLE
[MXNET-1274] Add docstring comment about noise replication in SGLD optimizer and a test for SGLD optimizer

### PR DESCRIPTION
**Pull request by D-Roberts**
## Description ##
The SGLD optimizer adds Gaussian noise to the weights updates. A comment about the need to set seed to replicate this noise was added to SGLD optimizer docstring.
 A test is also added for the SGLD optimizer and the test passes. The test must use set seeds to be able to compare opt1 and opt2 and compare_optimizer method is updated to allow for this.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Add comment to SGLD optimizer docstring.
- [x] Add unit test for SGLD optimizer that passes with two different noise seeds.

### CODE REVIEW

**Comment by Roshrini** [comment]
@D-Roberts Thanks for the contribution.
@mxnet-label-bot Add [pr-awaiting-review, Optimizer]

**Comment by sandeep-krishnamurthy** [comment]
@D-Roberts - Thank you for your contributions.
Can use set seed in his program? Why to set seed in the optimizer?

**Comment by D-Roberts** [comment]
> @D-Roberts - Thank you for your contributions.
> Can use set seed in his program? Why to set seed in the optimizer?

@sandeep-krishnamurthy The optional seed allows for identical replication of the noise generated by normal() and added to the weight updates. For example, if a researcher wants to replicate exactly the weight updates path, that's impossible if new noise is added at each weight update. Likewise, in the test for the optimizer, for the test to pass the same noise must be added. Please let me know if this is clear.

**Comment by sandeep-krishnamurthy** [comment]
> > @D-Roberts - Thank you for your contributions.
> > Can use set seed in his program? Why to set seed in the optimizer?
> 
> @sandeep-krishnamurthy The optional seed allows for identical replication of the noise generated by normal() and added to the weight updates. For example, if a researcher wants to replicate exactly the weight updates path, that's impossible if new noise is added at each weight update. Likewise, in the test for the optimizer, for the test to pass the same noise must be added. Please let me know if this is clear.

Thanks, for the detailed explanation. I understand the motivation for this change. But, my question was - Why can't a user program seed(fixed_seed) why should it be inside the optimizer logic?

I am concerned that we are adding new parameters to optimizer API just for testing/reproducibility and may have unintended consequences for the user in regular model building experiments.

**Comment by D-Roberts** [comment]
> > > @D-Roberts - Thank you for your contributions.
> > > Can use set seed in his program? Why to set seed in the optimizer?
> > 
> > 
> > @sandeep-krishnamurthy The optional seed allows for identical replication of the noise generated by normal() and added to the weight updates. For example, if a researcher wants to replicate exactly the weight updates path, that's impossible if new noise is added at each weight update. Likewise, in the test for the optimizer, for the test to pass the same noise must be added. Please let me know if this is clear.
> 
> Thanks, for the detailed explanation. I understand the motivation for this change. But, my question was - Why can't a user program seed(fixed_seed) why should it be inside the optimizer logic?
> 
> I am concerned that we are adding new parameters to optimizer API just for testing/reproducibility and may have unintended consequences for the user in regular model building experiments.

@sandeep-krishnamurthy Thank you Sandeep, I understand your concern and I can see what you mean. How does this sound: leave the optional parameter out of the optimizer, include set seed separately in the test code, as well as add a comment in SGLD optimizer docstring about the need for a user program to set seed for norm noise reproducibility?

**Comment by sandeep-krishnamurthy** [comment]
> > > > @D-Roberts - Thank you for your contributions.
> > > > Can use set seed in his program? Why to set seed in the optimizer?
> > > 
> > > 
> > > @sandeep-krishnamurthy The optional seed allows for identical replication of the noise generated by normal() and added to the weight updates. For example, if a researcher wants to replicate exactly the weight updates path, that's impossible if new noise is added at each weight update. Likewise, in the test for the optimizer, for the test to pass the same noise must be added. Please let me know if this is clear.
> > 
> > 
> > Thanks, for the detailed explanation. I understand the motivation for this change. But, my question was - Why can't a user program seed(fixed_seed) why should it be inside the optimizer logic?
> > I am concerned that we are adding new parameters to optimizer API just for testing/reproducibility and may have unintended consequences for the user in regular model building experiments.
> 
> @sandeep-krishnamurthy Thank you Sandeep, I understand your concern and I can see what you mean. How does this sound: leave the optional parameter out of the optimizer, include set seed separately in the test code, as well as add a comment in SGLD optimizer docstring about the need for a user program to set seed for norm noise reproducibility?

Yes. This sounds good. If user wants reproducibility, he will explicitly seed in his program. And, in unit test we will seed, if reproducibility is required. Thank you!

**Comment by D-Roberts** [comment]
@sandeep-krishnamurthy Added one line comment to SGLD docstring and a test that passes. How does it look?

**Comment by D-Roberts** [comment]
I will open a separate pull request for only adding sgld test.

**Pull request closed without merging**
