### PR TITLE
Multiplatform docker based builds

### PR DESCRIPTION
**Pull request by larroy**
Set of docker files + tool to build MXNet for different architectures and collect the artifacts.

### CODE REVIEW

**Comment by piiswrong** [comment]
please add apache license header to docker/tool.py

**Comment by sergeykolychev** [comment]
This pull removes dockers for perl and R and I believe  will break tests for perl and R.

**Comment by larroy** [comment]
@sergeykolychev I think we should have a separate set of dockerfiles for running MxNet / building MxNet. I can refine the PR tomorrow.

**Comment by larroy** [comment]
@piiswrong ping

**Comment by larroy** [comment]
@nswamy @mbaijal

**Comment by piiswrong** [comment]
This is not how our jenkins setup works. Builds and tests are defined in jenkins. Dockerfiles only define the environment

**Comment by larroy** [comment]
The goal of these dockerfiles is not to replace CI but to create multi-arch binary artifacts. Also when you use the docker build with these kind of dockerfile you get the benefit of command caching. But I get your point with regards environment vs execution.

**Comment by piiswrong** [comment]
Then you can probably add these to a separate folder without removing existing code

**Comment by mbaijal** [comment]
@larroy The existing dockerfiles in the docker folder as well as the tool.sh script are being used to release mxnet docker images to dockerhub. I am in the process of automating this process and updating these scripts. 
Can you please not modify existing content in the docker folder and instead add a separate subfolder.

**Comment by larroy** [comment]
@mbaijal @piiswrong Done, separate folder.

**Comment by larroy** [comment]
skip ci

**Comment by larroy** [comment]
@marcoabreu @KellenSunderland

**Comment by larroy** [comment]
skip ci

**Comment by piiswrong** [comment]
Is this good to merge?

**Comment by larroy** [comment]
Yes please merge it, we would refine and improve with further PRs, but this is already useful & usable for us and the community. Thank you!

**Comment by larroy** [comment]
can we merge this and close?

**Comment by sergeykolychev** [comment]
@larroy when you'll be improving this please add Hash::Ordered after Function::Parameters for perl image ?
This is new dependency that was introduced on Oct 1

**Comment by themummy** [comment]
Has anyone successfully amalgamated mxnet for Android x86-64? I need to run mxnet on an Android Emulator on Jenkins.

**Pull request merged**
