### PR TITLE
OpenMP License Update v1.8x 

### PR DESCRIPTION
**Pull request by Zha0q1**
https://github.com/apache/incubator-mxnet/issues/19427

### CODE REVIEW

**Comment by Zha0q1** [comment]
@samskalicky @leezu Could you review thanks!

**Review by leezu — COMMENTED** [review]
You're attaching a bunch of licenses under the keyword "OpenMP", but it's not clear to what files the apply. We need to specify the licenses with respect to the files (subfolders) they apply to.
Sometimes, multiple licenses may apply to a particular code and we should state if the users can choose one of the or what their relation is

**Comment by Zha0q1** [comment]
> You're attaching a bunch of licenses under the keyword "OpenMP", but it's not clear to what files the apply. We need to specify the licenses with respect to the files (subfolders) they apply to.
> Sometimes, multiple licenses may apply to a particular code and we should state if the users can choose one of the or what their relation is

Those licenses are from the master License.txt in the root directory. There they do not specify to which submodules those license apply to. In fact there is no clear submodule by the way they structure the directories https://github.com/llvm-mirror/openmp/tree/b76842ed16984ae5edcbbc4b00a94fda20419431

**Comment by leezu** [comment]
You need to read the license file. It states:

> ==============================================================================
> The LLVM Project is under the Apache License v2.0 with LLVM Exceptions:
> ==============================================================================

as well as

> ==============================================================================
> Software from third parties included in the LLVM Project:
> ==============================================================================
> The LLVM Project contains third party software which is under different license
> terms. All such code will be identified clearly using at least one of two
> mechanisms:
> 1) It will be in a separate directory tree with its own `LICENSE.txt` or
>    `LICENSE` file at the top containing the specific license and restrictions
>    which apply to that software, or
> 2) It will contain specific license and restriction terms at the top of every
>    file.


Based on these instructions, you need to modify the MXNet LICENSE so that it separately lists

- an entry for the LLVM openmp project together with a reference to the LICENSE.txt file in the openmp folder
- an entry for each sub-project of the openmp project as identified by other LICENSE.txt files located someweher the openmp folders and subfolders
- an entry for each set of files that "contain [the same] specific license and restriction terms at the top of every file."

The latter may best be scripted.

**Comment by leezu** [comment]
The easiest option here is to delete the 3rdparty/openmp folder as it's unused by the default Makefile build and optional for the cmake build.

**Comment by Zha0q1** [comment]
> You need to read the license file. It states:
> 
> ```
> ==============================================================================
> The LLVM Project is under the Apache License v2.0 with LLVM Exceptions:
> ==============================================================================
> ```
> 
> as well as
> 
> ```
> ==============================================================================
> Software from third parties included in the LLVM Project:
> ==============================================================================
> The LLVM Project contains third party software which is under different license
> terms. All such code will be identified clearly using at least one of two
> mechanisms:
> 1) It will be in a separate directory tree with its own `LICENSE.txt` or
>    `LICENSE` file at the top containing the specific license and restrictions
>    which apply to that software, or
> 2) It will contain specific license and restriction terms at the top of every
>    file.
> ```
> 
> Based on these instructions, you need to modify the MXNet LICENSE so that it separately lists
> 
>     * an entry for the LLVM openmp project together with a reference to the LICENSE.txt file in the openmp folder
> 
>     * an entry for each sub-project of the openmp project as identified by other LICENSE.txt files located someweher the openmp folders and subfolders
> 
>     * an entry for each set of files that "contain [the same] specific license and restriction terms at the top of every file." which are not already covered by the two points above
> 
> 
> The latter may best be scripted.

I totally agree with this methodology but I checked all the file, and there was no mentioning of any license other than Apache 2.0. I tried to associate those extra licenses with specific files/submodules but I could not find any such links.

**Comment by leezu** [comment]
In that case you don't need to include them. Referencing the LICENSE.txt is sufficient. We don't need to copy the license text into our LICENSE file. We only need to ensure that we point to each file / set of files of a particular license and provide a pointer where the user can read their license

**Comment by Zha0q1** [comment]
> In that case you don't need to include them. Referencing the LICENSE.txt is sufficient. We don't need to copy the license text into our LICENSE file. We only need to ensure that we point to each file / set of files of a particular license and provide a pointer where the user can read their license

Sounds good. I have deleted these licenses from our file
sounds good, will do it

**Review by josephevans — APPROVED** [review]

**Review by leezu — CHANGES_REQUESTED** [review]
3rdparty/openmp/LICENSE.txt specifies Apache License v2.0 with LLVM Exceptions not MIT License

**Comment by Zha0q1** [comment]
@leezu Yeah sorry did not notice that. I moved it under the apache list and also attached the llvm exception at the bottom

**Pull request closed without merging**
