### PR TITLE
[1.7.x] Backport of LSTM and GRU fix (#17898) and RNN op (#17632)

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
Fix for LSTM and GRU layers without DNNL enabled give wrong gradients #17898
[Large Tensor] Fixed RNN op #17632

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
- This PR is backport of #18203 and #17632

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge, windows-gpu]

**Comment by ciyongch** [comment]
@bgawrych Please help to rebase the code, the failure of `edge` job was already fixed.

**Comment by ciyongch** [comment]
Hi @bgawrych , seems the failed cases is still caused by the CI itself. Please hold on for a while, I've create a PR https://github.com/apache/incubator-mxnet/pull/18452 to address such failure.

**Comment by ciyongch** [comment]
Hi @bgawrych , PR https://github.com/apache/incubator-mxnet/pull/18456 was merged to fix the CI issue, it's ok to re-trigger the CI now, thanks!

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by bgawrych** [comment]
@ciyongch Everything is alright :) branch 1.x too

**Pull request merged**
