### PR TITLE
Improve cmake flags

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
Change CMAKE_CXX_FLAGS for MKL-DNN build on Windows to remove below warnings:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vector(750): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ankkhedia** [comment]
@mxnet-label-bot [pr-work-in-progress, cmake]

**Comment by kalyc** [comment]
Thanks for your contribution @TaoLv,  Has this change been tested locally?

Requesting @nswamy @sandeep-krishnamurthy for review
@mxnet-label-bot update [pr-awaiting-review]

**Comment by TaoLv** [comment]
@kalyc Yes, it has been tested on my local machine. You can also find those warnings in the GPU+MKL-DNN+Windows build in other PRs. For example: http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-13252/runs/2/nodes/124/steps/718/log/?start=0

They are removed in this PR:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-13109/runs/6/nodes/124/steps/739/log/?start=0

Issue was raised by @srochel on dev@.

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-review, cmake]

**Comment by larroy** [comment]
@kalyc CMake is owned by @lebeg

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-merge, cmake]

**Pull request merged**
