### PR TITLE
[BUGFIX] Fix to quantization dshape bug

### PR DESCRIPTION
**Pull request by grygielski**
## Description ##
This PR fixes https://github.com/apache/incubator-mxnet/issues/19477

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- Moved `data_shape=dshape` assignment inside `if calib_data is not None:` branch

### CODE REVIEW

**Comment by grygielski** [comment]
@anko-intel @pengzhao-intel

**Comment by anko-intel** [comment]
LGTM

**Comment by grygielski** [comment]
@mxnet-bot run ci [windows-cpu]

**Comment by grygielski** [comment]
@szha

**Comment by szha** [comment]
@grygielski thanks for the fix!

**Pull request merged**
