### PR TITLE
assert size eq between shared_module.execs and context

### PR DESCRIPTION
**Pull request by formath**
@piiswrong

### CODE REVIEW

**Comment by piiswrong** [comment]
why?

**Comment by formath** [comment]
When binding an executor with shared one, it get a shared executor via index `i`.  If not equal, it could occur index error? So explicitly add a assert would be helpful.
```
shared_exec = None if shared_group is None else shared_group.execs[i]
```

**Comment by sxjscience** [comment]
@formath There's the case that `len(shared_group.execs) > len(self._context)`, which should also be valid. So we need to change the assertion to `len(shared_group.execs) >= len(self._context)`.

**Comment by formath** [comment]
I will check it later. thanks

**Comment by sxjscience** [comment]
@formath Have you checked it?

**Comment by formath** [comment]
holiday now. I will check it when working

**Comment by formath** [comment]
@sxjscience assert len(shared_group.execs) >= len(self._context) is ok. But some other things must be known by user.
If the the batch size is `N` and devices are '0,1,2,3' for the `shared_group`, the batch size for each `exec` is `N/4`. So the batch size for the new `exec` to be created using existing shared one should also be `N/4` for shape consistent of shared arguments. Thus, the batch size for the new `exec_group` should be `N/4 * 2` if devices are `0,1` or any others containing two. This may be a burden for users who are not familiar with mxnet low level code. Otherwise, I saw the `shared_group` is just used by bucketing in which devices will not changed. Right? If I'm wrong, I will fix it. Thanks.

**Comment by sxjscience** [comment]
@formath We should be able to share the parameters even if the batch_size is different. In fact, in my usage case, I have one Module that's built on 2 GPUs for training. I want to create another shared module that only uses 1 GPU for testing. In this case, `len(shared_group.execs)=2` and `len(self._context)=1`

**Comment by formath** [comment]
@sxjscience Nice https://github.com/apache/incubator-mxnet/pull/8185

**Pull request merged**
