### PR TITLE
Fix for handling negative indices in the fusion of slice

### LINKED ISSUE #17914: Operator fusion breaks '+' operator on GPU with CachedOp
## Description
In some cases `broadcast_add` and `+` give different results. This issue seems to be new  in 1.6.

## To Reproduce

The following network gives the wrong outputs when hybridizing and running on a GPU.

```python
import mxnet as mx
import numpy as np


class MyModel(mx.gluon.HybridBlock):
    def __init__(self) -> None:
        super().__init__()
        with self.name_scope():
            self.cs = self.params.get_constant("cs", np.arange(10))

    def hybrid_forward(self, F, dummy, cs):
        u = F.broadcast_add(cs, dummy.zeros_like())

        # r = F.broadcast_add(
        #     F.slice_axis(u, axis=-1, begin=0, end=-1),
        #     F.slice_axis(u, axis=-1, begin=1, end=None)
        # ) / 2.0

        r = (
            F.slice_axis(u, axis=-1, begin=0, end=-1) +
            F.slice_axis(u, axis=-1, begin=1, end=None)
        ) / 2.0

        return r


def main():
    ctx = mx.Context('gpu')
    # ctx = mx.Context('cpu')

    model = MyModel()
    model.collect_params().initialize(mx.init.Xavier(), ctx=ctx)
    print("hybridizing");  model.hybridize()

    dummy = mx.nd.array(
        [
            np.ones(10),
            np.ones(10),
            np.ones(10),
        ],
        ctx=ctx
    )
    with mx.autograd.record():
        out = model(dummy)
        print(out.asnumpy())


if __name__ == '__main__':
    main()
```

It returns:
```
[[0.  1.  2.  3.  4.  5.  6.  7.  8. ]
 [9.  0.  1.  2.  3.  4.  5.  6.  7. ]
 [8.  9.  0.  0.5 1.  1.5 2.  2.5 3. ]]
```

The correct result is:
```
[[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]]
```

Any of the following changes will give the correct result:
- switch to cpu
- don't hybridize
- switch to `broadcast_add` instead of `+` (see code that is commented out)

This did not happen on mxnet 1.5.

I think it is related to the `get_constant` and broadcasting that happens before in the network. 

## Environment

```
----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 7.2.0
Build        : ('default', 'Apr 29 2018 16:14:56')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.3.1
Directory    : /home/ubuntu/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.6.0
Directory    : /home/ubuntu/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet
Num GPUs     : 1
Commit Hash   : 6eec9da55c5096079355d1f1a5fa58dcf35d6752
----------System Info----------
Platform     : Linux-4.4.0-1104-aws-x86_64-with-debian-stretch-sid
system       : Linux
node         : ip-172-31-28-101
release      : 4.4.0-1104-aws
version      : #115-Ubuntu SMP Mon Mar 2 06:35:35 UTC 2020
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2213.210
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.12
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0022 sec, LOAD: 0.6087 sec.
Timing for GluonNLP GitHub: https://github.com/dmlc/gluon-nlp, DNS: 0.0006 sec, LOAD: 0.5831 sec.
Timing for GluonNLP: http://gluon-nlp.mxnet.io, DNS: 0.1805 sec, LOAD: 0.4238 sec.
Timing for D2L: http://d2l.ai, DNS: 0.0274 sec, LOAD: 0.0487 sec.
Timing for D2L (zh-cn): http://zh.d2l.ai, DNS: 0.0148 sec, LOAD: 0.1029 sec.
Timing for FashionMNIST: https://repo.mxnet.io/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1235 sec, LOAD: 0.1370 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0178 sec, LOAD: 0.3628 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0015 sec, LOAD: 0.0679 sec.
```

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Fixes #17914

@leezu @vafl

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Handling of the negative axis in the `build_tuple` helper function and added tests

### CODE REVIEW

**Comment by leezu** [comment]
Thanks @ptrendx. Do you plan to backport this change to 1.6 and perhaps have a 1.6.1 release?

**Comment by ptrendx** [comment]
@leezu Having a patch release would require following a release process again and my understanding is that there is going to be 1.7 release soon. @TaoLv I believe you guys wanted to do 1.7, right? Could you comment on the timeline?

**Comment by ptrendx** [comment]
unix-gpu failed with gcc segfaulting - @ChaiBapchya have you seen this before?

**Comment by ChaiBapchya** [comment]
Nope.. does it have something to do with your change?

**Comment by ptrendx** [comment]
I don't believe so - my change does not even touch files that are compiled in CPU only build.

**Comment by ptrendx** [comment]
Let's test the bot :-)

@mxnet-bot run ci [unix-cpu]

**Comment by TaoLv** [comment]
> @leezu Having a patch release would require following a release process again and my understanding is that there is going to be 1.7 release soon. @TaoLv I believe you guys wanted to do 1.7, right? Could you comment on the timeline?

@ptrendx Thank you for the ping. @ciyongch will help to manage the release of 1.7 and will send out the plan and timeline to dev@ soon.

**Comment by ciyongch** [comment]
@ptrendx It's really a great job to complete the journey of MXNet 1.6.0 release! I'm going to manage the release of 1.7 with the support from @TaoLv, and will update the plan later in dev.

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ptrendx** [comment]
@szha @ChaiBapchya Is anybody looking at this hang after e.g. `test_np_empty` tests? It would be really useful for the CI admins to hop on the node as it hangs and at least get a stacktrace or something to start figuring out where exactly the failure happens. From my experience those hangs are pretty common.

**Comment by ChaiBapchya** [comment]
Yes. Getting a stacktrace as it hangs needs to be done before the instance is shut down by the autoscaler [as it is not feasible to disable autoscaler]. Right now only 1 unix-gpu instance is running and the python3 tests have passed. So we really have to time it such that the gpu test fail and the node is alive so that we get the stacktrace.

@leezu found that this might be operator related bug that can be tested locally.
To check the hypothesis, I am trying out testing these files in following order:
test_contrib_amp test_deferred_compute_gpu test_device test_extensions_gpu test_forward test_fusion test_gluon_gpu test_operator_gpu
If I can reproduce it locally then we can ID the issue with the operator test.

**Comment by leezu** [comment]
@ChaiBapchya the hang occurs after ~10 minutes but the instance will remain available until timeout happens (3 hours). So @ptrendx's suggestion should also work.
I do remember that someone attempted this for the same or a similar issue before? I think there are logs in the internal issue tracker?

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu]

**Comment by ptrendx** [comment]
Added the v1.x label even though this PR goes to master in order to track that we want this included in 1.7 @ciyongch FYI.

**Comment by ciyongch** [comment]
@ptrendx thanks for point it out, I'm adding this to 1.7.0 roadmap https://github.com/apache/incubator-mxnet/issues/16864. 
BTW, are you going to backport this PR to v1.x after it's merged into master?

**Comment by ptrendx** [comment]
Yes, I'm going to backport my prs.

**Comment by vafl** [comment]
> Yes, I'm going to backport my prs.

Thanks for the fix. I'm wondering when are you planning to release a fix for 1.6?
This is a somewhat urgent issue for gluonts.

**Comment by ptrendx** [comment]
@vafl There is pretty much 0 chance that something like 1.6.1 would happen before 1.7.0 (at least that 's my understanding, @szha please correct me if I'm wrong), is there anything preventing GluonTS from jumping straight to 1.7?

**Comment by leezu** [comment]
@ptrendx not everyone is using the binary wheels from pypi. Having the fix in the 1.6 branch can still be useful despite not having a 1.6.1 release in the short term

**Comment by ptrendx** [comment]
I see. Ok, will push it there.

**Pull request merged**
