### PR TITLE
Updated news.md with the latest mkldnn submodule version

### PR DESCRIPTION
**Pull request by piyushghai**
## Description ##
As title

@aaronmarkham Please review.

### CODE REVIEW

**Comment by TaoLv** [comment]
@piyushghai Thank you for the change. Not sure if we also need have it on v1.4.x.

**Comment by pengzhao-intel** [comment]
@piyushghai retrigger the CI?

**Comment by piyushghai** [comment]
> @piyushghai retrigger the CI?

Done. @pengzhao-intel

**Comment by piyushghai** [comment]
> @piyushghai Thank you for the change. Not sure if we also need have it on v1.4.x.

@TaoLv No we don't need it on the v1.4.x branch. The master branch contains the latest news info on the previous release.

**Comment by TaoLv** [comment]
Thank you. Merging now.

**Pull request merged**
