### PR TITLE
A solution to prevent zombie containers locally and in CI

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
This PR adds mechanisms on the build scripts to cleanup docker containers when there is a cancellation, either from the user by sending SIGINT / SIGTERM or when the process inside the container ends with an error.

It also propagates the environment variables from Jenkins which are used by the process tree killer to identify runaway processes so processes inside the container are killed when the Jenkins job is stopped.

With this patch we catch SIGINT and SIGTERM and install a handler on atexit which cleans (stops) docker containers which were created during execution of the build.

We also switch to python docker API for better management of running containers.

@aaronmarkham @marcoabreu @lebeg @KellenSunderland

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by KellenSunderland** [comment]
LGTM, let's get the host AMIs changed.

**Comment by aaronmarkham** [comment]
I was hoping to see some usage info. 1) how to make a zombie; 2) how to kill it - I'd be happy to test this out.

**Comment by larroy** [comment]
I added info in the readme. Do you see it in the patch?

**Comment by larroy** [comment]
Done. I don't know why the PR is not updated.

**Comment by larroy** [comment]
any ideas? is a github problem?

**Comment by larroy** [comment]
I can't reopen the PR, had some troubles with PR not updating and Jenkins, new pR:

https://github.com/apache/incubator-mxnet/pull/12381

**Comment by KellenSunderland** [comment]
Github is having issues today.  https://status.github.com/messages

**Pull request closed without merging**
