### PR TITLE
[master] Fix issue with even number of channels in BatchNorm

### PR DESCRIPTION
**Pull request by piotrwolinski-intel**
## Description ##
Goal of this PR is to prevent bug with BatchNorm, that was seen on other versions ([here for instance](https://github.com/apache/incubator-mxnet/issues/20858)).    
Fix is done by calling oneDNN implementations via `DNNLRun` method, not directly.

### CODE REVIEW

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [website ]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [edge, unix-cpu, windows-gpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
