### PR TITLE
User Feedback Widget

### PR DESCRIPTION
**Pull request by ys2843**
## Description ##
Milestone 2 of #18548 -  Build user feedback widget based Google Analytics on MXNet website.
This PR implements a website widget to collect user feedback which can be added to any tutorials and API pages. It will be attached to the end of the page with 2 clickable button with responses YES and NO. 

Screen Shot 2020-06-29 at 1 40 52 PM

Once user clicks on a response button, it hides the widget and show "Thanks for you feedback!" and fire a google analytics event with relating data to record this feedback. The report of user feedback can be viewed on Google Analytics console, under `Behavior` => `Events`. Google Analytics provide 3 available fields for an event and below is how we define it.
```bash
Category: "Did this page help you?"    # Common name for all feedback event
Label: $URI_PATH     # The URI where event was fired, for example "api/scala/docs/tutorials/io"
Action: yes or no     # User feedback 
Value: 1 or 0  # used to calculate the satisfactory percentage of feedback
```
To add feedback widget to website:
+ On main site: Found the target markdown or html page, add `feedback: true`  in its Jekyll front matter
+ Python microsite: all pages are enabled automatically

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:

### Changes ###
- [x] Added user feedback widget to MXNet main website and Python tutorials&API pages. 

## Comments ##
- Preview on Python microsite: http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/

### CODE REVIEW

**Comment by ys2843** [comment]
@mxnet-label-bot add [Website]

**Comment by ys2843** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu]

**Comment by sandeep-krishnamurthy** [comment]
@aaronmarkham can you please help review?

**Comment by ys2843** [comment]
> @ys2843 can you please send an email to the mailing list requesting guidance on how to disclose the use of google analytics? @aaronmarkham made the point that the website is not compliant with GDPR.
> We should ask ASF to consider including whatever guidance they give, into their policies.

Will do. I will share the info with team later.

**Pull request merged**
