### PR TITLE
[MXNET-749] Bug fixes in control flow operators

### PR DESCRIPTION
**Pull request by junrushao1994**
## Description ##
This PR fixes some bugs for control flow operators `mx.sym.contrib.while_loop` and `mx.sym.contrib.cond`.

Takeaways:
- if now I understand correctly, we should call `MXSymbolCutSubgraph` to capture free variables of a closure before calling `MXSymbolGetInputSymbols`. I guess we should document this so that others won't be confused.
- `symbol._internal.something` always return a single Symbol, regardless of how many outputs it actually has.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Bug fixes

## Comments ##
- See takeaways

### CODE REVIEW

**Comment by junrushao1994** [comment]
@zheng-da @piiswrong Could you help review this? Thank you guys!

**Comment by junrushao1994** [comment]
@zheng-da And I am not sure if my understanding is correct, but I guess another thing we should discuss is: is the `SubgraphSanityCheck` we did in [NNVM](https://github.com/dmlc/tvm/blob/142c7da392a232e5610b6d7bcfd5b40f9c4dd027/nnvm/src/core/graph.cc#L24), actually too restrictive?

For example, there is a huge graph, containing two subgraphs `A` and `B`, and `A` and `B` has there own subgraphs, say `A.0` and `B.0`. Some intermediate results are shared across several subgraphs. If `CutSubgraph` fails to copy-and-split them into different subgraphs, then `SubgraphSanityCheck` will raise an error. However, in theory, `CutSubgraph` should do the copy-and-split stuff, but it is not working on my case. I suspect there is more bugs, either in control flow operators, or in subgraph cut. Could we discuss sometime?

**Comment by zheng-da** [comment]
To make sure cutting subgraphs works correctly, I think we should give each subgraph a unique name. Maybe we aren't doing it correctly.

**Comment by junrushao1994** [comment]
@zheng-da I tried to comment out the sanity check, and everything seems to work

**Comment by junrushao1994** [comment]
This fix is pretty simple, I think we should merge this so that it doesn't block subsequent work. Thanks!

**Pull request merged**
