### PR TITLE
[Feature][Master] Flake8 changes have been applied.

### PR DESCRIPTION
**Pull request by mozga-intel**
## [Feature] Description ##
[Refactring] Following the #20429, running flake8 on the current master produces a bunch of errors (pasted below).  This pull request contains changes as following: I neglected some flake8 errors, and we just smooth the line of the code.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [all]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [website]

**Comment by szha** [comment]
@mxnet-bot run ci [centos-gpu,unix-gpu,website]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-cpu , centos-gpu, edge ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, website]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [edge]

**Pull request closed without merging**
