### PR TITLE
add retry to S3 uploads for test results

### PR DESCRIPTION
**Pull request by larroy**
See title.

https://github.com/apache/incubator-mxnet/pull/16512

### CODE REVIEW

**Comment by marcoabreu** [comment]
Good idea. Will this rethrow the original exception if the retry limit is reached?

**Comment by ChaiBapchya** [comment]
Nice idea. But do we know if it will actually upload the xml within 3 attempts? Coz I have seen S3 upload fail many times when some test fails. S3upload is independent of test failure. But just to be sure.

**Comment by larroy** [comment]
@marcoabreu I don't know. Looks like people are using it assuming it handle exceptions: https://gist.github.com/daipresents/c7f982ffce9c1bda73b4387d6b1ae3da
Do you know better?

@ChaiBapchya ok, what would you suggest instead?

**Comment by marcoabreu** [comment]
Seems like it's handling in exactly that fashion.

**Comment by marcoabreu** [comment]
Could you also add some diagnostics to debug the error? The execution in the mentioned PR said success but then had the return code 1. Seems odd

**Comment by ChaiBapchya** [comment]
> 
> @ChaiBapchya ok, what would you suggest instead?

No my point was have you by any chance tested that if PR fails on a particular build, does it still upload on S3 or does it fail everytime build fails? But nevermind, it's tough to check that. (I tried doing it myself but its like searching for needle in haystack.

**Comment by larroy** [comment]
I wouldn't think it uploads to s3 if the PR fails.

**Pull request closed without merging**
