### PR TITLE
try without force inline

### PR DESCRIPTION
**Pull request by szha**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by szha** [comment]
The size change after turning off force inline seems minuscule.

Take unix-gpu int64 build for example, [before](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/master/2002/pipeline/54#step-358-log-9): 935M, [after](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18404/1/pipeline/54#step-352-log-9): 931M

It's unlikely this approach will be sufficient for reducing binary size and overcome address space limit.

**Comment by szha** [comment]
Turning off inlining results in [compilation error](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18404/1/pipeline/49#step-270-log-4) in some builds in InsertSingleIndexKernel. @JiangZhaoh would you mind taking a look?

**Comment by JiangZhaoh** [comment]
Sorry but I can't reproduce the CI compile issue.
I use **Deep Learning AMI (Ubuntu 18.04) Version 29.0 (ami-0ffd41ee43c386b23)** as my local machine and the build command as follows:
```
make clean
rm -rf build
mkdir -p build && cd build
cmake -DUSE_OPENCV=0 \
            -DUSE_CUDA=1 \
            -DUSE_CUDA_PATH=/usr/local/cuda \
            -DUSE_CUDNN=1 \
            -DUSE_MKLDNN=0 \
            -DCMAKE_BUILD_TYPE=RELEASE \
            -DBUILD_CYTHON_MODULES=ON \
            -GNinja ..
ninja
```

**Comment by szha** [comment]
@JiangZhaoh you will need to use gcc-7 for getting the warning. I was able to obtain the warning on mac by installing `brew install gcc@7` and specify `CC=gcc-7 CXX=g++-7`. The builds in CI failed because we have `-Werror` on.

**Pull request closed without merging**
