### PR TITLE
[v1.8.x] Update for MXNet 1.8.0 website release

### PR DESCRIPTION
**Pull request by waytrue17**
## Description ##
Preparing for mxent 1.8 website release. Also https://github.com/dmlc/web-data/pull/265

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by waytrue17** [comment]
@ys2843 @leezu Can you please review? thanks

**Comment by access2rohit** [comment]
@waytrue17 
is there a way to view your changes locally ? If you have tested the website on your local machine can you paste a screenshot ?

**Comment by waytrue17** [comment]
> @waytrue17
> is there a way to view your changes locally ? If you have tested the website on your local machine can you paste a screenshot ?
Here is a screenshot from the local test, we can see the added note for gpu pip package
Screen Shot 2021-03-09 at 6 03 26 PM

**Review by Zha0q1 — APPROVED** [review]
LGTM

**Review by access2rohit — APPROVED** [review]
LGTM!

**Pull request merged**
