### PR TITLE
[Example] Gradcam consolidation in tutorial

### PR DESCRIPTION
**Pull request by ankkhedia**
## Description ##
The PR fixes GradCAM example (https://github.com/apache/incubator-mxnet/tree/master/example/cnn_visualization) which is tracked in #11895.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
1. Fixes the implementation bug (it was not fully replicating the reference paper)
2. Consolidate example and tutorial for this use case.

### CODE REVIEW

**Comment by ankkhedia** [comment]
@nswamy @aaronmarkham @ThomasDelteil @indhub 
This PR consolidates the tutorial and examples together as discussed in the dev-list. Could you please take a look?

**Comment by ankkhedia** [comment]
@mxnet-label-bot [Example, pr-awaiting-review]

**Comment by ankkhedia** [comment]
@aaronmarkham  Inside tutorial_utils  we can have directories with same name as tutorial and we can put associated file over there. I will make that change for this PR

**Comment by ankkhedia** [comment]
@aaronmarkham Added directory structure and related changes.

**Comment by aaronmarkham** [comment]
Thanks @ankkhedia - I think the organization of the folder will be helpful.

**Pull request merged**
