### PR TITLE
[DO NOT MERGE] Testing subrepo by branch

### PR DESCRIPTION
**Pull request by KellenSunderland**
[DO NOT MERGE] Testing subrepo by branch

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-work-in-progress]
Thanks for your contribution @KellenSunderland

**Comment by KellenSunderland** [comment]
@marcoabreu Yeah it's a good question.  It's actually explained really well in the main PR that prompted me to open this pr: https://github.com/apache/incubator-mxnet/pull/13322

Basically what I'm testing in this PR is to see if there's any way we can avoid taking down everyone's build and CI whenever there's a force push in a submodule.  So far it seems like even if we track a branch it hard codes some sha1 somewhere, so I'm not sure if it's possible.

**Comment by marcoabreu** [comment]
Anton submitted a patch to make CI resilient against submodule problems. That should be fine now.

But yeah it's a good point about developers. In the end, they have to update the submodules anyway. Hmmm, hard choice

**Comment by marcoabreu** [comment]
Gotcha, thanks for the explanation. I'm really curious :)

**Comment by vandanavk** [comment]
@mxnet-label-bot  add [Build]

**Comment by roywei** [comment]
@KellenSunderland ping for update. Is this PR still needed? Thanks

**Comment by KellenSunderland** [comment]
PR not needed.

**Pull request closed without merging**
