### PR TITLE
[WIP] [v1.9.x] license updates

### PR DESCRIPTION
**Pull request by josephevans**
## Description ##
Updates per feedback from RC7 release.

### CODE REVIEW

**Comment by barry-jin** [comment]
Should we also add the license checker workflow into v1.9.x and v1.x branch. I'm trying to create [one](https://github.com/apache/incubator-mxnet/pull/20617/files#diff-f720c7c88099c1833198924651795ee4dde030fced213a99fcdb701a6b410b42) in master branch.

**Comment by josephevans** [comment]
> Should we also add the license checker workflow into v1.9.x and v1.x branch. I'm trying to create [one](https://github.com/apache/incubator-mxnet/pull/20617/files#diff-f720c7c88099c1833198924651795ee4dde030fced213a99fcdb701a6b410b42) in master branch.

Great idea, I've added the workflow to this PR.

**Review by barry-jin — APPROVED** [review]
LGTM

**Review by waytrue17 — APPROVED** [review]
LGTM, thanks!

**Review by mseth10 — APPROVED** [review]

**Pull request merged**
