### PR TITLE
[WIP][Review Required] License Fixes based on Apache RAT Feedback Part 4 

### PR DESCRIPTION
**Pull request by mbaijal**
## Fixing Apache RAT failures - Part 4 ##
PLEASE HELP REVIEW! @szha @pracheer  @bhavinthaker 
I am not entirely sure about this file format so please verify that these changes are valid. 

Fixing Licenses based on Apache RAT feedback - adding License to MANIFEST.in files

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
This is currently an incremental work in progress for 1.0.1 release

## Please Review the following - ##
- [x] It is ok to add a license to these files (nothing will break)
- [x] Please help make sure that NO CODE has been affected in this PR (only blank spaces and comments)
- [x] That correct **comment markers** have been used in all files (MANIFEST.in)

### CODE REVIEW

**Comment by szha** [comment]
Thanks for fixing it, @mbaijal. The change looks fine and the change won't affect the packaging behavior. Some details can be found at https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by szha** [comment]
Is this still WIP?

**Comment by szha** [comment]
Ping @mbaijal

**Comment by mbaijal** [comment]
Yes Sheng, this is WIP because Pracheer wanted to confirm the license on
one file.

**Comment by szha** [comment]
Thanks, @mbaijal. @pracheer, let me know when this PR is ready.

**Comment by pracheer** [comment]
The change looks good to me. Thanks @mbaijal !

**Pull request merged**
