### PR TITLE
[v2.0] Split Large Source Files

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Refactor large numpy files to unblock CI build. 
Reference: #19688

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu]

**Review by leezu — APPROVED** [review]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Pull request merged**
