### PR TITLE
[v1.7.x] Backport PRs

### PR DESCRIPTION
**Pull request by sxjscience**
Backport:
- #18080
- #17788
- #18393

### CODE REVIEW

**Comment by sxjscience** [comment]
@ciyongch These three commits can be safely ported.

**Comment by ciyongch** [comment]
Thanks @sxjscience , so only two remaining PRs (#18250 and #18523) to be backported, right?
BTW, please help to re-trigger the [unix-gpu] job.

**Comment by TaoLv** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
Hi @TaoLv @pengzhao-intel , please help to merge, thanks.

**Comment by ChaiBapchya** [comment]
Any reason why this is not ported into v1.x?

**Comment by ciyongch** [comment]
This PR includes the minimal PR set that need to be backported, while the original analysis showed much more related PRs are required at that time.
So the three PRs will be needed and probably more PRs from master are required as well. Do we have any specific test cases to cover those numpy features in v1.x, just to make sure the patches in master branch are backported accordingly.

**Pull request merged**
