### PR TITLE
[v1.8.x][BUGFIX] Fix MKLDNN BatchNorm with even number of channels (#19150) #19299 #19425

### PR DESCRIPTION
**Pull request by akarbown**
## Description ##
It's the change (#19299) ported form mxnet 1.7.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-gpu]

**Review by wkcn — APPROVED** [review]
LGTM. Thank you!

**Comment by TaoLv** [comment]
@samskalicky Do you want to confirm this is needed for the release?

**Comment by samskalicky** [comment]
Bug fixes are still ok until we finish the license issues. 

Can someone confirm this fix has already been ported to the 1.x branch already before we merge this?

**Comment by akarbown** [comment]
> Bug fixes are still ok until we finish the license issues.
> 
> Can someone confirm this fix has already been ported to the 1.x branch already before we merge this?

I'll create PR with that fix for 1.x today.

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-gpu, windows-gpu]

**Comment by samskalicky** [comment]
Thanks @akarbown for creating #19445 on v1.x too!

**Review by samskalicky — APPROVED** [review]

**Pull request merged**
