### PR TITLE
Silence excessive log output in tests

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
See title.

### CODE REVIEW

**Comment by ZhennanQin** [comment]
This is a major change between master and v1.5, so we want to print this log to let user notice that if they have a problem on master build, they can turn off MKLDNN subgraph for a try. This log will only show once for symbol bind, so it's OK for most use case. I admitted that it's a bit annoying in CI, let's find a way to disable this in CI, not just simply quote it out for all build.

**Comment by pengzhao-intel** [comment]
@larroy friendly ping :)

**Comment by larroy** [comment]
Not sure what's the next action here.

**Comment by pengzhao-intel** [comment]
> Not sure what's the next action here.

Let's make it pass the CI :)

**Comment by ZhennanQin** [comment]
https://github.com/apache/incubator-mxnet/pull/16607 is the action for this request. I guess we can close this PR if CI log is clean enough.

**Comment by pengzhao-intel** [comment]
> #16607 is the action for this request. I guess we can close this PR if CI log is clean enough.

Thanks to the great efforts @larroy @ZhennanQin, I am closing this PR now.

**Pull request closed without merging**
