### PR TITLE
[COMMUNITY] Add Przemek Tredak as a new PPMC member

### PR DESCRIPTION
**Pull request by DickJC123**
## Description ##
Please join me in welcoming Przemek Tredak (@ptrendx) as our latest Apache MXNet PPMC member.  Przemek became a committer of MXNet in May 2019 and has made major contributions to a number of key components including AMP, the fusion framework and RTC to name a few.  Przemek also served as release manager for MXNet 1.6.

Congratulations to @ptrendx on this achievement.  We all look forward to working with Przemek in guiding the project!

PRs (>100):
https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+author%3Aptrendx+
Issues he participated in:
https://github.com/apache/incubator-mxnet/issues?q=is%3Aissue+involves%3Aptrendx
PR reviews:
https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+reviewed-by%3Aptrendx
dev@:
https://lists.apache.org/list.html?dev@mxnet.apache.org:lte=24M:ptrendx

### Essentials ###
- [X] Add @ptrendx to PPMC list in CONTRIBUTORS.md 
- [X] Minor tweeks to wording.  Formatting corrections.

### CODE REVIEW

**Review by szha — APPROVED** [review]
Congratulations, @ptrendx. Well deserved!

**Comment by szha** [comment]
Congratulations Przemyslaw!

**Comment by szha** [comment]
Congratulations Przemyslaw or ptrendx!

**Comment by wkcn** [comment]
Congratulations, Przemek(@ptrendx). Well deserved!

**Pull request merged**
