### PR TITLE
[R] update tutorial link. close #6536

### LINKED ISSUE #6536: R Documentation hyperlinks at http://mxnet.io/api/r/index.html all lead to something other than R
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

### PR DESCRIPTION
**Pull request by thirdwing**

### CODE REVIEW

**Comment by piiswrong** [comment]
Where is this going to be displayed?

**Comment by thirdwing** [comment]
This will add an index page at http://mxnet.io/tutorials/r/index.html

All the R tutorials are already on our website (http://mxnet.io/tutorials/r/), but no links to them.

screenshot from 2017-08-15 10-44-53

**Comment by thirdwing** [comment]
@sandeep-krishnamurthy Please have a look at this.

**Comment by piiswrong** [comment]
How do you select the R tutorials?

**Comment by piiswrong** [comment]
Is there going to be a dropdown menual like API?

**Comment by kevinthesun** [comment]
You need to add index information to https://github.com/apache/incubator-mxnet/blob/master/docs/tutorials/index.md just like python.

**Pull request merged**
