### PR TITLE
[DOC] Add examples of running Python unittests to docs

### PR DESCRIPTION
**Pull request by r3stl355**
## Description ##
Added an example of running Python tests in Conda environment

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

**Review by leezu — COMMENTED** [review]
When we build MXNet outside of conda and use it inside conda, there can be toolchain mismatch issues causing segfault or deadlock. For example, this is known to happen when building mxnet-horovod with mpi. The reason appears to be a conflict between statically linked libraries in the conda python binary and binaries linked by the mpi integration.

As we don't have any instructions for building mxnet with the conda toolchain, how about updating this PR to be independent of conda?

**Comment by r3stl355** [comment]
Sure, I'll conda

**Comment by r3stl355** [comment]
run ci [macosx-x86_64]

**Comment by r3stl355** [comment]
run ci [centos-cpu,centos-gpu, unix-cpu]

**Comment by r3stl355** [comment]
@mxnet-bot run ci [macosx-x86_64,centos-cpu,centos-gpu, unix-cpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [macosx-x86_64,centos-cpu,centos-gpu, unix-cpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [centos-cpu,centos-gpu, unix-cpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [edge]

**Comment by szha** [comment]
Many thanks for the contribution, Nikolay!

**Comment by r3stl355** [comment]
Ahh, merged - thanks. I can now starting looking at something else

**Pull request merged**
