### PR TITLE
[MXNET-255] Temporarily disable partial test until hang is fixed

### PR DESCRIPTION
**Pull request by KellenSunderland**
## Description ##
This removes a partial test that's currently causing CI to hang.  Details here: https://github.com/apache/incubator-mxnet/issues/10341

### CODE REVIEW

**Comment by KellenSunderland** [comment]
@cjolivier01 Think merging this temporarily would make sense?  The rest of this test should be fine, so I don't think we need to revert the whole commit.

**Comment by cjolivier01** [comment]
I'd prefer to revert the whole commit so that we can be sure it gets fixed.

**Comment by cjolivier01** [comment]
we seem to just keep disabling tests to fix CI. But clearly something is wrong and maybe it isn;t the test, so the tech debt is getting bug.  I think better to really get it fixed for real.

**Comment by cjolivier01** [comment]
Can you make another PR with a revert?

**Comment by KellenSunderland** [comment]
@cjolivier01 The thing is that the PR that introduces the test is not the root cause of the problem.  I don't see that reverting it will accomplish much.  On the other hand if we keep the test running our CI system won't be functional.  

If we can fix the root cause of the hang let's do that, it's our best option.  Otherwise I think we'll have to start disabling + tracking tests first until the CI is stable, then start addressing root causes.

**Comment by cjolivier01** [comment]
WHat's the root cause?

**Comment by KellenSunderland** [comment]
The root cause seems to be a potential deadlock in CuDNNConvolutionOp.  I'd have to dig in a little deeper to be 100% sure.  I have reproduced it many times on a g3.8x with the same script CI is using.  For me removing this section of the test resolved the hang.

**Comment by cjolivier01** [comment]
actually, you can try setting cudnn_off=True for the convolution sym

**Comment by cjolivier01** [comment]
we can try after this passes (if it passes)

**Comment by cjolivier01** [comment]
(after this is merged)

**Pull request merged**
