### PR TITLE
[Flaky Test] Disables flaky test_l2_normalization

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
Disables flaky test_l2_normalization (see #15004).

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by pinaraws** [comment]
@mxnet-label-bot add[CI, pr-awaiting-review]

**Comment by zachgk** [comment]
@perdasilva For temporarily dealing with flaky tests, it is probably better to specify a fixed seed (see https://github.com/zachgk/incubator-mxnet/blob/master/tests/python/unittest/common.py#L117) rather than disable the test completely

**Comment by perdasilva** [comment]
@zachgk good idea! I'll try to do that in the future. I'll also spread the word.

**Comment by perdasilva** [comment]
@zachgk, @marcoabreu claims this was the procedude in the past. But it made flaky test fixes fall in priority, since this creates no sense of urgency... maybe you would like to bring this up as a topic for discussion on the mailing list?

**Comment by szha** [comment]
@zachgk @perdasilva FYI just in case you aren't aware, we used to mark tests with fixed seed as issues to fix. https://github.com/apache/incubator-mxnet/issues/11726

**Comment by szha** [comment]
And here's the guideline on fixing flaky tests: https://cwiki.apache.org/confluence/display/MXNET/Fixing+Flaky+Tests

**Pull request merged**
