### PR TITLE
avoid skipping validation stage when data read iterator exists

### PR DESCRIPTION
**Pull request by heaseny**
## Description ##
avoid skipping validation stage when data read iterator exists.
Test commands:
cd example/image-classification
python  train_cifar10.py --network='resnet' --num-layers=50 --image-shape='3,28,28' --num-epochs=1

Abnormal test log in current master branch:
INFO:root:Epoch[0] Train-accuracy=0.386069
INFO:root:Epoch[0] Train-top_k_accuracy_5=0.875060
INFO:root:Epoch[0] Time cost=38.553

Normal test log which is expected:
INFO:root:Epoch[0] Batch [360-380]    Speed: 1302.17 samples/sec        accuracy=0.497266      top_k_accuracy_5=0.935156
INFO:root:Epoch[0] Train-accuracy=0.386069
INFO:root:Epoch[0] Train-top_k_accuracy_5=0.875060
INFO:root:Epoch[0] Time cost=39.096
INFO:root:Epoch[0] Validation-accuracy=0.448378
INFO:root:Epoch[0] Validation-top_k_accuracy_5=0.918018

### Essentials ###
- [ ] Changes are completed
- [ ] All changes have test coverage.

### Changes ###
- [ ] Feature: avoid skipping validation stage when validation data read iterator exists

### CODE REVIEW

**Comment by heaseny** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by heaseny** [comment]
@aaronmarkham Is there something wrong with CI or repository? the error is not caused by my PR

**Comment by heaseny** [comment]
@szha Can you help to review this pull request, and merge it if there is no problem? Thanks a lot.

**Comment by szha** [comment]
apologies for the spam.

@heaseny we deprecated module in the master branch and we will continue to support it in v1.x. it would be great if you could rebase your change to the v1.x branch.

**Comment by heaseny** [comment]
@szha as work changing and I am not focusing on the mxnet test and have no environment, if the change is necessary in v1.x, can you help to rebase the change, or  should I  close this PR?

**Comment by szha** [comment]
picked up the change for v1.x in the above PR.

**Pull request closed without merging**
