### PR TITLE
[MXNET-118] Added tutorial for Data Augmentation with Masks

### PR DESCRIPTION
**Pull request by thomelane**
## Description ##

Added tutorial on types of data augmentations with masks (for Object Segmentation with COCO dataset pixel maps).
Updated tutorial index.md.

### Essentials ###

N/A, as only added a single markdown file and updated tutorial index.md.

### Changes ###

Added tutorial.

## Comments ##

Contains images of types of augmentation with masks.
Contain asserts on array shapes, to allow future testing.
Completes the series on data augmentation.

### CODE REVIEW

**Comment by thomelane** [comment]
JIRA: https://issues.apache.org/jira/browse/MXNET-118

**Comment by marcoabreu** [comment]
Hello, thanks for your contribution! 

A build of the website with your changes will be available at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-10178/1/index.html after CI executed successfully. Feel free to review the newly added tutorial there.

**Comment by thomelane** [comment]
@marcoabreu thanks for the link. It looks good to me, but the tutorial links all direct to http://mxnet.incubator.apache.org/ rather than http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-10178/1/. It's easy to change the URL but wondering if there's an easy fix for this?

**Comment by marcoabreu** [comment]
Unfortunately, there is none right now. That server is really only to watch the generated documents in exactly the same way as they would get published - it's really just raw copy&paste to see the result.
@aaronmarkham would this possible in future?

**Comment by thomelane** [comment]
@rahul003 @szha @piiswrong can we get this merged?

**Comment by ThomasDelteil** [comment]
@thomelane index.md has conflicts, resolve them to be able to merge your tutorial,
Also I have reviewed this tutorial and it looks good to me 👍

**Pull request merged**
