### PR TITLE
Fix omp bug in multibox_detection to avoid accuracy variance in ssd

### PR DESCRIPTION
**Pull request by xinyu-intel**
## Description ##
This PR is to fix omp bug in `multibox_detection` to avoid accuracy variance of SSD topology.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] delete pragma omp in multibox_detection.cc

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

@pengzhao-intel @TaoLv

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
@apeforest @yuxihu could you help take a review?

**Comment by roywei** [comment]
@mxnet-label-bot add[Backend, pr-awaiting-review]

**Comment by TaoLv** [comment]
@xinyu-intel please also paste the performance change of SSD model. If it's negligible, I think this PR is good to go. Thank you.

**Comment by xinyu-intel** [comment]
P40:
```
INFO:root:Finished inference with 2240 images
INFO:root:Finished with 98.885987 images per second
aeroplane: 0.9057971014492755
bicycle: 0.8785621389155159
bird: 0.8363940601702841
boat: 0.815100739467124
bottle: 0.5618223281277894
bus: 0.8598314060584938
car: 0.8784382442430079
cat: 0.9079754601226996
chair: 0.7933105641842106
cow: 0.8931324110671939
diningtable: 0.7848938200906703
dog: 0.9082568807339451
horse: 0.9072727272727275
motorbike: 0.8930925944284724
person: 0.8115480659727458
pottedplant: 0.6432418831953183
sheep: 0.768227393378024
sofa: 0.901451489686784
train: 0.9090909090909093
tvmonitor: 0.8745790605051967
mAP: 0.8366009639080195
```
Skylake Before fix:
```
INFO:root:Finished inference with 2240 images
INFO:root:Finished with 35.336766 images per second
aeroplane: 0.9064366290643664
bicycle: 0.8764411277427806
bird: 0.8329125417396593
boat: 0.8169674072031251
bottle: 0.5641319814350945
bus: 0.8518312996387211
car: 0.8786306281515983
cat: 0.9079754601226996
chair: 0.7892002458528512
cow: 0.8938258442549063
diningtable: 0.7858787878787877
dog: 0.9082568807339451
horse: 0.9072727272727275
motorbike: 0.8940118558899026
person: 0.8054880205849446
pottedplant: 0.644885725730972
sheep: 0.7581358014045285
sofa: 0.901451489686784
train: 0.9090909090909093
tvmonitor: 0.8752740177218932
mAP: 0.8354049690600599
```
Skylake After fix
```
INFO:root:Finished inference with 2240 images
INFO:root:Finished with 35.335017 images per second
aeroplane: 0.9057971014492755
bicycle: 0.8785621389155159
bird: 0.8363940601702841
boat: 0.815100739467124
bottle: 0.5618223281277894
bus: 0.8598314060584938
car: 0.8784382442430079
cat: 0.9079754601226996
chair: 0.7933105641842106
cow: 0.8931324110671939
diningtable: 0.7848938200906703
dog: 0.9082568807339451
horse: 0.9072727272727275
motorbike: 0.8930925944284724
person: 0.8115480659727458
pottedplant: 0.6432418831953183
sheep: 0.768227393378024
sofa: 0.901451489686784
train: 0.9090909090909093
tvmonitor: 0.8745790605051967
mAP: 0.8366009639080195
```

**Comment by TaoLv** [comment]
Thank you for the fix.

**Pull request merged**
