### PR TITLE
Edit shape.array doc and some style improvements

### PR DESCRIPTION
**Pull request by terrytangyuan**
* fix grammar in shape.array doc 
* consistent use of <- instead of = for assignment
* necessary spaces
* shorten line length

### CODE REVIEW

**Comment by lupesko** [comment]
Thanks for the contribution @terrytangyuan !
Can you please update the description to be more informative?
Looping in @ankkhedia @anirudhacharya @hetong007 for review.

**Comment by terrytangyuan** [comment]
What's the difference? I am just making some enhancements myself manually for this particular file. All the changes are valid here. Others feel free to use formatR themselves for enhancement for the overall package.

**Comment by anirudhacharya** [comment]
@terrytangyuan Because we are in the process of having uniform standards for the R-package and eventually have lintR run on the pipeline. For example - https://github.com/apache/incubator-mxnet/pull/12360

**Comment by terrytangyuan** [comment]
I believe that should be done in a separate PR. I doubt that `formatR` gives the most readable code, e.g. I've rarely seen the following style but it appears to be on the PR you referred to:
```
convolution_module <- function(net, kernel_size, pad_size, filter_count, stride = c(1, 
  1), work_space = 2048, batch_norm = TRUE, down_pool = FALSE, up_pool = FALSE, 
```
or
```
if (Sys.getenv("R_GPU_ENABLE") != "" & as.integer(Sys.getenv("R_GPU_ENABLE")) == 
  1) {
```

**Comment by hetong007** [comment]
@terrytangyuan You can trigger the CI again, with an empty commit by
`git commit --allow-empty -m "Trigger CI"`

**Comment by ankkhedia** [comment]
looks good to me!

**Comment by terrytangyuan** [comment]
Re-triggered but failed again. Seems like Python tests are failing which is unrelated to this PR.

**Comment by terrytangyuan** [comment]
Ok now it's passing after retriggering CI for twice.

**Pull request merged**
