### PR TITLE
Fix LeakyRELU Bug

### PR DESCRIPTION
**Pull request by sbodenstein**
`mx.symbol.LeakyReLU` crashes when using vector inputs. For example, this crashes for the forward pass:
```
a = mx.sym.var('data')
s=mx.symbol.LeakyReLU(data=a, act_type="elu")
e=s.simple_bind(mx.cpu(), data=(2,))
e.forward()
```
This PR is a simple fix, along with a test for `mx.sym.LeakyReLU(x, act_type="elu", slope=1.0)` for vector inputs.

### CODE REVIEW

**Comment by sbodenstein** [comment]
@piiswrong: the addition of a test for ELU is causing failures in `test_operator.test_broadcast_binary_op`:
```
Items are not equal:
Error 14.595687 exceeds tolerance rtol=0.010000, atol=0.001000.  Location of maximum error:(0, 0, 4), a=0.014596, b=0.000000
 NUMERICAL_a: array([[[ 1.72120333,  1.26115978,  1.4104917 ,  1.06704044,  0.01459569]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,  0.44905394]],...
 BACKWARD_a: array([[[ 1.72122073,  1.26117206,  1.41049075,  1.06703949,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,  0.4490537 ]],...
```
This PR makes no changes to any dependencies of this test, so the only explanation is that different random numbers are used, and this is causing a violation of the tolerance bound.

What should I do?

**Comment by piiswrong** [comment]
This doesn't look like a random number problem.
I think something really is broken.
Please try rebasing to master first

**Comment by sbodenstein** [comment]
Ok, done.

**Comment by piiswrong** [comment]
This reliably fails on the same test. So I think these is a bug.

**Comment by sbodenstein** [comment]
Yes. Going to close this and make a new PR.

**Pull request closed without merging**
