### PR TITLE
Optuna

### PR DESCRIPTION
**Pull request by Crissman**
## Description ##
Add Optuna to the MXNet ecosystem

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Edit Ecosystem page to add Optuna
- [x] Add optuna.png image

## Comments ##
From issue #18401

### CODE REVIEW

**Comment by Crissman** [comment]
I tried to look at the ci/jenkins failures, but I'm afraid I wasn't able to see an issue related to this PR. Let me know if there's something I should change.

Thanks,

**Comment by marcoabreu** [comment]
@mxnet-bot run [miscellaneous, unix-cpu]

**Comment by marcoabreu** [comment]
@mxnet-bot run ci [miscellaneous, unix-cpu]

**Comment by wkcn** [comment]
@mxnet-bot run ci [miscellaneous]

**Pull request merged**
