### PR TITLE
[R] update Makefile. close #7675

### LINKED ISSUE #7675: [Jenkins CI] Broken R Unit test during build
@thirdwing 

R GPU unit tests are failing more frequently on the master branch. Can you please take a look at this?
Example failed CI build - https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/272/pipeline/

### PR DESCRIPTION
**Pull request by thirdwing**

### CODE REVIEW

**Comment by madjam** [comment]
@thirdwing what was the issue here?

**Comment by thirdwing** [comment]
As @sandeep-krishnamurthy pointed out, we might some problems like https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/272/pipeline/#step-611-log-1184

This is quite weird and broke our CI testing. This PR is a workaround.

**Comment by sandeep-krishnamurthy** [comment]
Thanks @thirdwing

**Comment by thirdwing** [comment]
I am afraid we merge too quick. The CI is still broken...

**Comment by cjolivier01** [comment]
Issue is thought to be resolved

**Comment by thirdwing** [comment]
@cjolivier01 Thank you for handling this!

**Pull request merged**
