### PR TITLE
Add installation instruction for Fedora (#7107)

### PR DESCRIPTION
**Pull request by kottmann**

### CODE REVIEW

**Comment by kottmann** [comment]
I am not sure why it is necessary to add the include for openblas manually, the path https://github.com/dmlc/mxnet/blob/9efb2d93f77043fab1765e1a4969ecf9f0fb4e65/cmake/Modules/FindOpenBLAS.cmake#L9 here is correct. Is that not used by default?

**Comment by madjam** [comment]
what version of Fedora is this tested on? We have CI tests for validating installation instructions. Not sure if Fedora is popular enough to warrant being tested in CI.
@sandeep-krishnamurthy what do you think?

**Comment by kottmann** [comment]
@madjam I tested this with Fedora 26, and let me test it as well with Fedora 25. Older versions are not supported anymore.

**Comment by sandeep-krishnamurthy** [comment]
@kottmann - Thank you for the contribution. However, I see below issues to accept this contribution.

1) We do not have CI setup for Fedora distribution.
2) Due to very few customer/developer base, I do not see it as the higher priority task that will be planned soon. 
3) Without tests, I see a greater risk in having the installation guide on the docs site. As it can lead to broken installation guide and we will never notice.
4) Following the Ubuntu installation guide, I am hopeful that users will be able to find equivalent installation command for Fedora.

**Comment by kottmann** [comment]
@sandeep-krishnamurthy I think it would also add value without CI, because it will make it easier for people to figure it out them self and if it is broken they could also send a PR to fix it again.

About point 4, today you still need to add this include /usr/include/openblas manually, maybe we can somehow fix that in the build and people would get away transforming the Ubuntu steps to Fedora. 
Do you think it would be worth fixing that?

**Comment by sandeep-krishnamurthy** [comment]
@kottmann that is a good suggestion - Can you please open a different PR for that?

**Comment by kottmann** [comment]
The proposed steps also work with Fedora 25.

**Comment by piiswrong** [comment]
The instruction for ubuntu and fedora is mixed together. Would be better to add a selection button.

Close for now. Let's revisit in the future to list instructions for different distributions.

**Pull request closed without merging**
