### PR TITLE
[MXNET-507] Set arbitrary dtype for ret_indices in ordering ops

### PR DESCRIPTION
**Pull request by sxjscience**
## Description ##
Continue https://github.com/apache/incubator-mxnet/pull/11134

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Arbitrary dtype of indices for ordering operators, tests
- [x] For topk, argsort, add the dtype option to specify the type of the output indices, tests
- [x] Fix the bug that ordering ops do not support kNullOp, tests
- [x] Fix the doc of topk to state the the elements are sorted.

## Comments ##
- Currently, the operator do not support to have input dtype=float16.

### CODE REVIEW

**Comment by szha** [comment]
cc'd @ciyongch @pengzhao-intel

**Comment by leezu** [comment]
@sxjscience would it make sense to point out in the documentation that not specifying integer dtype may lead to the issues described in https://github.com/apache/incubator-mxnet/pull/11134

**Comment by sxjscience** [comment]
Yes, I think we need to add the doc to encourage the user to use int32.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leezu** [comment]
@szha @sxjscience it seems this was merged without the documentation being updated.

**Comment by szha** [comment]
good catch. @sxjscience could you make another PR for the doc update?

**Pull request merged**
