### PR TITLE
[FEATURE] Add binomial sampling and fix multinomial sampling

### PR DESCRIPTION
**Pull request by IrishWhiskey**
## Description ##
I implemented the binomial and multinomial sampling. I also renamed the previous multinomial implementation to categorical.

### CODE REVIEW

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu, centos-cpu, website, miscellaneous]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu, centos-gpu, website, miscellaneous, windows-gpu]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu, centos-gpu, website, miscellaneous, windows-gpu]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-gpu, centos-gpu, windows-gpu]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Comment by IrishWhiskey** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by szha** [comment]
@IrishWhiskey thanks for the contribution!

**Comment by IrishWhiskey** [comment]
@szha thanks for reviewing :)

**Pull request merged**
