### PR TITLE
Fix broken website build pipeline

### LINKED ISSUE #11810: website build and deploy failing
Seems like a new param was injected into the build process which is causing the site builds to fail.
Maybe this... added six hours ago...
https://github.com/apache/incubator-mxnet/pull/11779/files#diff-709fab86767b8ea8dc16edf75a346144R54

```
[docs] Running shell script
+ ci/build.py -p ubuntu_cpu --docker-registry mxnetci %USE_NVIDIA% --docker-build-retries 3 /work/runtime_functions.sh build_docs master;1.2.0;1.1.0;1.0.0;0.12.0;0.11.0 master;1.2.0;1.1.0;1.0.0;0.12.0;0.11.0 master http://mxnet.incubator.apache.org/
usage: build.py [-h] [-p PLATFORM] [--build-only] [-a] [-n]
                [--shm-size SHARED_MEMORY_SIZE] [-l] [--print-docker-run] [-i]
                [-d DOCKER_REGISTRY] [-r DOCKER_BUILD_RETRIES] [-c]
                [--ccache-dir CCACHE_DIR]
                [command [command ...]]
build.py: error: unrecognized arguments: /work/runtime_functions.sh build_docs master;1.2.0;1.1.0;1.0.0;0.12.0;0.11.0 master;1.2.0;1.1.0;1.0.0;0.12.0;0.11.0 master http://mxnet.incubator.apache.org/
```

### PR DESCRIPTION
**Pull request by szha**
## Description ##
fix for #11810 due to #11779 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] remove excess placeholder

### CODE REVIEW

**Comment by szha** [comment]
@aaronmarkham @KellenSunderland

**Comment by marcoabreu** [comment]
Sorry, this was my bad! Thanks for noticing and the fix. Please excuse the inconvenience.

**Comment by cclauss** [comment]
This PR could have a more descriptive / helpful name.  ;-)

**Comment by marcoabreu** [comment]
I have changed the name

**Pull request merged**
