### PR TITLE
[v1.x] Backport "Add missing license header for md files (#18541)"

### PR DESCRIPTION
**Pull request by szha**
## Description ##
Backport "Add missing license header for md files (#18541)" to v1.x

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Backport "Add missing license header for md files (#18541)" to v1.x

### CODE REVIEW

**Comment by szha** [comment]
cc @samskalicky @sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
Thank you very much @szha

**Comment by sandeep-krishnamurthy** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Comment by sandeep-krishnamurthy** [comment]
mxnet-bot run ci [unix-gpu-cu110]

**Review by ChaiBapchya — APPROVED** [review]
Thanks!

**Pull request merged**
