### PR TITLE
[v1.9.x] Cherry-pick ArmPL changes from v1.x

### PR DESCRIPTION
**Pull request by mseth10**
## Description ##
Cherry pick https://github.com/apache/incubator-mxnet/commit/e37dfda27e90abad145f974bb4091a4e8b5ce25b https://github.com/apache/incubator-mxnet/commit/2d891d993b8fbe440829f9dc50c56b2ff8627862 https://github.com/apache/incubator-mxnet/commit/247899ad82ca44fa4226ac34ebe0e0bf2bde7f9e

### CODE REVIEW

**Review by Zha0q1 — APPROVED** [review]
LGTM! would you also start a test cd run?

**Comment by josephevans** [comment]
I think you also need https://github.com/apache/incubator-mxnet/pull/20357 to get the CI tests to pass.

**Review by josephevans — APPROVED** [review]
You may also need to cherry-pick https://github.com/apache/incubator-mxnet/pull/20357 to get the CI tests to pass.

**Comment by mseth10** [comment]
> LGTM! would you also start a test cd run?

These commits are already tested in CD pipeline of v1.x branch https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-mxnet-cd%2Fmxnet-cd-release-job-1.x/activity

**Comment by mseth10** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by mseth10** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Pull request merged**
