### PR TITLE
[BUGFIX] Fix floor divide

### PR DESCRIPTION
**Pull request by Kacper-Pietkun**
## Description ##
Incorrect rounding of a number.

```
import numpy as onp
import mxnet as mx


onp_d1 = onp.array([0.941], dtype=onp.float16)
onp_d2 = onp.array([0.1569], dtype=onp.float16)
mx_d1 = mx.numpy.array(onp_d1, dtype=onp.float16)
mx_d2 = mx.numpy.array(onp_d2, dtype=onp.float16)

# 0.941 / 0.1569 = 5.997450605481198
onp_out = onp.floor_divide(onp_d1, onp_d2)  # onp_out = [5.] <= GOOD
mx_out = mx.np.floor_divide(mx_d1, mx_d2)  # mx_out = [6.] <= WRONG
```

## Cause ##
Incorrect rounding was caused by unnecessary implicit conversion from float to float16 after division but before rounding (5.99745 was saved as 6 during conversion from float to float16, because of lack of precision).

## Solution #
From now, before doing calculations float16 arguments are explicitly casted to float and they are converted back to float16 only after division and rounding has been made.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage

### CODE REVIEW

**Review by bartekkuncer — APPROVED** [review]

**Review by agrabows — COMMENTED** [review]
Please add yourself to contibutors.md file.

**Review by anko-intel — APPROVED** [review]

**Comment by Kacper-Pietkun** [comment]
[@mxnet-bot](https://github.com/mxnet-bot) run ci [centos-cpu]

**Comment by Kacper-Pietkun** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by Kacper-Pietkun** [comment]
@mxnet-bot run ci [centos-gpu]

**Pull request merged**
