### PR TITLE
refactor: handle mshadow as cmake target

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Refactor to localize mshadow related configuration in `3rdparty/mshadow` and expose everything as a cmake target. Previously mshadow was configured with global variables and configuration was placed all around the mxnet cmake file.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [X] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [X] cmake: handle mshadow as target

### CODE REVIEW

**Comment by leezu** [comment]
Ping @yajiedesign @szha

**Comment by leezu** [comment]
Ping @yajiedesign @szha

**Comment by leezu** [comment]
I'll merge this based on lazy consensus in 72 hours.

**Comment by yajiedesign** [comment]
LGTM

**Comment by TaoLv** [comment]
Sorry, why there is no BLAS/MKL related instructions in the cmake file? They exist in the Makefile of mshadow. See, https://github.com/apache/incubator-mxnet/blob/master/3rdparty/mshadow/make/mshadow.mk#L74.

**Comment by leezu** [comment]
There is cmake/ChooseBlas.cmake file. What do you mean?

**Comment by TaoLv** [comment]
Okay, sorry for missing that. I was wondering how does mshadow cmake handling the BLAS build flags like MSHADOW_USE_MKL and how the MKL library statically linked like the logic in mshadow.mk. But seems it another problem now.

**Comment by leezu** [comment]
> Okay, sorry for missing that. I was wondering how does mshadow cmake handling the BLAS build flags like MSHADOW_USE_MKL and how the MKL library statically linked like the logic in mshadow.mk. But seems it another problem now.

No worries. The `cmake/ChooseBlas.cmake` will be replaced by https://cmake.org/cmake/help/latest/module/FindBLAS.html and https://cmake.org/cmake/help/latest/module/FindLAPACK.html in the future. The build flags like `MSHADOW_USE_MKL` are a separate problem. Do you have any change in mind for them @TaoLv?

**Comment by TaoLv** [comment]
@leezu, I tried to build mxnet from source code with cmake and found that `libmkl_rt.so` is linked. Previously in makefile, we support both statically and dynamically linking, and statically linking by default.

**Comment by leezu** [comment]
@TaoLv did you try running with `cmake -DMKL_USE_STATIC_LIBS=1 [...]`.

See

https://github.com/apache/incubator-mxnet/blob/7895f93e67dc3e9da360f7a9c667e3c0f1e76c0f/cmake/Modules/FindMKL.cmake#L18-L35

**Comment by TaoLv** [comment]
No, I didn't. So at least the default behavior is different from makefile.

**Comment by leezu** [comment]
@TaoLv we can change the behavior, if you recommend to do so. Would you recommend that?

**Comment by TaoLv** [comment]
Personally I will recommend static linking just as the default behavior of makefile. :)

**Pull request merged**
