### PR TITLE
[v2.0] Update Examples

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
After migrating to Gluon2.0, most of the examples in master branch will not work any more. This pr will temperarily remove these out-dated examples and adapt some of the examples to use Gluon2.0. Once those removed examples are compatible with master branch, I will add them back. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-cpu, miscellaneous, unix-cpu, unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [windows-gpu, unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Review by szha — APPROVED** [review]

**Pull request merged**
