### PR TITLE
[MXNET-305] Scala tutorial table fix

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##

Fixes a table in the scala intellij tutorial.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@eric-haibin-lin - can you please merge?

**Comment by eric-haibin-lin** [comment]
screen shot 2018-04-11 at 9 38 47 am

Some texts are not well-aligned. Could you fix that? 
> From the IntelliJ welcome screen ...

**Comment by aaronmarkham** [comment]
GitHub doesn't render markdown the same way that Atom's plugin does. Oh joy. Spacing added.

**Comment by eric-haibin-lin** [comment]
Maybe also fix this ? 
screen shot 2018-04-11 at 11 53 25 am

Please check http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-10488/2/tutorials/scala/mxnet_scala_on_intellij.html

**Comment by anirudh2290** [comment]
@aaronmarkham can you also address the image rendering after "Run the Hello World App:" as pointed out by @eric-haibin-lin

**Comment by anirudh2290** [comment]
Sorry, my bad. I see it is fixed in the latest commit. @eric-haibin-lin does this look good to merge ?

**Pull request merged**
