### PR TITLE
change default arc to Common

### PR DESCRIPTION
**Pull request by yajiedesign**
## Description ##
change default arc to Common

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage

~~~- [ ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented.~~~

~~~- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change~~~

### Changes ###


## Comments ##

### CODE REVIEW

**Comment by yajiedesign** [comment]
`Common` is small then `All` arc. it exclude 3.2 3.7 5.3. yes you can set it.
yes ,if cpu machine with gpu enabled it default `All` and this PR is change default behavior. from `All` to `Common`.

**Comment by yajiedesign** [comment]
or we consider a smaller subset as the default value?

**Comment by cjolivier01** [comment]
The normal (previous) behavior is to detect the exact version of the architecture being built upon.
In mshadow/cmake/Cuda.cmake:
  function(mshadow_detect_installed_gpus out_variable)

**Comment by cjolivier01** [comment]
@piiswrong Can we safely exclude CUDA architectures:  3.2 3.7 5.3 ?
I recall there was some pushback when someone (me or you, I don't recall) tried to obsolete an old architecture, about a year ago.

**Comment by piiswrong** [comment]
Why are 3.2 3.7 5.3 not common?

**Comment by yajiedesign** [comment]
@piiswrong 
3.2 5.3 is only Tegra and Jetson.
3.7 is only K80

**Comment by cjolivier01** [comment]
IMHO, All is better than "Common", but we should be able to override with CUDA_ARCH_ALL=52 (for example), and if there's no override, then auto-detect the current architecture like the other Cuda does (probably that part can be copy-pasted).
wdyt?

**Comment by piiswrong** [comment]
I'm ok with disabling Tegra and Jetson. K80 should be kept.

**Pull request merged**
