### PR TITLE
cuda support for linalg-functions, restructuring of linalg interfaces

### PR DESCRIPTION
**Pull request by asmushetzel**
Linear algebra operators are now restructured to following interfaces (and cuda support has been added):

- c_lapack_api.h : Header to integrate lapack functions on CPU

- linalg.h:  Tensor based interface to call linear algebra operators on gpu/cpu in a unified way

- la_op.cc/la_op.cu: Operators that expose these functions to a user. 

The whole implementation of cpu/gpu handling is in linalg_impl.h. It turned out that there are various specialties when dealing with cuBlas/cuSolver for the different functionalities, so decided to hide this in a separate file and not clutter the interface (linalg.h) with all these details. 

We are planning to add more functions in the future (and other people are planning this too). So hopefully we can ensure that this structure is used as much as possible for new additional linear algebra functionalities. 

This PR requires PR 274 for mshadow as prerequisite. 

The CUDA functions still have to be tested. Am in the process of doing so but would like to send the changes already now for review.

### CODE REVIEW

**Comment by jli05** [comment]
I'm just thinking, would you mind submitting just one PR with just one Wiki page (if we could open up the Wiki functionality on the repo) about the functions you plan to add? Prof Anima Anandkumar's team is also working on tensors and there may be much overlapping in work. It'd be great if we could have a clear summary design before coding. @JeanKossaifi

**Comment by piiswrong** [comment]
Can we move include/mxnet/c_lapack_api.h to src?
I feel like these functions should be used through operators and not visible externally

**Comment by asmushetzel** [comment]
This means that we also move linalg.h to src.  Which specific directory have you in mind? src/operator/tensor or src/common?

Concerning more operators: We (our group in Berlin/Cambridge) will likely add QR-decomposition as well (and potentially 1-2 minor ones). 
I will try to sort the planning out in 3 weeks when I'm in Palo Alto. There are even more stakeholders involved. Agree that it is currently not clear who all wants to do/have what.

**Comment by asmushetzel** [comment]
Will wait with further updates for this PR until we got the prerequisite PR 274 from mshadow in.

**Comment by piiswrong** [comment]
doesn't seem to be building

**Comment by piiswrong** [comment]
somewhere under src
can it be put in src/operator/linalg?

**Comment by asmushetzel** [comment]
Makes a lot of sense. The linalg-stuff will grow and it deserves it's own directory then. 
Just for status: I had almost zero time in the last two weeks for this. Will try to finish next week (the CUDA-tests have problem, regardless what Jenkins shows here).

**Comment by DickJC123** [comment]
What is the status on readying this PR for acceptance?  We're considering adapting this code to support NVIDIA's new Volta/TensorCore technology.

**Comment by asmushetzel** [comment]
It's in the final rounds of testing. Goal is to have it integrated next week.
It would be awesome if you can put Volta/Tensorcore in there. Another topic that I discussed with Marek Kolodziej is whether NVidia people can also investigate ways how to do more efficient batch-implementations of potrf/trmm. One important use case will be having a batch of relatively small matrices and there the current implementation won't be that great (and cuBlas/cuSolver miss native batch processing for these operations).

**Comment by asmushetzel** [comment]
Should all be o.k. now but Jenkins seems to be non-responsive. Have to wait until it is up again.

**Pull request merged**
