### PR TITLE
[BUGFIX] Fix test_bf16_binary_broadcast_elemwise_mixed_input

### PR DESCRIPTION
**Pull request by agrabows**
## Description ##
Fix bug that appeared on CI:
MXNET_TEST_SEED=384773208 pytest /home/agrabows/repository/incubator-mxnet/tests/python/dnnl/test_bf16_operator.py::test_bf16_binary_broadcast_elemwise_mixed_input[float32-add]

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage

## Comments ##
- Better support for broadcasting is considered to be done in the future.

### CODE REVIEW

**Comment by agrabows** [comment]
@mxnet-bot run ci [windows-gpu, unix-cpu, centos-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu, website, windows-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu, website, windows-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [unix-cpu, windows-gpu]

**Comment by bgawrych** [comment]
Shouldn't be there check earilier that broadcasting does not support >5 dimensions (e.g. infer shape)?

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu, miscellaneous, unix-gpu, website, windows-gpu, clang]

**Comment by agrabows** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by agrabows** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [website]

**Comment by agrabows** [comment]
@mxnet-bot run ci [website]

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu, unix-cpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by agrabows** [comment]
@mxnet-bot run ci [unix-gpu]

**Review by bgawrych — APPROVED** [review]

**Pull request merged**
