### PR TITLE
Update multi-task learning example

### PR DESCRIPTION
**Pull request by ThomasDelteil**
## Description ##

- Remove symbolic implementation
- add gluon implementation with actual multi-task

@ankkhedia I remember you asked about a multi-task learning implementation a while ago, you can have a look at that one and tell me what you think

### CODE REVIEW

**Comment by roywei** [comment]
@ThomasDelteil Thanks for the contribution!
@mxnet-label-bot [pr-awaiting-review]

**Comment by roywei** [comment]
@mxnet-label-bot [pr-awaiting-merge,Example]

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy Could you please merge this PR as it has been approved.

**Comment by sandeep-krishnamurthy** [comment]
@aaronmarkham - FYI. New example. Can you take a look at this?

**Comment by aaronmarkham** [comment]
Curious why this can't be in /tutorials and have the main notebook source (of truth) be in markdown?

**Comment by ThomasDelteil** [comment]
@aaronmarkham I am doing a first pass on the examples where I do one of:
- fix
- delete
- replace with Gluon
depending on the state and complexity of each example

The second pass of the work will include a restructure of the folder architures, move to tutorials etc.

**Comment by ankkhedia** [comment]
@aaronmarkham Could you please look into this PR?

**Comment by Ishitori** [comment]
Looks good to me.

**Comment by anirudhacharya** [comment]
@nswamy @anirudh2290 for review/merge.

**Pull request merged**
