### PR TITLE
Julia: rename `mx.clip` to `clamp` for `NDArray`

### PR DESCRIPTION
**Pull request by iblis17**
- in order to match Base interface

- depwarn for `mx.clip` included

## Checklist ##

- [x] Changes are complete
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by iblis17** [comment]
There is a API name `clamp`, which functionality is same as `mx.clip`, in Julia's stdlib.

e.g.
```julia
julia> A = [1,2,3,4,5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> clamp.(A, 3, 4)
5-element Array{Int64,1}:
 3
 3
 3
 4
 4
```

So I renamed and make it overload the `clamp` function for type `NDArray`.

**Comment by larroy** [comment]
Why not leave both?

**Comment by iblis17** [comment]
I'm ok if making aliasing is an acceptable option.

**Comment by wkcn** [comment]
This PR has been merged.
Thanks for your contribution!

**Pull request merged**
