### PR TITLE
[MXNET-716] Adding Scala Inference Benchmarks

### PR DESCRIPTION
**Pull request by piyushghai**
## Description ##
Added a base wrapper class to benchmark Scala Inference examples. The class runs single inference and batch inference calls and emits the the inference time taken in easy to consume metrics :  p50, p99 and average. 

There is also an attached README indicating the usage, as well as an example ```ImageClassifierExample``` using Resnet-152 to show how the tool can be used. 
A simple run of the benchmark class with the provided ```run_image_inference_bm.sh``` produces the following sample output when run locally on a MacBook Pro : 

```
[main] INFO org.apache.mxnetexamples.benchmark.CLIParserBase - 
single_inference_p99 1663, single_inference_p50 729, single_inference_average 755.170000
...        
INFO org.apache.mxnetexamples.benchmark.CLIParserBase - 
batch_inference_p99 4241, batch_inference_p50 4241, batch_inference_average 4241.000000
```

More examples around this tool are under development and will be contributed soon by @lanking520 ( Thanks for helping out on this! ) 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by vrakesh** [comment]
@mxnet-label-bot [pr-awaiting-review]

**Comment by vrakesh** [comment]
@mxnet-label-bot [scala]

**Comment by gigasquid** [comment]
Looks good to me. Nice improvement.

A quick question :
- Out of curiosity, can you use this to compare the Scala to the Python benchmarks now?
If so, how does the Scala benchmarks compare to the Python ?

**Comment by piyushghai** [comment]
Thanks @gigasquid, that's a (not-so-long-term) goal of this exercise, to be able to compare the inference times across languages. 
We are making a start with Scala and would love to extend it to other language bindings. 
More on this coming soon...

**Comment by gigasquid** [comment]
@piyushghai I believe there is already one in use in python https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/benchmark_score.py 

The results are posted here https://mxnet.incubator.apache.org/faq/perf.html#scoring-results
Shouldn't we be able to compare that against the Scala RESNET-152?

**Comment by piyushghai** [comment]
@gigasquid Thanks for pointing out the script, I will look into it. :) Primarily for this PR, we want to be able to draw a comparison with the upcoming new Java APIs.

**Pull request merged**
