### PR TITLE
[MXNET-875] pass global step and names of params to callback function stat_func i…

### PR DESCRIPTION
**Pull request by knwng**
…n class Monitor

## Description ##
(Brief description on what this PR is about)
pass global step and parameters' names to Monitor's callback function stat_func, so that mxboard can be easily integrated into fit() interface for visualization.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by stu1130** [comment]
@knwng could you fix the unit test? let us know if you need help!

**Comment by stu1130** [comment]
Thanks for the contribution! @knwng
could you please fix the unit test? let us know if you need help!

**Comment by vandanavk** [comment]
@mxnet-label-bot [pr-awaiting-response]

**Comment by knwng** [comment]
@stu1130 thank you for your attention! I'm still working on it. I'm not familiar with CI tools yet but I'd like to have another try(if it won't cause too many troubles). 😃

**Comment by vrakesh** [comment]
@knwng Hope you troubles with the CI tools are resolved :) Requesting an update on addressing the build failures

**Comment by Roshrini** [comment]
@knwng ping again to see if there is any update on this PR :)

**Comment by ankkhedia** [comment]
@knwng ping! :)

**Comment by kalyc** [comment]
@knwng we are looking forward to merging your changes. Please let us know if this PR cannot be completed at the moment and close it; you can re-open another PR whenever you have the time

**Comment by vandanavk** [comment]
@mxnet-label-bot update [pr-awaiting-testing]

**Comment by roywei** [comment]
@knwng  Thanks for the contribution, could you help re-trigger our CI by push an empty commit?

**Comment by Roshrini** [comment]
@knwng Thanks for the contribution. Do you need any help to move forward with this PR? Thanks

**Comment by stu1130** [comment]
@knwng since the PR is inactive for a while, we will close it. Feel free to reopen it if you have time to work on it. Please let us know if you need our help! :) @sandeep-krishnamurthy could you close it

**Pull request closed without merging**
