### PR TITLE
Fast cuDNN BatchNorm NHWC kernels support

### PR DESCRIPTION
**Pull request by mk-61**
## Description ##
This PR makes cuDNN-backed BatchNorm operator use newer API calls (cudnnBatchNormalizationForwardTrainingEx / cudnnBatchNormalizationBackwardEx), which bring in significant speed up in some cases (fp16 NHWC / NDHWC layouts).

I also refactored and simplified code a bit.

I tested fp16 NHWC speedup on my Layout Management feature branch (not up-streamed yet) on ResNet50 model.
The correctness should be covered by existing tests.

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Make use of newer cuDNN API calls / new kernels
- [x] Refactoring

@DickJC123

### CODE REVIEW

**Comment by mk-61** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, website]

**Comment by mk-61** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by ptrendx — APPROVED** [review]
LGTM, did you also check the performance of NCHW case?

**Comment by mk-61** [comment]
> LGTM, did you also check the performance of NCHW case?

You mean compared to functions without "Ex" suffix? Not, I haven't, can do if you like me to. Although I think the logic behind "Ex" functions is "make it faster in some case and fallback to the previous implementations otherwise". Specifically, I expected (and verified) speedup in FP16/NHWC, assumed it shouldn't regress in other cases, unless there's a bug, which cuDNN would need to fix.

**Comment by ptrendx** [comment]
Yeah, it would be good to check that NCHW does not regress.

**Comment by mk-61** [comment]
> Yeah, it would be good to check that NCHW does not regress.

Verified on RN50 / Volta - no regressions and the same kernels used, as far as nsys stats show.

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ptrendx** [comment]
Thanks for the contribution!

**Pull request merged**
