### PR TITLE
Add more gluon computation test on MKLDNN with memory operation(s)(slice, reshape etc.)

### PR DESCRIPTION
**Pull request by juliusshufan**
## Description ##
This PR introduces more test cases to cover the gluon computation on MKLDNN with ndarray related memory operations, such as slice, reshape etc. I am also implementing more test cases covering more gluon computations involving MKLDNN (such as BN, pooling etc.), and will be reflected in standalone PR(s) accordingly.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
All the changes is reflected by tests/python/mkl/test_mkldnn.py

## Comments ##
1. For the correctness check on gluon computation, it follows the design used by tests/python/unittest/test_gluon.py, and therefore, the helper functions defined in tests/python/unitest/common.py is also used.
2. A minor change on the existing test case in same source file is just addressing the additional module import supporting the newly added test cases.

### CODE REVIEW

**Comment by juliusshufan** [comment]
@zheng-da @pengzhao-intel

**Comment by ashokei** [comment]
@juliusshufan @piiswrong we cannot import mxnet in this test, as one of the unittests test if we can load mxnet properly. May be we could move that test to separate file.

**Comment by ashokei** [comment]
@piiswrong made changes here https://github.com/apache/incubator-mxnet/pull/10591

**Comment by juliusshufan** [comment]
@ashokei Hi Ashok, if I hope keep these cases in same source file, I need to import the mxnet module for each case separately similar to the existing cases, right? If this is the right understanding, I'll make changes in next PR. Thanks.

**Comment by ashokei** [comment]
I think it is good idea to move the test_mkldnn_install to separate file, i made changes in #10591 . Your changes are ok.

**Comment by pengzhao-intel** [comment]
Good job @juliusshufan !
It's really what we need to verify the quality of new MKL-DNN backend.
In the future, we will add more test cases for the CPU.

Thanks, @piiswrong for the review and merging.

**Comment by zheng-da** [comment]
to be honest, i was a little surprised that the test is passed. i expect mkldnn conv doesn't work on an ndarray generated as a view of a MKLDNN NDArray (i.e., a slice from the mkldnn conv output). maybe we should take a little closer look at the C++ code how it works.

**Comment by ashokei** [comment]
I notice these tests seem to just use nchw.

@juliusshufan i would consider using tensor shapes of (32,3,224,224), this would trigger mkldnn layout conversions.

**Comment by juliusshufan** [comment]
@ashokei Thanks for comments, I might take a trial and make amendment.

**Pull request merged**
