### PR TITLE
Enable smoothing in softmax operator

### PR DESCRIPTION
**Pull request by KellenSunderland**
As proposed by @fhieber in #6996 this PR helps reduce memory usage when using smoothing during softmax computation by doing the smoothing directly in the operator.  This modification was tested by @tdomhan and I and we found it reduced memory usage during training on a typical MT model by ~ 3GB.  

This PR should be backwards compatible.  

This PR will require https://github.com/dmlc/mshadow/pull/295 to be in place before it will be able to be merged.

### CODE REVIEW

**Comment by KellenSunderland** [comment]
Mshadow modifications have been made, so this should now be able to merge after code review + CI passes.

**Comment by fhieber** [comment]
@piiswrong Any chance we can get this into the 0.12 release?

**Comment by KellenSunderland** [comment]
I'd love to get this into the .12 release, but let's hold off on the merge until tests are passing.  This failure is triggered by our code change, even if it's not directly related.

**Comment by KellenSunderland** [comment]
Looks like it was our test that was causing a failure in an unrelated test.  I've amended the PR, it should be mergable. @fhieber @piiswrong

**Comment by piiswrong** [comment]
Please resolve conflict.

BTW, is there a more common/standard name of smooth_alpha?

**Comment by cjolivier01** [comment]
I attempted to resolve the conflict, looks like a simple matter of two branches adding unit tests in the same part of the file.

**Comment by fhieber** [comment]
thanks for looking into this!

Regarding the parameter name, the vision community introduced it as ``epsilon``(https://arxiv.org/pdf/1512.00567.pdf), but it's really just a form of exponential/'alpha' smoothing, so I am not sure I have a better name at this point.

**Comment by KellenSunderland** [comment]
Thanks for getting this one in, big impact for our team.

**Pull request merged**
