### PR TITLE
Fix script retrieval

### PR DESCRIPTION
**Pull request by vandanavk**
## Description ##
Removing reference to CI scripts in documentation

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Change to do generic installation

### CODE REVIEW

**Comment by vandanavk** [comment]
@mxnet-label-bot add [Java, Doc, pr-awaiting-review]

**Comment by vandanavk** [comment]
@mxnet-label-bot update [Java, Doc, pr-awaiting-merge]

**Comment by marcoabreu** [comment]
FYI, This file is not intended for enduser usage and I'd not recommend linking it in any documentation.

**Comment by vandanavk** [comment]
@marcoabreu Changed the command to use generic installation. Can these instructions be used now that CI scripts are not referenced?

@lanking520 for review

**Comment by wkcn** [comment]
Thank you!

**Pull request merged**
