### PR TITLE
[BUGFIX] Fix workspace of BoxNMS

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
This commit fixes 2 problems:
 - previously in the calculation of the workspace size of NMS operator the space for the buffer was not included, resulting in potentially too small allocation
 - because the type requested for `uint8_t`, the maximum workspace size without setting large tensor support was 2GB, which was too small for some cases, without any error reporting (going over that limit would make the index_t in Shape1 overflow, resulting in negative value, which would later be cast to size_t in the allocator and MXNet would try to allocate a huge amount of memory, resulting in OoM). This PR changes the type of the allocation to double so that the size limit for workspace rises to 16 GB when large tensor support is not enabled. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-gpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-cpu]

**Review by DickJC123 — APPROVED** [review]
This looks like an appropriate fix for this operator.  LGTM.

**Pull request merged**
