### PR TITLE
Round and sign straight-through-estimators C operators.

### PR DESCRIPTION
**Pull request by igolan**
## Description ##
Implemented sign and round straight-through-estimators operators in C.
Straight-through-estimators have derivative of 1 everywhere instead of 0 everywhere, this is required for quantized training.

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are not affected by this change.

### Changes ###
- [x] contrib.round_ste() including test and API doc
- [x] contrib.sign_ste() including test and API doc

## Comments ##
N/A

### CODE REVIEW

**Comment by sxjscience** [comment]
@szhengac @xidulu I think the stochastic version of straight-through estimator is related to the distribution package.

**Comment by igolan** [comment]
@sxjscience , just to clarify, it's not a stochastic version of round/sign, it's just round and sign with derivative of 1 (instead of 0).

**Comment by sxjscience** [comment]
@igolan Yes, just to ping the other people to see if we could merge the efforts.

**Comment by xidulu** [comment]
@sxjscience 
You are right, `straight through estimator` could be useful when performing hard assignment on relaxed discrete variable. (e.g. https://arxiv.org/pdf/1611.01144.pdf section 2.2).

**Pull request merged**
