### PR TITLE
Revert "Many loss functions  (#7605)"

### PR DESCRIPTION
**Pull request by piiswrong**
This reverts commit 9d56db66e2e94a8a3d9bf020b9682e91e7baf203.

revert before names/comments/tests are fixed

### CODE REVIEW

**Comment by szha** [comment]
Shouldn't you at least talk to the contributor before reverting this?

**Comment by szha** [comment]
For the record, I've been helping @smolix cleaning up the naming in #8007, cleaning doc in #7914.

**Comment by piiswrong** [comment]
This is a large amount of untested user facing code. That's enough ground for a veto.

**Comment by szha** [comment]
Has there been known bugs or issues? If not, I'd suggest that a better path is forward, by applying the appropriate fixes. #7605 was opened a month ago and there has been plenty of time for you and other reviewers to look at and comment on that PR.

**Comment by piiswrong** [comment]
Roll back is always better than fix forward. This is directly user facing top level API. It needs to be tested.

**Comment by szha** [comment]
Only when there's known bug in the code, at which time we should roll back the part with bugs.

**Comment by piiswrong** [comment]
For one thing, the names are inconsistent.

**Comment by thatindiandude** [comment]
I think rudimentary tests aren't much too ask for. This would expose such
bugs that currently aren't known.

The idea that you can push untested code because a known bug doesn't exist
contradicts test-driven development principles.

**Comment by szha** [comment]
Like I commented in the third comment, the naming has been fixed in #8007

**Comment by piiswrong** [comment]
That's fixing forward on untested code.

**Pull request merged**
