### PR TITLE
[BUGFIX] Fix Precision

### LINKED ISSUE #20420: [2.0] Precission loss when exporting a model from 2.0
Here's a simple model which just has one operator:
```
    def forward(self, a):
        return a - 37.38088245350211

```
This model will export this symbol file:
```
{
  "nodes": [
    {
      "op": "null",
      "name": "data",
      "attrs": {"__profiler_scope__": "<unk>:"},
      "inputs": []
    },
    {
      "op": "_npi_subtract_scalar",
      "name": "node_0",
      "attrs": {
        "is_int": "0",
        "scalar": "37.3809"
      },
      "inputs": [[0, 0, 0]]
    }
  ],
  "arg_nodes": [0],
  "node_row_ptr": [0, 1, 2],
  "heads": [[1, 0, 0]],
  "attrs": {
    "is_np_shape": ["int", 1],
    "mxnet_version": ["int", 20000]
  }
}
```
as we can see here the scalar only has 4 digits precision after the decimal point.

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
fix #20420 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Review by Zha0q1 — APPROVED** [review]
lgtm! thanks for the quick fix!

**Review by leezu — APPROVED** [review]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu]

**Comment by Zha0q1** [comment]
looks like some sources used in unix-gpu and miscellaneous are still in sync..

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
