### PR TITLE
[Community] add @ciyongch as a new committer

### PR DESCRIPTION
**Pull request by szha**
### Description ###

Please join me in welcoming Ciyong Chen (@ciyongch) as our new committer. He is our 1.7.0 release manager and he helped work through many issues during the release process and towards the end he shared very useful summary on how we could improve our release process in #19029. Prior to that, Ciyong has contributed to important components related to MKLDNN integration, along with several other operator implementations and bug fixes.

PRs: https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+author%3Aciyongch+
Issues he participated: https://github.com/apache/incubator-mxnet/issues?q=is%3Aissue+involves%3Aciyongch+
Code reviews: https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+reviewed-by%3Aciyongch+

### Changes ###
- [x] add Ciyong Chen as a new committer

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Congratulations @ciyongch 
Well deserved!

**Review by ChaiBapchya — APPROVED** [review]

**Review by mseth10 — APPROVED** [review]
Congrats @ciyongch . Well deserved! 👍🏽

**Comment by kshitij12345** [comment]
Congrats @ciyongch!
Great Job!!

**Review by pengzhao-intel — APPROVED** [review]
Congratulations!

**Pull request merged**
