### PR TITLE
[v1.7] Fix the monitor_callback invalid issue during calibration with variable input shapes

### PR DESCRIPTION
**Pull request by ciyongch**
## Description ##
Backport #18632 to addressed the calibration invalid issue with variable input shapes.

@szha @TaoLv @ChaiBapchya

### CODE REVIEW

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
Hi @TaoLv @szha @leezu @ChaiBapchya , please help to take a review and merge.

**Comment by TaoLv** [comment]
I just rebased your source branch. @ciyongch

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ciyongch** [comment]
Hi @TaoLv , please help to merge.

**Pull request merged**
