### PR TITLE
[MXNET-134] Don't do imperative bulk when profiling aggregate stats

### PR DESCRIPTION
**Pull request by cjolivier01**
https://issues.apache.org/jira/browse/MXNET-134

## Description ##
When profiling aggregate stats, `ImperativeBulk()` will group many ops together, making the aggregate statistics nonsensical and useless.  

This change keeps the bulk size as zero when profiling aggregate stats, so that operator statistics are kept separate.  This has a slight performance hit, although recording aggregate stats *already* has a slight performance hit, so it isn't introducing anything new in that area.  This is explained in the python description:

```python
def set_config(**kwargs):
    """Set up the configure of profiler (only accepts keyword arguments).

    Parameters
    ----------
    ...
    aggregate_stats : boolean,
        whether to maintain aggregate stats in memory for console
        dump.  Has some negative performance impact.
    """
   ...
```
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by piiswrong** [comment]
How about making engine->bulk_size always 0 when aggregate is running?

**Comment by cjolivier01** [comment]
the option can be turned on and off at will. I think calling it from Profiler::SetConfig() would be weird

**Comment by cjolivier01** [comment]
Plus, this way it saves it and resores

**Comment by cjolivier01** [comment]
I was thinking about this last night and I think I can come up with a more elegant solution. However, I would prefer not to directly overwrite the bulk size variable because:
1) The whole save/restore thing the way it is done now doesn't seem very thread-safe (or multi-graph safe) since there's only one engine, but possibly many graphs, so there seems to be some disconnect here that may need to be dealt with one day (although it's currently not a problem).  Please correct me if I am wrong here.
2) If profiler sets bulk size to zero, then saves the old value and something else wants to set the bulk size (ie from python), it will both overwrite the 0 set by the profiler and also, when the aggregate is turned off, it will replace the older pre-python-set value.  Because of this, you won;t be able to toggle aggregate or profiling without possibly affecting the deterministic behavior of the *intended* bulk size value

**Comment by cjolivier01** [comment]
Oh, I see -- Engine::bulk_size() is a function...

**Comment by ashokei** [comment]
@cjolivier01 this PR seems to cause issues with MKL-DNN build, is CI done for this. thanks.

**Comment by cjolivier01** [comment]
what problem with mkldnn build?

**Comment by ashokei** [comment]
does not crash if built with `make -j(nproc) USE_MKLDNN=1 USE_PROFILER=1` ;

crashes if built with `make -j(nproc) USE_MKLDNN=1`

**Comment by ashokei** [comment]
i see you have a PR to disable profiler option, please ignore above.

**Pull request merged**
