### PR TITLE
update default windows Visual Studio from 2015 to 2017

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
Currently on CI, windows instances contained both VS2015 and 2017.
However, the default is 2015 and that's the one used for CI Builds
Aim is to update the VSCode build to latest (ideally 2019) but for now transitioning to 2017 (and then to 2019)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Verified by building on Windows with following commands
`py -3 ci/build_windows.py -f WIN_GPU`

**Comment by marcoabreu** [comment]
How did you verify exactly? CI is failing 🙈

**Comment by ChaiBapchya** [comment]
Ooops (I forgot i had manually upgraded the opencv version on windows instance)
Putting a PR on the concerned repo (which builds windows instances) and will retrigger CI once that PR is merged.

**Comment by ChaiBapchya** [comment]
Closing in favor of https://github.com/apache/incubator-mxnet/pull/17962

**Pull request closed without merging**
