### PR TITLE
[MXNET-408] inplace ReLU activation (#10847)

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
Patch the v1.2.0 branch to include the ReLU fix which significantly reduce memory usage for resnet, vgg, etc. Original PR: #10847

### CODE REVIEW

**Comment by rahul003** [comment]
+1 for this change. It's an important fix and helps MXNet favorably in comparisions with other frameworks.
Should we consider making a patch release to ensure it gets out faster?

**Comment by reminisce** [comment]
Agree with @rahul003. This is important in building the reputation of MXNet in terms of performance.

**Comment by anirudh2290** [comment]
+1 for adding this change to 1.2.0. Since historically we have not created new branches for patch releases we should continue with that convention.

**Comment by marcoabreu** [comment]
Could you maybe reference the original PR which you took the changes from?

**Comment by anirudh2290** [comment]
@nswamy can you please make the other changes for scala package related to the patch version bump.

**Comment by eric-haibin-lin** [comment]
Original PR: #10847

**Comment by nswamy** [comment]
@eric-haibin-lin I am handling the version bump for Scala on a separate PR https://github.com/apache/incubator-mxnet/pull/11147

**Comment by nswamy** [comment]
Please wait for https://github.com/apache/incubator-mxnet/pull/11147 to be merged.

**Comment by eric-haibin-lin** [comment]
@nswamy do i only need to handle non-scale version bumps now?

**Comment by eric-haibin-lin** [comment]
@anirudh2290 I've resolved conflicts and bumped the rest of the versions.

**Comment by eric-haibin-lin** [comment]
Doc build is failing. Will that be a blocker, or this PR is good to go?

**Comment by anirudh2290** [comment]
lets wait for https://github.com/apache/incubator-mxnet/pull/11211 @aaronmarkham @marcoabreu will this fix the docs issue ?

**Pull request merged**
