### PR TITLE
Fix quantized graphpass bug

### PR DESCRIPTION
**Pull request by xinyu-intel**
## Description ##
This is a fix of quantize graph pass. This fix can enable resnet-50-v1 quantization locally and may be helpful to issues #11794 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
@pengzhao-intel @reminisce

### CODE REVIEW

**Comment by reminisce** [comment]
Please add a unit test.

**Comment by xinyu-intel** [comment]
@reminisce @pengzhao-intel I've added a test case and passed jenkins:)

**Comment by reminisce** [comment]
@xinyu-intel Thanks for the fix. Is the unit test the one that fails without this PR?

**Comment by xinyu-intel** [comment]
@reminisce yes, both gpu and mkldnn will come across below error when quantizing residual unit like resnet-50-v1:
```
RuntimeError: simple_bind error. Arguments:
data: (4, 4, 10, 10)
softmax_label: (4, 10)
Error in operator _plus0: [08:21:17] /home/chenxiny/mxnet-gpu/3rdparty/mshadow/../../src/operator/tensor/../elemwise_op_common.h:133: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _plus0 at 1-th input: expected float32, got int8
```

**Pull request merged**
