### PR TITLE
Add docker file which includes sample jupyter notebook (#12611)

### PR DESCRIPTION
**Pull request by gautamkmr**
Dockerfile installs and runs the jupyter notebook based on latest released mxnet docker.
Added few sample notebook to get start with mxnet.

## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by gautamkmr** [comment]
@KellenSunderland  @sandeep-krishnamurthy  @mbaijal  @bhavinthaker

**Comment by stu1130** [comment]
Thanks for your contribution @gautamkmr 
@mxnet-label-bot[pr-awaiting-review]

**Comment by gautamkmr** [comment]
@nswamy   I have requested this feature here https://github.com/apache/incubator-mxnet/issues/12611


Regarding sample notebook, we can come up with different set of notebook which can empower user to get started with MXNet from basics. I don't understand why it will create a confusion.

**Comment by gautamkmr** [comment]
@nswamy   I am not sure how many tutorials we have but I don't agree that we should have everything just top 3 for beginners to get start with should be sufficient for docker image. The main purpose here is to get the jupyter notebook experience from docker image.  

Feel free to suggest me top 3 MXNet tutorial I will change it and will add it as a part of CI.

**Comment by KellenSunderland** [comment]
PR feedback: we could run tinypng on these images and compress them a bit further before checking them in.

Is the idea here that it would be nice if users could run a quick docker command and then have a notebook usable with tutorials?

**Comment by nswamy** [comment]
@gautamkmr what are you trying to solve with this? how would you synchronize if changes/bug fixes made to the 3 notebooks on the docs page?

**Comment by gautamkmr** [comment]
@nswamy   I think intent has been clearly defined in the issue. However I am reiterating it basically if user uses mxnet docker image the jupyter notebook experience should be available out of the box.  Its separate question on what/how to keep the tutorial with it. I was trying to get some introduction tutorial.  They can be directly copied from their specified location in that way we dont maintain a new copy. 

@KellenSunderland  Yes thats the idea but having said that for tutorial purpose since its creating a lots of confusion I can just have a notebook which does 'import mxnet and print its version'

**Comment by cjolivier01** [comment]
Does this install ipython on the docker image as new behavior or it was on there before this PR?

**Comment by gautamkmr** [comment]
@nswamy Removed any tutorial. I created a sample notebook which does following

"import mxnet"
"print (mxnet.__version__")

**Comment by nswamy** [comment]
@gautamkmr thanks for making the changes and your understanding. I changed the name of the python notebook to mxnet-test from mxnet-sample since it was just printing the version of MXNet. 
I don't think this particular notebook is useful for the user - may be useful for testing, so I'll leave it there.

**Comment by gautamkmr** [comment]
@nswamy  so whats next step here ?

**Comment by nswamy** [comment]
@gautamkmr I am not convinced about the usefulness of this PR(in my mind `pip install jupyter` is very straightforward) and understandably you'll disagree with that - Lets get more opinions and I am willing to disagree and commit. 

What I liked in your issue was to provide tutorials out of the box but not just sample notebooks copied, i think all the tutorials that are on the website can be pulled by a script at startup of the docker instance, it could install all the pre-reqs of the tutorials, make sure they run in the docker instance without any issue - this could be really valuable for MXNet users to easily get started.

**Comment by gautamkmr** [comment]
@nswamy  A/C to your argument MXNet docker can also be achieved via just having `pip install of mxnet`. The main point here to give the user notebook experience out of box. 

I don't think we should have whole sets of tutorial which will completely bloat the size of Docker image.  I will let other chime in.  Meanwhile unless you have any further suggested changes(except adding complete tutorial which I am not in favor)  would you mind removing '@nswamy
nswamy requested changes '  option from the PR?

**Comment by nswamy** [comment]
you can use the code in this script https://github.com/apache/incubator-mxnet/blob/master/docs/mxdoc.py#L352-L366 to generate python notebooks from markdown files from the tutorials folder at the startup of this docker.

**Comment by Roshrini** [comment]
@gautamkmr I like the idea of giving users out of the box notebook experience with MXNet. But I think we should give users some tutorials to start with, in the dockerfile rather than just testing MXNet. 
Pulling some of the basic tutorials(all of them not needed) from MXNet website with the script @nswamy mentioned will also do. 

@marcoabreu @sandeep-krishnamurthy Can you review this PR?

**Comment by gautamkmr** [comment]
@Roshrini  Thanks but I dont agree of adding complete set of tutorial to the docker image. 
That will simply bloat the size of image.

**Comment by Roshrini** [comment]
@gautamkmr I didn't mean adding a complete set of tutorials. Just basic (3/4) introductory gluon tutorials should be fine. What do you think?

**Comment by ankkhedia** [comment]
@gautamkmr Ping!
Did you get a chance to work on recommendations given above by @Roshrini and @nswamy

**Comment by kalyc** [comment]
@gautamkmr thanks for your contribution! Could you update the diff as you mentioned above?

**Comment by stu1130** [comment]
@mxnet-label-bot update [pr-work-in-progress]

**Comment by vandanavk** [comment]
@mxnet-label-bot add [Docker]

**Comment by sandeep-krishnamurthy** [comment]
Thanks @gautamkmr for the update.
@nswamy - Is the update looks good to you?

And to add my 2 cents - I see, like @nswamy mentioned, if you are targeting beginner users, then having a docker image with all the tutorial notebooks. As a beginner user, I will just pull this docker image (cpu/gpu) and run the notebooks one by one and learn!

**Comment by Roshrini** [comment]
@mxnet-label-bot Update [Docker, pr-awaiting-review]
@nswamy Can you take a look at this PR again?

**Comment by stu1130** [comment]
@nswamy ping again thanks

**Comment by sandeep-krishnamurthy** [comment]
I still feel - If we are helping the beginner user then we need to have a docker image like - mxnet-tutorials and then include all tutorial notebooks in it. This docker image with only 3 examples may not really serve the purpose.

**Comment by lupesko** [comment]
Chiming in: sounds like a nice thing to have.
@gautamkmr - you should also update:
- https://github.com/apache/incubator-mxnet/blob/master/docker/README.md listing the new container
- Release CWiki to make sure the release process is updated to ensure the new image is uploaded to dockerhub on release

**Comment by ankkhedia** [comment]
@gautamkmr Thanks for your contribution! Could you please look into the comments by @lupesko

**Comment by anirudhacharya** [comment]
@gautamkmr can you please update the PR with the requested changes.

**Comment by karan6181** [comment]
@gautamkmr Thank you for your contribution! Can you please provide the update on this PR since there is no activity from last couple of weeks. Thank you!

**Comment by abhinavs95** [comment]
@gautamkmr Ping again! could you please give an update on the PR? Thanks

**Comment by piyushghai** [comment]
@gautamkmr Any updates on this PR ?

**Comment by Roshrini** [comment]
@gautamkmr Sorry for back and forth. Can you please address Sandeep's comments? Thanks

**Comment by gautamkmr** [comment]
I am going to close this PR due to lack of bandwidth. I encourage MXNet team to add this feature if they think is good idea for customer.

**Pull request closed without merging**
