### PR TITLE
Disables  test_random.test_exponential_generator

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
Disables  test_random.test_exponential_generator due to isse  #14187 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by ankkhedia** [comment]
@perdasilva Thanks for your contribution!
@mxnet-label-bot add [Flaky, test, pr-awaiting-review]

**Comment by anirudhacharya** [comment]
@perdasilva why are disabling this test, rather than track and fix the flakiness?

**Comment by perdasilva** [comment]
@anirudhacharya the process when you find a flaky test, as I understand it, is open an issue (#14187) then create a PR to disable the test while it's fixed.

**Comment by access2rohit** [comment]
Fix is already on the way. No need to merge this. You can close it once my fix is merged #14287

**Comment by access2rohit** [comment]
Fix has been merged. You can close this PR now. :)

**Comment by lupesko** [comment]
@perdasilva can you please close the issue as #14287 was merged? thanks!

**Pull request closed without merging**
