### PR TITLE
Use relative path for extension unit tests

### PR DESCRIPTION
**Pull request by heaseny**
## Description ##
Use relative path for extension tests, :
nosetests -s -v test_extensions:test_subgraph
nosetests -s -v test_extensions:test_custom_op
nosetests -v -s test_extensions_gpu:test_custom_op_gpu
can also support below test formats:
nosetests -s -v tests/python/unittest/test_extensions.py:test_subgraph
nosetests -s -v tests/python/unittest/test_extensions.py:test_custom_op
nosetests -v -s tests/python/gpu/test_extensions_gpu.py:test_custom_op_gpu
### Essentials ###

- [ ] Changes are complete 
- [ ] All changes have test coverage:
- [ ] Code is well-documented: 

- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html

### Changes ###
- [ ] Changes to relative path for build directory which is used by test_extensions:test_subgraph
- [ ] Changes to relative path for build directory which is used by test_extensions:test_custom_op
- [ ] Changes to relative path for build directory which is used by test_extensions_gpu:test_custom_op_gpu

### CODE REVIEW

**Comment by TaoLv** [comment]
@heaseny It seems you have missed your code changes.

**Comment by samskalicky** [comment]
shouldnt we do this for the test_custom_op_gpu test too?
https://github.com/apache/incubator-mxnet/pull/17626/files#diff-460d06cb3af2af996c5ec259b086712fR170

**Comment by rondogency** [comment]
Thanks for the contribution. @samskalicky I think if this PR comes first then we can make the fix on gpu one

**Comment by leezu** [comment]
Could someone explain why this should be done / hasn't been done before?

**Comment by samskalicky** [comment]
@leezu this is only needed for running the tests locally on building from source. And only when the tests are being run in a non-standard way. They run fine in the CI, which runs the tests from the top level directory. But if you go down into the tests/python/unittests and try and run them from there, the paths wont be correct. So the library wont be loaded and it will error out.

@TaoLv and the Intel folks have been asking to make it so that these tests can run from whichever directory you are in for manual builds from source.

**Comment by heaseny** [comment]
Thanks for exact checks, the fix for test_custom_op_gpu has been added .

**Comment by leezu** [comment]
Please fix conflicts

**Comment by heaseny** [comment]
@leezu the confict issue has been fixed,  thanks for your reminder.

**Comment by leezu** [comment]
Retriggered CI

**Pull request merged**
