### PR TITLE
Fixed C++ inference tutorial

### PR DESCRIPTION
**Pull request by NRauschmayr**
## Description ##
Tutorial did not properly preprocess images and as such produce incorrect predictions. The example would set default values for mean but not for std_dev. So if the user does not provide the file that contains those values, the example would crash. The C++ example predicts now the same class as in the Python example. However, the probabilities differ (9.72 versus 10.411) and we should to look into that

### CODE REVIEW

**Comment by Roshrini** [comment]
@NRauschmayr Thank you for fixing the example. Can you please fix failing CI? 
@leleamol Can you take a look?

**Comment by NRauschmayr** [comment]
I think we have to update the unit-test: it is using an outdated and not maintained model https://github.com/apache/incubator-mxnet/blob/a9458caec285d3c28d16588fef6aef5e219c7472/cpp-package/example/inference/unit_test_inception_inference.sh 
The test should rather use a model from the official model zoo. According to https://mxnet.incubator.apache.org/api/python/gluon/model_zoo.html pre-processing has to be done the following way 
```
image = image/255
normalized = mx.image.color_normalize(image,
                                      mean=mx.nd.array([0.485, 0.456, 0.406]),
                                      std=mx.nd.array([0.229, 0.224, 0.225]))
```

**Comment by karan6181** [comment]
@NRauschmayr Could you please resolve the merge conflicts??

@nswamy @szha Could you please review it? Thanks!

**Comment by piyushghai** [comment]
@NRauschmayr Can you rebase with the latest master please ? 

@leleamol Gentle ping for review.

**Comment by NRauschmayr** [comment]
Sorry for the late reply. I have not done the rebase yet, because I saw that the files I modified were deleted by the following commit https://github.com/apache/incubator-mxnet/pull/15164 I wanted to check first whether or not it makes sense to re-add those files, but I did not have the time yet to compile the latest c++ tutorial of the master branch.

**Comment by szha** [comment]
@mxnet-bot run ci [all]

**Comment by szha** [comment]
OK looks like this part is already refactored into the imagenet_inference.cpp example and it's handling the mean values correct. Still, thanks for proposing the patch.

**Pull request closed without merging**
