### PR TITLE
[v1.4.x] Backport of pip package scripts

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
This PR backports the scripts used to compile libmxnet for, and package, the wheel file posted to PyPI.

Backporting state before #14884, since mxnet built with cuDNN 7.5 does not yet pass the test pipeline.

### CODE REVIEW

**Comment by vandanavk** [comment]
@mxnet-label-bot add [pr-awaiting-review, Build]

**Comment by szha** [comment]
Seems to be a subset of #14812. cc @lanking520

**Comment by perdasilva** [comment]
@szha you are right! Do you know what the timing issue was? The changes, in this and the referenced PR, shouldn't affect anything except CI and building the statically linked library...

How would you suggest we proceed?

**Comment by lanking520** [comment]
During the timeline of 1.4.x. I didn’t have enough time to figure out what is the problem with CI since it is a TensorRT failure

**Comment by perdasilva** [comment]
@lanking520 would it still be ok to merge this PR, at least in the interim until you find time to figure out the tensorRT issues? We can then revert this PR in favor of yours. This would just unblock my release automation pipelines in the meantime =)

**Pull request merged**
