### PR TITLE
Fix non-MSVC build problem

### PR DESCRIPTION
**Pull request by cjolivier01**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by marcoabreu** [comment]
How did you find out about this error?

**Comment by cjolivier01** [comment]
That's an MSVC flag...

**Comment by marcoabreu** [comment]
I know... But how was it able to break the build and pass CI?

**Comment by cjolivier01** [comment]
maybe because you have older Cmake that doesn’t know how to compile cuda as
a first-class language?

**Comment by marcoabreu** [comment]
Which version Cmake are you using?

**Comment by cjolivier01** [comment]
3.9.6

**Comment by marcoabreu** [comment]
On Windows, right?

**Comment by cjolivier01** [comment]
broken for linux because those are windows compile flags

**Comment by marcoabreu** [comment]
Thanks!

@KellenSunderland do you know which Cmake version we are using? In the dockerfile build_cuda, we're not explicitly specifying the CMake-version, so I'd assume we're using the latest one - but in that case we should have caught this problem, right?

**Comment by KellenSunderland** [comment]
CI is using 3.5.  Pedro and I also saw this with 3.9 (bundled clion version).

**Comment by KellenSunderland** [comment]
It should be fairly straightforward to upgrade the cnake in CI.  I'd recommend keeping on at 3.5 and updating the other to something more modern.

**Pull request merged**
