### PR TITLE
Added early stop call back class

### PR DESCRIPTION
**Pull request by hantingxie**
This is an updated version of the pull request #6304 .
It adds a new class for handling early stopping while training the neural networks.
The class supports early stopping and save checkpoints when the early stopping happened.

### CODE REVIEW

**Comment by hantingxie** [comment]
Hey guys @piiswrong @mli @tqchen , can anyone have a review on this? This is an update of the pull request #6304 which adds an early stopping class for the training module. This class is capable of stopping the training early by either non-improving training errors or eval errors (if eval data is given). Users can customise the paticen to decide how many rounds of non-improvement can be tolerated. While early stopping happens, models will be saved by enabling the option. 

This is an extention to the current callback apis which can be used very similar to the Speedometer class so that new users should find it very easy.

Thank you!

**Comment by piiswrong** [comment]
The fit logic is already over complicated. We don't want to further complicate it. It's better to write your own training loop for this kind of advanced behavior

**Comment by hantingxie** [comment]
@piiswrong I do respect your concerns, but I think early stopping is something quite standard to me and there is currently no way to do it if the users want to use the fit module for training their networks. Making module complicated is definitely something we wish to avoid, but given that early stopping is commonly used, I still think it's reasonable to add few lines of codes. As I said, I recommend to add this feature, but I shall definitely respect your decision. 👍

**Comment by piiswrong** [comment]
Closed for now. Custom training loop is the recommended way of handling this

**Pull request closed without merging**
