### PR TITLE
[website] Fix broken website for master version 

### PR DESCRIPTION
**Pull request by waytrue17**
## Description ##
Fix broken website for master version described in #19943. The issue is due to the format of license header introduced by #19743, which blocks the pages from building by Jekyll:
```
<!---
  Licensed to the Apache Software Foundation (ASF) 
  ....
-->
---
layout: default
---
```
This PR attempts to fix the broken website by rearranging the license format.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by waytrue17** [comment]
@ys2843 @szha @leezu Can you please review?

**Review by Zha0q1 — APPROVED** [review]
LGTM!

**Comment by sandeep-krishnamurthy** [comment]
Thank you.

**Review by sandeep-krishnamurthy — APPROVED** [review]

**Comment by waytrue17** [comment]
@mxnet-bot run ci [windows-cpu]

**Review by josephevans — APPROVED** [review]
LGTM, thanks Wei!

**Comment by leezu** [comment]
@waytrue17 any ideas how to update our CI to fail if a PR introduces problems similar to #19743?

**Comment by ys2843** [comment]
could add a snapshot check in CI?

**Pull request merged**
