### PR TITLE
clean up math operators

### PR DESCRIPTION
**Pull request by piiswrong**
@mseeger @asmushetzel

### CODE REVIEW

**Comment by mseeger** [comment]
It is funny this should work. If you define float name(DType a) in the templated class, I thought you cannot specialize this to be double name(double a) in the specialization.

We just have to be really careful not to fall back to the old state, namely that everything is computed in float, even for DType = double. The unit tests should indicate this.

**Comment by mseeger** [comment]
I am looking at pages like this:

https://stackoverflow.com/questions/15911890/overriding-return-type-in-function-template-specialization

It seems to be complicated to change the return type in the specialization.

**Comment by mseeger** [comment]
Independent of this PR, I'd like to do one more change.
I am not happy with many of the backward expressions: different to the forward ones, they compute arithmetic expressions in DType and not in float.

This can be fixed by introducing one more function: square, which computes a * a, either in float or in double.

**Comment by piiswrong** [comment]
Its not specialization. Its overloading.

**Comment by mseeger** [comment]
Well if this works, it is fine. Just make sure that if the arg is double, then the computation is done in double. But I think my new unit tests would likely fail otherwise.

I'd like to give this another go afterwards (square function), but I wait until this one is in.

**Comment by mseeger** [comment]
Hi Eric, I did some test to confirm that this solution works.

Please do merge it in. Otherwise, if you are too busy, I can take it over.

I'd like to do some further modification on top of it.

**Comment by mseeger** [comment]
Hello, if you don't mind, I take this over, and add something on top.
I'll return to work from my leave next Wed, and would like to have all of this done before that.

**Pull request closed without merging**
