### PR TITLE
Add -DMXNET_USE_OPENMP to Makefiles so runtime info gets updated accordingly

### PR DESCRIPTION
**Pull request by larroy**
## Description ##

Fixes OPENMP info in runtime features.

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/runtime.py

This would be also needed to fix BLAS flags.
https://github.com/apache/incubator-mxnet/pull/15424

### CODE REVIEW

**Comment by karan6181** [comment]
@mxnet-label-bot add [Installation, Makefile, pr-awaiting-review]

**Comment by larroy** [comment]
This is a bit of a departure of how we are testing since we are not testing depending on specific build flags (other than GPU and CPU which we could remove now thanks to libinfo). In that case we should also do all the permutation builds and check the build flags and also for Make and Cmake. This means adding quite a number of recompilations to test this. I'm not sure is worth the increased cost and trouble. Is it justified for you?

**Comment by larroy** [comment]
@mxnet-label-bot add Bug

**Comment by larroy** [comment]
@mxnet-label-bot add [Bug]

**Pull request merged**
