### PR TITLE
Fixed python website double scroller and improve UX

### LINKED ISSUE #18838: double scroll on website
## Description
on the website, two scrolls appear which prevents keyboard scrolling.

image

## To Reproduce

Use Chrome Version 84.0.4147.105 (Official Build) (64-bit) on OSX and visit
https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/image/mnist.html

### PR DESCRIPTION
**Pull request by ys2843**
## Description ##
fix #18838 and improve user experience of python site. 

### Changes ###
- [x] Fixed double scroller
- [x] Added scroll aware animation to top nav bar
- [x] Reduce the height of the second top nav bar to hide it when scrolling down

## Comments ##
- Preview: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/index.html

### CODE REVIEW

**Comment by ys2843** [comment]
@mxnet-label-bot add [Website]

**Comment by szha** [comment]
@ys2843 thanks for the fix! I verified that the double scroller problem is gone and the page seems to run smoother too.
I tried page-up and page-down but it still doesn't seem to work unless I click on the inner div to adjust the focus first. Is there any way to make page scrolling with keyboard work too?

**Comment by ys2843** [comment]
> @ys2843 thanks for the fix! I verified that the double scroller problem is gone and the page seems to run smoother too.
> I tried page-up and page-down but it still doesn't seem to work unless I click on the inner div to adjust the focus first. Is there any way to make page scrolling with keyboard work too?

Thanks for reviewing, the keyboard control depends on the focused element. I added a fix to auto focus the content element when the pages finish rendering. Please see the (updated) preview.

**Comment by szha** [comment]
awesome! things are working as expected now. thanks for making the browsing experience smooth!

**Pull request merged**
