### PR TITLE
[v1.x] Fix issue with even number of channels in BatchNorm

### PR DESCRIPTION
**Pull request by piotrwolinski-intel**
## Description ##
This PR is meant to fix [this issue](https://github.com/apache/incubator-mxnet/issues/20858) by calling MKLDNN implementations via `MKLDNNRun` method.

### CODE REVIEW

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by piotrwolinski-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by bgawrych — APPROVED** [review]

**Pull request merged**
