### PR TITLE
Bumping MXNet version to 1.6.0 in base.h for C APIs

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
Bumping MXNet version to 1.6.0 in base.h for C APIs
https://github.com/apache/incubator-mxnet/issues/16904

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

**Comment by access2rohit** [comment]
@lanking520 @ptrendx

**Comment by ptrendx** [comment]
@ChaiBapchya @larroy all those failed builds are because of a hang during compilation, what can we do to diagnose and fix it?

**Comment by lanking520** [comment]
restarted all the tests

**Comment by ChaiBapchya** [comment]
@ptrendx prima facie (I could see lots of pipelines timing out) Need to dig deep to find out where exactly was it consuming the most time. In December, we will be revisiting this in greater detail. For now CI is to be kept running...

**Comment by access2rohit** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Pull request merged**
