### PR TITLE
[BUGFIX] fix npi_concatenate quantization dim/axis

### PR DESCRIPTION
**Pull request by sfraczek**
## Description ##
Fix to first problem reported in issue https://github.com/apache/incubator-mxnet/issues/20354

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage

## Comments ##
Now npi concatenate can be quantized just like Concat it uses the same operator

### CODE REVIEW

**Review by bgawrych — APPROVED** [review]
LGTM

**Comment by sfraczek** [comment]
@mxnet-bot run ci [all]

**Comment by sfraczek** [comment]
@mxnet-bot run [centos-gpu]

**Comment by sfraczek** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by akarbown** [comment]
@mxnet-bot run[centos-cpu, unix-gpu]

**Comment by akarbown** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu]

**Review by akarbown — APPROVED** [review]

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by akarbown** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by sfraczek** [comment]
@mxnet-bot run ci [centos-cpu]

**Pull request merged**
