### PR TITLE
Refactored storage handling

### PR DESCRIPTION
**Pull request by lebeg**
## Description ##

Made Storage::Handle objects and the memory they are handling be reference counted.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
  - Unit tests are added
  - Added a functional test
- [x] Code is well-documented: 
  - Existing docs improved
  - New methods documented
- [x] To the my best knowledge, examples are not affected by this change

### Changes ###
- Ensured that access to memory pointed by storage::Handles is protected by reference counting
- Introduced a common interface to public Storage class and the underlying internal StorageManagers
- Changed referencing of shared memory to a string key
- Separated platform specific CPUSharedStorageManager implementations
- Introduced a functional C++ test

- Moved NDArray::Chunk implementation to .cc file for compile time and dependendencies reduction

## Comments ##
- The change has grown significantly due to a lot of usages in the code.

## Still to be done in next iterations ##
- Add Android implementation of CPUSharedStorageManager
- Introduce locking for shared memory
- Add coverage and more edge cases to Storage unit testing
- Add functional test to automation

### CODE REVIEW

**Comment by piiswrong** [comment]
What's the benefit of using shared_ptr for storage? Chunks are already in shared_ptr and never copied anyway.

How much performance is lost by refactoring to shared_ptr and std::function?

**Comment by lebeg** [comment]
> What's the benefit of using shared_ptr for storage? 

The ownership of memory storage::Handles are pointing to with their dptr is protected from extinction and managed by the shared_ptr.

> Chunks are already in shared_ptr and never copied anyway.

There are other places which use storage::Handle and mostly as just a pointer to some allocated memory without access protection.

> How much performance is lost by refactoring to shared_ptr and std::function?

* There is an additional reference count stored on the heap next to each Handle
* 1 indirection when constructing a TBlob

**Comment by piiswrong** [comment]
@cjolivier01 
Since the current implementation is working OK, we need to make sure the refactor does not have visible impact on performance before merging it.

**Comment by lebeg** [comment]
I already figured it out - it was due to a mess in includes in the amalgamation. This should be fixed.

I'm running the performance tests currently to get metrics on the changes, will post as soon as results are available.

**Comment by cjolivier01** [comment]
How many reference count changes occur for a given pointer during alloc? during free?  Is it accessed anywhere during its useful lifetime in such a way that it causes a reference count change?

What's the code path/situation where it might have a problem that makes it need to be reference-counted?  I there a situation where it might be destroyed why another thread is using it? If so, where?

**Comment by cjolivier01** [comment]
I think for the performance question, piiswrong@ is talking about the fact that the cache/memory may be locked during the interlocked increment/decrement (i.e. "lock inc ds:[esi]")

**Comment by lebeg** [comment]
Thank you @cjolivier01 and @piiswrong for your questions. Please find my answers below:

> How many reference count changes occur for a given pointer during alloc? 

That should be 1. Even if copies of the pointers are returned from functions they will be moved instead of copied which should not affect the reference count.

> during free? 

Exactly the number of references. Which in the case of a unique shared_ptr will be 1 as well.

> Is it accessed anywhere during its useful lifetime in such a way that it causes a reference count change? (ie is there an assignment operation where a copy of the shared pointer is taken (thus increasing the reference count) anywhere or is the shared pointer just used from its place in a class/struct data member)?

Potentially NDArray and it's corresponding Chunk could be copied.

> What's the code path/situation where it might have a problem that makes it need to be reference-counted? I there a situation where it might be destroyed while another thread is using it? If so, where?

In my opinion NDArray and it's underlying structure should be Copy-On-Write. In that case you can many cheap copies of the unmodified original that will be just referenced through the shared_ptr. A copy is performed only once you call a mutating method (can be distinguished by the const modifier).

**Comment by lebeg** [comment]
There might be another not thread safe, but simplified approach. Instead of a shared_ptr we could use a unique_ptr. That does not have a interlocking performance impact, but still provides an appropriate freeing guarantee. What do you think?

**Comment by piiswrong** [comment]
If we use unique_ptr then it would be a purely aesthetic change.
I would be fine with it as long as it's correct

**Comment by lebeg** [comment]
I'll close this PR in favour of future more small and discreet changes that are worth making.

**Pull request closed without merging**
