### PR TITLE
[OpPerf] Fix axis_shape and function mismatch for LTS

### PR DESCRIPTION
**Pull request by ChaiBapchya**

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@access2rohit Thanks for reminding

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [sanity]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu, centos-cpu]

**Comment by marcoabreu** [comment]
No Test!?

**Comment by ChaiBapchya** [comment]
There's no text for OpPerf per se. But for every PR related to opperf, run the test utility and confirm if its working or not.

**Pull request merged**
