### PR TITLE
[v1.x] Backport [LICENSE] Reorganize rat-excludes file to ease license auditing (#19743)

### PR DESCRIPTION
**Pull request by szha**
## Description ##
backport #19743

### CODE REVIEW

**Review by samskalicky — APPROVED** [review]

**Comment by samskalicky** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Comment by szha** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Comment by szha** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by szha** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by samskalicky** [comment]
Thanks @szha!

**Pull request merged**
