### PR TITLE
Disable flaky test test_operator_gpu.test_multinomial_generator

### PR DESCRIPTION
**Pull request by Chancebair**
Disable flaky test, issue here https://github.com/apache/incubator-mxnet/issues/14158

### CODE REVIEW

**Comment by ankkhedia** [comment]
@Chancebair Thanks for your contribution!

@mxnet-label-bot add [pr-awaiting-review, test, flaky]

**Comment by apeforest** [comment]
When disabling the flaky test, it would be great if you could also provide the last successful run (the end of a continuous set of successful runs)of this test, so it will help people to pinpoint the potential PR that made this test flaky. Thanks!

**Comment by anirudhacharya** [comment]
@Chancebair why disable this test, rather than track and fix the flakiness?

**Comment by perdasilva** [comment]
@anirudhacharya the point is to disable it while it is being worked on so that it doesn't get in the way of other PRs.

**Comment by piyushghai** [comment]
@Chancebair Is this PR still relevant for the CI ?
What's the path forward for this ?

**Comment by Chancebair** [comment]
The issue tracking this flaky test is listed in the first comment.  The way we handle flaky tests once they are identified, is _quickly_ disabling them, tracking a fix in the issue, and re-enabling them in the fix PR.  Since this PR was not merged when it should have been, I will close.

**Pull request closed without merging**
