### PR TITLE
[COREML] Update the json getter

### PR DESCRIPTION
**Pull request by tqchen**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

### CODE REVIEW

**Comment by tqchen** [comment]
cc  @piiswrong @pracheer

**Comment by piiswrong** [comment]
I think attr was also referenced in the other files?

**Comment by piiswrong** [comment]
Also this needs to support both attr and attrs because we need to handle json saved by previous versions

**Comment by tqchen** [comment]
Already did that( support attr and attrs) they are only refered in layer file

**Comment by pracheer** [comment]
Looks good to me.

One nitpick suggestion if you think it is useful: can you add some documentation to _get_attrs() with some info on attr/attrs story (like models created w/ which mxnet version will have "attrs" as part of their defn etc)?

**Comment by tqchen** [comment]
@pracheer updated,

**Comment by tqchen** [comment]
Merge this ?

**Comment by pracheer** [comment]
Yes please!

**Pull request merged**
