### PR TITLE
[MXNET-503] Website landing page for MMS, PR II

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
This is a redo of:
https://github.com/apache/incubator-mxnet/pull/11037

As it was rolled back by:
https://github.com/apache/incubator-mxnet/pull/11154

### CODE REVIEW

**Comment by aaronmarkham** [comment]
That's fine. I'll make an entry on the examples README page for it and then link to this page. I'll move the page from docs and put it in /examples/mms/ instead.

**Comment by aaronmarkham** [comment]
Rather than make a special folder for mms in /examples, I created a model-server folder, so any other model serving examples can be added there.

**Comment by marcoabreu** [comment]
@aaronmarkham please rebase

**Comment by aaronmarkham** [comment]
Closing for now. Will add this to an ecosystem page soon.

**Pull request closed without merging**
