### PR TITLE
[v2.0][LICENSE] Port #20520

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Port #20520. Thanks @sandeep-krishnamurthy for the license updates. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by szha — APPROVED** [review]
There may be additional changes from @josephevans that you'd want to pick for the related files and licenses. Up to you whether you want to do it together or as a separate PR.

**Comment by barry-jin** [comment]
> There may be additional changes from @josephevans that you'd want to pick for the related files and licenses. Up to you whether you want to do it together or as a separate PR.

I see. I will probably update the license in this pull request.

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
