### PR TITLE
[WIP] Revert v1.x

### PR DESCRIPTION
**Pull request by Zha0q1**
unix-cpu/gpu are failing on v1.x. This pr checks if https://github.com/apache/incubator-mxnet/commit/031dc5b7c2b7f5c1cb61d0193b048c0d77abb9d8 is the cause

### CODE REVIEW

**Comment by szha** [comment]
@Zha0q1 unix-gpu job has been failing in my PR #19799 before #19670 was merged.

**Comment by Zha0q1** [comment]
@szha Thanks for the info! @waytrue17 is creating an issue and the current oncall will look into this

**Comment by Zha0q1** [comment]
Closing pr for now since we confirmed the ci issue was not caused by that pr

**Comment by access2rohit** [comment]
> @Zha0q1 unix-gpu job has been failing in my PR #19799 before #19670 was merged.

@szha I looked at your PR and our log of the v1.x branch. After the PR #19670 there is only one PR merged(#19837) and its CPU unittests passed 4 days ago. Your PR passed its first 13 days ago and then remaining 3 re-runs started 2 days ago. I am currently running unix_CPU CI w/ and W/o #19670 to verify. Will update shortly

**Comment by Zha0q1** [comment]
> > @Zha0q1 unix-gpu job has been failing in my PR #19799 before #19670 was merged.
> 
> @szha I looked at your PR and our commit log of the v1.x branch. After the PR #19670 there is only one PR merged(#19837) and its CPU unittests passed 4 days ago. Your PR passed its first 13 days ago and then remaining 3 re-runs started 2 days ago. I am currently running unix_CPU CI w/ and W/o #19670 to verify. Will update shortly

I think Sheng was right that #19670 was not the cause of the ci issue. In this PR even after reverting #19670 the failure still happened. @josephevans opened a pr https://github.com/apache/incubator-mxnet/pull/19872 to attempt to fix the issue

**Comment by access2rohit** [comment]
ok ... i will stop then. Since you already verified that reverting the PR doesn't fix the issue.

**Pull request closed without merging**
