### PR TITLE
Remove pip upgrade step from install docs

### PR DESCRIPTION
**Pull request by anirudh2290**
## Description ##
It is not advised to upgrade a system pip package(install with debian package manager for example) to be upgraded by doing `pip install -U pip` (https://github.com/pypa/pip/issues/5221). I don't think we need this upgrade step here since MXNet installs fine with the pip version that is available after doing `sudo apt-get install python-pip`. Please see the PIP upgrade issue: https://github.com/pypa/pip/issues/5221 . We ran into this issue when running the nightly tests.
Removed the upgrade step in this PR. 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by anirudh2290** [comment]
@mbaijal @gautamkmr @marcoabreu can you please take a look ?

**Comment by mbaijal** [comment]
@anirudh2290 The test still fails on nightly when i run it on your local branch. 
I think you removed the step only from the cpu instructions for build from source, the test actually fails on the gpu version (line 479)

**Comment by szha** [comment]
After the pip 10 update, for some users it's actually recommended/mendatory to upgrade, see https://pypi.org/help/#tls-deprecation

**Comment by mbaijal** [comment]
After the GPU fix, the nightly test passes.

**Comment by anirudh2290** [comment]
The issue is that installing pip with debian package manager (`sudo apt-get install python-pip`) and then upgrading with pip package manager(`pip install --upgrade pip`) is not recommended. Currently, on ubuntu 16.04 doing this breaks pip. 
There is no problem with upgrading to pip 10 if that is done with the same package manager that you installed pip with. 
Also, for the tls issue, I think upgrading python should suffice.

**Comment by anirudh2290** [comment]
@gsemet Thanks for your inputs. Even with the `--user` flag the system pip breaks on Ubuntu 16.04:
```
$ pip install --upgrade pip --user
$ pip -v
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
$ /usr/bin/pip -v
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
 
Since, the upgrade to pip doesn't seem to be required here (unless there is a counter use case that i am not aware of), we can just omit the upgrade step here.

**Comment by gsemet** [comment]
what does `which pip` returns? You need to ensure you have ~/.local/bin in your PATH

**Comment by anirudh2290** [comment]
Yes it's in the path. You can see that I have outputted path. which pip
returns ~/.local/bin/pip. It's weird because when I try with
~/.local/bin/pip it works fine.

**Pull request merged**
