### PR TITLE
CPU reduce kernel optimization

### PR DESCRIPTION
**Pull request by Zha0q1**
This pr optimizes the cpu reduce kernel. This is used in many ops: `np.sum`, `np.mean`, `np.prod`, `np.argmin`, `np.argmax`, `np.var`, `np.std`, `np.constraint`, `np.norm`, `np.where`, `fully_connected`, etc.

Before
``` c++
template<typename Reducer, int ndim, typename AType, typename DType, typename OType, typename OP>
void seq_reduce_compute(const size_t N, const size_t M, const bool addto,
                        const DType *big, OType *small, const Shape<ndim> bshape,
                        const Shape<ndim> sshape, const Shape<ndim> rshape,
                        const Shape<ndim> rstride) {
  #pragma omp parallel for num_threads(engine::OpenMP::Get()->GetRecommendedOMPThreadCount())
  for (index_t idx = 0; idx < static_cast<index_t>(N); ++idx) {
    seq_reduce_assign<Reducer, ndim, AType, DType, OType, OP>(idx, M, addto, big, small,
        bshape, sshape, rshape, rstride);
  }
}

template<typename Reducer, int ndim, typename AType, typename DType, typename OType, typename OP>
void seq_reduce_compute(const size_t N, const size_t M, const bool addto,
                        const DType *big, OType *small, const Shape<ndim> bshape,
                        const Shape<ndim> sshape, const Shape<ndim> rshape,
                        const Shape<ndim> rstride) {
  #pragma omp parallel for num_threads(engine::OpenMP::Get()->GetRecommendedOMPThreadCount())
  for (index_t idx = 0; idx < static_cast<index_t>(N); ++idx) {
    seq_reduce_assign<Reducer, ndim, AType, DType, OType, OP>(idx, M, addto, big, small,
        bshape, sshape, rshape, rstride);
  }
}
```

Before this pr we use openmp to parallelize the rows along the axis to be reduced (`N`). However when `N` is smaller than the number of omp threads, such as when `axis=None` or the product of the other dimension is smaller than the number of threads, then parallelism is not used to the fullest. This pr optimizes such cases by parallelizing within the row (`M`). So now we have: 1.) N >= omp_thread_count, then parallelize `N` 2.) else parallelize `M`

Now
``` c++
template<typename Reducer, int ndim, typename AType, typename DType, typename OType, typename OP,
         typename IndexOP = mxnet::op::mshadow_op::set_index_no_op<AType, index_t>>
MSHADOW_XINLINE AType seq_reduce_assign_block(size_t start, size_t len,
                                              size_t j,
                                              const DType* __restrict big,
                                              const Shape<ndim>& rshape,
                                              const Shape<ndim>& rstride) {
  Shape<ndim> coord;
  AType val, residual;
  Reducer::SetInitValue(val, residual);
  for (size_t k = start; k < start + len; ++k) {
    coord = mxnet_op::unravel(k, rshape);
    AType temp = OP::Map(big[j + mxnet_op::dot(coord, rstride)]);
    if (IndexOP::do_op)
      IndexOP::Op(&temp, k);
    Reducer::Reduce(val, temp, residual);
  }
  Reducer::Finalize(val, residual);
  return val;
}

template<typename Reducer, int ndim, typename AType, typename DType, typename OType,
         typename OP, typename IndexOP = mxnet::op::mshadow_op::set_index_no_op<AType, index_t>>
MSHADOW_XINLINE void seq_reduce_assign(const index_t idx, const size_t M, const bool addto,
                                       const DType* __restrict big, OType *small,
                                       const Shape<ndim>& bshape, const Shape<ndim>& sshape,
                                       const Shape<ndim>& rshape, const Shape<ndim>& rstride,
                                       const bool use_omp = false) {
  Shape<ndim> coord = mxnet_op::unravel(idx, sshape);
  index_t j = mxnet_op::ravel(coord, bshape);
  AType val, residual;
  Reducer::SetInitValue(val, residual);
  if (!use_omp) {
    for (size_t k = 0; k < M; ++k) {
      coord = mxnet_op::unravel(k, rshape);
      AType temp = OP::Map(big[j + mxnet_op::dot(coord, rstride)]);
      // argmin/max, set IndexedNum.idx
      if (IndexOP::do_op)
        IndexOP::Op(&temp, k);
      Reducer::Reduce(val, temp, residual);
    }
  } else {
    const int thread_count = engine::OpenMP::Get()->GetRecommendedOMPThreadCount();
    auto vals = std::make_unique<AType[]>(thread_count);
    #pragma omp parallel for num_threads(engine::OpenMP::Get()->GetRecommendedOMPThreadCount())
    for (int i = 0; i < thread_count; ++i) {
      vals[i] = seq_reduce_assign_block<Reducer, ndim, AType, DType, OType, OP, IndexOP>
          (i * (M / thread_count),
          i < (thread_count - 1) ? (M / thread_count) : (M / thread_count) + M % thread_count,
          j, big, rshape, rstride);
    }
    for (int i = 0; i < thread_count; ++i) {
      Reducer::Reduce(val, vals[i], residual);
    }
  }
  Reducer::Finalize(val, residual);
  assign(&small[idx], addto, OType(val));
}

template<typename Reducer, int ndim, typename AType, typename DType, typename OType, typename OP,
         typename IndexOP = mxnet::op::mshadow_op::set_index_no_op<AType, index_t>>
void seq_reduce_compute(const size_t N, const size_t M, const bool addto,
                        const DType *big, OType *small, const Shape<ndim> bshape,
                        const Shape<ndim> sshape, const Shape<ndim> rshape,
                        const Shape<ndim> rstride) {
  const int thread_count = engine::OpenMP::Get()->GetRecommendedOMPThreadCount();
  #pragma omp parallel for num_threads(thread_count) if (N >= thread_count)
  for (index_t idx = 0; idx < static_cast<index_t>(N); ++idx) {
    seq_reduce_assign<Reducer, ndim, AType, DType, OType, OP, IndexOP>
        (idx, M, addto, big, small, bshape, sshape, rshape, rstride, N < thread_count);
  }
}
```

Performance improvement (np.sum, omp_thread_count=16):

> (8, 300000) float32 axis = 1
> before: 15.54 now: 8.02
> 
> (4, 300000) float32 axis = 1
> before: 15.51 now: 4.07
> 
> (300000, 4) float32 axis = 0
> before: 15.57 now: 4.10
> 
> (5000, 5000) float32 axis=None
> before: 1284 now: 81
> 
> (500, 50000) float32 axis=None
> before: 1284 now: 82
> 
> (2, 2**25) float32 axis=1
> before: 1719 now: 217
> 
> (2, 2**25) float32 axis=None
> before: 3433 now: 217

unit is ms

### CODE REVIEW

**Comment by Zha0q1** [comment]
```c++
template<typename Reducer, int ndim, typename AType, typename DType, typename OType, typename OP,
         typename IndexOP = mxnet::op::mshadow_op::set_index_no_op<AType, index_t>>
MSHADOW_XINLINE AType seq_reduce_assign_block(size_t start, size_t len,
                                              size_t j,
                                              const DType* __restrict big,
                                              const Shape<ndim>& rshape,
                                              const Shape<ndim>& rstride) {
  Shape<ndim> coord;
  AType val, residual;
  Reducer::SetInitValue(val, residual);
  for (size_t k = start; k < start + len; ++k) {
    coord = mxnet_op::unravel(k, rshape);
    AType temp = OP::Map(big[j + mxnet_op::dot(coord, rstride)]);
    if (IndexOP::do_op)
      IndexOP::Op(&temp, k);
    Reducer::Reduce(val, temp, residual);
  }
  Reducer::Finalize(val, residual);
  return val;
}
```

So here I can also get rid of `Reducer::Finallize` and return both `val` and 'residual' and use `Reducer::Merge` rather than `Reducer::Reduce` in `seq_reduce_assign`. This is more rigorous but is also more expensive (~5%). However the accuracy does not seem to differ by much so I use the current solution. My initial commit has the `Reducer::Merge` implementation for reference.

**Comment by Zha0q1** [comment]
@mxnet-bot run ci [miscellaneous, unix-cpu]

**Comment by Zha0q1** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by Zha0q1** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by Zha0q1** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by Zha0q1** [comment]
@sandeep-krishnamurthy @szha @sxjscience

**Comment by sandeep-krishnamurthy** [comment]
Great work.

**Comment by Zha0q1** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by sxjscience — COMMENTED** [review]
LGTM

**Review by sxjscience — APPROVED** [review]

**Pull request merged**
