### PR TITLE
Implementation for equivalence of tf.moments

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
https://www.tensorflow.org/api_docs/python/tf/nn/moments

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Forward & Backward
- [x] Unit Test

## Comments ##
Related to #11283, pre-requisite of group norm implementation.
Flakiness Check:
```
MXNET_TEST_COUNT=10000 nosetests tests/python/unittest/test_operator.py:test_moments
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=862626152 to reproduce.
.
----------------------------------------------------------------------
Ran 1 test in 1380.770s

OK
```
```
MXNET_TEST_COUNT=10000 nosetests tests/python/gpu/test_operator_gpu.py:test_moments
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=688103580 to reproduce.
.
----------------------------------------------------------------------
Ran 1 test in 2116.433s

OK
```

### CODE REVIEW

**Comment by haojin2** [comment]
@eric-haibin-lin @reminisce @szha  ping for review.

**Comment by wkcn** [comment]
Great! Is it convenient to support the tensor with arbitrary dimension? Thank you!

**Comment by haojin2** [comment]
One thing is that usually tensors do not have >5 dims. The kernel can actually handle any # of dims, but we need to modify the mxnet::TShape/Tuple class to enable GPUs to read from mxnet::TShape/Tuple.

**Comment by haojin2** [comment]
@eric-haibin-lin The op gives variance of the input on arbitrary axis/axes, so it's technically the `np.var` operator's equivalence with an extra `mean` output. The impl of this op could also become the common helper function for various versions of normalizations.

**Comment by haojin2** [comment]
@eric-haibin-lin @hetong007 Is this good for merge?

**Comment by hetong007** [comment]
LGTM

**Comment by haojin2** [comment]
@eric-haibin-lin @szha Can any of you take a final look and help with merging this op? Thanks!

**Comment by haojin2** [comment]
@eric-haibin-lin @szha Ping for one more review.

**Pull request merged**
