### PR TITLE
V1.8.x

### PR DESCRIPTION
**Pull request by leezu**
Use [magit-cherry mode](https://magit.vc/manual/magit/Cherries.html) to check for commits present in v1.7.x but missing from v1.8.x. `-` indicates that the commit is also present in v1.8.x, whereas `+` indicates that the commit is missing.

Screenshot from 2020-09-30 20-14-33

There are a couple of false positives (declared missing but actually present), as those commits were forward ported to v1.8.x in a squashed form. I went through all `+` marked commits and applied them to the `v1.8.x` branch.

Only conflict to resolve was https://github.com/apache/incubator-mxnet/commit/8c7c2f111d57802d5c642f51ac7bfe02ea9a3bf8 which had to take into account the change by https://github.com/apache/incubator-mxnet/commit/ce0a518e74a7bd0d1d80ab625199ecfd71200809

### CODE REVIEW

**Comment by sxjscience** [comment]
Also CC @samskalicky @sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
Thank you so much @leezu

**Comment by sxjscience** [comment]
In fact, should we ensure that each release needs to include all the commits of the previous release? @samskalicky @sandeep-krishnamurthy

**Comment by samskalicky** [comment]
> In fact, should we ensure that each release needs to include all the commits of the previous release? @samskalicky @sandeep-krishnamurthy

I like the idea of comparing to the previous release to ensure no PRs were missing (backwards comparing all previous releases seems to be a bit too much though). But theres already a lot of work required by the release manager: https://cwiki.apache.org/confluence/display/MXNET/Release+Process .

Maybe we should consider adding the instructions for committers/release-managers to verify that commits to release branches (ie. 1.7.x or 1.8.x) are just cherry-pick/porting PRs from the base branch (ie. 1.x) to avoid the problem in the first place.

**Comment by sxjscience** [comment]
@samskalicky I agree. We should revise the guideline for cherry-picking the commits. That means, we need to both cherry-pick to the specific branch and also to 1.x / 2.x in the future.

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by samskalicky** [comment]
@leezu how do you wanna handle this, should we merge this PR so we have a single commit we can cherry-pick to v1.x? Or do you wanna open a separate PR there first before merging this one? Just want to make sure we dont merge this into a feature branch without having it in the main v1.x branch again...

**Review by sxjscience — APPROVED** [review]

**Pull request merged**
