### PR TITLE
update ruby & jekyll, remove incompatible plugins

### LINKED ISSUE #17918: Website / docs build breaking due to Jekyll/Ruby version update
## Description
Local docs builds are breaking. Production is working fine and will stay that way until the docker cache gets invalidated and it tries to build the site again. When it does it'll hit this issue and website/docs publishing will be blocked.

### Error Message
```
Step 10/23 : RUN source /etc/profile.d/rvm.sh &&     rvm requirements &&     rvm install 2.6 &&     rvm use 2.6.3 --default
 ---> Running in e633769ea98c
mesg: ttyname failed: Inappropriate ioctl for device
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system..
Installing required packages: gawk, autoconf, automake, bison, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, pkg-config, sqlite3, libgmp-dev, libreadline6-dev, libssl-dev..................
Requirements installation successful.
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/16.04/x86_64/ruby-2.6.5.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.6.5 - #configure
ruby-2.6.5 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18.0M  100 18.0M    0     0  18.6M      0 --:--:-- --:--:-- --:--:-- 18.6M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.6.5 - #validate archive
ruby-2.6.5 - #extract
ruby-2.6.5 - #validate binary
ruby-2.6.5 - #setup
ruby-2.6.5 - #gemset created /usr/local/rvm/gems/ruby-2.6.5@global
ruby-2.6.5 - #importing gemset /usr/local/rvm/gemsets/global.gems..................................
ruby-2.6.5 - #generating global wrappers.......
ruby-2.6.5 - #gemset created /usr/local/rvm/gems/ruby-2.6.5
ruby-2.6.5 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.6.5 - #generating default wrappers.......
Required ruby-2.6.3 is not installed.
To install do: 'rvm install "ruby-2.6.3"'
The command '/bin/bash -l -c source /etc/profile.d/rvm.sh &&     rvm requirements &&     rvm install 2.6 &&     rvm use 2.6.3 --default' returned a non-zero code: 1
Traceback (most recent call last):
  File "ci/build.py", line 454, in <module>
    sys.exit(main())
  File "ci/build.py", line 364, in main
    num_retries=args.docker_build_retries, no_cache=args.no_cache)
  File "ci/build.py", line 116, in build_docker
    run_cmd()
  File "/home/ubuntu/aaron-mxnet/ci/util.py", line 84, in f_retry
    return f(*args, **kwargs)
  File "ci/build.py", line 114, in run_cmd
    check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-f', 'docker/Dockerfile.build.ubuntu_cpu_jekyll', '--build-arg', 'USER_ID=1000', '--build-arg', 'GROUP_ID=1000', '--cache-from', 'mxnetci/build.ubuntu_cpu_jekyll', '-t', 'mxnetci/build.ubuntu_cpu_jekyll', 'docker']' returned non-zero exit status 1
```
## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. `ci/build.py --docker-registry mxnetci --platform ubuntu_cpu_lite /work/runtime_functions.sh build_ubuntu_cpu_docs`
2. `ci/build.py --docker-registry mxnetci --platform ubuntu_cpu_jekyll /work/runtime_functions.sh build_jekyll_docs`

## What have you tried to solve it?

1. Nada yet
2. Probably try to force it to install the previous version... or upgrade it so it all works.

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
Fixes #17918
More detailed notes are in the issue:
https://github.com/apache/incubator-mxnet/issues/17918#issuecomment-605290574

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- [ ] Code is well-documented: 
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Update Jekyll to v4.0
- [x] Update Ruby to 2.6.5
- [x] Remove redcarpet markdown parser; replace with Kramdown 2.1
- [x] Remove minima theme (doesn't seem that it was being used and not supported w/ Jekyll 4)

## Comments ##

Preview: http://ec2-54-234-175-8.compute-1.amazonaws.com/

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@connorgoggins @TEChopra1000

**Comment by aaronmarkham** [comment]
@ThomasDelteil I removed redcarpet as it was incompatible with jekyll 4 - can you shed any light on what might break now that the site will use kramdown instead?

**Comment by aaronmarkham** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu, unix-gpu]

**Comment by ThomasDelteil** [comment]
I think you should look at the syntax highlighting and see if anything broke

**Comment by aaronmarkham** [comment]
4 hours later... unix-gpu is still running....

**Comment by aaronmarkham** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by leezu** [comment]
@aalexandrov is your preview website working correctly? If so, it appears this PR will break the documentation. Compare http://ec2-54-234-175-8.compute-1.amazonaws.com/api/python/docs/tutorials/ https://mxnet.apache.org/api/python/docs/tutorials/

In the preview website, it's 404 error

**Comment by aaronmarkham** [comment]
> @aaronmarkham is your preview website working correctly? If so, it appears this PR will break the documentation. Compare http://ec2-54-234-175-8.compute-1.amazonaws.com/api/python/docs/tutorials/ https://mxnet.apache.org/api/python/docs/tutorials/
> 
> In the preview website, it's 404 error

That’s the python docs, and i’m just touching the jekyll website. I didn't generate every doc set in the preview. This PR doesn't touch Python.

**Comment by sandeep-krishnamurthy** [comment]
@aaronmarkham - Can you please rebase and resolve conflicts and we are good to go here? Thanks.

**Pull request merged**
