### PR TITLE
Fix sphinx issues 

### PR DESCRIPTION
**Pull request by Roshrini**
## Description ##
Fixes https://github.com/apache/incubator-mxnet/issues/13015, Fixes https://github.com/apache/incubator-mxnet/issues/13018, Fixes https://github.com/apache/incubator-mxnet/issues/13019

@aaronmarkham 

http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13256/2/index.html

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by Roshrini** [comment]
@mxnet-label-bot Add [pr-awaiting-review]

**Comment by kalyc** [comment]
Thanks for your contribution @Roshrini 
There appears to be a CI failure could you re-trigger your PR?
Also please add a preview link to the PR

**Comment by aaronmarkham** [comment]
Some R test failed... that's a new one to me...
```
test_img_seg.R:157: error: UNET

could not find function "mx.ctx.default"

1: .handleSimpleError(function (e) 

   {

       handled <<- TRUE

       test_error <<- e

       options(expressions = expressions_opt_new)

       on.exit(options(expressions = expressions_opt), add = TRUE)

       e$expectation_calls <- frame_calls(11, 2)

       test_error <<- e

       register_expectation(e)

       e$handled <- TRUE

       test_error <<- e

   }, "could not find function \"mx.ctx.default\"", quote(mx.ctx.default())) at R-package/tests/testthat/test_img_seg.R:157

2: eval(code, test_env)
```
I restarted CI in case it is transient...

**Comment by Roshrini** [comment]
Thanks Aaron. I will add preview link once CI passes.

**Comment by kalyc** [comment]
PR looks good to me @aaronmarkham could you take a look

@mxnet-label-bot add [pr-awaiting-merge]

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Pull request merged**
