### PR TITLE
remove meaningless type qualifier

### PR DESCRIPTION
**Pull request by ZiyueHuang**
## Description ##
Otherwise there are so many warnings `warning: type qualifier on return type is meaningless`.

```
g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
cc @eric-haibin-lin @cjolivier01 

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by cjolivier01** [comment]
That’s actually there because my gcc complains without it. The alternative was the const_cast in the function above it. Can you return via the const_cast reference as well? It’s changed to that in one of my other PRs as well.

**Comment by cjolivier01** [comment]
Note it is changed here, but feel free to do it in this PR, which will likely go in sooner: https://github.com/apache/incubator-mxnet/pull/8719/files#diff-bf9721b2b5dd01c635c6efe941fa9da9R188

**Comment by ZiyueHuang** [comment]
@cjolivier01 Thanks for your reference! Update :)

**Comment by ZiyueHuang** [comment]
CI has passed. @szha @cjolivier01

**Pull request merged**
