### PR TITLE
Fixes #9210: Cosine Loss Formula

### LINKED ISSUE #9210: Cosine Loss: Formula
https://github.com/apache/incubator-mxnet/blob/911c81ea7f0598235adea68a788fec429481c317/example/recommenders/recotools.py#L30

that is bounded between 0 and 2

### PR DESCRIPTION
**Pull request by harshit98**
## Description ##
Fixes #9210 
- `cosine = 1 - dot` was bounded between 0 and 2.
- I have divided cosine by 2 so that it becomes bounded between the values 0 and 1.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Feature1, tests, (and when applicable, API doc)
- [x] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by szha** [comment]
@leopd

**Comment by marcoabreu** [comment]
@harshit98 please add a test

**Comment by piiswrong** [comment]
@marcoabreu This is an example. We currently don't test examples

**Comment by marcoabreu** [comment]
Ups, sorry.

**Comment by marcoabreu** [comment]
So are we good to merge then?

**Comment by CodingCat** [comment]
Hi, the community has passed to vote about associating the code changes with JIRA (https://lists.apache.org/thread.html/ab22cf0e35f1bce2c3bf3bec2bc5b85a9583a3fe7fd56ba1bbade55f@%3Cdev.mxnet.apache.org%3E)

We have updated the guidelines for contributors in https://cwiki.apache.org/confluence/display/MXNET/Development+Process, please ensure that you have created a JIRA at https://issues.apache.org/jira/projects/MXNET/issues/ to describe your work in this pull request and include the JIRA title in your PR as [MXNET-xxxx] your title where MXNET-xxxx is the JIRA id

Thanks!

**Pull request merged**
