### PR TITLE
An empty NDArray should have size 0

### PR DESCRIPTION
**Pull request by ziyuang**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by Roshrini** [comment]
@ziyuang Can you add unittest for this change?

**Comment by ziyuang** [comment]
> @ziyuang Can you add unittest for this change?

Yes, where are the other unit tests for cpp-package? I can add one there.

**Comment by reminisce** [comment]
Can you confirm that an empty shape represents an empty ndarray in cpp-package? In Python and C++ backend, an empty shape actually represents a scalar tensor.

**Comment by ziyuang** [comment]
> Can you confirm that an empty shape represents an empty ndarray in cpp-package? In Python and C++ backend, an empty shape actually represents a scalar tensor.

The expected behavior is to return 0 when the array is empty; now I do this check directly without touching the shape vector.

**Comment by ziyuang** [comment]
> @ziyuang Can you add unittest for this change?

Will add a standalone one under `tests/cpp/misc/` if that's good for you

**Comment by vandanavk** [comment]
@ziyuang please fill in the PR description template with relevant details about the changes

**Comment by pinaraws** [comment]
@mxnet-label-bot add[pr-awaiting-response]

**Comment by pinaraws** [comment]
@mxnet-label-bot remove[pr-awaiting-review]

**Comment by abhinavs95** [comment]
@ziyuang any update on the PR? Also please fill the PR description with relevant details.

**Comment by piyushghai** [comment]
@apeforest For review.

**Comment by Roshrini** [comment]
@ziyuang any update on the PR?

**Comment by ziyuang** [comment]
Hi, has this zero-size NDArray issue been handled well by https://github.com/apache/incubator-mxnet/pull/14661 already?

**Comment by karan6181** [comment]
@ziyuang Could you please see if [#14661](https://github.com/apache/incubator-mxnet/pull/14661) fix your issue or not by running small reproducible code and installing the latest pre-release version of MXNet.

**Comment by piyushghai** [comment]
@ziyuang Ping for an update.

**Comment by roywei** [comment]
@ziyuang please trigger CI and update this PR?

**Pull request closed without merging**
