### PR TITLE
[MXNET-716]Scala Benchmark Extension pack

### PR DESCRIPTION
**Pull request by lanking520**
## Description ##
This PR is an extension of this PR: https://github.com/apache/incubator-mxnet/pull/12721
Please merge the previous one first and then this one
adding two examples: `charRNN` and `Object detector`.
@piyushghai @andrewfayres @nswamy @yzhliu 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by vrakesh** [comment]
@mxnet-label-bot [pr-awaiting-review, Scala]

**Comment by piyushghai** [comment]
@lanking520 Can you push an empty commit once more to re-trigger the CI so that we can get this approved PR merged :) ? 
The CI seems to be working for the other PRs now.

**Comment by lanking520** [comment]
Due to an unknown issue with Jenkins, I created a mirror PR here: #12758, this one will temporarily open for future investigation

**Comment by lanking520** [comment]
@lebeg : after confirming with @larroy, `git pull --rebase` doesn't help.

**Comment by lebeg** [comment]
@lanking520 well, there might be a problem if there was already a rebase that sucked up some unrelated changes during conflict resolution. Can you check whether [this](https://github.com/apache/incubator-mxnet/pull/12723/commits/8bf10b9ba6badf2287cfe4c4af85571f8444668d) commit contains only your changes?

**Comment by piyushghai** [comment]
@lanking520 Since https://github.com/apache/incubator-mxnet/pull/12723 is now merged into master, can you close this PR ?

**Comment by lanking520** [comment]
> @lanking520 well, there might be a problem if there was already a rebase that sucked up some unrelated changes during conflict resolution. Can you check whether [this](https://github.com/apache/incubator-mxnet/pull/12723/commits/8bf10b9ba6badf2287cfe4c4af85571f8444668d) commit contains only your changes?

@lebeg Yes, this PR contains only my change. Apart from that, the new PR I sent by simply copying all data is working and passed the CI.

**Comment by lanking520** [comment]
Reproducing the issue with rebasing the up-to-date master branch

**Comment by lebeg** [comment]
@lanking520 ok, I give up) maybe close this PR then since the other is working fine?

**Comment by lebeg** [comment]
https://github.com/apache/incubator-mxnet/pull/12784 should help to prevent such failures in the future.

**Comment by lanking520** [comment]
> #12784 should help to prevent such failures in the future.

Thanks for your effort! This PR close now.

**Pull request closed without merging**
