### PR TITLE
Creating sim-link to raw1394 file

### PR DESCRIPTION
**Pull request by b0noI**
Description of the bug: https://github.com/jsk-ros-pkg/jsk_travis/issues/187

There are a lot of build failures with this problem:
https://builds.apache.org/view/Incubator%20Projects/job/incubator-mxnet/job/master/482/
https://builds.apache.org/view/Incubator%20Projects/job/incubator-mxnet/job/master/475/

### CODE REVIEW

**Comment by gautamkmr** [comment]
LGTM Thanks for doing this.

**Comment by gautamkmr** [comment]
The failure is not related to this PR. Please put a  rebuild .

**Comment by szha** [comment]
the 1394 error is not really an error

**Comment by szha** [comment]
To really find the error, please print the error instead of `sh "echo caught error"`

**Comment by b0noI** [comment]
@szha I agree that this, in majority (all?) of the failures, not the root cause. But can we still eliminate it so whoever is looking on the build would not be distracted by the red herring.

**Comment by szha** [comment]
Find a single one that's failed due to this first.

**Comment by szha** [comment]
On the other hand, it would be really helpful to print the actual error in the Jenkinsfile by fixing the line `sh "echo caught error"`

**Comment by b0noI** [comment]
I want to remove red herring so no one else will spend time investigating something that is not relevant to build problems(even if 0 builds are failing due to this reason). And yep, I completely agree that fixing sh "echo caught error" would be a bigger win, I will try to allocate some time later to fix it.

**Comment by szha** [comment]
The place to edit is at https://github.com/apache/incubator-mxnet/blob/master/Jenkinsfile#L526
The reference on how to edit is at https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#code-catcherror-code-catch-error-and-set-build-result
Hopefully you won't have to allocate too much time.

**Comment by gautamkmr** [comment]
Doing it here https://github.com/apache/incubator-mxnet/pull/8199

**Pull request closed without merging**
