### PR TITLE
Fix setting cudnn bias stride and change order of bgrad and wgrad to boost performance

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
cuDNN expects bias stride to be (C, 1, C, C), whereas currently it is provided by MXNet as (C, 1, 1, 1).
This PR also changes the order of calls to wgrad and bgrad. This has potential to boost performance, because wgrad uses the same data as bgrad, but is typically compute-limited (so the data transfer cost is hidden), so there is a chance that the data needed by purely BW-bound bgrad is already in cache.. 

@DickJC123

### CODE REVIEW

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-cpu, miscellaneous, unix-cpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by DickJC123** [comment]
Beginning my review.  The change in strides looks good to me based on the following reasoning:

A kernel that accesses an element at location (n_index, c_index, h_index, w_index) will use the equation:
```
element_offset = n_index * n_stride + c_index * c_stride + h_index * h_stride + w_index * w_stride
```
For a tensor with a particular dimension size of 1, the only valid index in that dimension is 0, so the stride in that dimension is essentially a don't care.  Your PR is changing strides of the bias tensor for dimension sizes equal to 1, so that really shouldn't matter.  The new strides you are proposing seem to make more sense though, and if that helps existing cuDNN libraries make a better bias kernel choice, all the better.

Did you measure perf gains and under what environments?  Did you come to understand whether it was because of the reordering of bias and wgrad, or based on the actual cuDNN bias kernel choice, or both?

Thanks for making the changes similarly in Deconvolution- it's good to keep these operators in sync as much as possible for ease of code maintenance.

**Comment by ptrendx** [comment]
The strides change does not really change anything, you are right - this change is here just because cuDNN internally does tests only with the bias strides in the form of (C, 1, C, C), so with this change we are safer.

As for performance impact - this change was prompted by tests of NVIDIA MLPerf SSD submissions, where we were comparing MXNet and pyTorch performance. The difference in bias gradient performance between those 2 implementations was 4x and this turned out to be the difference in order of wgrad and bgrad.

**Pull request merged**
