### PR TITLE
LAMB optimizer

### PR DESCRIPTION
**Pull request by anirudhacharya**
## Description ##
LAMB optimizer - https://arxiv.org/pdf/1904.00962.pdf

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Comments
- will add documentation. 
@apeforest @eric-haibin-lin

### CODE REVIEW

**Comment by apeforest** [comment]
@anirudhacharya Please resolve the conflict.

**Comment by sxjscience** [comment]
@anirudhacharya Any update?

**Comment by anirudhacharya** [comment]
sorry for the delay. i was away.

these are the changes i will do to the existing PR - 

create multi-tensor kernel that performs the following part of the optimizer.
```python
        grad *= self.rescale_grad
        if self.clip_gradient is not None:
            grad = clip(grad, -self.clip_gradient, self.clip_gradient)

        mean, var = state
        mean[:] = self.beta1 * mean + (1. - self.beta1) * grad
        var[:] = self.beta2 * var + (1. - self.beta2) * mx.nd.square(grad)
        if not self.bias_correction:
            g = mean / (mx.nd.sqrt(var) + self.epsilon) + wd * weight

        else:
            mean_hat = mean / (1. - mx.nd.power(self.beta1, t))
            var_hat = var / (1. - mx.nd.power(self.beta2, t))
            g = mean_hat / mx.nd.sqrt(var_hat + self.epsilon) + wd * weight
```

then use the existing `multi_sum_sq` operator to calculate the norms 
```python
r1 = weight.norm()
r2 = g.norm()
```

create another multi-tensor kernel to perform the clipping operation on r1 tensor and calculating the trust ratios.
```python
if not self.bias_correction:
r1 = mx.nd.minimum(mx.nd.maximum(r1, self.lower_bound), self.upper_bound)
# calculate lamb_trust_ratio
r = 1. if r1 == 0. or r2 == 0. else r1 / r2
lr *= r
```

and finally call the existing `multi_sgd_update` rule to update the weight matrices.
```ptyhon
        # update weight
        weight[:] -= lr * g
```

**Comment by eric-haibin-lin** [comment]
related: https://github.com/apache/incubator-mxnet/pull/16122/files

**Pull request closed without merging**
