### PR TITLE
Revert "Static memory allocation for cached_op (#10817)"

### PR DESCRIPTION
**Pull request by marcoabreu**
This reverts commit 2dbd143e4892bb9ad4aa1835c79f0046603e3531.

See https://github.com/apache/incubator-mxnet/issues/11171 for reference. #10817 has not been approved and is causing regressions.

### CODE REVIEW

**Comment by zheng-da** [comment]
can we move forward instead of backward?

**Comment by tqchen** [comment]
close due to bugfix introduced in #11117

**Comment by tqchen** [comment]
https://github.com/apache/incubator-mxnet/pull/11310

**Comment by tqchen** [comment]
Who talked about not self-merging....

**Comment by tqchen** [comment]
with great power comes great responsibility. I would never abused that power to any changes just to make a point and bring things backward.

**Pull request merged**
