### PR TITLE
Add unit tests for potri and potrf backward and check output shape.

### PR DESCRIPTION
**Pull request by josephevans**
Add unit tests for backward linalg_potri and linalg_potrf operators. Verify output shape.

Test results (with modified function names):
```
python3 -m pytest --verbose tests/nightly/test_large_array.py::test_potrf tests/nightly/test_large_array.py::test_potri
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/ubuntu/anaconda3/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/ubuntu/incubator-mxnet/.hypothesis/examples')
rootdir: /home/ubuntu/incubator-mxnet, inifile: pytest.ini
plugins: remotedata-0.3.2, openfiles-0.4.0, astropy-header-0.1.2, timeout-1.4.1, hypothesis-5.8.3, arraydiff-0.3, doctestplus-0.5.0
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collected 2 items

tests/nightly/test_large_array.py::test_potrf PASSED                                                                                                                 [ 50%]
tests/nightly/test_large_array.py::test_potri PASSED                                                                                                                 [100%]

============================================================================ 2 passed in 1654.43s (0:27:34)  ============================================================================
```

### CODE REVIEW

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by Zha0q1** [comment]
LGTM

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
