### PR TITLE
[Numpy]Fix einsum issue #18102

### PR DESCRIPTION
**Pull request by hanke580**
## Description ##
Fix einsum gradient bug in Issue #18102

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by sxjscience** [comment]
@hanke580 Would you fix the lint check and add some test cases?

**Comment by hanke580** [comment]
Sure, tests adding

**Comment by leezu** [comment]
This looks like something we should backport to 1.6, 1.7, 1.x branches @hanke580 @sxjscience?

cc @ciyongch

**Comment by sxjscience** [comment]
It should be backported to 1.7.

**Comment by ciyongch** [comment]
Hi @hanke580 , can you help to backport this PR to v1.7.x branch as suggested by @sxjscience and @leezu , and tag me in the new PR? Thanks.

**Comment by hanke580** [comment]
Sure @ciyongch

**Comment by ChaiBapchya** [comment]
@sxjscience Why isn't this backported to v1.x branch? Any specific reason or just a miss?

**Comment by sxjscience** [comment]
It's just a miss.

**Comment by ChaiBapchya** [comment]
Can we get a cherry-pick for this?

**Pull request merged**
