### PR TITLE
update mklml and mkl mac support

### PR DESCRIPTION
**Pull request by szha**
needs dmlc/mshadow#290 to work

### CODE REVIEW

**Comment by piiswrong** [comment]
compile failed

**Comment by piiswrong** [comment]
Updates?

**Comment by szha** [comment]
Sorry, been occupied. I'm working on this today.

**Comment by szha** [comment]
@piiswrong ready for review. The test error doesn't seem related.

**Comment by mli** [comment]
did a quick look, lgtm, i'll merge it first

**Pull request merged**
