### PR TITLE
backport Julia patches to v1.5.x

### PR DESCRIPTION
**Pull request by iblis17**
- #15608 
- #15609 
- #16138

### CODE REVIEW

**Comment by iblis17** [comment]
cc @TaoLv

**Comment by iblis17** [comment]
Hi @apeforest , could you elaborate the reason of closing this PR?

**Comment by apeforest** [comment]
Hi @iblis17 I am so sorry. This must be an accident when I was viewing PRs on my cell phone. I have re-opened it for review. Again, I am truly sorry for the inconvenience caused by my misoperation.

**Comment by iblis17** [comment]
haha, :ok_hand:

**Pull request merged**
