### PR TITLE
[v1.5.x] Fix _copy_to on MKLDNN backend (#15637)

### PR DESCRIPTION
**Pull request by juliusshufan**
* Fix _copy_to

* Add comment

## Description ##
cherry-pick PR#15637

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
@kostayScr We're going to include this PR to 1.5.1 patch release to fix issue #15555. It would be highly appreciated if you can apply this change to the 1.5.0 code base and verify it with your application. Thanks!

**Comment by juliusshufan** [comment]
@ZhennanQin Could you please take a look if the CI failure is relevant to this commit?

Thanks.

**Comment by ZhennanQin** [comment]
@juliusshufan 

The error output is 
```
test_operator_gpu.test_ndarray_elementwisesum ... [07:38:05] src/operator/tensor/./.././../common/../operator/mxnet_op.h:794: Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:an illegal memory access was encountered
```
Seems doesn't relate to this PR.

**Comment by roywei** [comment]
@juliusshufan could you trigger CI again? thanks!

**Comment by juliusshufan** [comment]
@roywei @TaoLv @ZhennanQin This PR failed to pass the CI after multiple retiggering.
May I have your time to confirm if it is relevant to the changes?

Thanks.

**Comment by ZhennanQin** [comment]
@juliusshufan CI seems either timeout for build, or failed to executing `apt-get update`, or failed to create doc, which are all irrelevant with this PR.
@roywei @TaoLv Can you please check the CI status for this branch? Like create an empty PR to see if it can pass CI and fix all problems if not.

**Comment by TaoLv** [comment]
@juliusshufan Could you please re-trigger the CI? Thanks.

**Comment by kostayScr** [comment]
@TaoLv I've upgraded to mxnet 1.5.0. Reproduced the bug using the code from https://github.com/apache/incubator-mxnet/issues/15555#issuecomment-513219404. Applying this patch fixed the bug.

**Comment by TaoLv** [comment]
@shufan @ZhennanQin Could you please rebase to see if it can pass the CI? I notice there are other PRs passed the CI properly last night and got merged into the branch.

**Comment by juliusshufan** [comment]
@TaoLv CI passed. Thanks.

**Comment by pengzhao-intel** [comment]
merging now.

**Pull request merged**
