### PR TITLE
[1.x] Revert PR 17767 for fixing GPU memory usage regression (#18283)

### PR DESCRIPTION
**Pull request by rondogency**
* Revert "Fix and optimize handling of vectorized memory accesses (#17767)"

This reverts commit 5542d03695b4a2589afb88acf128d4ba8ac94d0d.

* add license to reverted file

This revert has been patched into 2.0, need to cherry-pick to 1.x and 1.7

@ciyongch

### CODE REVIEW

**Comment by ciyongch** [comment]
Hi @rondogency , can you help to create another PR for v1.7.x as well, as I don't have the permission to do the cherry-pick. Thanks!
@TaoLv @pengzhao-intel please help to merge once it pass the CI.

**Comment by rondogency** [comment]
@mxnet-bot run ci [edge]

**Comment by rondogency** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
@rondogency can we rename the title with [1.x] pre-pend to the existing name? For easier access. Thanks

**Comment by ChaiBapchya** [comment]
Since https://github.com/apache/incubator-mxnet/pull/18375 is merged, edge pipeline should be unblocked
@mxnet-bot run ci [edge]

**Comment by rondogency** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by rondogency** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
