### PR TITLE
fix latency calculation and print issue

### PR DESCRIPTION
**Pull request by ciyongch**
## Description ##
This PR is to correct the latency calculation in `example/quantization/launch_inference_mkldnn.sh`. the latency should be related to a batch not an image. Also change print from `bc` to `awk` as `bc` might not come always as installed package.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here
@pengzhao-intel @xinyu-intel @TaoLv

### CODE REVIEW

**Comment by TaoLv** [comment]
@ciyongch Could you please paste the refined log message here?

**Comment by TaoLv** [comment]
And please re-trigger CI :(

**Comment by ciyongch** [comment]
> @ciyongch Could you please paste the refined log message here?

The updated message looks like this:
```
target machine has 56 physical core(s) on 2 numa nodes of 2 socket(s).
  benchmark configs
  cores per instance: 28
  total instances: 1
  batch size: 64
  iterations: 10

  0 instance use 0-27 cores and 0 mem with BENCHMARK_0.log
overall throughput (image/sec): 299.068
latency per batch per instance (ms): 214.00
benchmark finish:)
```

**Comment by TaoLv** [comment]
How about changing `0 instance use 0-27 cores and 0 mem with BENCHMARK_0.log` to `Instance 0 uses core 0-27 and mem 0: BENCHMARK_0.log`?

**Comment by ciyongch** [comment]
> How about changing `0 instance use 0-27 cores and 0 mem with BENCHMARK_0.log` to `Instance 0 uses core 0-27 and mem 0: BENCHMARK_0.log`?

Sure.

**Comment by ciyongch** [comment]
@pengzhao-intel @TaoLv please review again :)

**Pull request merged**
