### PR TITLE
Fix memory leak in NaiveEngine

### LINKED ISSUE #15375: Memory leak in Naive engine when profiling
I believe there's a memory leak in Naive engine here:

https://github.com/apache/incubator-mxnet/blob/master/src/engine/naive_engine.cc#L164

I think it would be a great opportunity to refactor how NewOperator is released. As it's also difficult to reason about the release of the operator memory in the threaded engine (looks correct to me, but it takes quite a bit to dig it up and understand).

I would propose returning a unique_ptr directly with a custom deleter using a virtual operator() that is specialized for the engine type which will get the same effect as how operators are being released now. This would make easier to reason about this memory management part.

https://github.com/apache/incubator-mxnet/blob/master/src/engine/threaded_engine.cc#L270

### PR DESCRIPTION
**Pull request by larroy**
Fixes #15375

## Description ##
Fixes a memory leak in NaiveEngine when using operator profiling.

### CODE REVIEW

**Comment by larroy** [comment]
Added valgrind run which shows the memory being leaked.

naive_engine_leak

**Comment by larroy** [comment]
@mxnet-label-bot add [Engine, Bug, Memory]

**Comment by larroy** [comment]
@mxnet-label-bot add [Backend]

**Comment by larroy** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by wkcn** [comment]
Merged. Thank you!

**Pull request merged**
