### PR TITLE
[BUGFIX] Fix MKLDNN BatchNorm with even number of channels (#19150) #19299

### PR DESCRIPTION
**Pull request by akarbown**
## Description ##
It's the change (https://github.com/apache/incubator-mxnet/pull/19299) ported form mxnet 1.7.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [ ] Code is well-documented

### CODE REVIEW

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by akarbown** [comment]
@mxnet-bot run ci [greeting, unix-cpu]

**Comment by akarbown** [comment]
@TaoLv, @wkcn, @samskalicky - could you please take a look at this change & review it!? (it's the same change as for the 1.x, 1.7 & 1.8 branches)

**Review by samskalicky — APPROVED** [review]
Thanks @akarbown for porting this fix!

**Pull request merged**
