### PR TITLE
[MXNET-521] Add Facebook open-graph tag integration

### PR DESCRIPTION
**Pull request by kpmurali**
## Description ##
Adding Facebook Open-Graph tags

### Changes ###
- [ x ] Adding meta og tags for title, image and description.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@thomelane @ThomasDelteil - any thoughts on this? Sharing should be better... I made the image according to the minimum requirements FB suggests.
https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/image/og-logo.png

**Comment by aaronmarkham** [comment]
@szha Can you please merge this?

**Comment by thomelane** [comment]
Yes, looks great!

**Comment by aaronmarkham** [comment]
@eric-haibin-lin @szha Bueller? Can you please merge this?

**Comment by aaronmarkham** [comment]
bueller

**Comment by ThomasDelteil** [comment]
@anirudh2290 @indhub could one of you merge this please?

**Pull request merged**
