### PR TITLE
Update Apache License for mshadow

### PR DESCRIPTION
**Pull request by ciyongch**
## Description ##
Update Apache License for mshadow as described in https://github.com/apache/incubator-mxnet/issues/17329.

@TaoLv @pengzhao-intel @szha

### CODE REVIEW

**Comment by ciyongch** [comment]
Ping @mjwall as well.

I will backport this PR to v1.x and v1.7.x branch later.

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by leezu** [comment]
Please update the RAT license checker to enforce license in the 3rdparty/mshadow folder

Ie need to fix this line

https://github.com/apache/incubator-mxnet/blob/6198d1d7e10ba58ccc64ab7701d0c528b64bd58e/tests/nightly/apache_rat_license_check/rat-excludes#L34

**Comment by ciyongch** [comment]
> Thanks @ciyongch ! Let's have a mechanism to ensure the mshadow folder stays compliant (ie. disable the exclusion in rat?)

@leezu Thanks for point it out, I've updated the `rat-excludes` to enable check for `mshadow`, and keep the rest of folders under `3rdparty` unchanged. Not sure if there's any other elegant way to handle this.

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu ]

**Comment by ciyongch** [comment]
@TaoLv @pengzhao-intel @nswamy @szha Please help to take a review, thanks.

**Comment by pengzhao-intel** [comment]
Looks and merging now.

**Pull request merged**
