### PR TITLE
[Backport][v1.5.x] Fix the bug of `MXEnginePushAsyncND` and `MXEnginePushSyncND`

### PR DESCRIPTION
**Pull request by wkcn**
## Description ##
Fix the bug of `MXEnginePushAsyncND` and `MXEnginePushSyncND` in v1.5.x release

Issue: #15774 
master branch: #15751 
v1.5.x branch: #15775 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Modify the type of arguments to 'NDArry**'
- [x] Update the unittest

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by wkcn** [comment]
Thank @szha ! The PR will be merged if there is no change in https://github.com/apache/incubator-mxnet/pull/15751

**Comment by TaoLv** [comment]
To make the git history consistent, should we cherrypick the commit to v
1.5.x after #15751 is merged to master?

发自我的 iPhone

在 2019年8月8日，上午7:47，JackieWu <notifications@github.com<mailto:notifications@github.com>> 写道：


Thank @szha<https://github.com/szha> ! The PR will be merged if there is no change in #15751<https://github.com/apache/incubator-mxnet/pull/15751>

―

**Comment by wkcn** [comment]
@TaoLv Should I reopen a PR created by cherry-pick?

**Comment by wkcn** [comment]
I see. Close this PR, and I will reopen a PR committed by cherry-pick : )

**Comment by wkcn** [comment]
Hi @TaoLv , I have created a new PR #15792 committed by cherry-pick.

**Pull request closed without merging**
