### PR TITLE
MXNET-1444/MXNET-1445: replace NULL by nullptr literal

### PR DESCRIPTION
**Pull request by olk**
- using nullptr is more explicit
- macro NULL can be a integer literal with value zero (since C++11)
- literal nullptr is of type std::nullptr_t
- as template arg NULL and 0 evaluate to integer

### CODE REVIEW

**Comment by leezu** [comment]
Please see CI, lint is failing:

`[2020-02-06T19:25:21.265Z] include/mxnet/lib_api.h: 1 Errors of 1 Categories map={'whitespace': 1}
`

**Comment by olk** [comment]
whitespace error was introduced by commit ae472c266 dynamic custom operator support (#15921) - I've fixed it

**Comment by leezu** [comment]
`[2020-02-06T20:48:22.104Z] include/mxnet/lib_api.h:631:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
`

**Comment by olk** [comment]
There was an additional whitespace error from a previous commit - I don't know why it could pass the lint check.
I've adopted my vimrc accordingly.

Could I get a link to the coding/code formating standards used in MXNet?

**Comment by olk** [comment]
generating Julia docs fails with:
```
[2020-02-07T10:19:19.325Z] raise VersionConflict(dist, req).with_context(dependent_req)
[2020-02-07T10:19:19.325Z] pkg_resources.VersionConflict: (Markdown 3.2 (/home/jenkins_slave/.local/lib/python3.5/site-packages), Requirement.parse('markdown<3.2'))
```

**Pull request closed without merging**
