### PR TITLE
[v1.x]Fix Nightly CI

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
Update v1.x Nightly CI CPU/GPU image to ubuntu 18
Update Rat check image to ubuntu 18

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
Running Will post results once complete.

### CODE REVIEW

**Review by mseth10 — APPROVED** [review]
LGTM

**Review by waytrue17 — APPROVED** [review]
LGTM!

**Comment by access2rohit** [comment]
Local run succeded: 
```
$ ci/build.py --docker-registry 021742426385.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci --platform ubuntu_nightly_cpu --docker-build-retries 3 --shm-size 500m /work/runtime_functions.sh build_ubuntu_cpu_large_tensor
.
.
.
.
[442/445] Linking CXX static library libmxnet.a
[443/445] Linking CXX executable im2rec
[444/445] Linking CXX shared library libmxnet.so
[445/445] Linking CXX executable tests/mxnet_unit_tests
```

**Review by mseth10 — APPROVED** [review]
LGTM

**Pull request merged**
