### PR TITLE
Improved git reset for CI builds

### PR DESCRIPTION
**Pull request by lebeg**
## Description ##

Prevent [strange CI failures](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12723/10/pipeline).

### CODE REVIEW

**Comment by lebeg** [comment]
@marcoabreu i see your point. We can look what caused the failure on the master as well later. Do you think this PR does not bring any value? What changes are you requesting?

**Comment by marcoabreu** [comment]
Yes, I don't think this PR brings any value because the git workspace is managed on master. This PR won't bring any benefit because the code in question won't actually be executed - tampering a mirrored copy that Jenkins and all tools expect to be an exact copy rather poses more risks than potential benefits

**Comment by larroy** [comment]
@marcoabreu  I don't get your point, isn't this executed on the worker namespace?

**Comment by marcoabreu** [comment]
Yes, but the problem in question occurs on the master. We don't even get to the worker stage. To be more specific, the Jenkinsfile won't even be evaluated.

**Comment by lebeg** [comment]
@marcoabreu Yes, I see you point that this PR will not resolve the mentioned problem. If I remove the description and just leave the title `Improved git reset for CI builds`. Would you be in favour of reviewing and merging it?

**Comment by marcoabreu** [comment]
I'd still be opposed to merging because this would break our Jenkins validation strategy. Jenkins automatically creates a merge commit and does other modifications to align the various repository states. Merging this PR would destroy that structure and result in PRs not being validated in merge- but standalone mode. That's not something we would want.

At the moment I'm having difficulties to find the benefit of this change. Could you maybe a elaborate which problem this would solve?

Otherwise, I'd advocate for not changing a running system since that part has not caused an issues that I am aware of.

**Comment by lebeg** [comment]
This will save builds from CI failure that had modified checked in code for whatever reason.

> I'd still be opposed to merging because this would break our Jenkins validation strategy. 

What is the strategy and what are we validating with it? My PR ensures that for every build attempt we have a guaranteed clean default state.

**Comment by marcoabreu** [comment]
> This will save builds from CI failure that had modified checked in code for whatever reason.
Do you have an example of such a case?

> What is the strategy and what are we validating with it? My PR ensures that for every build attempt we have a guaranteed clean default state.
The strategy merges your PR with the head of master. This allows us to always validate a PR as if it would be merged at that moment opposed to requiring the user to rebase constantly. This change would revert this merge and effectively switch from a "PR-merge" to a "PR-head" strategy. 

The problem with your PR is that it's actually purging too much and putting the repository into a "too" clean state. It's effectively invalidating Jenkins' actions.

**Comment by lebeg** [comment]
> Do you have an example of such a case?

We recently had a problem with some buildscripts that would [modify some Makefiles](https://github.com/apache/incubator-mxnet/pull/11245/files#diff-1335fbaf3930b1438d9be18edb07a1a6R73) for Jetson cross compilation.

> The problem with your PR is that it's actually purging too much and putting the repository into a "too" clean state. It's effectively invalidating Jenkins' actions.

I'm afraid I don't understand what is a "too clean" state. What actions of Jenkins we are invalidating? What situation we are trying to validate by not resetting the repository before a clean build? 

> ... revert this merge and effectively switch from a "PR-merge" to a "PR-head" strategy.

We try to merge a PR into not modified master state. We are not switching any strategies, nor moving `HEAD` in any way.

**Comment by marcoabreu** [comment]
> We recently had a problem with some buildscripts that would modify some Makefiles for Jetson cross compilation.

But for the scope of that run, the modification is valid, right? After the run finishes, the workspace is automatically cleaned up. This means that a subsequent run won't be using these modified files but will get a unmodified version of the repository.

> I'm afraid I don't understand what is a "too clean" state. What actions of Jenkins we are invalidating? What situation we are trying to validate by not resetting the repository before a clean build?

Let's look at the following SCM log from Jenkins:
```
Cloning the remote Git repository

Cloning with configured refspecs honoured and without tags

Cloning repository https://github.com/apache/incubator-mxnet.git

 > git init /home/jenkins_slave/workspace/sanity-lint # timeout=10

Fetching upstream changes from https://github.com/apache/incubator-mxnet.git

 > git --version # timeout=10

using GIT_ASKPASS to set credentials 

 > git fetch --no-tags --progress https://github.com/apache/incubator-mxnet.git +refs/pull/12656/head:refs/remotes/origin/PR-12656 +refs/heads/master:refs/remotes/origin/master

 > git config remote.origin.url https://github.com/apache/incubator-mxnet.git # timeout=10

 > git config --add remote.origin.fetch +refs/pull/12656/head:refs/remotes/origin/PR-12656 # timeout=10

 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10

 > git config remote.origin.url https://github.com/apache/incubator-mxnet.git # timeout=10

Fetching without tags

Fetching upstream changes from https://github.com/apache/incubator-mxnet.git

using GIT_ASKPASS to set credentials 

 > git fetch --no-tags --progress https://github.com/apache/incubator-mxnet.git +refs/pull/12656/head:refs/remotes/origin/PR-12656 +refs/heads/master:refs/remotes/origin/master

Merging remotes/origin/master commit 76ae7252a6751275565600d287b7d432b685fd7d into PR head commit 9451518b19406a6d5cc24ab0ea83d9776c078f3c

 > git config core.sparsecheckout # timeout=10

 > git checkout -f 9451518b19406a6d5cc24ab0ea83d9776c078f3c

 > git merge 76ae7252a6751275565600d287b7d432b685fd7d # timeout=10

 > git rev-parse HEAD^{commit} # timeout=10

Merge succeeded, producing 9451518b19406a6d5cc24ab0ea83d9776c078f3c

Checking out Revision 9451518b19406a6d5cc24ab0ea83d9776c078f3c (PR-12656)

 > git config core.sparsecheckout # timeout=10

 > git checkout -f 9451518b19406a6d5cc24ab0ea83d9776c078f3c

Commit message: "[MXNET-703] Show perf info for TensorRT during tests"
```

As you can see, Jenkins runs ```git merge 76ae7252a6751275565600d287b7d432b685fd7d``` and thus creates a temporary commit that merges the PR with the head of master (in case your PR was not rebased). Your command would delete that commit.


> We try to merge a PR into not modified master state. We are not switching any strategies, nor moving HEAD in any way.

Unfortunately, you are actually moving HEAD with that action. The PR-merge strategy syncs up the HEAD of the PR (incase it has not been rebased) with the HEAD of master. After the PR-merge strategy has been applied, the HEAD of the PR (during that run) and the HEAD of master are equivalent + the changes of the PR. If we execute your git clean (or run PR-head strategy), the HEAD of the PR will be depending on the base of the PR. This means that the PR might have diverged from master. Think about the message
```
This branch is 66 commits ahead, 1750 commits behind apache:master.
```
The PR-head strategy (which you are enforcing that way) will keep it that way. The PR-merge strategy will make the PR look like 
```
This branch is 66 commits ahead of apache:master.
```

Does that make it clearer for you?

**Comment by lebeg** [comment]
> As you can see, Jenkins runs git merge 76ae7252a6751275565600d287b7d432b685fd7d and thus creates a temporary commit that merges the PR with the head of master (in case your PR was not rebased). Your command would delete that commit.

This is not true, since after merge is performed `HEAD` points to the merge commit.

> If we execute your git clean (or run PR-head strategy), the HEAD of the PR will be depending on the base of the PR.

This is not true either.

Refer to `git-reset --hard` [documentation](https://git-scm.com/docs/git-reset#git-reset---hard). Without an argument it assues `HEAD`, with as I've stated previously points to the merge commit.

**Comment by ankkhedia** [comment]
@marcoabreu @lebeg ping!
Any updates on the PR.

**Comment by marcoabreu** [comment]
Okay, that makes sense then. Thanks for elaborating. I'm slightly on the fence here, but I'm happy to merge it and observe whether we encounter any problems down the road. Sorry for the delayed response.

**Pull request merged**
