### PR TITLE
Fix of log10_grad, log2_grad

### PR DESCRIPTION
**Pull request by mseeger**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] For user-facing API changes, API doc string has been updated.
- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Intersting edge cases to note here

### CODE REVIEW

**Comment by mseeger** [comment]
@piiswrong The change you are asking for (good catch).

BTW: One open point here is whether all DType's are supported. I think that mshadow::half::half2_t is not, because conversion to/from float is missing.
I am not much interested in half-precision arithmetic, so would not want to own doing this, but if somebody works on CUDA half2 support and needs help with mshadow_op.h, please loop me in.

I note that CUDA has own implementations for a subset of math.h functions for its half types. But I also have the feeling that this is never the bottleneck for DNNs, and so casting to/from float for them seems OK to me.

**Comment by piiswrong** [comment]
I'll let nv folks make that decision

**Comment by piiswrong** [comment]
@ptrendx

**Comment by ptrendx** [comment]
Casting inside the kernel should be fine.

**Comment by mseeger** [comment]
@ptrendx : The one type I have seen, for which cast to/from float (so float32) is not implemented, is half2_t. I don't know whether that is important, and what the relationship to half_t is. Just to let you know: none of the math.h functions will work for half2_t.

**Pull request merged**
