### PR TITLE
[MXNET-319][DO NOT MERGE][Deprecated] Javadoc fix

### PR DESCRIPTION
**Pull request by lanking520**
## Description ##
This is an experimental PR used to find a best way to generate Javadoc for Scala
@nswamy @yzhliu 
Here are two solution I proposed:
1. use new API signature to replace the old one (this PR)
2. create signature for old api and not change the current functions

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Feature1, tests, (and when applicable, API doc)
- [x] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by lanking520** [comment]
Since this is a risky decision to work on this way, I will close this once we have NDArray bug fix merged. There will be another PR for Documentation with Signature for all old APIs.

**Comment by andrewfayres** [comment]
commenting to see if this fixes the problem with you tagging me on this

**Comment by lanking520** [comment]
@andrewfayres Thanks!

**Comment by yzhliu** [comment]
Is it duplicated with #11143 ?

**Comment by nswamy** [comment]
@lanking520 Can we close this, as discussed in another PR we agreed not to change the internal APIs to use new APIs?

**Comment by lanking520** [comment]
Master branch merged, no need to go with this solution

**Pull request closed without merging**
