### PR TITLE
Adds install via CMake

### PR DESCRIPTION
**Pull request by fran6co**
The install target will copy all the relevant files and create the cmake config file for easy integration with other projects using find_package(mxnet)

### CODE REVIEW

**Comment by lupesko** [comment]
@fran6co please follow up on the build failure so we can move this along... thanks!

**Comment by lupesko** [comment]
@fran6co - bumping the issue.
@mxnet-label-bot [pr-awaiting-testing]

**Comment by vandanavk** [comment]
@fran6co ping

@sandeep-krishnamurthy Please change label to pr-awaiting-testing

**Comment by vrakesh** [comment]
@fran6co requesting you to look into the build failures.

**Comment by fran6co** [comment]
@vrakesh sorry but I don't have time to get back to this PR. Should I close it?

**Comment by Roshrini** [comment]
@fran6co Can you close this PR if you cannot work on it now?
Feel free to reopen whenever you can.

**Comment by ankkhedia** [comment]
@fran6co ping!

**Pull request closed without merging**
