### PR TITLE
Re-enables test_operator.test_dropout

### LINKED ISSUE #12329: Flaky test: test_operator.test_dropout
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12311/1/pipeline

```
======================================================================
FAIL: test_operator.test_dropout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/unittest/common.py", line 172, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5844, in test_dropout
    check_dropout_ratio(0.0, shape)
  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5788, in check_dropout_ratio
    assert exe.outputs[0].asnumpy().min() == min_value
AssertionError: 
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=119185068 to reproduce.
--------------------- >> end captured logging << ---------------------
```

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
Fixes #12329
Re-enables test_operator.test_dropout
I've tested it 10k times and it passed. I also tested it using the issue's random seed and it passed.
I believe it is safe to re-enable.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by vrakesh** [comment]
@mxnet-label-bot  [pr-awaiting-review]

**Comment by vandanavk** [comment]
Please add 

> Fixes https://github.com/apache/incubator-mxnet/issues/12329

 in the PR description so that the issue is closed automatically when this PR is merged.

**Comment by perdasilva** [comment]
Done

**Comment by sandeep-krishnamurthy** [comment]
Hello @perdasilva Thanks for this contribution.
Did you run this test with this seed - 119185068 which was reported in the issue as failure?

**Comment by perdasilva** [comment]
@sandeep-krishnamurthy yup - I've ran it 10k times and tested it with the suggested seed. No failures for me.

**Pull request merged**
