### PR TITLE
send _send_command_to_servers must be string

### PR DESCRIPTION
**Pull request by azai91**
## Description ##
_send_command_to_servers  expects to send a string. Python3 pickles objects into bytes (https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/kvstore.py#L391). I added validation to type check the body and decode to string if needed.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] For user-facing API changes, API doc string has been updated.
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Intersting edge cases to note here

### CODE REVIEW

**Comment by piiswrong** [comment]
Fix this at caller and use base.py_str

**Comment by azai91** [comment]
@piiswrong any reason this can't be built?

**Comment by rahul003** [comment]
@azai91 Try pushing empty commit to trigger CI again. We are facing some issues with CI currently.

**Comment by rahul003** [comment]
@azai91 This doesn't fix the issue. It would still throw the error at Line 392. 
Either way, I believe your issue would be fixed by a recently merged PR https://github.com/apache/incubator-mxnet/pull/8334. Can you please check.

**Comment by azai91** [comment]
Can we merge this in?

**Comment by anirudh2290** [comment]
@cjolivier01 can you please help in closing the PR. The change seems to be similar to #8334 which is merged.

**Comment by eric-haibin-lin** [comment]
Thanks for the contribution. But it looks like #8334 already fixed it. Closing it for now.

**Pull request closed without merging**
