### PR TITLE
fix row_sparse demo tutorials doc

### PR DESCRIPTION
**Pull request by burness**
## Description ##
[row sparse demo tutorials](https://mxnet.incubator.apache.org/versions/master/tutorials/sparse/row_sparse.html), it has a mistake that x should be 1*2 and w should be 2*3.

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
The CI is a bit brittle. Do you mind sync with master and trigger the CI again?

**Comment by burness** [comment]
Ok! I will try @eric-haibin-lin

**Comment by piiswrong** [comment]
why is there no change?

**Comment by piiswrong** [comment]
Looks like this is already merged in. Closing

**Pull request closed without merging**
