### PR TITLE
Provide instructions to install a particular release.

### PR DESCRIPTION
**Pull request by indhub**

### CODE REVIEW

**Comment by mli** [comment]
I'm not sure we want to let users clone a particular tag in default. Firstly these codes are not copy-pasted runnable, secondly, we need to update the doc for everything release

**Comment by indhub** [comment]
Do you agree we need to document how to install a particular version from source? If yes, and if you don't think this is the right way to do it, could you please let me know a better way to do it?

Answers to your specific questions:

>> I'm not sure we want to let users clone a particular tag in default.
I'm not sure if I understand this. How will user install a particular version without cloning a particular tag?

>> Firstly these codes are not copy-pasted runnable
Yes, user needs to enter the version number the user wants. Do you have a way to make this copy-paste runnable?

>> we need to update the doc for everything release
Do you mean the example in this line needs to be changed for every release?
```
$ git checkout tags/<name-of-the-release-tag> #Example: git checkout tags/v0.10.0
```
I agree keeping it updated with the latest version number is good. Note that this is only an example. While it is good to keep that updated with the latest version, it won't break anything if we miss.

**Comment by mli** [comment]
First I'm not sure having doc for cloning a particular tag is necessary. People can easily google "git clone a tag" for instructions. Most time people just download the source tar from https://github.com/dmlc/mxnet/releases. 

Second, even we want to add the instructions in the document, I don't think we should replace the instructions for building from source. I suggest to only add one sentence that

> You can use `git checkout tags/xxx` to build a particular release. See https://github.com/dmlc/mxnet/releases for all releases.

**Comment by indhub** [comment]
I agree most people know `git checkout tags/xxx`. The non-trivial part is updating the submodules correctly (`git submodule update --init --recursive`). 

Google search for "git clone a tag" does not return results that talk about how to update the submodules correctly. 
Given this problem happened with our own DL AMI builds (the builds were not updating the submodules, the script was just doing a `git checkout tags/xxx` which is not sufficient), I don't think this is a trivial thing that everybody gets right. 

Given it is non-trivial and we ourselves have got it wrong before, I suggest we document the steps so that it is easy for people who want to build a particular release. 

@bhavinthaker, @madjam - Thoughts?

**Comment by madjam** [comment]
This whole thing started because it was not obvious that submodules needed to be updated after cloning a tag. It is not common and and so I do agree and think it is important that it should be mentioned in the instructions.

@mli any concerns?

**Comment by mli** [comment]
another way is `git clone --recursive --branch v0.10.0
https://github.com/dmlc/mxnet/` ?

**Comment by indhub** [comment]
> another way is `git clone --recursive --branch v0.10.0 https://github.com/dmlc/mxnet/` ?

I like this better. I'll test it and make the change.

**Pull request closed without merging**
