### PR TITLE
[BUGFIX] Ubuntu 20.04: support for in-distro Intel MKL libraries

### PR DESCRIPTION
**Pull request by akarbown**
## Description ##
Since Ubuntu 20.04 Intel MKL packages are available in the distribution. Thus, its search could be simplified by using the unified cmake FindBLAS function.

## Changes ##
 - add support for intel-mkl distribution version;
 - use FindBLAS cmake function to look for the intel-mkl;
 - add FindBLAS.cmake file upstream version (due to Intel10_64_dyn &
   --start-group/--end-gropup options support)
 - remove FindMKL.cmake;
 - preserve Ubuntu 18.04 images for TensorRT pipeline;
 - preserve MKL libraries linking support on non-Ubuntu 20.04 OSes
   (w/o FindMKL.cmake file).

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

## Comments ##
Reconsidering MKL_USE_SINGLE_DYNAMIC_LIBRARY option as the potential solution for [18255](https://github.com/apache/incubator-mxnet/issues/18255). This needs more investigation.

### CODE REVIEW

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by leezu** [comment]
@akarbown the CI fails because the tensorrt gpu build uses Ubuntu 18.04. The reason is that TensorRT was not available for 20.04 yet (see https://gitlab.com/nvidia/container-images/cuda/-/issues/99)

But for 18.04 intel-mkl is not available, so you may need to add a bash if/else statement to install `intel-mkl` if base image is 20.04 and rely on the apt repo otherwise.

```
[2021-01-21T18:40:17.268Z] E: Unable to locate package intel-mkl

[2021-01-21T18:40:18.193Z] Service 'ubuntu_tensorrt_cu111' failed to build: The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     apt-get update &&     apt-get install -y wget software-properties-common &&     apt-get update &&     apt-get install -y         curl         unzip         pandoc         build-essential         ninja-build         git         protobuf-compiler         libprotobuf-dev         default-jdk         clang-6.0         python-yaml         clang-10         clang-tidy-10         g++         g++-7         g++-8         intel-mkl         libomp-dev         libgomp1         libturbojpeg0-dev         libcurl4-openssl-dev         libatlas-base-dev         libzmq3-dev         libopencv-dev         libxml2-dev         numactl         libnuma-dev         python3         python3-pip         doxygen         pandoc         autoconf         gperf         libb2-dev         libzstd-dev         gfortran &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by akarbown** [comment]
> @akarbown the CI fails because the tensorrt gpu build uses Ubuntu 18.04. The reason is that TensorRT was not available for 20.04 yet (see https://gitlab.com/nvidia/container-images/cuda/-/issues/99)
> 
> But for 18.04 intel-mkl is not available, so you may need to add a bash if/else statement to install `intel-mkl` if base image is 20.04 and rely on the apt repo otherwise.

I thought that it would be able to remove apt repo.
> 
> ```
> [2021-01-21T18:40:17.268Z] E: Unable to locate package intel-mkl
> 
> [2021-01-21T18:40:18.193Z] Service 'ubuntu_tensorrt_cu111' failed to build: The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     apt-get update &&     apt-get install -y wget software-properties-common &&     apt-get update &&     apt-get install -y         curl         unzip         pandoc         build-essential         ninja-build         git         protobuf-compiler         libprotobuf-dev         default-jdk         clang-6.0         python-yaml         clang-10         clang-tidy-10         g++         g++-7         g++-8         intel-mkl         libomp-dev         libgomp1         libturbojpeg0-dev         libcurl4-openssl-dev         libatlas-base-dev         libzmq3-dev         libopencv-dev         libxml2-dev         numactl         libnuma-dev         python3         python3-pip         doxygen         pandoc         autoconf         gperf         libb2-dev         libzstd-dev         gfortran &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
> ```
> 
> Another option is to wait until nvidia makes tensorrt available on 20.04

ok, thanks!
I was just trying to test:
```
@@ -95,7 +95,7 @@ services:
       dockerfile: Dockerfile.build.ubuntu
       target: gpu
       args:
-        BASE_IMAGE: nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
+        BASE_IMAGE: nvidia/cuda:11.1-cudnn8-devel-ubuntu20.04
       cache_from:
         - ${DOCKER_CACHE_REGISTRY}/build.ubuntu_tensorrt_cu111:latest
   ubuntu_gpu_cu111:
```
but it seems that there is no sense to check it, isn't it?

**Comment by leezu** [comment]
> but it seems that there is no sense to check it, isn't it?

Yes, until https://gitlab.com/nvidia/container-images/cuda/-/issues/99 it won't work.

cc @TristonC as missing TensorRT for Ubuntu 20.04 is causing issues in this PR.

**Comment by akarbown** [comment]
@mxnet-bot run ci [sanity]

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by akarbown** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by akarbown** [comment]
@mxnet-bot run ci [miscellaneous]

**Review by leezu — APPROVED** [review]
LGTM, thank you!

**Comment by akarbown** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, website, windows-gpu, windows-cpu]

**Comment by leezu** [comment]
@akarbown as you marked this WIP, can you clarify what more you like to include?

**Comment by akarbown** [comment]
> @akarbown as you marked this WIP, can you clarify what more you like to include?

I just wanted to make sure that after I squashed the commits into one all the tests passes without issues.

**Comment by leezu** [comment]
> I just wanted to make sure that after I squashed the commits into one all the tests passes without issues.

Thank you. Actually we can squash the commits automatically during "merge". I think the tests passed previously, but now there seems to be an issue with np.linspace? I think it's due to the new numpy release and to workaround the issue you can force numpy<1.20.0

**Pull request merged**
