### PR TITLE
[MXNET-16] [DO NOT MERGE] Move submodules to 3rdparty

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@marcoabreu do you know why this happens on CI?
```
GitHub has been notified of this commit’s build result



hudson.plugins.git.GitException: Command "git merge 93e0ceb99724a06f30b8058b795e8427ba05fe41" returned status code 128:

stdout: 

stderr: error: Merging is not possible because you have unmerged files.

hint: Fix them up in the work tree, and then use 'git add/rm <file>'

hint: as appropriate to mark resolution and make a commit.

fatal: Exiting because of an unresolved conflict.



	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1990)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1958)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1954)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1592)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$3.execute(CliGitAPIImpl.java:692)

	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:122)

	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1068)

	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1161)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)

	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:130)

	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)

	at hudson.model.ResourceController.execute(ResourceController.java:97)

	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE


```

**Comment by marcoabreu** [comment]
Git seems to have a problem if you try changing a 3rd party module and merge at the same time. Could you try to rebase to make sure no merge happens? Additionally, it could be possible that this PR left the workspace (these actions happen on the master) in a corrupt state. In that case, please open a new PR.

**Comment by eric-haibin-lin** [comment]
You mean CI may not clean up the workspace if it is corrupted in some case? If so maybe we want to prevent it from happening next time

**Comment by marcoabreu** [comment]
CI merges automatically if your branch diverged from the master. Since your branch is behind it, it will try to merge your commit. Please try to rebase

**Comment by marcoabreu** [comment]
No, I don't know if that's happening. Please try rebasing within the same PR and see if it succeedes. If it doesn't, but works in a new PR, then I will have to take action

**Comment by eric-haibin-lin** [comment]
Oh right, I didn't notice my branch is already behind master. Will do rebase

**Comment by marcoabreu** [comment]
Hmm, doesn't work either.. Can you try opening a new PR?

**Pull request closed without merging**
