### PR TITLE
Sync Horovod distributed training examples with latest changes

### PR DESCRIPTION
**Pull request by yuxihu**
Sync distributed training examples with MXNet and Horovod with latest changes in Horovod:

1. Added DistributedTrainer, a subclass of Gluon Trainer in Horovod, to make distributed training using MXNet Gluon API with PS and Horovod have the same internal workflow.
2. Resovled the known GCC incompatibility issue.

### CODE REVIEW

**Comment by yuxihu** [comment]
@mxnet-label-bot add [pr-working-in-progress]

**Comment by vandanavk** [comment]
@mxnet-label-bot add [Distributed]

**Comment by yuxihu** [comment]
@apeforest @eric-haibin-lin please help review.

@mxnet-label-bot update [pr-awaiting-review]

**Comment by yuxihu** [comment]
@mxnet-label-bot update [Distributed, pr-awaiting-merge]

**Pull request merged**
