### PR TITLE
[mkldnn-v1.0] Rebase the feature branch to the latest master

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
This PR indents to rebase the feature branch to the latest master to mitigate the discrepancy of the two branches, especially there are some fixes for flaky tests on the master branch which will also save the CI on this feature branch.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by marcoabreu** [comment]
Puh rebasing makes it *really* messy since history rewrites are not allowed. How about a merge commit instead?

**Comment by TaoLv** [comment]
Thank you @marcoabreu. I didn't know which one is a better practice. But I see the commit ids in the PR are exactly the same as they are in the master history. Anyway I will try your suggestion right now.

**Comment by TaoLv** [comment]
@marcoabreu, just force pushed to the PR branch. Hope it looks good to you now. :)

**Comment by TaoLv** [comment]
BTW, which option is preferred when merging this PR to the feature branch, "squash and merge" or "rebase and merge"?

**Comment by marcoabreu** [comment]
Either rebase and merge or merge commit. I'd recommend you to make a copy of the target branch and try out both methods. Then you will see the difference.

**Comment by TaoLv** [comment]
> Either rebase and merge or merge commit. I'd recommend you to make a copy of the target branch and try out both methods. Then you will see the difference.

"merge commit" is disabled for this repository. "rebase and merge" has conflicts per my experiment. So we just have the last option: "squash and merge". :(

**Comment by TaoLv** [comment]
@pengzhao-intel Please review and approve if possible. Thanks!

**Comment by marcoabreu** [comment]
You have write access to the branch, so you can also just make a merge commit directly without the PR process. Feel free to go ahead.

**Comment by marcoabreu** [comment]
Just make sure to not force-push please :)

**Pull request closed without merging**
