### PR TITLE
Add test case for oneDNN RNN

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
This PR enables test case which produces seg faults with oneDNN < 1.6.5
https://github.com/apache/incubator-mxnet/pull/19308
https://github.com/apache/incubator-mxnet/pull/19451

Problem should be fixed with: https://github.com/apache/incubator-mxnet/pull/19444

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge, unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by bgawrych** [comment]
@anko-intel @pengzhao-intel Can we merge it?

**Review by pengzhao-intel — APPROVED** [review]
LGTM

**Comment by anko-intel** [comment]
LGTM

**Pull request merged**
