### PR TITLE
 Fix flaky test test_operator/test_operator_gpu.test_laop

### PR DESCRIPTION
**Pull request by ankkhedia**
## Description ##
Fix for issue #11718-- Removing fixed seed as the flakiness is not reproducible.

Ran tests/python/unittest/test_operator.py:test_laop
and tests/python/gpu/test_operator_gpu.py:test_laop for 20k times each.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Remove fixed seed for test_operator:test_laop
## Comments ##

Fix for the issue #11718

### CODE REVIEW

**Comment by ankkhedia** [comment]
@haojin2 @szha Could you take a look?

**Comment by haojin2** [comment]
Please indicate the flaky test you're fixing in your title like: fix flaky test test_operator/test_operator_gpu.test_laop

**Comment by ankkhedia** [comment]
@haojin2 Added name to title

**Comment by ankkhedia** [comment]
@szha Could you take a look and merge this PR?

**Comment by ankkhedia** [comment]
@marcoabreu Could you please take a look and merge this PR?

**Pull request merged**
