### PR TITLE
Add stable nrm2 for L2_normalization

### PR DESCRIPTION
**Pull request by TccccD**
Call interface of the 2-norm (#11573) to, it got the same results as this method in three different modes and  solve this problem #11938 ;
But I think my modifications may still be optimized，
please help me to optimize it. thanks!
@haojin2 @piiswrong @leezu @anirudh2290 @szha

### CODE REVIEW

**Comment by szha** [comment]
@leezu

**Comment by leezu** [comment]
There seems to be a build error with mklml. Can you re-trigger the CI?

```
collect2: error: ld returned 1 exit status

Makefile:486: recipe for target 'lib/libmxnet.so' failed

make: *** [lib/libmxnet.so] Error 1

make: *** Waiting for unfinished jobs....

/work/mxnet/3rdparty/mkldnn/install/lib//libmklml_gnu.so: file not recognized: File truncated

collect2: error: ld returned 1 exit status

Makefile:515: recipe for target 'bin/im2rec' failed

make: *** [bin/im2rec] Error 1

```

**Comment by leezu** [comment]
@TccccD there seems to be a bug in the current version of this PR leading to `Shape size mismatch 3 v.s. 15`:

```
======================================================================

ERROR: test_operator.test_l2_normalization

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_operator.py", line 3135, in test_l2_normalization

    check_l2_normalization((nbatch, nchannel, height), mode, dtype)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_operator.py", line 3123, in check_l2_normalization

    check_numeric_gradient(out, [in_data], numeric_eps=1e-3, rtol=1e-2, atol=1e-3)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 900, in check_numeric_gradient

    symbolic_grads = {k:executor.grad_dict[k].asnumpy() for k in grad_nodes}

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 900, in <dictcomp>

    symbolic_grads = {k:executor.grad_dict[k].asnumpy() for k in grad_nodes}

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\ndarray\ndarray.py", line 1972, in asnumpy

    ctypes.c_size_t(data.size)))

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\base.py", line 252, in check_call

    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [12:50:19] c:\jenkins_slave\workspace\build-gpu@3\include\mxnet\./tensor_blob.h:146: Check failed: this->shape_.Size() == shape.Size() (3 vs. 15) Shape size mismatch 3 v.s. 15

```

**Comment by leezu** [comment]
The test may be using random shapes, so the bug may not be triggered on every run.

**Comment by TccccD** [comment]
I traversed all the use cases in the test, but none of them gave an error. This may be a running environment issue? What environment should I use to look for this bug?
@haojin2 @piiswrong @leezu @anirudh2290 @szha

**Comment by leezu** [comment]
@TccccD it should be sufficient to run the test on any GPU environment to reproduce the failure. The CI has some special setup to decide if to run on CPU or GPU. For your use-case, you may just want to change

``` python
def check_l2_normalization(in_shape, mode, dtype, norm_eps=1e-10):
    ctx = default_context()
    ...
```

to 

``` python
def check_l2_normalization(in_shape, mode, dtype, norm_eps=1e-10):
    ctx = mx.gpu(0)
    ...
```

Please let me know if that doesn't help or if you have any other questions.

**Comment by TccccD** [comment]
Thank you for your reply, but I tried this method and it doesn't work. @leezu

**Comment by leezu** [comment]
@TccccD  thanks for trying. I also built your branch and could not observe any failing tests. Could you restart the CI  (e.g. by rebasing your branch to the current `master` version of mxnet)?

**Pull request closed without merging**
