### PR TITLE
[v1.x] CI fixes to make more stable and upgradable

### PR DESCRIPTION
**Pull request by josephevans**
## Description ##
This PR makes a number of changes to make it more stable:

* Remove SafeDocker client which uses python docker package to run containers. Change to use "docker run" command directly using subprocess.call(), because the python-docker client does not support a `gpus` parameter which newer docker versions use and we don't get timeout issues when using the docker command directly. This will allow us to update our AMIs to use newer docker versions.
* In order to support both docker variants simultaneously, we first try to use the `--gpus all` parameter to `docker run`, if it fails with error code 125 (which means docker run command itself failed,) then we retry using the old `--runtime nvidia` parameter.
* Change the GPU pipelines to use G4 instances instead of P3 (for the 3 remaining pipelines that still use P3.)
* Remove the extra custom codecov calls (which usually fail and have to retry multiple times, even though the initial codecov command works.)

### CODE REVIEW

**Comment by josephevans** [comment]
Could you guys please review? @leezu @szha

**Review by Zha0q1 — APPROVED** [review]
LGTM

**Review by waytrue17 — APPROVED** [review]
LGTM, thanks!

**Review by access2rohit — APPROVED** [review]
LGTM

**Comment by szha** [comment]
LGTM

**Pull request merged**
