### PR TITLE
update julia install doc

### PR DESCRIPTION
**Pull request by Ksoy**
cc @iblis17

### CODE REVIEW

**Comment by iblis17** [comment]
Preview link is here:
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15609/1/install/index.html?platform=Linux&language=Julia&processor=CPU

That code block display is weird.

**Comment by karan6181** [comment]
@mxnet-label-bot add [Julia, Doc, pr-work-in-progress]

**Comment by iblis17** [comment]
Could you add a section about "install the latest release" ?... via

```
]add MXNet
```

**Comment by iblis17** [comment]
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-15609/4/install/index.html?platform=Linux&language=Julia&processor=CPU

**Comment by iblis17** [comment]
looks fine.
Could you rebase to re-trigger CI again?

**Pull request merged**
