### PR TITLE
[Do not merge] Testing a segfault in CI

### PR DESCRIPTION
**Pull request by asitstands**
This is to test a problem found in https://github.com/apache/incubator-mxnet/pull/10951#issuecomment-411370941.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Please test locally using the reproducing test results guide in confluence (I don't have a link on handy sorry)

**Comment by marcoabreu** [comment]
https://cwiki.apache.org/confluence/display/MXNET/Reproducing+test+results

**Comment by asitstands** [comment]
@marcoabreu Thanks for the guide. I have some trouble to reproduce the failed test in my local environment. I'll try further.

**Comment by marcoabreu** [comment]
Does local environment mean local computer or within docker?

**Comment by asitstands** [comment]
@marcoabreu I'm failing to reproduce the test result in a machine running Arch linux. And I'm also failing to run docker in the machines (not actual CI testing). I think I need to develope some familiarity with docker.

**Comment by marcoabreu** [comment]
We use Ubuntu 16.04, docker and nvidia-docker2. Then follow the guide and it should be straight forward. Feel free to attend our office hours if it doesn't work then.

**Pull request closed without merging**
