### PR TITLE
fix bug in sgd

### PR DESCRIPTION
**Pull request by solin319**
`ResourceRequest` will make `sgd_mom_update` can't overlap the backward computation. #9782
So can we delete `ResourceRequest` when register `sgd_mom_update`.

### CODE REVIEW

**Comment by sxjscience** [comment]
I think the temporary workspace is used in the code @eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
Would setting MXNET_EXEC_NUM_TEMP help? @solin319  https://github.com/apache/incubator-mxnet/blob/master/docs/faq/env_var.md#memory-options

**Comment by solin319** [comment]
@eric-haibin-lin 
MXNET_EXEC_NUM_TEMP doesn't work.
But make MXNET_CPU_TEMP_COPY and MXNET_GPU_TEMP_COPY larger can solve the overlap problem.
It's difficult to find the description for these two env vars, and I think it's difficult to use for many users.

**Comment by solin319** [comment]
set MXNET_CPU_TEMP_COPY = 100
When training resnet-50, the sgd_mom_update still can't start directly after fist backward computation.
default

**Comment by eric-haibin-lin** [comment]
Are you training with multi-machine and multi-GPU? What type of kvstore are you using?
I guess one walk-around is to update the `FResourceRequest ` interface so that it only allocate temp space when the operator is sparse

**Comment by solin319** [comment]
The results above was get in multi-GPU training with kv_store='local'.
The same problem was in kv_store='device' too.
When we training in multi-machine, the problem doesn't exists.
@eric-haibin-lin 

It's a good idea to update FResourceRequest interface.

**Comment by eric-haibin-lin** [comment]
Tracked in #10366

**Comment by eric-haibin-lin** [comment]
@solin319 how much performance difference did you see if you remove temp resource?

**Comment by solin319** [comment]
@eric-haibin-lin 
gpus=2*k80
network=vgg16
data=imagenet
The performance is  131samples/sec when we remove temp resource.
 If not the performance is 117samples/sec

**Comment by eric-haibin-lin** [comment]
Thanks! Just curious - why were you not using device kvstore? Is it taking too much memory? 
Also, what's the batch size you're using?

**Pull request closed without merging**
