### PR TITLE
Fix symbol load json

### LINKED ISSUE #6419: [c++] Model File(.json) Loading error
Hi. I'm keep trying to implement [MTCNN](https://github.com/kpzhang93/MTCNN_face_detection_alignment) with C++ and MxNet.

However now, I receive an error when I try to load a model file with `Symbol.Load`.

If any of you ever have tried to load model files to use as classifier, I'd love to know how did you make it.

I leave what I've tried below. Thanks in advance.

## Environment info
Operating System: OS X 10.12.4

Compiler: AppleClang

Package used (Python/R/Scala/Julia): C++

MXNet commit hash (`git rev-parse HEAD`): 918d48526481cf424197079ae47841e1b8afe399

```error
/Users/chihiro/Programs/Jolie-joli/mxnet_cpp_mtcnn_face_detection/cmake-build-debug/mxnet_cpp_mtcnn_face_detection
Hello, World!
[19:40:29] /Users/chihiro/Programs/oss/mxnet/dmlc-core/include/dmlc/logging.h:304: [19:40:29] src/core/op.cc:55: Check failed: op != nullptr Operator Convolution is not registered

model_folder: model
Stack trace returned 10 entries:
minsize: 20.000000
threshold: 0.600000
factor: 0.709000
[bt] (0) 0   libmxnet.so                         0x000000010e452078 _ZN4dmlc15LogMessageFatalD2Ev + 40
num_worker: 4
accureate_landmark: 0
[bt] (1) 1   libmxnet.so                         0x000000010e44f6b9 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010ed7801d _ZN4nnvm2Op3GetERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 429
[bt] (3) 3   libmxnet.so                         0x000000010edaa158 _ZN4dmlc20JSONObjectReadHelper14ReaderFunctionINSt3__16vectorIN4nnvm4pass12_GLOBAL__N_18JSONNodeENS2_9allocatorIS7_EEEEEEvPNS_10JSONReaderEPv + 2024
[bt] (4) 4   libmxnet.so                         0x000000010eda935a _ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE + 218
[bt] (5) 5   libmxnet.so                         0x000000010eda5c67 _ZN4nnvm4pass12_GLOBAL__N_18LoadJSONENS_5GraphE + 1415
[bt] (6) 6   libmxnet.so                         0x000000010eb5b9c1 _ZNSt3__128__invoke_void_return_wrapperIN4nnvm5GraphEE6__callIJRPFS2_S2_ES2_EEES2_DpOT_ + 209
[bt] (7) 7   libmxnet.so                         0x000000010eb5b8b2 _ZNSt3__110__function6__funcIPFN4nnvm5GraphES3_ENS_9allocatorIS5_EES4_EclEOS3_ + 18
[bt] (8) 8   libmxnet.so                         0x000000010ed7aadb _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 795
[bt] (9) 9   libmxnet.so                         0x000000010ea53cbb _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 187

[19:40:29] /Users/chihiro/Programs/Jolie-joli/mxnet_cpp_mtcnn_face_detection/lib/mxnet-cpp/dmlc/logging.h:304: [19:40:29] /Users/chihiro/Programs/Jolie-joli/mxnet_cpp_mtcnn_face_detection/lib/mxnet-cpp/symbol.hpp:79: Check failed: MXSymbolCreateFromFile(file_name.c_str(), &(handle)) == 0 (-1 vs. 0) 

Stack trace returned 7 entries:
[bt] (0) 0   mxnet_cpp_mtcnn_face_detection      0x000000010d5fa15e _ZN4dmlc15LogMessageFatalD2Ev + 46
[bt] (1) 1   mxnet_cpp_mtcnn_face_detection      0x000000010d5f4b25 _ZN4dmlc15LogMessageFatalD1Ev + 21
[bt] (2) 2   mxnet_cpp_mtcnn_face_detection      0x000000010d613b0a _ZN5mxnet3cpp6Symbol4LoadERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 570
[bt] (3) 3   mxnet_cpp_mtcnn_face_detection      0x000000010d6134bd _ZN14mtcnn_detectorC2ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEfNS0_6vectorIfNS4_IfEEEEfib + 5389
[bt] (4) 4   mxnet_cpp_mtcnn_face_detection      0x000000010d6141d0 _ZN14mtcnn_detectorC1ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEfNS0_6vectorIfNS4_IfEEEEfib + 64
[bt] (5) 5   mxnet_cpp_mtcnn_face_detection      0x000000010d5f4e57 main + 759
[bt] (6) 6   libdyld.dylib                       0x00007fffae835235 start + 1

libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [19:40:29] /Users/chihiro/Programs/Jolie-joli/mxnet_cpp_mtcnn_face_detection/lib/mxnet-cpp/symbol.hpp:79: Check failed: MXSymbolCreateFromFile(file_name.c_str(), &(handle)) == 0 (-1 vs. 0) 

Stack trace returned 7 entries:
[bt] (0) 0   mxnet_cpp_mtcnn_face_detection      0x000000010d5fa15e _ZN4dmlc15LogMessageFatalD2Ev + 46
[bt] (1) 1   mxnet_cpp_mtcnn_face_detection      0x000000010d5f4b25 _ZN4dmlc15LogMessageFatalD1Ev + 21
[bt] (2) 2   mxnet_cpp_mtcnn_face_detection      0x000000010d613b0a _ZN5mxnet3cpp6Symbol4LoadERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 570
[bt] (3) 3   mxnet_cpp_mtcnn_face_detection      0x000000010d6134bd _ZN14mtcnn_detectorC2ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEfNS0_6vectorIfNS4_IfEEEEfib + 5389
[bt] (4) 4   mxnet_cpp_mtcnn_face_detection      0x000000010d6141d0 _ZN14mtcnn_detectorC1ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEfNS0_6vectorIfNS4_IfEEEEfib + 64
[bt] (5) 5   mxnet_cpp_mtcnn_face_detection      0x000000010d5f4e57 main + 759
[bt] (6) 6   libdyld.dylib                       0x00007fffae835235 start + 1


Process finished with exit code 6

```

```cpp
#include <vector>
#include <string>
#include "lib/mxnet-cpp/MxNetCpp.h"
#include "lib/mxnet-cpp/model.h"
#include "lib/mxnet-cpp/symbol.h"

using namespace std;
using namespace mxnet::cpp;

mtcnn_detector(std::string model_folder,
                   float minsize,
                   std::vector<float> threshold,
                   float factor,
                   int num_workder,
                   bool accurate_landmark
    );

int main(){
  mtcnn_detector detector = mtcnn_detector("model", 20, {0.6, 0.7, 0.8}, 0.709, 4, false);
}


mtcnn_detector::mtcnn_detector(std::string model_folder, float minsize, std::vector<float>
                                threshold, float factor, int num_worker, bool accurate_landmark)
{
    this->num_worker = num_worker;
    string model_dir_path = "/Path/to/model/";
    vector<string> models{"det1", "det2" "det3" "det4"};
    vector<string> model_formats{"-symbol.json", "-0001.params"};

    vector<Symbol> symbols(4);
    vector<Context> ctx = {Context::cpu()};
    int num_epoch = 0;
    int epoch_size = 0;
    string optimizer = "sgd";

    for(int i = 0; i < symbols.size(); i++){
      // seems like this Load function doesn't work well.
        symbols[i].Load((model_dir_path + models[i] + model_formats[0]).c_str());
    }
    vector<FeedForwardConfig> configs(4);
    for (int i = 0; i < configs.size(); i++){
        configs[i].symbol = symbols[i];
        configs[i].num_epoch = num_epoch;
        configs[i].epoch_size = epoch_size;
        configs[i].optimizer = optimizer;
    }

    vector<FeedForward*> PNets;
    for (int i = 0; i < num_worker; i++){
        PNets.push_back(new FeedForward(configs[0]));
    }

    this->RNet = new FeedForward(configs[1]);
    this->ONet = new FeedForward(configs[2]);
    this->LNet = new FeedForward(configs[3]);

    this->minsize = float(minsize);
    this->factor = float(factor);
    this->threshold = threshold;
}
```

## Steps to reproduce

1. Download model directory from [here](https://github.com/pangyupo/mxnet_mtcnn_face_detection/tree/master/model) and place it in your working directory.

2. Copy and paste the code written above!

The `CMakeLists.txt` is as below.
```make
cmake_minimum_required(VERSION 3.7)
project(mxnet_cpp_mtcnn_face_detection)

set(CMAKE_CXX_STANDARD 11)
set(SOURCE_FILES main.cpp)

file(COPY ${PROJECT_SOURCE_DIR}/lib/libmxnet.so ${PROJECT_SOURCE_DIR}/lib/libmxnet.a
            DESTINATION ${PROJECT_BINARY_DIR}/lib)

file(COPY ${PROJECT_SOURCE_DIR}/model DESTINATION ${PROJECT_BINARY_DIR}/)

add_executable(mxnet_cpp_mtcnn_face_detection ${SOURCE_FILES})

# Add lib
include_directories(${PROJECT_SOURCE_DIR}/lib)
find_library(LIBMXNET NAMES mxnet PATHS ${PROJECT_SOURCE_DIR}/lib)
target_link_libraries(mxnet_cpp_mtcnn_face_detection ${LIBMXNET})

```

My working directory's tree is like this.

```
.
├── CMakeLists.txt
├── README.md
├── build
├── lib
│   ├── libmxnet.a
│   ├── libmxnet.so
│   └── mxnet-cpp
│       ├── CPPLINT.cfg
│       ├── dmlc
│       ├── mxnet
│       ├── nnvm
├── main.cpp
├── model
     ├── det1-0001.params
     ├── det1-symbol.json
     ├── det1.caffemodel
     ├── det1.prototxt
     ├── det2-0001.params
     ├── det2-symbol.json
     ├── det2.caffemodel
     ├── det2.prototxt
     ├── det3-0001.params
     ├── det3-symbol.json
     ├── det3.caffemodel
     ├── det3.prototxt
     ├── det4-0001.params
     ├── det4-symbol.json
     ├── det4.caffemodel
     └── det4.prototxt
```

## What have you tried to solve it?

1. I've tried to load with `Symbol.Load("model_file_path");` though the error returned.
2. Then I've checked if `Load` function is working correct and realized that `MXSymbolCreateFromFile` function which is called in Load function doesn't work well. 

If you have any ides or noticed how I'm doing wrong, please tell me.

Thanks for your corporation!!

### PR DESCRIPTION
**Pull request by lx75249**
Fix #6419

### CODE REVIEW

**Comment by chicn** [comment]
Hi @lx75249 .

It made it to load a json model file and received this.
```
[20:33:36] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[20:33:36] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
```

However, it seems like it fails when I try to load it more than twice.
Perhaps this issue is already mentioned at `Can't load json file more than twice in linux using cpp-package`  #5889 ?

**Comment by kentrino** [comment]
I'm now confronted with @chicn 's issue.

**Comment by lx75249** [comment]
@kentrino You also got error when loading model twice?

**Comment by kentrino** [comment]
@lx75249 Yes. Thanks for swift reply.

**Comment by piiswrong** [comment]
Should this be merged?

**Comment by lx75249** [comment]
Not ready yet.

**Comment by chicn** [comment]
This issue was actually solved and the point of this was just a my mistake of giving the path of model files. Sorry for make it confusing.

**Comment by lx75249** [comment]
@kentrino see discussion above. Could you check the path to the model you were loading?

**Comment by piiswrong** [comment]
Is this still needed?

**Comment by lx75249** [comment]
@piiswrong Yes

**Comment by piiswrong** [comment]
Should I merge this now?

**Comment by lx75249** [comment]
@piiswrong Yes, this patch solves that bug.

**Pull request merged**
