### PR TITLE
Back port the PR #17672:boolean indexing to branch v1.7.x

### PR DESCRIPTION
**Pull request by Alicia1529**
Back port the PR #17672:boolean indexing from master to branch v1.7.x

@ciyongch

### CODE REVIEW

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [clang, edge, miscellaneous, unix-cpu, unix-gpu,  windows-cpu]

**Comment by ciyongch** [comment]
Hi @Alicia1529 , please re-trigger the failed CI, thanks!

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [clang, edge, miscellaneous, unix-cpu, unix-gpu]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by ciyongch** [comment]
Hi @Alicia1529 , PR https://github.com/apache/incubator-mxnet/pull/18339 to address the `edge` job failure was merged into v1.7.x branch. Please help to re-trigger the `edge` job which is supposed to be passed now.

**Comment by leezu** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
Hi @ciyongch, this pr has passed all the tests and is ready to be merged.

**Comment by ciyongch** [comment]
Thanks @Alicia1529 , ping @TaoLv @pengzhao-intel @leezu to help merge.

**Pull request merged**
