### PR TITLE
Relax Visual Studio version constraint in the specialization of `dmlc::type_name_helper<DT>` for `DT=mxnet::Tuple<T>`

### LINKED ISSUE #14116: Failure in generated op.h in version 1.3.1
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
When compiling MXNET with CPP package, an op.h header is generated with syntax errors. Compared to version 1.3.0, some operators have been added to have this syntax error (missing type specifier in argument list of inline function)

## Environment info (Required)
WINDOWS 10 Pro, X64
MXNET 1.3.1.
VS2017
MKL
OPENCV 3.4.5
CMake 3.13.4
CUDA 9.2
CUDNN 9.2

## Build info (Required if built from source)

Compiler: VS2017

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
1>------ Build started: Project: cpp_package_op_h, Configuration: Release x64 ------
1>"Running: OpWrapperGenerator.py"
1>D:/Projects/MXNet-versions/MxNet1-3-1/build/Release/libmxnet.dll
1>argument "lrs" of operator "multi_sgd_update" has unknown type ", required"
1>argument "wds" of operator "multi_sgd_update" has unknown type ", required"
1>argument "lrs" of operator "multi_sgd_mom_update" has unknown type ", required"
1>argument "wds" of operator "multi_sgd_mom_update" has unknown type ", required"
1>argument "lrs" of operator "multi_mp_sgd_update" has unknown type ", required"
1>argument "wds" of operator "multi_mp_sgd_update" has unknown type ", required"
1>argument "lrs" of operator "multi_mp_sgd_mom_update" has unknown type ", required"
1>argument "wds" of operator "multi_mp_sgd_mom_update" has unknown type ", required"
========== Build: 1 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========

Problem in generated code (the parameters lrs and wds):
`inline Symbol multi_sgd_update(const std::string& symbol_name,
                               const std::vector<Symbol>& data,
                                lrs,
                                wds,
                               mx_float rescale_grad = 1,
                               mx_float clip_gradient = -1,
                               int num_weights = 1) {
  return Operator("multi_sgd_update")
           .SetParam("lrs", lrs)
           .SetParam("wds", wds)
           .SetParam("rescale_grad", rescale_grad)
           .SetParam("clip_gradient", clip_gradient)
           .SetParam("num_weights", num_weights)
(data)
           .CreateSymbol(symbol_name);
}`

The same for the inline functions: 
multi_sgd_mom_update
multi_mp_sgd_update
multi_mp_sgd_mom_update
..and overloaded functions

## Steps to reproduce

1.
2.

## What have you tried to solve it?

1. op.h generation worked with same system / compiler settings for 1.3.0
2.

### LINKED ISSUE #15143: dmlc::type_name_helper<T> specialization of mxnet::tuple<T> should not be disabled for MSVC
## Description
[In this PR](https://github.com/apache/incubator-mxnet/pull/14270), @junrushao1994 brought `mxnet::Tuple<T>` to mxnet. 

For the specialization of `dmlc::type_name_helper<T>`, it was disabled **completely** for MSVC: 
```cpp
namespace dmlc {
/*! \brief description for optional TShape */
DMLC_DECLARE_TYPE_NAME(optional<mxnet::TShape>, "Shape or None");
DMLC_DECLARE_TYPE_NAME(optional<mxnet::Tuple<int>>, "Shape or None");
// avoid low version of MSVC
#if !defined(_MSC_VER) // <----------- Here
template<typename T>
struct type_name_helper<mxnet::Tuple<T> > {
  static inline std::string value() {
    return "tuple of <" + type_name<T>() + ">";
  }
};
#endif
}  // namespace dmlc
```

It then brought up an issue that has not been solved in 4 months: #14116, and costed me [some effort](https://github.com/apache/incubator-mxnet/issues/14116#issuecomment-498497289) to dig it out.

Since this choice brought more problem than it was intended to solve ("avoid low version of MSVC"), I think we should at least:
* allow the condition to pass on newer version of visual studio (at least 2015 and later)
* or remove the `#if` block completely. 

## Build info

Compiler: Visual Studio 2019

MXNet commit hash: 9125f6ae8cf0fb11338f18cd27223b5ce367afbc

Build config:
```
cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=C:/Programs/Vcpkg/scripts/buildsystems/vcpkg.cmake -A x64 -T host=x64  -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_NVRTC=1 -DUSE_OPENCV=1 -DUSE_OPENMP=1 -DUSE_BLAS=mkl -DUSE_MKLDNN=1 -DUSE_LAPACK=1 -DUSE_DIST_KVSTORE=0 -DUSE_CPP_PACKAGE=1 "C:/Programs/mxnet"
```

## Error Message:
```
1>"Running: OpWrapperGenerator.py"
1>D:/Projects/MXNet-versions/MxNet1-3-1/build/Release/libmxnet.dll
1>argument "lrs" of operator "multi_sgd_update" has unknown type ", required"
1>argument "wds" of operator "multi_sgd_update" has unknown type ", required"
1>argument "lrs" of operator "multi_sgd_mom_update" has unknown type ", required"
1>argument "wds" of operator "multi_sgd_mom_update" has unknown type ", required"
1>argument "lrs" of operator "multi_mp_sgd_update" has unknown type ", required"
1>argument "wds" of operator "multi_mp_sgd_update" has unknown type ", required"
1>argument "lrs" of operator "multi_mp_sgd_mom_update" has unknown type ", required"
1>argument "wds" of operator "multi_mp_sgd_mom_update" has unknown type ", required"
```

## Steps to reproduce

See https://github.com/apache/incubator-mxnet/issues/14116#issuecomment-498497289

## What have you tried to solve it?

See https://github.com/apache/incubator-mxnet/issues/14116#issuecomment-498497289

## Environment info
```
----------Python Info----------
Version      : 3.7.1
Compiler     : MSC v.1915 64 bit (AMD64)
Build        : ('default', 'Dec 10 2018 22:54:23')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 18.1
Directory    : C:\Programs\Anaconda3\lib\site-packages\pip
----------MXNet Info-----------
Version      : 1.4.1
Directory    : C:\Programs\Anaconda3\lib\site-packages\mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.17763-SP0
system       : Windows
node         : SRTP-desktop
release      : 10
version      : 10.0.17763
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Name
Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
```

Package used (Python/R/Scala/Julia): Cpp

### PR DESCRIPTION
**Pull request by Vigilans**
## Description ##
Fix #14116, Fix #15143
Description of the content is covered in #15143.

### Essentials ###  
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Relax the version constraint of Visual Studio to allow 2015 and later to pass (_MSC_VER > 1900)

### CODE REVIEW

**Comment by piyushghai** [comment]
Thanks for your contributions @Vigilans 
@mxnet-label-bot Add[pr-awaiting-review, Backend]

**Comment by vandanavk** [comment]
Please add "Fixes https://github.com/apache/incubator-mxnet/issues/14116" in the PR description to automatically close the issue when the PR is merged

**Comment by roywei** [comment]
@Vigilans could you trigger the CI again? thanks!

**Comment by karan6181** [comment]
@Vigilans Could you please look into CI failure?

@anirudh2290 @eric-haibin-lin Could you please review this PR? Thanks!

**Comment by Vigilans** [comment]
@karan6181 Now all CI checks have been passed...seems to be the problem of syncing with master.

**Comment by piyushghai** [comment]
@anirudh2290 Can you review this PR.?

**Comment by QueensGambit** [comment]
I approve this PR, see https://github.com/apache/incubator-mxnet/issues/15632.

**Comment by zachgk** [comment]
@QueensGambit Thanks for reviewing. You can actually use the official approve GitHub approve button under Files Changed -> Review Changes -> Approve even if you are not a committer.

@anirudh2290 @junrushao1994 @eric-haibin-lin Can any of you help review this PR?

**Pull request merged**
