### PR TITLE
Add gluonCV to fix AMP Tutorial

### PR DESCRIPTION
**Pull request by Chancebair**
## Description ##
To fix the failure here: https://github.com/apache/incubator-mxnet/issues/15028

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by roywei** [comment]
Thanks for fixing this. could there be other errors from the tutorial if we fix the install?

**Comment by ptrendx** [comment]
Is there a way to trigger the test of the tutorial on the CI before merging and waiting for the nightly test?

**Comment by anirudh2290** [comment]
Thanks for the fix! @ptrendx AFAIK the tutorials take a long time to run and since the customer impact from a broken tutorial is much lesser, they are not part of the CI.

**Comment by ptrendx** [comment]
@roywei I don't expect any other errors - I was running this tutorial before submitting it ;-). I did not know about the configuration of the tutorial CI, sorry for that!

**Comment by roywei** [comment]
@ptrendx It's ok, reproduce on CI could be troublesome. As long as notebooks are running fine locally and dependencies are installed in CI docker, it should be fine. It's documented here.
https://cwiki.apache.org/confluence/display/MXNET/Reproducing+test+results
Here are the steps, on AWS Deeplearning Base AMI Ubuntu:
1. clone mxnet repo
2. install requirements
```
pip3 install -r ci/requirements.txt --user
```
3. run build command copied from jenkins log (click `Build` -> `GPU: CUDA9.1+cuDNN7` -> 'Shell Scripts' -> 'show complete log'):
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/320/pipeline/38

```
ci/build.py --docker-registry mxnetci --platform ubuntu_build_cuda --docker-build-retries 3 --shm-size 500m /work/runtime_functions.sh build_ubuntu_gpu_cuda100_cudnn7
```

4. Run the specifc job failed (Tutorial Python2 and 3), copy the command from log.
```
ci/build.py --docker-registry mxnetci --nvidiadocker --platform ubuntu_nightly_gpu --docker-build-retries 3 --shm-size 1500m /work/runtime_functions.sh nightly_tutorial_test_ubuntu_python2_gpu
```

**Comment by roywei** [comment]
@Chancebair @ptrendx I have tested it and unfortunately it failed again. It seems the tutorial test is treating warning as failures.

```
ERROR:root:Warning:
      "/work/mxnet/python/mxnet/gluon/block.py:1146: UserWarning: Cannot decide type for the fo
llowing arguments. Consider providing them as input:\n",

Warning:
    "    /mxnet/code/python/mxnet/gluon/block.py:1138: UserWarning: Cannot decide type for the 
following arguments. Consider providing them as input:\n",

Warning:
      "/work/mxnet/python/mxnet/gluon/block.py:1146: UserWarning: Cannot decide type for the fo
llowing arguments. Consider providing them as input:\n",

Warning:
    "    /mxnet/code/python/mxnet/gluon/block.py:1138: UserWarning: Cannot decide type for the 
following arguments. Consider providing them as input:\n",
======================================================================
FAIL: test_tutorials.test_amp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/tutorials/test_tutorials.py", line 203, in test_amp
    assert _test_tutorial_nb('amp/amp_tutorial')
AssertionError

**Comment by Chancebair** [comment]
We can either ignore the warnings or implement the suggestion of providing the type for args.  @ptrendx would this be trivial enough?

**Comment by karan6181** [comment]
@mxnet-label-bot add [Gluon, Installation, pr-awaiting-testing]

**Comment by ptrendx** [comment]
@Chancebair I made a PR to your branch with a fix.

**Comment by roywei** [comment]
@Chancebair could you rebase? CI should be passing now. Thanks

**Pull request merged**
