### PR TITLE
Disable long running tests

### PR DESCRIPTION
**Pull request by KellenSunderland**
## Description ##
As discussed here in a few threads, segmenting tests will go a long way in stabilizing our CI.  This PR is a WIP that aims to remove some of the most problematic tests.  All tests ignored here either crashed on a P3 instance with the release version (r 0.12) of mxnet from the deep learning AMI, or they took longer to run than a minute.  With these tests removed all tests were running in less than 2 minutes on a P3.

Tests are removed with test annotations (aka decorators).  Initially I've only used ```@nightly``` to indicate a test that would best be run on a nightly basis and ```@crashing``` to indicate a crashing test.  I'd propose we open issues for all crashing tests, assign owners and leave the tests ignored for the time being in the test suite.  I'd also like to discuss what the correct set of test annotations should be.  Should we consider ```@cuda_test```, ```@high_mem``` or ```@http_required``` test annotations for example?  Once we've decorated tests with annotations we can selectively choose to run them by passing the -a arg to nose (as shown in the new Jenkinsfile).

### Essentials ###
- [ ] Passed code style checking (`make lint`)  (not run)
- [x] Changes are complete (i.e. I finished coding on this PR) (WIP)
- [x] All changes have test coverage (removes tests)
- [x] For user-facing API changes, API doc string has been updated.
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Remove problem tests (slow running or crashing).

### CODE REVIEW

**Comment by marcoabreu** [comment]
Regarding ‘@high_mem’: I think considering a specific value as “high” is quite relative to what a developer usually works with. Maybe we should give the possibility to specify a category (like 1 = Super-small 1-100Mb, 2 = Medium 100-500Mb, etc…) or an actual amount (depending on how much the usage varies).

**Comment by KellenSunderland** [comment]
I've now opened individual issues for any tests that were skipped due to crashes.  I believe only one had to be disabled for this reason.

I tried to focus on tests that were really the worst offenders in terms of time to run (30 seconds+ run times).  In total tests are running in under four minutes with this patch.
```
python3 -m nose  --verbose  -a '!nightly,!crashing' --with-timer  tests/python/gpu
...
----------------------------------------------------------------------
Ran 231 tests in 70.928s

OK (SKIP=6)
```

```
python3 -m nose  --verbose  -a '!nightly,!crashing' --with-timer  tests/python/unittest
...
----------------------------------------------------------------------
Ran 359 tests in 111.434s

FAILED (SKIP=4, errors=2)
```
(errors are expected here, not compiled with profiler, etc).

**Comment by piiswrong** [comment]
I think its better to try to make them run faster than disabling them

**Comment by marcoabreu** [comment]
Only the crashing ones are disabled. The long running tests are classified as nightly and are of such a complexity that they should not be executed for every single PR.

**Comment by KellenSunderland** [comment]
@piiswrong I think having a multi-stage approach to speeding up tests is going to be the best way to make progress here.  This first stage could be to segment tests that run each PR from ones that run nightly.  The second could be to optimize the nightly tests (or create fast-running tests with equivalent coverage).

I'll leave to yourself and the commiters to decide how best to fix the current tests.  This PR hopefully can at least be a first crack at test segmentation in case you want a reference to discuss.

**Comment by larroy** [comment]
I think this is a good approach. I would like to see this merged. >30s or too high of resource consumption for a unit test is not acceptable.

**Comment by mseeger** [comment]
I've had the same issues with another team at Amazon.
A unit test is short running. Anything else is just not a unit test, and why should these slow everybody else down?
Sometimes, people create these monster tests instead of spending the time to write unit tests, because testing the end application is just faster to do. But it slows down everybody else. I view Kellen's approach to re-balance the situation.

**Comment by larroy** [comment]
Right @mseeger  a unit test tests a unit of functionality independently, which will often correspond 1:1 to a class a function, or a single module, with any other modules and dependencies being mocked. If you are testing more than that, you should call it a functional test, an acceptance test, and end-to-end test or whatever, but don't call it a unit test. It's fine to have such tests, but they can run nightly, not in every PR. which is creating the situation that we have now.

**Comment by KellenSunderland** [comment]
I'm closing this one temporarily to try and get a good idea of which tests can be sped up rather than being moved to nightly.

**Pull request closed without merging**
