### PR TITLE
[WIP] Remove redundant shared_ptr for exception_ptr

### PR DESCRIPTION
**Pull request by yuxihu**
[std::exception_ptr](https://en.cppreference.com/w/cpp/error/exception_ptr) is already reference counted. There is no need to wrap it with shared_ptr. This PR removes the redundant shared_ptr for var_exception and opr_exception members.

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-awaiting-review]
@yuxihu Thanks for your contribution

**Comment by ChaiBapchya** [comment]
Thanks for your contribution. Looks like CI is failing. LGTM otherwise!

**Comment by pinaraws** [comment]
@yuxihu Any updates?

**Comment by yuxihu** [comment]
@pinaraws Have not got a chance to look into the test failure. @anirudh2290 had explanation about why we are using shared_ptr around exception_ptr [here](https://github.com/apache/incubator-mxnet/pull/14397#discussion_r264884326). I think this PR is no longer needed. Closing it.

**Pull request closed without merging**
