### PR TITLE
[TEST] Add microbenchmark for FC + add fusion

### PR DESCRIPTION
**Pull request by anko-intel**
## Description ##
Add microbenchmark for Fully Connected with add fusion
and utility scripts to run it with proper OMP parameters set and check performance against different number of threads

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)

## Comments ##
Examples of test output:
- ./run.sh fc_add.py

elemwise_add, float 

|    Shape    | Hidden | Mean [ms] |
|------------:|-------:|----------:|
| (   1, 224) |    512 |     0.236 |
| (   1, 224) |   4096 |     0.227 |
| (  16,1024) |   1024 |     0.337 |
| (  32,4096) |   1024 |     0.530 |
| (  32,4096) |   4096 |     1.539 |
| ( 512, 512) |   4096 |     0.956 |

npi_add, float 

|    Shape    | Hidden | Mean [ms] |
|------------:|-------:|----------:|
| (   1, 224) |    512 |     0.165 |
| (   1, 224) |   4096 |     0.164 |
| (  16,1024) |   1024 |     0.286 |
| (  32,4096) |   1024 |     0.523 |
| (  32,4096) |   4096 |     1.444 |
| ( 512, 512) |   4096 |     0.846 |

elemwise_add, mode = smart, granularity = tensor-wise 

|    Shape    | Hidden | Mean [ms] |
|------------:|-------:|----------:|
| (   1, 224) |    512 |     0.240 |
| (   1, 224) |   4096 |     0.236 |
| (  16,1024) |   1024 |     0.330 |
| (  32,4096) |   1024 |     0.396 |
| (  32,4096) |   4096 |     0.541 |
| ( 512, 512) |   4096 |     0.900 |

- ./run_per_thread.sh 48 8 64 fc_add.py

NUM_THREADS = 48 56 64

elemwise_add, float   

|    Shape    | Hidden | Mean [ms] | Mean [ms] | Mean [ms] |
|------------:|-------:|----------:|----------:|----------:|
| (   1, 224) |    512 |     0.204 |     0.214 |     0.244 |
| (   1, 224) |   4096 |     0.205 |     0.211 |     0.232 |
| (  16,1024) |   1024 |     0.307 |     0.321 |     0.346 |
| (  32,4096) |   1024 |     0.569 |     0.535 |     0.536 |
| (  32,4096) |   4096 |     2.028 |     1.796 |     1.531 |
| ( 512, 512) |   4096 |     1.124 |     1.085 |     0.962 |

### CODE REVIEW

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu, windows-cpu, windows-cpu ]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [windows-gpu ]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu]

**Review by bartekkuncer — APPROVED** [review]
LGTM

**Review by bgawrych — APPROVED** [review]

**Pull request merged**
