### PR TITLE
[v1.x] Attempt to fix v1.x CI issues.

### PR DESCRIPTION
**Pull request by josephevans**
## Description ##
Update to python 3.7, added numpy requirement for onnx dependencies so gluoncv doesn't overwrite the numpy version we need.

### CODE REVIEW

**Review by waytrue17 — APPROVED** [review]
LGTM, thanks

**Review by Zha0q1 — APPROVED** [review]
LGTM Thanks!!

**Comment by josephevans** [comment]
Please change description when merging to "Update to python 3.7, added numpy requirement for onnx dependencies so gluoncv doesn't overwrite the numpy version we need."

**Review by access2rohit — APPROVED** [review]
LGTM!

**Pull request merged**
