### PR TITLE
Bugfix: kAddTo support for swap_axes.

### PR DESCRIPTION
**Pull request by tdomhan**
## Description ##
With this PR the swapaxes operator no longer ignores the req argument. Previously this silently lead to wrong gradients.

### Essentials ###
- [X] Passed code style checking (`make lint`)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by KellenSunderland** [comment]
@eric-haibin-lin Any chance we can get this in the next release?

**Comment by KellenSunderland** [comment]
@tdomhan Could you amend the commit and add
```
Co-authored-by: Hetzel <ahhetzel@amazon.com>
```
at the bottom?

**Comment by tdomhan** [comment]
yeah of course. I also wouldn't mind to close the PR and update the other PR. Just whatever solution gets the fix into the next release works for me :)

**Comment by asmushetzel** [comment]
@piiswrong 
Somehow I forgot about the pending #9495 , sorry. This here is indeed the suitable fix. I will close 9495. 
That definitely should go into next release

**Comment by sxjscience** [comment]
Like my comments in https://github.com/apache/incubator-mxnet/pull/9495, we should also revise the test here (https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L361-L377) to add a test for “grad_req=addto”. You may refer to the test codes in https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L775-L781

**Comment by marcoabreu** [comment]
Tracked at https://github.com/apache/incubator-mxnet/issues/9546.

@tdomhan would you mind adding a test in a second PR? It would be great if we could test this ASAP.

**Comment by tdomhan** [comment]
thanks for merging! I will try to create an appropriate test based on pointers from @sxjscience.

**Pull request merged**
