### PR TITLE
Update float16 tutorial

### PR DESCRIPTION
**Pull request by Ishitori**
## Description ##
Some word smiting on float16 tutorial. Fixed the code by adding imports. Added extra examples how to download the data

### CODE REVIEW

**Comment by abhinavs95** [comment]
@mxnet-label-bot add [Doc]

**Comment by Ishitori** [comment]
@roywei, I completely agree that we should make sure that nightly tests are working. However, this particular tutorial is a part of FAQ section, which is currently not covered by automatic tests. The tests covers only items under `tutorials/` folder. I assume the reason for that is that FAQ items may have some incomplete parts of the code, as for example, this one.

I have addressed comments by @vishaalkapoor made in another copy of this PR (closed now).

**Comment by thomelane** [comment]
@Ishitori can you link to the other PR? Would be good to see comments here.

**Comment by Ishitori** [comment]
@thomelane https://github.com/mli/new-docs/pull/114

**Comment by thomelane** [comment]
LGTM

**Pull request merged**
