### PR TITLE
Bumped minor version to 1.4.0 as 1.3.1 will be continued in the v1.3.…

### PR DESCRIPTION
**Pull request by lebeg**
…x branch

## Description ##

https://github.com/apache/incubator-mxnet/pull/13225

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by lebeg** [comment]
@szha done

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by kalyc** [comment]
@lebeg could you re-trigger the PR with an empty commit? CI appears to have failed

**Comment by kalyc** [comment]
CI still appears to have failed because of https://github.com/apache/incubator-mxnet/issues/13274
Please re-trigger

**Comment by lebeg** [comment]
Thanks @kalyc, re-triggered again.

**Comment by lebeg** [comment]
Rebased the change, should not fail again on arm qemu tests

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
