### PR TITLE
Remove stale unused Keras1-MXNet tests from MXNet repo

### PR DESCRIPTION
**Pull request by sandeep-krishnamurthy**
## Description ##
* Remove all stale and deprecated Keras1.2 with MXNet tests and cleaning up. 
* Keras 1.2.1 with MXNet backend is no more supported and deprecated - https://github.com/dmlc/keras/
* Most recent release and active development is happening for Keras2 with MXNet backend - https://github.com/awslabs/keras-apache-mxnet
* Keras2-MXNet has is own CI and build pipelines.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Removing obsolete unused Keras1-MXNet tests from MXNet repo

## Comments ##
N/A

@marcoabreu @roywei

### CODE REVIEW

**Comment by roywei** [comment]
I think we should:
1. update these tests to prevent mxnet making breaking changes that will break Keras2-MXNet. 
2. Change Keras-MXNet 1.2 home page clearly stating it's deprecated and only works with old versions of mxnet. Also points to Keras2-MXNet repo.

If these tests are currently breaking CI, shall we first disable them util we update them?

**Comment by sandeep-krishnamurthy** [comment]
@roywei 

I do not have strong opinion, I am ok for both having/removing it from here. But, I was thinking in below terms.

Technically, MXNet is independent of Keras2-MXNet. Because, I see it as Keras2 is depending on MXNet and not vice-versa. So any changes in MXNet should not worry a lot about Keras2-MXNet. Keras2-MXNet should have nightly CI in Keras2-MXNet (we have) that can verify its dependencies (MXNet) and make necessary changes if required, recommend which version of MXNet works with Keras2-MXNet etc.

**Comment by sandeep-krishnamurthy** [comment]
@roywei - Your concerns are addressed? Is this ready to be merged?

**Comment by roywei** [comment]
@sandeep-krishnamurthy Yes, please go ahead

**Pull request merged**
