### PR TITLE
Cherry-pick #18310 #18355

### PR DESCRIPTION
**Pull request by MoisesHer**
## Description ##
Fixing issue: https://github.com/apache/incubator-mxnet/issues/18120 on Mxnet v.1.7.x

Cherry-pick [#18310](https://github.com/apache/incubator-mxnet/pull/18310)
Cherry-pick  [#18355](https://github.com/apache/incubator-mxnet/pull/18355)
Cherry pick [#18713](https://github.com/apache/incubator-mxnet/pull/18713)

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Can we rebase this cherry-pick? 1.7.x seems to regularly get commits merged so CI shouldn't be an issue..

**Comment by ChaiBapchya** [comment]
@leezu @TaoLv @ciyongch gentle ping.. for help..
unix-gpu: Any idea why specifically python3 GPU tests are failing while trying to add mkl headers?
edge: Jetson build failure: `libmxnet.a(random_generator.cu.o): error adding symbols: File in wrong format` I haven't seen this before.. maybe you guys have some idea?

**Comment by ciyongch** [comment]
Hi @ChaiBapchya , I took a look at the failure of [unix-gpu] which showed TVM compilation error and GPU OOM runtime error, seems it's more like the CI side issue. can you try to trigger the failed jobs?
This patch is targeting to fix the header issue for the gpu binary, right?

**Comment by MoisesHer** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by MoisesHer** [comment]
> Hi @ChaiBapchya , I took a look at the failure of [unix-gpu] which showed TVM compilation error and GPU OOM runtime error, seems it's more like the CI side issue. can you try to trigger the failed jobs?
> This patch is targeting to fix the header issue for the gpu binary, right?

Thank you for taking a look. I triggered again, but still faiilig.
Yes, this i to fix headers for gpu binary.

**Comment by MoisesHer** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by ChaiBapchya** [comment]
@MoisesHer no point in retriggering edge pipeline. It's not a flaky issue.

I saw the same issue in my cherrypick PR: https://github.com/apache/incubator-mxnet/pull/18742 

Please update the cmakevar: @leezu https://github.com/apache/incubator-mxnet/pull/18713
That should resolve the edge issue.  I cherry-picked it in 1.x 
You should do that for 1.7.x

Thanks.

**Comment by ChaiBapchya** [comment]
@sandeep-krishnamurthy @leezu @ciyongch 
This one fixes MKLDNN missing headers. Please help review/merge.

**Comment by ciyongch** [comment]
Hi @ChaiBapchya @MoisesHer please check the failed job. BTW, as it's for the binary release, then I think it's not a mandatory patch for the source release (the current release candidate is rc1). We might consider to include this patch in 1.7.0 release if there's rc2, otherwise, this patch will be in  v1.7.x branch and the binary release, what do you think?

**Comment by ChaiBapchya** [comment]
@MoisesHer sorry about hitting that flaky test. Please retrigger unix-cpu pipeline. Hopefully that should be the last retrigger for this PR.

> We might consider to include this patch in 1.7.0 release if there's rc2, otherwise, this patch will be in v1.7.x branch and the binary release

@ciyongch sounds good to me.

**Comment by MoisesHer** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by MoisesHer** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by MoisesHer** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
