### PR TITLE
[v1.7] Backport Gluon Activations Fix #18370

### PR DESCRIPTION
**Pull request by sxjscience**

### CODE REVIEW

**Comment by sxjscience** [comment]
@ciyongch I will also need this fix about Gluon Activations in Numpy.

**Comment by sxjscience** [comment]
@ciyongch Would you help review or merge this?

**Comment by ciyongch** [comment]
Hi @TaoLv , please help to merge the PR. Thanks.

**Comment by ChaiBapchya** [comment]
@TaoLv @sxjscience Missing in v1.x branch. Intentional?

**Comment by sxjscience** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChaiBapchya** [comment]
Can we cherry-pick this into v1.x then? So that we can ensure it gets into v1.8 as well?

**Comment by sxjscience** [comment]
@ChaiBapchya Yes, feel free to go ahead and pick it to v1.x.

**Pull request merged**
