### PR TITLE
add resnet50_v2 pretrained

### PR DESCRIPTION
**Pull request by zhreshold**
validation: accuracy=0.748306, top_k_accuracy_5=0.921317
@szha verified

### CODE REVIEW

**Comment by piiswrong** [comment]
What's the input scale?

**Comment by zhreshold** [comment]
@piiswrong 224x224

**Comment by piiswrong** [comment]
I mean data range. like 0-1 or 0-255

**Comment by zhreshold** [comment]
0-255

**Comment by szha** [comment]
Input to the network should be after applying the following transformation, which is consistent with other models in the gluon model zoo:
```
image = image/255
normalized = mx.image.color_normalize(image,
                                                                   mean=mx.nd.array([0.485, 0.456, 0.406]),
                                                                   std=mx.nd.array([0.229, 0.224, 0.225]))
```

**Comment by zhreshold** [comment]
```
if mean is True:
mean = np.array([123.68, 116.28, 103.53])
if std is True:
std = np.array([58.395, 57.12, 57.375])
```
Mean and std both equals True, same script tested with other models in mode_zoo

**Comment by szha** [comment]
Yeah, these two transformation should result in the same data range. (e.g. 0.485*255 = 123.675.)

**Pull request merged**
