### PR TITLE
Add magic method `abs` to NDArray and Symbol.

### PR DESCRIPTION
**Pull request by kshitij12345**
## Description ##
This magic method was missing.
Allow the natural `abs(x)`.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Add `abs` magic method.
- [x] Test for the same.

### CODE REVIEW

**Comment by kshitij12345** [comment]
@wkcn Have updated the code. Please review.

**Comment by wkcn** [comment]
@kshitij12345 Great! LGTM. Thanks for your contribution!

**Comment by kshitij12345** [comment]
@wkcn The update for 1 CI check shows that it is pending, however its details show that it has completed successfully. Should I retrigger the CI or is that okay?

**Comment by wkcn** [comment]
@kshitij12345 I have retriggered it : )

**Comment by piyushghai** [comment]
@mxnet-label-bot Add [pr-awaiting-merge, NDarray]

**Pull request merged**
