### PR TITLE
[MXNET-1294] Add PushPull API

### PR DESCRIPTION
**Pull request by anandj91**
## Description ##
This PR introduces a new KVStore API called `pushpull`.
`pushpull` is a coalesced version of `push` and `pull` APIs. `pushpull` however can send and receive the key-value pairs with just one network call to the KVServer, thus eliminating the need to send a separate `pull`.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] PushPull API, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by anandj91** [comment]
This is PR is work in progress and is raised to get the API definition reviewed.
This PR is part of the https://github.com/apache/incubator-mxnet/pull/15124.

**Comment by karan6181** [comment]
@mxnet-label-bot add [KVStore, C API, pr-work-in-progress]

**Comment by roywei** [comment]
@anandj91 gentle ping to address the comments, thanks!

**Comment by eric-haibin-lin** [comment]
@anandj91 thanks for the awesome contribution!

**Pull request merged**
