### PR TITLE
[BUGFIX] Fix and cleanup _contrib_quantized_elemwise_add

### PR DESCRIPTION
**Pull request by anko-intel**
## Description ##
The key for caching oneDNN kernel was made from different elements than used for building the kernel.
 \+ some additional cleanup

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

**Review by bartekkuncer — APPROVED** [review]
LGTM.

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-cpu]

**Review by bgawrych — APPROVED** [review]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, website, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, website, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, website, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
