### PR TITLE
Static link MKL-DNN library

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
This PR intends to change MKL-DNN library from dynamic linking to static linking. That will help:
1. Simplify the build, packaging and distribution process;
2. Avoid linkage error during runtime when different versions of MKL-DNN are installed on user's machine.

There were other attempts to do so before. But before MKL-DNN v1.0 integrated, it also depends on libmklml_intel.so. So it doesn't make much sense if we only make MKL-DNN static linked and leave libmklml_intel.so outside.

 This PR is also removing a python unit test which was designed to check MKL-DNN install by doing grep against the proc maps to make sure mkldnn.so is linked. After changing to static link, the approach would not work and not needed.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
@Taolv could you give a simple summary of the reason for this change and any possible impacts?

**Comment by TaoLv** [comment]
@pengzhao-intel , sure, PR description is added.

**Comment by TaoLv** [comment]
@szha @lanking520 @perdasilva @marcoabreu Could you please review, especially the parts about CD and packaging?

**Comment by pengzhao-intel** [comment]
> @pengzhao-intel , sure, PR description is added.

Very great explanation.  Ping me when your PR is ready to merge.

**Comment by pengzhao-intel** [comment]
Wait for the internal testing results. Let's know if you have any comments or concerns.
I will merge the PR after we get the internal validation results.

**Comment by TaoLv** [comment]
@szha @lanking520 @perdasilva @marcoabreu Call for review :)

**Comment by lanking520** [comment]
Have you tried?
```
source tools/staticbuild/build.sh mkl pip
```

**Comment by TaoLv** [comment]
@lanking520 Attached the build log. Please take a look. Thanks!
[build_mkl_pip.txt](https://github.com/apache/incubator-mxnet/files/3840345/build_mkl_pip.txt)

**Comment by pengzhao-intel** [comment]
Merging now

**Pull request merged**
