### PR TITLE
v1.4.x: Backport of Windows CI Fixes

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##

Backports the windows ci changes to v1.4.x branch. I've had to drop the julia tests for windows cpu, since those were added with a different Julia related PR.

Related PRs: #14355 and #14336

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by perdasilva** [comment]
@Chancebair @marcoabreu reviews please

**Comment by Chancebair** [comment]
LGTM

**Comment by karan6181** [comment]
@mxnet-label-bot add [CI, Windows, pr-awaiting-testing]

**Comment by karan6181** [comment]
@perdasilva Thank you for the contribution!. Could you please look into it why CI if failing?
Thanks!

**Comment by szha** [comment]
Could you please link the related commit/PR here?

**Pull request merged**
