### PR TITLE
Numpy argmin optimization

### PR DESCRIPTION
**Pull request by Zha0q1**
This pr applies the argmax optimization https://github.com/apache/incubator-mxnet/pull/19339 to argmin and updates the tests

### CODE REVIEW

**Comment by Zha0q1** [comment]
@sandeep-krishnamurthy

**Comment by sxjscience** [comment]
LGTM.

**Comment by sandeep-krishnamurthy** [comment]
Can you please post before and after benchmark test results?

**Comment by Zha0q1** [comment]
> Can you please post before and after benchmark test results?

Yeah, the performance improvement is about the same as seen on argmax.

I just ran the benchmarks again on argmin:

Contiguous:
>     (300000, 64) float axis=1
>     before: 14.0549
>     now: 3.2826
> 
>     (64, 300000) float axis=1
>     before: 376.1702
>     now: 3.0881

Non-contiguous:

>     (300000, 64) float axis=0
>     before: 268.1024
>     now: 3.6338
> 
>     (64, 300000) float axis=0
>     before: 1.5355
>     now: 2.8061

unit is ms

**Comment by Zha0q1** [comment]
CPU 

Contiguous:

>     (300000, 64) float axis=1
>     before: 38.3453
>     now: 65.8971
> 
>     (64, 300000) float axis=1
>     before: 35.6059
>     now: 62.2148

Non-contiguous:

    (300000, 64) float axis=0
    before: 994.6203
    now: 194.5434

    (64, 300000) float axis=0
    before: 711.3664
    now: 76.4318

unit is ms

**Pull request merged**
