### PR TITLE
Fix softmax, logsoftmax failed on empty ndarray

### LINKED ISSUE #18569: [Numpy] softmax, logsoftmax failed on empty ndarray
## Description
latest mxnet pip wheel
```
import mxnet as mx
from mxnet import npx
npx.set_np()
a = mx.np.array([]).reshape(2, 1, 0)
b = mx.npx.softmax(a)
b.wait_to_read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 2353, in wait_to_read
    check_call(_LIB.MXNDArrayWaitToRead(self.handle))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:43:29] src/ndarray/ndarray.cc:507: Check failed: delay_alloc:
Stack trace:
  [bt] (0) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x6d554b) [0x7efe143bd54b]
  [bt] (1) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::NDArray::Chunk::SetMKLMem(mxnet::TShape const&, int)+0x7b2) [0x7efe177b2082]
  [bt] (2) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::NDArray::GetMKLDNNData() const+0x70) [0x7efe177b6ae0]
  [bt] (3) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::op::MKLDNNSoftmaxForward(nnvm::NodeAttrs const&, mxnet::OpContext const&, mxnet::NDArray const&, mxnet::OpReqType const&, mxnet::NDArray const&)+0x564) [0x7efe14466a24]
  [bt] (4) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x115e4bd) [0x7efe14e464bd]
  [bt] (5) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFComputeEx(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x3c4) [0x7efe1765e4f4]
  [bt] (6) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x3895c84) [0x7efe1757dc84]
  [bt] (7) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x38a3c31) [0x7efe1758bc31]
  [bt] (8) /home/ubuntu/.local/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x38a6fa4) [0x7efe1758efa4]
```
The root cause should be missing proper zero-dim ndarray handle on the kernel.

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
This PR fixes #18569
When executing logsoftmax/softmax on empty ndarray (one of the dimensions is 0) mxnet throws  
mxnet.base.MXNetError: [20:43:29] src/ndarray/ndarray.cc:507: Check failed: delay_alloc:
error. 
Fix issue by delegate to native implementation when tensor size is 0.  
Similar fix like in #16850

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by TaoLv** [comment]
@stu1130 @reminisce Could you please take a look? Is this a good way to check zero size tensor?

**Comment by stu1130** [comment]
We usually just check and return directly before we launch the kernel
```
if (inputs[0].shape().Size() == 0U) return;
```

**Comment by bgawrych** [comment]
> We usually just check and return directly before we launch the kernel which is run against different contexts
> 
> ```
> if (inputs[0].shape().Size() == 0U) return;
> ```
> 
> As the bug also affect on GPU and all the other contexts if possible

So this condition should be put in the beginning of FCompute and FComputeEx functions, right? @stu1130 @TaoLv

**Comment by stu1130** [comment]
@bgawrych Yes, so you don't need to take care of this edge case on the mkldnn integration part

**Comment by TaoLv** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [codecov/project]

**Comment by TaoLv** [comment]
@szha @leezu  do we need to fix the codecov status before merging?

**Comment by szha** [comment]
@TaoLv no it's not enforced at the moment. feel free to merge when ready

**Comment by TaoLv** [comment]
Got it. Thanks for confirming that!

**Comment by TaoLv** [comment]
Thanks for the effort @bgawrych @stu1130. Do we need to cherry pick the fix to v1.x?

**Pull request merged**
