### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by kevinthesun**
Website UI upgrade.
Merge after https://github.com/dmlc/web-data/pull/27
web1
web2

@piiswrong @lupesko @sandeep-krishnamurthy @nswamy

### CODE REVIEW

**Comment by sandeep-krishnamurthy** [comment]
This is coming up really nice. Thanks Yao for the awesome work.

**Comment by piiswrong** [comment]
how big are these ttf files? Can we also put them in web-data?

**Comment by piiswrong** [comment]
also the logo file

**Comment by szha** [comment]
How does the change impact load time?

**Comment by kevinthesun** [comment]
@piiswrong https://github.com/dmlc/web-data/pull/28

**Comment by kevinthesun** [comment]
@szha It won't affect most pages. the largest resource added is the background image for landing page.

**Comment by traderd65** [comment]
A couple of errors in why_mxnet.html:
(1) X  = nd.zeros((**10000**, 40000), mx.cpu(0)) _[should be 1000 instead of 10000]_
(2) # Create a numpy array from an mxnet NDArray _[should be "Create a mxnet NDArray from numpy array"]_
     A_np = np.array([[0,1,2,3,4],[5,6,7,8,9]])
     A_nd = nd.array(A) _[should be A_np instead of A]_

**Pull request merged**
