### PR TITLE
[CI][1.6.x] fix centos 7 url to unblock centos-cpu & gpu pipeline

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Currently, 1.6.x branch is failing on multiple pipelines

1. centos-cpu & centos-gpu pipelines due to 
```
Cannot open: https://centos7.iuscommunity.org/ius-release.rpm. Skipping.
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-cpu/detail/v1.6.x/51/pipeline

2. Flaky test on unix-cpu mkldnn
3. Edge pipeline

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@szha can we revert this PR? While it fixed centos-cpu & centos-gpu
While trying to fix the edge pipeline, I cherry-picked #18339 into 1.6.x [which helped resolve edge pipeline issue for 1.7.x] but it ended up breaking unix-gpu: http://jenkins.mxnet-ci.amazon-ml.com/job/mxnet-validation/job/unix-gpu/job/v1.6.x/52/display/redirect

So as a result, unix-gpu & edge pipeline are now broken.

Way forward:
1. Revert this PR
2. I'll submit another PR just to fix centos-cpu & centos-gpu [by updating the link : https://github.com/apache/incubator-mxnet/pull/18560/commits/9103f2088890a1190cc2b9865e8c1b3f3fc7c82c ]
3. I will leave edge pipeline broken & get help from @weichu & @leezu to unblock edge pipeline on 1.6.x

**Comment by leezu** [comment]
>  @josephevans Is there a way to prevent merge a branch if only sanity has passed but other 10 pipelines haven't even run/triggered?

This needs to be configured in Github Project Settings. There is a setting related to "require checks". It's currently only turned on for the master branch. This may require Apache Infra to change the setting.

**Comment by szha** [comment]
@ChaiBapchya I think it's ok to fix forward.

**Comment by marcoabreu** [comment]
We opted to not turn that in for feature branches to not bother infra too much and also allow the release manager to make certain calls without hitting limits. It's the general policy within the project that PRs with failed CI do not get merged. 

If a PR was merged, then the committer who merged the PR should be contacted and reminded.

**Comment by szha** [comment]
> We opted to not turn that in for feature branches to not bother infra too much and also allow the release manager to make certain calls without hitting limits.

I don't think that's the case. We didn't have explicit discussion on this, nor do I think it's the right approach. It doesn't make sense to allow force push to release branches while protecting the development branch. Also, enabling branch protection for release branches doesn't necessarily "bother" apache infra either, as the setup is likely one-time. Branch protection can be turned on for branches that match a pattern, and we do have an explicit pattern for release branches according to the release process.

**Comment by ChaiBapchya** [comment]
Makes sense.
Can someone then help create this branch protection ticket to apache-infra? @leezu @marcoabreu 
I'm not sure if I as a contributor can do that. Thanks everyone for the advice & clarification.

**Comment by marcoabreu** [comment]
We'd need a vote on dev@ first

**Comment by szha** [comment]
we should be able to do so with a lazy consensus.

**Comment by marcoabreu** [comment]
In any case there's a dev@ vote thread necessary

**Pull request merged**
