### PR TITLE
Fix regression in MKLDNN caused by PR 12019

### PR DESCRIPTION
**Pull request by azai91**
## Description ##
In https://github.com/apache/incubator-mxnet/pull/12019 fallback was implemented to support non MKLDNN operators. A tag was added to each MKLDNN operator to check if it needed to be converted. A flag was not added to all operators which caused a regression.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] add TIsMKLDNN to flatten and elementwise_add

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by azai91** [comment]
@pengzhao-intel

**Comment by azai91** [comment]
@zheng-da

**Comment by azai91** [comment]
Verified by setting breakpoint inside fallback region and seeing if resnet50 reached it - it doesnt after this change.

**Comment by vrakesh** [comment]
@mxnet-label-bot [pr-awaiting-review]

**Comment by pengzhao-intel** [comment]
Thanks @azai91 

Acutally we need a list of MKL-DNN supported OP in somewhere (document/test/code, @zheng-da @eric-haibin-lin ). At leaset, we can check the list and see if all is covered. 

The best way is to design a suite of test and check each MKL-DNN OP for the new change. I know it's not such easy and let us keep in mind.

**Comment by pengzhao-intel** [comment]
https://github.com/apache/incubator-mxnet/blob/1e8e68b9245ff1181b3c307e48f3edc12303c823/src/operator/tensor/matrix_op.cc#L106

`Reshape` is also MKL-DNN OP and the attribute is lost too.

**Comment by pengzhao-intel** [comment]
#12703

**Comment by pengzhao-intel** [comment]
ping @zheng-da @eric-haibin-lin @ZhennanQin  could you help to review the code?
We prefer to fix the regression ASAP.

**Comment by zheng-da** [comment]
it looks good to me. @pengzhao-intel can your team help verify that all MKLDNN-related operators set the flag `TIsMKLDNN ` properly?

**Comment by pengzhao-intel** [comment]
> it looks good to me. @pengzhao-intel can your team help verify that all MKLDNN-related operators set the flag `TIsMKLDNN` properly?

Yes, we are working on this :)

**Pull request merged**
