### PR TITLE
[CMAKE] Cmake changes, upgrade training test so it converge

### PR DESCRIPTION
**Pull request by tqchen**
Redo #8311  

The reason failure happens after its mergeis due to the problem of test-case giving wrong parameters. I have fixed that so that now it actually converges to meanful value.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @piiswrong

**Comment by tqchen** [comment]
failure in the tests appears due to the missing ci machine. need retrigger when they are up

**Comment by cjolivier01** [comment]
Triggered a rebuild attempt due to CI problems

**Comment by tqchen** [comment]
cc @cjolivier01 @piiswrong I just squash merged this

**Pull request merged**
