### PR TITLE
[MKLDNN] Use MKLDNNRun

### PR DESCRIPTION
**Pull request by ZhennanQin**
## Description ##
MKLDNNRun will handle ndarray view and enhance code quality. 

@PatricZhao @TaoLv 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
LGTM but let's wait for the performance testing reports.

**Comment by pengzhao-intel** [comment]
@TaoLv @ciyongch any comments?

**Comment by TaoLv** [comment]
Do we fix any specific issue with these changes or they're just for code refactoring?

**Comment by ZhennanQin** [comment]
> Do we fix any specific issue with these changes or they're just for code refactoring?

Not for any particular issue, but a code refactoring to improve code quality. Currently, ndarray view check doesn't cover all mkldnn operators, which may cause trouble in rare case. This is to prevent that happen.

**Comment by pengzhao-intel** [comment]
@TaoLv is this refactor OK?

**Comment by ZhennanQin** [comment]
@ciyongch Yes. MKLDNNRun has 2 versions. One is for unary ops, and other one is for ops with multiple inputs & outputs.  elemwise_add will use the second version, and all inputs are well handled.

**Comment by pengzhao-intel** [comment]
@ZhennanQin please rebase the code

**Pull request merged**
