### PR TITLE
Revert "Static alloc for hybridblock"

### PR DESCRIPTION
**Pull request by marcoabreu**
Reverts apache/incubator-mxnet#11313

My veto has been ignored and thus I'm allowed to revert this PR. See https://www.apache.org/foundation/voting.html for reference.

### CODE REVIEW

**Comment by tqchen** [comment]
it seems p

**Comment by marcoabreu** [comment]
My as well as Thomas' concerns have not been addressed.

**Comment by tqchen** [comment]
If you have specific concerns, raise them. Your concern of lack of test coverage has been addressed, and you are abusing your right as committer to revert good changes back...

**Comment by marcoabreu** [comment]
https://github.com/apache/incubator-mxnet/issues/11171 has not been addressed

Pedros review in https://github.com/apache/incubator-mxnet/pull/10817 has not been addressed

Thomas comment https://github.com/apache/incubator-mxnet/pull/10817#issuecomment-396701926 has not been addressed

**Comment by ThomasDelteil** [comment]
I think I have raised specific concerns (twice) that have gone unanswered, just in case they got lost in the flow, let me write them here again:
- "good changes", I'm sure they are, but the problem with the previous PR was that it was actually making things slower due to a bug, hopefully now fixed. I think we cannot just rely on blind trust, being data driven is beneficial for everybody. Could we have a runtime of maybe just a MNIST training to show that the speed is actually improved and rejoice accordingly? 
- The new API says that static_shape cannot be used without static_alloc. Can we assert that static_alloc is set if users set static_shape to True to avoid undefined behavior?

Bonus ask:
- a description of the PR to help reviewers, and users alike to appreciate the changes and guide them through the 1400 lines of code, that have barely any comments.
- better documentation on the impact of the bulk_size arguments in the hybridize() function

**Comment by tqchen** [comment]
This PR is already fixing the problems and added test coverages. If we just block this, how can we move forward?

**Comment by tqchen** [comment]
This PR is already fixing the problems and added test coverages. If we just block this, how can we move forward?

**Comment by zheng-da** [comment]
@marcoabreu I have been intensively using CachedOp with static memory allocation this week. I also read the code this week. Other than the small bug reported previously, I don't find problems and it works very well with me in my PR. https://github.com/apache/incubator-mxnet/pull/10451
I observe the memory allocation behavior and it works exactly as I expected. 

What are you looking for? If you are looking for test code, my entire PR can serve as test code. If you are looking for review, I have been reading the code for the entire week. I don't think it's reasonable to block other people's work for no reason.

**Comment by zheng-da** [comment]
@marcoabreu I think you should at least give people who understand the PR the opportunity to review it.

**Comment by marcoabreu** [comment]
Exactly, that's all I'm asking for. Give the community enough time to review the PR and address their concerns before merging it.

**Pull request merged**
