### PR TITLE
[BUGFIX] [Numpy] MXNet fp16 initialization bug #19118

### LINKED ISSUE #19118: [Bug][Numpy] MXNet fp16 initialization bug
Ignore the following reproducible and see the comment later.
```python
import mxnet as mx
mx.npx.set_np()
net = mx.gluon.nn.Dense(16, in_units=16)
net.cast("float16")
net.initialize(ctx=mx.gpu())
net.hybridize()
net(mx.np.random.normal(0, 1, (16, 16), dtype=mx.np.float16, ctx=mx.gpu()))
```

Error:
```
MXNetError: Traceback (most recent call last):
  File "../src/imperative/./imperative_utils.h", line 306
MXNetError: Check failed: outputs[i]->dtype() == out_types[i] (2 vs. 0) : 0-th output has invalid dtype. Expecting 0 got 2 in operator _npi_uniform
```

Root cause:
https://github.com/apache/incubator-mxnet/blob/fb73de7582de4e622299a4ad045e25f771568193/python/mxnet/initializer.py#L510

This should be changed to `uniform_fn(-self.scale, self.scale, arr.shape, dtype=arr.dtype, out=arr)`

@mk-61 This should also be related to AMP.

### PR DESCRIPTION
**Pull request by AnshuTrivedi**
## Description ##
(Brief description on what this PR is about)
Fixes Issue #19118 

### Essentials ###
- [✅] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [✅] Changes are complete (i.e. I finished coding on this PR)
- [✅] All changes have test coverage
- [✅] Code is well-documented

### Changes ###
- [✅] Fixes #19118 
## Comments ##
- MXnet fp16 Initialization bug

### CODE REVIEW

**Comment by sxjscience** [comment]
Thanks for the contribution @AnshuTrivedi . You may try to fix the initializers and add a test case in https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_numpy_gluon.py

**Comment by sxjscience** [comment]
Try to write the test case based on the reproducible example:
```python
import mxnet as mx
mx.npx.set_np()
net = mx.gluon.nn.Dense(16, in_units=16)
net.cast("float16")
net.initialize(ctx=mx.gpu())
net.hybridize()
net(mx.np.random.normal(0, 1, (16, 16), dtype=mx.np.float16, ctx=mx.gpu()))
```

**Comment by szha** [comment]
@mxnet-bot run ci [all]

**Comment by leezu** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by sxjscience — APPROVED** [review]

**Pull request merged**
