### PR TITLE
Make the Ubuntu scripts executable after download.

### PR DESCRIPTION
**Pull request by Biserkov**
Just a documentation fix.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Feel free to just change the chmod of the files directly

**Comment by Biserkov** [comment]
How do you mean? It is my understanding that Unix permissions are not transferred via HTTP, like in the instructions?

**Comment by lupesko** [comment]
Thanks for the contribution @Biserkov !
Looping in some folks with Scala interest: @nswamy @lanking520 @andrewfayres

**Comment by kalyc** [comment]
Thanks for your contribution @Biserkov 
@mxnet-label-bot[pr-awaiting-merge]

**Pull request merged**
