### PR TITLE
[v2.0][LICENSE] Port #20495

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Port #20495. Thanks @hsl89 for the license fixes. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by szha — APPROVED** [review]

**Pull request merged**
