### PR TITLE
Improve clojure tutorial

### PR DESCRIPTION
**Pull request by daveliepmann**
## Description ##
This is a documentation PR.

I updated the Clojure REPL-based tutorials (e.g. *contrib/clojure-package/examples/tutorial/src/tutorial/module.clj*) to match their online/markdown versions (e.g. [Module API](https://mxnet.incubator.apache.org/api/clojure/module.html)). This will allow people to more easily switch back and forth from the online and REPL versions of the same tutorial.

This primarily involved standardizing section headings to four-semicoloned comments with an extra line of whitespace above them, wrapping long lines, and adding namespace docstrings. In the Symbol tutorial I removed a duplicated section and some sections that seem to be partially copied from the [basic tutorial](https://mxnet.incubator.apache.org/tutorials/basic/symbol.html), but which did not seem to make sense out of that context. (I would like to circle back in a later PR to completely translate that tutorial to Clojure.)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Clojure Module API tutorial
- [x] Clojure KVStore API tutorial
- [x] Clojure NDArray API tutorial
- [x] Clojure Symbol API tutorial

## Comments ##
I fixed three small .clj-tutorial-adjacent issues in the course of this PR:
 - deleted a duplicated section in the online/markdown docs (https://github.com/apache/incubator-mxnet/commit/b846d634d5b3908ef32ad5e52c208d9dcf145b37)
 - fixed a code-block typo in the online docs (https://github.com/apache/incubator-mxnet/commit/8597817d727fcfe83af89255b0cde21e2f8ac390)
 - I changed the Maven dependency that the tutorials run on from the (unreleased and therefore unusable-without-extra-steps) version 1.3.1-SNAPSHOT of coordinates which don't seem to exist to 1.3.0 of coordinates that are referenced in [the new README](https://github.com/apache/incubator-mxnet/pull/12881) (https://github.com/apache/incubator-mxnet/commit/bf8391e78a5bb0513bd8cfc307d5f8fb31f524b4)

### CODE REVIEW

**Comment by gigasquid** [comment]
Thanks so much @daveliepmann - I have some time carved out to look at this tomorrow 💯

**Comment by gigasquid** [comment]
@daveliepmann I'm not sure why CI is failing, could you try rebasing on current master and pushing to retrigger a new run and see if it fixes it?

**Comment by daveliepmann** [comment]
> @daveliepmann I'm not sure why CI is failing, could you try rebasing on current master and pushing to retrigger a new run and see if it fixes it?

Sure thing. I rebased and pushed that and the build seems to have failed again.

The only thing I can imagine could remotely cause a build error is [my change to the project.clj](https://github.com/apache/incubator-mxnet/pull/12974/files#diff-24982e2098b7a38d5e366e772c65fa25R22). But I don't think that's the problem; I see "The job exceeded the maximum time limit for jobs, and has been terminated." ([link](https://travis-ci.org/apache/incubator-mxnet/builds/446814634#L2642)) Does the build frequently time out?

**Comment by gigasquid** [comment]
@marcoabreu @larroy the Travis builds seem to be timing out on this PR `The job exceeded the maximum time limit for jobs, and has been terminated.` and quite a few other PRs in the queue. Any ideas?

**Comment by ankkhedia** [comment]
@mxnet-label-bot [pr-awaiting-response]

@marcoabreu @larroy @lebeg Could you please help with the question above?

**Comment by ankkhedia** [comment]
@gigasquid The Travis CI build failures doesnot hold back PRs from getting merged if approved. They are just for informational purpose as of now.
Could you please make sure that the PR looks good after the previous rebase?

**Comment by gigasquid** [comment]
@ankkhedia - Thanks for the clarification. I'm so conditioned to seeing red as a stop :)

**Comment by gigasquid** [comment]
Thanks again @daveliepmann 💯

**Pull request merged**
