### PR TITLE
add new cloud providers to install page

### LINKED ISSUE #13713: MXNet usage on non-AWS cloud providers
Currently there is no information how to use MXNet on non-AWS cloud providers.
Please add the information how to use Nvidia containers with MXNet.

As requested, we distribute our Nvidia MXNet container, updated each month, that runs on our customized virtual images for multiple CSPs in addition to AWS:
 
GCP - VM: https://console.cloud.google.com/marketplace/details/nvidia-ngc-public/nvidia_gpu_cloud_image

Azure - VM: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.ngc_azure_17_11?tab=Overview

Alibaba – VM: https://docs.nvidia.com/ngc/ngc-alibaba-setup-guide/launching-nv-cloud-vm-console.html#launching-nv-cloud-vm-console
Oracle – VM: https://docs.cloud.oracle.com/iaas/Content/Compute/References/ngcimage.htm

All of these use our Nvidia MXNet docker container: https://ngc.nvidia.com/catalog/containers/nvidia%2Fmxnet

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
This PR adds several new cloud options.
Fixes #13713

## Preview
http://34.201.8.176/versions/cloud_options/install/index.html?platform=Cloud&language=Python&processor=GPU
http://34.201.8.176/versions/cloud_options/install/index.html?platform=Cloud&language=Python&processor=CPU

## Comments
As is typical with this install page, the selector doesn't work as expected. I tried to set GPU as the default button, but it still has CPU as default. 🤷‍♂️ Just tack this on to #13430.

### CODE REVIEW

**Comment by ptrendx** [comment]
The link to MXNet docker container should be https://ngc.nvidia.com/catalog/containers/nvidia:mxnet instead of https://ngc.nvidia.com/catalog/containers/nvidia%2Fmxnet

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by aaronmarkham** [comment]
Preview looks good. http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-14039/3/install/index.html?platform=Cloud&language=Python&processor=GPU

Merging...

**Comment by szha** [comment]
@aaronmarkham actually the row spacing looks weird to me. Here's a screenshot.
image

**Comment by szha** [comment]
I'm using Chrome 71.0.3578.98 on OSX 10.13.6.

**Pull request merged**
