### PR TITLE
[MXNET-138]Create CentOS gcc4.8 & MKLDNN ci-test

### PR DESCRIPTION
**Pull request by xinyu-intel**
## Description ##
This pr is created to add a new ci-test which use gcc4.8 & MKLDNN to solve issues on #10168 and #10200 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by TaoLv** [comment]
@marcoabreu Compiling error is reproduced here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10218/3/pipeline/51
```
tests/cpp/operator/mkldnn.cc: In function 'bool test_mem_align(void*, size_t, size_t, size_t)':
tests/cpp/operator/mkldnn.cc:37:10: error: 'align' is not a member of 'std'
   ret2 = std::align(alignment, size, mem, space2);
          ^
```
I will try to restrict compiler version to >5.0 for this test case.

**Comment by marcoabreu** [comment]
Great, thanks. Feel free to go ahead. Please don't forget to print a message if this specific test-case is disabled but run.

**Comment by TaoLv** [comment]
GCC version check is added. Currently, I don't know which versions of msvc and clang support std::align, so I restrict this test to GCC > 5.0.
Below is the output when compiled with GCC 4.8:
$ ./build/tests/cpp/mxnet_unit_tests --gtest_filter=MKLDNN*
```
Note: Google Test filter = MKLDNN*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MKLDNN_UTIL_FUNC
[ RUN      ] MKLDNN_UTIL_FUNC.AlignMem
[17:07:58] tests/cpp/operator/mkldnn.cc:77: Skipped for GCC 4.8
[       OK ] MKLDNN_UTIL_FUNC.AlignMem (0 ms)
[----------] 1 test from MKLDNN_UTIL_FUNC (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

Please also note that centos7_mkldnn is compiled with test option on. I don't know if it is appropriate for building mxnet in ci environment.

**Comment by TaoLv** [comment]
@marcoabreu @xinyu-intel Seems there is an error when build mxnet with test option: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10218/6/pipeline
So I removed the test option from centos7_mkldnn in this PR for further testing.

**Comment by marcoabreu** [comment]
Ah that's totally fine. You were basically executing 'make test', which consists of different behaviour than 'make'. Thanks for your efforts!

**Comment by TaoLv** [comment]
JIRA issue is created: https://issues.apache.org/jira/browse/MXNET-138

**Comment by marcoabreu** [comment]
Thanks a lot, @TaoLv !

**Pull request merged**
