### PR TITLE
large tensor faq doc fix

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
fixes representation of code blocks in Large Tensor Support Doc

### Essentials ###
- [x] Changes are complete
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by access2rohit** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by access2rohit** [comment]
@aaronmarkham PR is ready for review

**Comment by aaronmarkham** [comment]
Restarted the two failed tests, both core dumps. One was some new AMP contribution.

**Comment by access2rohit** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Pull request merged**
