### PR TITLE
[MKLDNN] Support projection feature of LSTM

### PR DESCRIPTION
**Pull request by zixuanweeei**
## Description ##
As title.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Sopport projection feature using DNNL(oneDNN).
- [x] Add unit test for projection feature
- [x] Add env MXNE_USE_WEIGHT_CACHE to control the initializition behavior

## Comments ##
- Please note that MKLDNN is upgraded to v1.4-rc.
- Only support Forward pass. Backward pass has not been integrated yet.

@ciyongch @TaoLv @pengzhao-intel

### CODE REVIEW

**Comment by zixuanweeei** [comment]
> LGTM and I will merge this PR when CI passed.

Maybe we need to wait for #17972. @TaoLv Any comment?

**Comment by zixuanweeei** [comment]
Perhaps we need to upgrade dnnl to its v1.3 release (#17972) at first. #17872 could then be fixed, and backported to MXNet-1.7 with dnnl v1.3. This PR can be finally merged into master. @ciyongch @TaoLv @pengzhao-intel

**Comment by pengzhao-intel** [comment]
> Perhaps we need to upgrade dnnl to its v1.3 release (#17972) at first. #17872 could then be fixed, and backported to MXNet-1.7 with dnnl v1.3. This PR can be finally merged into master. @ciyongch @TaoLv @pengzhao-intel

Got it and will wait for a while.

**Comment by zixuanweeei** [comment]
@mxnet-bot run [unix-gpu]

**Comment by zixuanweeei** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by pengzhao-intel** [comment]
@zixuanweeei  please help resolve the conflict :)

**Comment by zixuanweeei** [comment]
Please note that mkldnn submodule is pinned to its v1.4-rc version in this PR.

**Comment by pengzhao-intel** [comment]
> Please note that mkldnn submodule is pinned to its v1.4-rc version in this PR.

Thanks for the reminder. I think it's fine with 1.4-rc and we can update to 1.4 later.

**Pull request merged**
