### PR TITLE
#13385 [Clojure] - Turn examples into integration tests

### PR DESCRIPTION
**Pull request by hellonico**
!!! This is work in progress. 

Would:
- the committed script 
- adding a bare minimum deftest inside each example

be ok?

### CODE REVIEW

**Comment by gigasquid** [comment]
Thanks so much @hellonico for tackling this. This will be a big improvement to stability and regression of the package as we develop it.  The way you are approaching it with a minimum test and then the script seems like the right direction. 😸

**Comment by hellonico** [comment]
The following examples are turned into integration tests:

SuperPinkicious:examples niko$ find . -name test 
./gan/test
./visualization/test
./neural-style/test
./tutorial/test
./multi-label/test
./module/test
./cnn-text-classification/test
./imclassification/test
./profiler/test
./rnn/test

rnn has a training section and a test trained network section, but the training section is very, very, very slow 
I am wondering if it should still be added or not? It largely depends on the CI setup at this stage, but on my dev machine I can not get anything in a reasonable amount of time.

**Comment by gigasquid** [comment]
@hellonico - Awesome work!
Regarding the rnn example - I think limiting it to just the test trained network is sufficient and will keep the time down to a somewhat reasonable level.

**Comment by hellonico** [comment]
Good morning ! 
Great. Just squashed the commits ... and rebased on master.

**Comment by gigasquid** [comment]
Great! I’ll take a look on Monday. Thanks!

Have a good rest of the weekend
:)

Carin

**Comment by hellonico** [comment]
> ci/jenkins/mxnet-validation/sanity — Job failed 

Any idea on how to avoid the (de facto not very possible) license check on json files ?

**Comment by hellonico** [comment]
Finally ... 

[nohup.txt](https://github.com/apache/incubator-mxnet/files/2661882/nohup.txt)

**Comment by gigasquid** [comment]
Awesome work! I think we can get the CI to pass the RAT check if you put the files having trouble:

`mxnet/contrib/clojure-package/examples/imclassification/test/test-symbol.json.ref`
 `mxnet/contrib/clojure-package/examples/profiler/test/profile-matmul-20iter.json.ref`

 in here https://github.com/apache/incubator-mxnet/blob/master/tests/nightly/apache_rat_license_check/rat-excludes

It gets called from here https://github.com/apache/incubator-mxnet/blob/master/ci/docker/runtime_functions.sh#L996

@marcoabreu Do you have thoughts on how these integration tests should be integrated in the CI? Should it be nightly since they run pretty long? Should we merge this first and then open another one for integrating into the CI?

**Comment by marcoabreu** [comment]
Yeah nightly would be a good place. I'll leave it up to you whether we do it in this PR or a separate one. But I think a separate one is a good idea

**Comment by hellonico** [comment]
- Rebased master (monday 10th commits) 
- Updated json files to be ignored in the nightly checks 

Ready to be merged !

Let's find out how much time it takes to run the suite. When the models are already there, those tests run in about 10-15 minutes on slow machine.

**Comment by gigasquid** [comment]
Thanks for taking this on and making it happen 💯 

I'm going to go ahead a merge this and then we can work on adding it to the nightly tests in another PR and see how it runs there.

**Pull request merged**
