### PR TITLE
Remove obsolete memory cost example

### PR DESCRIPTION
**Pull request by sandeep-krishnamurthy**
## Description ##
This removes an inaccurate example for showing memory usage.
fixes - https://github.com/apache/incubator-mxnet/issues/6272

In the next step, will add GLUON based example for memory profiling. Created below tracking issue.
https://github.com/apache/incubator-mxnet/issues/13233 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Remove inaccurate example
- Remove reference to this example from the web page.

@eric-haibin-lin

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by anirudhacharya** [comment]
will the proposed example in gluon be different from what is demonstrated here - https://www.youtube.com/watch?v=n8tN6pRZBdE ?

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting merge]

**Comment by kalyc** [comment]
@nswamy

**Pull request merged**
