### PR TITLE
Use different array comparison function for useful output

### PR DESCRIPTION
**Pull request by lxn2**
test_operator_gpu.test_rnn_layer has been failing intermittently. Increasing rtol will make this test more lenient.

### CODE REVIEW

**Comment by lxn2** [comment]
@madjam Can you merge this? We discussed this fix over email yesterday.

**Comment by szha** [comment]
Could you at least check whether there is an actual problem before pushing such fix?

**Comment by lxn2** [comment]
I've gone through a couple of failures and the mismatch is either between ~.0999 or ~.0499.

@piiswrong suggested: Increasing rtol and atol should fix it

**Comment by szha** [comment]
rtol of 0.1 is equivalent to saying that we can tolerate 10% error, which seems a bit too high. https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html

On which variant does the test fails consistently?

**Comment by cjolivier01** [comment]
What is the value of the variable being tested against (and failing) a 0.1 tolerance? i.e. 5000<->5000.01 is more acceptable than 0.11<->0.10

**Comment by lxn2** [comment]
Sorry, it's not failing consistently. It's failing intermittently. When it fails, it happens on python mkl and python gpu.

Do you recommend a different tolerance, or where to start looking?

**Comment by szha** [comment]
@cjolivier01 I think rtol takes the value range into consideration already. The `allclose` function tests for:
```
absolute(a - b) <= (atol + rtol * absolute(b))
```

@lxn2 first place to look at to decide the atol/rtol would be in the failed tests. It should print out the values of the largest differences. You can use them to guide the decision on atol/rtol, if you believe the implementation and tests are correct.

**Comment by lxn2** [comment]
Initially Bhavin and I thought the output "(mismatch 0.09999999999999432%)" was the largest difference, but looking at the code it seems to be a ratio of how many elements were mismatched. Instead of calling "assert_allclose()" we should maybe call "test_utils.assert_almost_equal()" for better debugging.

@reminisce and I did some experiments, but we couldn't get the test to fail. So that change would give us better data points during builds, if they fail, so we can pick a new atol/rtol.

**Pull request merged**
