### PR TITLE
CudnnFind() usage improvements (v1.3.x)

### PR DESCRIPTION
**Pull request by lebeg**
## Description ##

A port of https://github.com/apache/incubator-mxnet/pull/12804 to the v1.3.x release branch.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by lebeg** [comment]
Should `MXGetGPUMemoryInformation64` be left out of the perl interface in `perl-package/AI-MXNetCAPI/mxnet.i`? The function was not there before in the 1.3.0 release.

**Comment by lebeg** [comment]
@DickJC123 @nswamy

**Comment by DickJC123** [comment]
Happy to let PERL users decide.  The thinking was that the existing 32-bit MXGetGPUMemoryInformation interface was broken, and generally unavailable to users except for the PERL interface.  Rather than have the bug fix change the size of the method's arguments, a faux pas with semantic versioning, a new method name was introduced.  I wanted a working routine, made available via Python, for use in a new Python unittest I introduced.  PERL users that don't have this unittest might opt for not adding to their API in 1.3.x.

**Comment by anirudhacharya** [comment]
@mxnet-label-bot ["pr-awaiting-merge"]

**Pull request merged**
