### PR TITLE
[Website 2.0] Fix RVM version to satisfy Jekyll build in v1.7.x

### PR DESCRIPTION
**Pull request by connorgoggins**
## Description ##
Backporting my fix from master and v1.x to v1.7.x to fix Jekyll builds. See #18016 and #17948.

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- M ci/docker/Dockerfile.build.ubuntu_cpu_jekyll

@samskalicky

### CODE REVIEW

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [Website]

**Comment by leezu** [comment]
The 1.7 branch will be synced with 1.x on April 17th. https://lists.apache.org/thread.html/rca8c8a9ac11e24197b4ee536e8432dd97b67424b5ee2f31c68b2958c%40%3Cdev.mxnet.apache.org%3E

**Comment by connorgoggins** [comment]
@leezu so is this 1.7.x fix not necessary? I already backported my fix to 1.x.

**Comment by leezu** [comment]
Yes. @ciyongch will help to sync the branch and include the fix later this week.
Sorry for the confusion.

**Pull request closed without merging**
