### PR TITLE
[FEATURE] add oneDNN support for numpy transpose

### PR DESCRIPTION
**Pull request by RafLit**
## Description ##
 - numpy  and ndarray transpose now both use onednn reorder primitive
 ### Transpose operator benchmark results with onednn
<table>
    <tr>
      <td>  </ td>
        <td colspan=2 align="center"> This PR </ td> 
                 <td colspan=2 align="center"> Master </ td> 
   </tr>
   <tr>
<td> tensor shape </td>
                 <td> numpy [ms] </ td>    
<td> ndarray [ms]</ td>  
                 <td> numpy [ms] </ td>    
<td> ndarray [ms] </ td>
   </tr>
   <tr>
<td> (128, 128)</td>
                 <td> 0.5742</ td>    
<td> 0.5906 </ td>  
                 <td> 0.5274 </ td>    
<td> 0.5942 </ td>
   </tr>
   <tr>
<td> (2048, 2048)</td>
                 <td> 1.3554</ td>    
<td> 1.3458 </ td>  
                 <td> 1.7525 </ td>    
<td> 1.3128 </ td>
   </tr>
   <tr>
<td> (4096, 4096)</td>
                 <td> 4.6793</ td>    
<td>  4.6705 </ td>  
                 <td> 6.0797 </ td>    
<td> 4.6172 </ td>
   </tr>

   </tr>
<td> (2048,8192)</td>
                 <td> 4.397 </ td>    
<td>  4.4318  </ td>  
                 <td>  6.0283 </ td>    
<td> 4.3277 </ td>
   </tr>

   </tr>
<td> (256, 65536) </td>
                 <td> 4.1176 </ td>    
<td>  4.1757  </ td>  
                 <td> 6.0236 </ td>    
<td>  4.1361 </ td>
   </tr>

   </tr>
<td> (16, 1048576) </td>
                 <td> 3.7967 </ td>    
<td>  3.8144 </ td>  
                 <td> 4.6723 </ td>    
<td>  3.77 </ td>
   </tr>

<td> (256, 256, 256)</td>
                 <td> 4.0402</ td>    
<td> 3.9367 </ td>  
                 <td> 118.3312 </ td>    
<td> 3.9208 </ td>
   </tr>
   </tr>
<td> (64, 512, 512) </td>
                 <td>  4.1 </ td>    
<td>  4.1263  </ td>  
                 <td> 118.143 </ td>    
<td> 4.1153 </ td>
   </tr>

<td> (64, 64, 64, 64)</td>
                 <td> 4.1867</ td>    
<td>  4.2186 </ td>  
                 <td> 137.0017 </ td>    
<td> 4.1942 </ td>
   </tr>

   <tr>
<td> (16, 16, 256, 256) </td>
                 <td>  9.4766 </ td>    
<td>  9.5056  </ td>  
                 <td> 140.2853 </ td>    
<td> 9.5924 </ td>
   </tr>

</table>

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

**Review by anko-intel — APPROVED** [review]

**Comment by mozga-intel** [comment]
@RafLit For non-square matrices, the algorithms are more complicated. Could you tell me whether you have any results for a non-square matrix?

**Comment by RafLit** [comment]
> @RafLit For non-square matrices, the algorithm is more complicated (in-place). Could you tell me whether you have any results for a non-square matrix?

@anko-intel  I updated the table and added some data for non-square matrices

**Comment by RafLit** [comment]
@mxnet-bot run ci [centos-cpu, windows-cpu]

**Comment by mozga-intel** [comment]
> ## Question
> I also have a question regarding the axes parameter in numpy and ndarray transpose. Numpy axes supports negative indices in the axes parameter, so one can for example use:
> 
> ```
> x = mx.np.arange(20).reshape(2,5,2)
> y = mx.np.transpose(x, axes=(-3,-2,-1)
> ```
> 
> and it will work fine, but giving the same axes parameter to ndarray transpose is not supported, so for example:
> 
> ```
> x = mx.nd.arange(20).reshape(2,5,2)
> y = mx.nd.transpose(x, axes=(-3,-2,-1))
> ```
> 
> ends with an error.
> 
> should support for negative indices be added to ndarray transpose?

I think that mx.nd.transpose(x, axes=(-3,-2,-1)) should be valid, as it is in numpy. 
@szha What do you think about that?

**Comment by RafLit** [comment]
@mxnet-bot run ci [all]

**Comment by RafLit** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by mozga-intel** [comment]
@RafLit, @szha it’s worth adding that support. Could you please add support for negative axes?

**Comment by szha** [comment]
@mxnet-bot run ci [sanity]

**Comment by szha** [comment]
`src/operator/tensor/matrix_op-inl.h:613:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]`

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu, centos-cpu, centos-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by RafLit** [comment]
I changed the nd.transpose api, so that "axes=None" instead of "axes=[]" would run the default reversal of axes (like for numpy api):

master:
```
x = mx.nd.arange(24, ctx=mx.cpu()).reshape(2,3,4)

y = mx.nd.transpose(x, axes=[]) # works fine

y = mx.nd.transpose(x, axes=None)
MXNetError: Check failed: std: :max(shp.ndim(), out_shp.ndim()) == param.axes.ndim() (3 vs. -1) :
```
this PR:
```
y = mx.nd.transpose(x, axes=[])
MXNetError: Check failed: std: :max(shape.ndim(), out_shape.ndim()) == param.axes.ndim() (3 vs. 0) : The number of axes does not match the dimension of the tensor.

y = mx.nd.transpose(x, axes=None) # works fine
```

I think this solution is more intuitive and clear. @szha Is this change to the api fine?

**Comment by RafLit** [comment]
@mxnet-bot run ci [website, windows-gpu, unix-cpu, centos-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [windows-gpu, centos-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu,unix-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu, unix-gpu, windows-gpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu]

**Comment by RafLit** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by bgawrych — APPROVED** [review]
LGTM

**Comment by RafLit** [comment]
@szha Could you please review the changes and merge if it's ok?

**Comment by szha** [comment]
@bgawrych should be able to help with the merge.

**Pull request merged**
