### PR TITLE
Increase docker timeouts

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
as title

Sometimes with the new environment there are timeouts with the docker daemon, this resolves this issue observed in ci-dev.

### CODE REVIEW

**Comment by larroy** [comment]
Closing, as I don't have time to deal with. I have seen other projects dependent on docker having similar issue, could be a problem in the docker-py or docker daemon.

**Comment by leezu** [comment]
@larroy any further changes required to this PR or can it be merged?

**Comment by larroy** [comment]
I closed it. If @josephevans or @ChaiBapchya find this problem and think it solves they might want to reopen.

**Comment by leezu** [comment]
We did find this problem reoccurred after updating the Docker version used by CI. The timeout fix was merged as part of https://github.com/apache/incubator-mxnet/pull/16722. 

The issue is tracked upstream at docker/docker-py#2266. The rootcause is that when a new instance is spawned, booted, Docker agent started and Jenkins immediately requests starting a container, docker may take longer than 60 seconds to finish the startup, which is docker-py's timeout.

**Pull request closed without merging**
