### PR TITLE
Rename Dockerfile.build.* -> Dockerfile.*

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
see title

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by lebeg** [comment]
@larroy wasn't the idea to have Dockerfile.build.* for building artifacts and Dockerfile.test.* for preparing the test environment?

**Comment by larroy** [comment]
It has grown no to be the case anymore. As the environments are use for several different things such as building docs, sanity check, etc.

**Comment by lebeg** [comment]
@larroy i see. Have you checked any references to these files? From any docs?

**Comment by stu1130** [comment]
@larroy Could you address the feedback from @lebeg?
Thank you so much!

**Comment by larroy** [comment]
@lebeg  yes I didn't see any additional references in the repo.

**Comment by sandeep-krishnamurthy** [comment]
Thanks @larroy @lebeg 
@marcoabreu - Can you please take a look at this and merge if things looks good.

**Comment by marcoabreu** [comment]
I'm currently on vacation. I'll get back to this when I'm back in the office.

**Comment by aaronmarkham** [comment]
It has been a while since you looked...Please make sure you thoroughly search the project in case something else is calling those files by name. I have some recollection of using the Ubuntu scripts at some point. Like run the base one then run the docs one, but I may have swapped that out already.

**Comment by larroy** [comment]
@aaronmarkham thanks for your review. I checked again and see no references in the project.

**Pull request closed without merging**
