### PR TITLE
Revert "add mkl installation temp fix"

### PR DESCRIPTION
**Pull request by lanking520**
Reverts apache/incubator-mxnet#16304

### CODE REVIEW

**Comment by lanking520** [comment]
Onnx test are keep blocking, can somebody take a review?

**Comment by TaoLv** [comment]
Filed an issue for the onnx test: https://github.com/apache/incubator-mxnet/issues/16394

**Comment by lanking520** [comment]
@marcoabreu Will split them up :)

**Comment by lanking520** [comment]
@marcoabreu is this one good to go?

**Comment by marcoabreu** [comment]
Nah, please get rid of all commits except the revert

**Comment by lanking520** [comment]
@marcoabreu Done, please feel free to unblock.

**Pull request merged**
