### PR TITLE
[COMMUNITY] add Manu Seth as a new committer

### PR DESCRIPTION
**Pull request by szha**
## Description ##
Please join me in welcoming Manu Seth (@mseth10) as a new committer of Apache MXNet! Manu has been working on MXNet since 2018 and contributed ~40 patches to MXNet with increasing technical depth. He worked on improving tests and infrastructure, performance, and more recently on graph partitioning in CachedOp in the presence of dynamic shape operators, so that a neural network graph with dynamic shape operators can be just as performant as a static graph.

Congratulations to @mseth10!

PRs he authored: https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+author%3Amseth10+
Issues he participated in: https://github.com/apache/incubator-mxnet/issues?q=is%3Aissue+involves%3Amseth10
Code reviews: https://github.com/apache/incubator-mxnet/pulls?q=is%3Apr+reviewed-by%3Amseth10

### Changes ###
- [x] add Manu Seth as a new committer

### CODE REVIEW

**Comment by szha** [comment]
Awesome. Thanks for all the contributions Manu. Looking forward to more for
MXNet community.

**Comment by szha** [comment]
Incredible! Well deserved Manu! Good job!

**Comment by wkcn** [comment]
Congratulations! @mseth10 Well deserved!

**Comment by szha** [comment]
Congrats Manu !!!

JackieWu <notifications@github.com.invalid> 于2020年9月19日周六 下午6:26写道：

**Review by ChaiBapchya — APPROVED** [review]

**Comment by szha** [comment]
Congratulations Manu! Well deserved!!

**Comment by szha** [comment]
Hi,

Congrats Manu!

Kind Regards,
Furkan KAMACI

**Pull request merged**
