### PR TITLE
Disable codecov

### PR DESCRIPTION
**Pull request by josephevans**
## Description ##
Disable use of codecov in master branch.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Could you elaborate? The vulerability already has been patched.

**Comment by szha** [comment]
@marcoabreu safer to have AWS security review first before adding it back. For now we won't support codecov on the CI until it's deemed safe.

**Comment by szha** [comment]
The follow up step is to add the rotated credentials to make the CI work again, have the security team in AWS review whether codecov is acceptably safe on our system, and then add it back afterwards.

**Comment by marcoabreu** [comment]
Okay, works for me . Thanks!

Btw, with the cached version of codecov which we used before, this would have been averted.

**Comment by szha** [comment]
Indeed.

**Comment by leezu** [comment]
Are you referring to the code from 3 years ago?

https://github.com/apache/incubator-mxnet/blob/ecadeac9a2fbacc7e5b726783ecac6bdc7558b1e/ci/Jenkinsfile_utils.groovy#L126-L128

I'm not sure that would have prevented the problem as it's only fallback :)

**Comment by marcoabreu** [comment]
Oh I thought it was the other way around. Nevermind then

**Pull request merged**
