### PR TITLE
[v1.x] Backport #17702 and #17872 to v1.x branch

### PR DESCRIPTION
**Pull request by zixuanweeei**
## Description ##
As title. #17702 and #17872 revised same lines in `test_gluon_rnn.py`. So we need to backport them in one. @ciyongch @TaoLv @pengzhao-intel 

Also cc @stu1130.

### CODE REVIEW

**Comment by ciyongch** [comment]
Thanks @zixuanweeei, adding this to 1.7.0 roadmap https://github.com/apache/incubator-mxnet/issues/16864

**Comment by zixuanweeei** [comment]
@mxnet-bot run ci [centos-gpu, unix-gpu]

**Comment by stu1130** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by stu1130** [comment]
@zixuanweeei Thanks.

Could you also cherry-pick the commit to v1.7x?

**Comment by leezu** [comment]
```
[2020-04-13T18:39:37.116Z] W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

[2020-04-13T18:39:37.116Z] 

[2020-04-13T18:39:37.116Z] W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed
```

Please include Chai's recent fix: https://github.com/apache/incubator-mxnet/pull/18018

**Comment by leezu** [comment]
@stu1130 all 1.x commits made prior to a set date will be included in 1.7.

**Comment by ChaiBapchya** [comment]
Here : https://github.com/apache/incubator-mxnet/pull/18044

**Comment by zixuanweeei** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by pengzhao-intel** [comment]
Merging now.

**Pull request merged**
