### PR TITLE
fix template param as ndim is internally int

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
Remove the template param for dimtype since internally MXNet uses int (no need for uint32 in that case)
Introduced in https://github.com/apache/incubator-mxnet/pull/15593

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
modified: src/c_api/c_api.cc

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by ChaiBapchya** [comment]
@apeforest @access2rohit plz review. Thanks

**Comment by access2rohit** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by ChaiBapchya** [comment]
Verified this change works by 

1. Checking if the API MXNDArrayCreateEx64 is called
How? By adding a LOG(INFO) in here

2. Checking if the MXNDArrayCreateEx64 API called, returns correct results
How? By verifying test_basic
```
python3 -m nose tests/nightly/test_large_array.py:test_basic --verbose
```

**Pull request merged**
