### PR TITLE
MXNET-1444/MXNET-1445: replace NULL by nullptr 

### PR DESCRIPTION
**Pull request by olk**
- using nullptr is more explicit
- macro NULL can be a integer literal with value zero (since C++11)
- literal nullptr is of type std::nullptr_t
- as template arg NULL and 0 evaluate to integer

### CODE REVIEW

**Comment by olk** [comment]
Jenkins job related to website (Julia docu) fails because of :

> [2020-02-07T17:50:14.697Z] pkg_resources.VersionConflict: (Markdown 3.2 (/home/jenkins_slave/.local/lib/python3.5/site-packages), Requirement.parse('markdown<3.2'))
> [2020-02-07T17:50:14.697Z] Makefile:19: recipe for target 'all' failed
> [2020-02-07T17:50:14.697Z] make: Leaving directory '/work/mxnet/julia/docs'

**Comment by leezu** [comment]
Julia issue tracked at https://github.com/apache/incubator-mxnet/issues/16146. You can ignore that issue for now. Just make sure all other CI steps pass.

**Comment by leezu** [comment]
You don't need to close / open new PRs to retrigger CI. Whenever you push a new commit, CI will rerun.

**Comment by olk** [comment]
windows-gpu job fails with:

> 
> [2020-02-08T07:58:57.240Z] test_operator_gpu.test_rnnrelu_dropout ... 
> [2020-02-08T07:58:59.749Z] Error running tests, python exited with status code C0000374
> [2020-02-08T07:58:59.749Z] At C:\jenkins_slave\workspace\ut-python-gpu\ci\windows\test_py3_gpu.ps1:30 
> [2020-02-08T07:58:59.749Z] char:13
> [2020-02-08T07:58:59.749Z] + if (! $?) { Throw ("Error running tests, python exited with status co ...
> [2020-02-08T07:58:59.749Z]     + CategoryInfo : OperationStopped: (Error running t...s code C000 
> [2020-02-08T07:58:59.749Z]    0374:String) [], RuntimeException
> [2020-02-08T07:58:59.749Z]     + FullyQualifiedErrorId : Error running tests, python exited with status code C0000374

I can't imagine that this failure is caused by the nullptr patch.

exception **C0000374** == [Heap Corruption Exception 0xC0000374](https://docs.microsoft.com/en-us/archive/blogs/calvin_hsia/heap-corruption-exception-0xc0000374)

Maybe **Application Verfier** (appverif.exe) could help to locate the error.

**Pull request merged**
