### PR TITLE
[mkldnn-v1.0] Fused RNN Op

### PR DESCRIPTION
**Pull request by zixuanweeei**
## Description ##
This PR includes full variants of RNNs (vanilla-LSTM, GRU, vanilla-rnn), which supports inference and training over FP32.

### Changes ###
- [x] GRU integrated.
- [x] Training support.
- [X] Refactor.

@pengzhao-intel @ciyongch @TaoLv @rongzha1

### CODE REVIEW

**Comment by zixuanweeei** [comment]
@pengzhao-intel @TaoLv Only Onnx CPU on Unix failed. Please take a review. Thanks.

**Comment by pengzhao-intel** [comment]
retrigger again?

**Comment by zixuanweeei** [comment]
Sure. Timeout again.

**Comment by zixuanweeei** [comment]
CI passed. Please take a look again. @pengzhao-intel @TaoLv

**Comment by pengzhao-intel** [comment]
Merging now.

**Pull request merged**
