### PR TITLE
Fix quantize pass error when excluding a quantization supported op

### PR DESCRIPTION
**Pull request by ciyongch**
## Description ##
This PR is to address the error when excluding a quantization supported op in a model like the case below, where both `op1` and `op2` support quantization.  
  ```op1 -> op2```
When excluding `op1` from the model, the pattern is changed to
   ```op1 -> _contrib_quantize -> quantized_op2```
There's an incorrect connection (incorrect entry index) between `_contrib_quantize` and `quantize_op2` for `min/max` inputs in current code base.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

@TaoLv @pengzhao-intel @apeforest

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
Thanks for the fix. 
Could you attach the picture of the graph before and after the change?

**Comment by ciyongch** [comment]
@pengzhao-intel The picture of graph might not reflect the error, an enhanced test was added to cover this kind of cases. I paste the full symbol file of the test case w/ and w/o the fix.
- symbol file **w/o** fix [exclude_pool0.txt](https://github.com/apache/incubator-mxnet/files/2661750/exclude_pool0.txt)
- symbol file **w/** fix [exclude_pool0_fix.txt](https://github.com/apache/incubator-mxnet/files/2661751/exclude_pool0_fix.txt)

The incorrect connection (error entry index) is located at 3nd/4th input (counting from 0), **[21, 4294967295, 0], [21, 0, 0]**
```
    {
      "op": "_contrib_quantized_conv", 
      "name": "quantized_conv1", 
      "attrs": {
        "kernel": "(1, 1)", 
        "no_bias": "False", 
        "num_filter": "4", 
        "pad": "(0, 0)"
      }, 
      "inputs": [[21, 0, 0], [22, 0, 0], [23, 0, 0], [21, 4294967295, 0], [21, 0, 0], [24, 0, 0], [25, 0, 0], [26, 0, 0], [27, 0, 0]]
    },
```
After fixed, the connection is as below, 3nd/4th inputs are correct now **[21, 1, 0], [21, 2, 0]**
```
    {
      "op": "_contrib_quantized_conv", 
      "name": "quantized_conv1", 
      "attrs": {
        "kernel": "(1, 1)", 
        "no_bias": "False", 
        "num_filter": "4", 
        "pad": "(0, 0)"
      }, 
      "inputs": [[21, 0, 0], [22, 0, 0], [23, 0, 0], [21, 1, 0], [21, 2, 0], [24, 0, 0], [25, 0, 0], [26, 0, 0], [27, 0, 0]]
    }, 
    {
```

**Comment by ciyongch** [comment]
ping @apeforest @TaoLv to have a reveiw :)

**Comment by roywei** [comment]
@mxnet-label-bot add [Operator, pr-awaiting-review]
@ciyongch Thanks for the contribution, is there an issue related to this fix?

**Comment by ciyongch** [comment]
@roywei No open issue related to it so far. We found this error when trying to quantize Resnet50_v1 at local (with excluding some ops which supports quantization from the model script manually). In this case,  `NeedQuantize(e.node, excluded_nodes)` is much more accurate than `quantized_op_map.count(e.node->op())`. 
A test case is also added to cover this kind of error.

**Pull request merged**
