### PR TITLE
Load NDArray only to GPU if GPU is present

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Fix https://github.com/apache/incubator-mxnet/issues/16399

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [X] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [X] Fix crash when attempting to load a NDArray that was saved with GPU context on a MXNet runtime built with Cuda but when no GPUs are present

## Comments ##
- I'm not sure if the CI actually tests the case of "GPU build of MXNET but no GPU present". So the test added here may always pass on CI.

### CODE REVIEW

**Comment by ZhennanQin** [comment]
For a machine with GPU, if user want to run model on CPU only, will this change works for him?

**Comment by leezu** [comment]
This change only affects the case where a MXNet cuda-enabled build is used on a CPU-only machine. It avoids a crash that currently happens. So the use-case you describe is not affected.

**Comment by ZhennanQin** [comment]
So if user want to use MXNet cuda-enabled build on a GPU equipped machine, but want to run model on its CPU, is this case supported?

**Comment by leezu** [comment]
Yes. It is already supported currently. Nothing is changed with respect to that.

The problem addressed here, is that a serialized ndarray encodes the context it lived on before serialization. When loading it, and no GPU is present, MXNet crashes as it attempts to load the array to GPU. With this PR, we fallback to loading to CPU. This is also done for CPU-only builds of MXNet.

**Pull request merged**
