### PR TITLE
[MXNET-372] Add build flag for USE_F16C in CMake and clarify flag in make

### PR DESCRIPTION
**Pull request by rahul003**
## Description ##
Copy of https://github.com/apache/incubator-mxnet/pull/10760 for v1.2

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by szha** [comment]
Instead of keeping two copies at the same time, could you finish the other PR first, and then create a cherry-pick PR once that PR is merged?

**Comment by anirudh2290** [comment]
@szha the reason we did this is to save time by doing parallel builds on Release branch and master.  To make git history more clear we can put the link to the other PR in the title.

**Comment by rahul003** [comment]
@szha That makes sense yes. We just wanted to save time with this PR and PR10777 to try cutting the rc2 tonight.

**Comment by szha** [comment]
OK. I will stay out of your way then :)

**Pull request merged**
