### PR TITLE
[COMMUNITY] add Moises Hernandez as a new committer

### PR DESCRIPTION
**Pull request by szha**
## Description ##

Please join me in welcoming Moises Hernandez (@MoisesHer) as a new committer of Apache MXNet!

Moises has helped accelerate the BERT/Transformer-related operators in MXNet. He drives the performance improvement efforts and has accelerated several operators including split, interleaved_matmul, and einsum. He has great expertise in CUDA programming, and has demonstrated deep understanding of related codebase.

PRs: https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AMoisesHer+
Issues he participated: https://github.com/apache/incubator-mxnet/issues?utf8=%E2%9C%93&q=is%3Aissue+involves%3AMoisesHer
PR reviews: https://github.com/apache/incubator-mxnet/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3AMoisesHer
dev@: https://lists.apache.org/list.html?dev@mxnet.apache.org:lte=24M:MoisesHer

### Changes ###
- [x] Add Moises Hernandez as a committer

### CODE REVIEW

**Comment by Zha0q1** [comment]
@MoisesHer Congrats!!

**Comment by ChaiBapchya** [comment]
Congrats Moises! Well-deserved.

**Review by josephevans — APPROVED** [review]
Congrats Moises!

**Comment by MoisesHer** [comment]
thank you everyone
I am glad to become a committer

**Comment by TristonC** [comment]
Congrats, Moises!

**Pull request merged**
