### PR TITLE
[Example] add cpp inception in Jenkins and nightly test

### PR DESCRIPTION
**Pull request by roywei**
## Description ##
Depends on https://github.com/apache/incubator-mxnet/pull/13284 to be merged and code freeze on Jenkins file.

As we are having major refractors on CI and Jenkins files, I am separating adding unit test and change Jenkins file from https://github.com/apache/incubator-mxnet/pull/13284 out, so it can be merged.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
Add inception in Jenkins
Add inception in unit tests
## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-awaiting-review]
Thanks for your contribution @roywei

**Comment by marcoabreu** [comment]
please wait with changes to the Jenkinsfile until further notice

**Comment by vandanavk** [comment]
@mxnet-label-bot update [pr-awaiting-testing]

**Comment by roywei** [comment]
@marcoabreu can we change Jenkins file now? It's small change to compile inception_bn example, so it can be tested nightly.

**Comment by roywei** [comment]
closing this as Jenkinsfiles changed a lot and adding cpp test does not require changing Jekins file anymore

**Pull request closed without merging**
