### PR TITLE
[WIP]improving argmax perf

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
Removes mshadow implementation of argmax and add fresh implementation for it

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Performance Numbers ###
Machine: 
Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
32 Core
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K

|          | input             | axis | int32_p50 | int64_p50 | int64/int32 |
|----------|-------------------|------|-----------|-----------|-------------|
| Master   | 1024, 1024        | 1    | 0.71      | 0.99      | 139.51      |
| new_impl | 1024, 1024        | 1    | 0.78      | 0.66      | 84.11       |
| master   | 1024, 1024        | 0    | 8.30      | 17.77     | 213.96      |
| new_impl | 1024, 1024        | 0    | 0.76      | 0.75      | 98.70       |
| master   | 1024, 1024        | NA   | 5.41      | 12.10     | 223.52      |
| new_impl | 1024, 1024        | NA   | 0.27      | 0.31      | 113.24      |
| master   | 10000, 10000      | 1    | 39.28     | 79.76     | 203.06      |
| new_impl | 10000, 10000      | 1    | 52.15     | 35.66     | 68.38       |
| master   | 10000, 10000      | 0    | 761.33    | 1,780.18  | 233.82      |
| new_impl | 10000, 10000      | 0    | 69.32     | 64.75     | 93.41       |
| master   | 10000, 10000      | NA   | 506.62    | 1,143.15  | 225.64      |
| new_impl | 10000, 10000      | NA   | 15.71     | 15.99     | 101.81      |
| master   | 1000, 1000, 100   | 2    | 70.42     | 142.50    | 202.37      |
| new_impl | 1000, 1000, 100   | 2    | 243.46    | 154.18    | 63.33       |
| master   | 1000, 1000, 100   | 1    | 76.33     | 85.11     | 111.50      |
| new_impl | 1000, 1000, 100   | 1    | 62.88     | 57.40     | 91.28       |
| master   | 1000, 1000, 100   | 0    | 638.19    | 1,405.13  | 220.17      |
| new_impl | 1000, 1000, 100   | 0    | 63.82     | 61.14     | 95.80       |
| master   | 1000, 1000, 100   | NA   | 506.85    | 1,143.30  | 225.57      |
| new_impl | 1000, 1000, 100   | NA   | 15.67     | 15.77     | 100.65      |
| master   | 100, 100, 100,100 | 3    | 70.54     | 142.17    | 201.56      |
| new_impl | 100, 100, 100,100 | 3    | 243.63    | 169.22    | 69.46       |
| master   | 100, 100, 100,100 | 2    | 77.45     | 152.07    | 196.35      |
| new_impl | 100, 100, 100,100 | 2    | 65.38     | 59.67     | 91.26       |
| master   | 100, 100, 100,100 | 1    | 58.80     | 111.12    | 188.97      |
| new_impl | 100, 100, 100,100 | 1    | 79.35     | 72.74     | 91.67       |
| master   | 100, 100, 100,100 | 0    | 723.21    | 1,535.23  | 212.28      |
| new_impl | 100, 100, 100,100 | 0    | 66.24     | 62.98     | 95.07       |
| master   | 100, 100, 100,100 | NA   | 506.90    | 1,143.14  | 225.52      |
| new_impl | 100, 100, 100,100 | NA   | 15.68     | 15.69     | 100.05      |

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@access2rohit fix the lint & retrigger the CI (Julia CPU failing)

**Comment by iblis17** [comment]
(cc me)

**Comment by iblis17** [comment]
The failure case is this:
```julia
julia> x                                                                                                                                                                     
2×3 NDArray{Float64,2} @ CPU0:                                                                                                                                               
   1.0  2.0  3.0                                                                                                                                                             
 NaN    4.0  5.0                                                                                                                                                             

julia> argmax(x, dims = 2)                                                                                                                                                   
2×1 NDArray{Float64,2} @ CPU0:                                                                                                                                               
 3.0                                                                                                                                                                         
 1.0
```

The correct answer of `argmax(x, dims = 2)` is 
```
[3.0
 3.0]
```
The `NaN` should be skipped in the comparison.

**Comment by drivanov** [comment]
@access2rohit: 
- I was working in the same task and I just filed following PR: https://github.com/apache/incubator-mxnet/pull/16218.
-Currently in my code `NaN`'s are not expected, but if it's needed I can make minor changes and skip them.

**Comment by access2rohit** [comment]
@drivanov can you make changes to GPU part only ? My optimizations are particularly for CPU and speedup is roughly is 10x in some specific cases. I will update my PR with the data.

**Comment by iblis17** [comment]
Ah, I found that the `NaN` handling is provided as another function in NumPy.
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.nanargmax.html

**Comment by access2rohit** [comment]
> Ah, I found that the `NaN` handling is provided as another function in NumPy.
 @iblis17 yes also pease take a look at this issue : https://github.com/apache/incubator-mxnet/issues/16216

**Comment by drivanov** [comment]
@access2rohit: It seems that to pass following test fron  /work/mxnet/julia/test/unittest/ndarray.jl, lines1511-1531: 
```
function test_argmax()
. . .
  @info "NDArray::argmax"
   @info "NDArray::argmax::NaN"
  let
    A = [1.  5 3;
         NaN 2 6]
    x = NDArray(A)

    @test copy(argmax(x, dims = 1)) == [1 1 2]
    @test copy(argmax(x, dims = 2)) == reshape([2, 3], :, 1)
  end
end
```
We have to skip `NaN`s. As far as I understand, in that case the outputs of `nd.argmax` and `np.nanarmax` should be identical and we will non need `nd.nanargmax`. Is it correct?

**Comment by access2rohit** [comment]
> @access2rohit: It seems that to pass following test from /work/mxnet/julia/test/unittest/ndarray.jl, lines1511-1531:
> 
> ```
> function test_argmax()
> . . .
>   @info "NDArray::argmax"
>    @info "NDArray::argmax::NaN"
>   let
>     A = [1.  5 3;
>          NaN 2 6]
>     x = NDArray(A)
> 
>     @test copy(argmax(x, dims = 1)) == [1 1 2]
>     @test copy(argmax(x, dims = 2)) == reshape([2, 3], :, 1)
>   end
> end
> ```
> 
> We have to skip `NaN`'s. As far as I understand, in that case the outputs of `nd.argmax` and `np.nanarmax` should be identical and we will non need `nd.nanargmax`. Is it correct?
> 
> BTW, what would be correct output of `nd.argmax` when all elements of vector will be `NaN`'s?
> 
> ```
>     A = [1.  5 3;
>          NaN NaN NaN]
> ```

@drivanov Yes Correct
For all Nan along the axis we should ideally raise valueerror just like np.nanargmax: https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanargmax.html

**Comment by marcoabreu** [comment]
Did you mess up with the rebasing by any chance?

**Comment by access2rohit** [comment]
@marcoabreu I am debugging sth only on Windows machine. because it deosn't fail on windows ami on local but only on CI. Thats why I removed other CI files from the PR. Its won't be merged in this state. Don't worry!

**Comment by access2rohit** [comment]
> Please rebase... you're deleting a bunch of jenkinsfiles that are required.

@aaronmarkham I am not. This is only for debugging purposes. It will not be merged in this state.

**Comment by drivanov** [comment]
I just finished comparative profiling of currently used `argmax` vs. #16178 vs. #16218 on CPU.  Three versions of `argmax` were tested on 
- 3 axes of tensors of 24 different 3-dimentional shapes;
- 2 axes of tensors of 16 different 2-dimensional shapes.
(totally on 104 = 3*24 + 2*16 different combinations (shape, axis))

Here is a short summary:
```
                                   Current:       #16178       #16218
Average improvement:                  1x          2.283x       4.263x      
Maximal improvement:                 n/a          6.323x      14.318x
# of losses to Current Argmax:         0            22           1
# of losses to #16178                 82             0           5
# of losses to #16218                103            99           0
```

Complete results are in:
[ArgMax Results 16178_vs_16218.zip](https://github.com/apache/incubator-mxnet/files/3644322/ArgMax.Results.16178_vs_16218.zip)


According to these results #16218 is better. Besides, it uses the same templates for GPU version of `argmax` and
```
Average Improvement for GPU:        8.905
Maximal improvement for GPU:      119.704
# of losses to Current Argmax:       11
```

**Pull request closed without merging**
