### PR TITLE
[MXNET-102] Added tutorial on how to use data augmenters.

### PR DESCRIPTION
**Pull request by thomelane**
## Description ##

Added tutorial on methods of using data augmenters.

### Essentials ###

N/A, as only added a single markdown file.

### Changes ###

Added tutorial.

## Comments ##

Quote from tutorial:

In this tutorial we discuss the different interfaces avaliable in MXNet to perform data augmentation. We start by showing a complete example using Gluon's [`mxnet.gluon.data.Dataset`](https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.Dataset), and then unpack the example to gain a greater understanding of the internals. In the process you'll learn about augmentation functions, [`mxnet.image.Augmenter`](https://mxnet.incubator.apache.org/api/python/image/image.html?highlight=augmen#mxnet.image.Augmenter) classes and Augmenter lists. We also provide examples using [`mxnet.image.ImageIter`](https://mxnet.incubator.apache.org/api/python/image/image.html?highlight=imageiter#mxnet.image.ImageIter) if you haven't yet moved to Gluon.

### CODE REVIEW

**Comment by rahul003** [comment]
The filename and location (`docs/tutorials/python/using_data_augmenters/Methods of applying data augmentation.md`) are awkward.

Could you make it simpler like `docs/tutorials/python/data_augmentation.md` ?

**Comment by thomelane** [comment]
@rahul003 made the suggested changes.
@cjolivier01 added JIRA task https://issues.apache.org/jira/browse/MXNET-102

**Comment by thomelane** [comment]
@rahul003 @szha @piiswrong @cjolivier01 can we get this merged?

**Comment by piiswrong** [comment]
Mixing gluon and mx.image is weird.

**Comment by thomelane** [comment]
@piiswrong Until we've got the new Gluon augmentation, using mx.image inside a `transform` function is the best approach I though? It's the only way I've found in the examples.

**Comment by thomelane** [comment]
@marcoabreu the build seems temperamental at the moment, got a successful build on the 4th attempt. My 1st attempt errored trying to download CIFAR-100, 2nd attempt failed on `test_gluon.test_lambda` as `Error 1.270788 exceeds tolerance rtol=0.001000, atol=0.000000.` and the 3rd time I couldn't quite tell exactly what was the issue but `build.py: 2018-04-05 17:39:40,153 Running of command in container failed (255): docker run --rm -v /home/jenkins_slave/workspace/ut-perl-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-perl-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpugpu_perl`. Any idea what's causing this given my changes are only markdown?

**Comment by marcoabreu** [comment]
Yeah sorry, our tests are quite flaky :/

**Comment by thomelane** [comment]
@marcoabreu are there Github/JIRA issue(s) for the individual tests that fail? or is there a general issue I can add this information to?

**Comment by marcoabreu** [comment]
Yes, we track them with the labels "Flaky" and "test". I think they're all tracked (pexcept the perl ones), but feel free to double check if the ones you encountered are already there.

**Pull request merged**
