### PR TITLE
[v1.x] fix mx2onnx wheel

### PR DESCRIPTION
**Pull request by Zha0q1**
Move the _op_translations_opsetxx files outside the invisible _op_translation folder

### CODE REVIEW

**Comment by waytrue17** [comment]
Why would we remove the `_op_translation` folder? I think having the folder is better for tracking and maintenance, especially when we start to support more and more versions that ONNX will release.

**Comment by Zha0q1** [comment]
> Why would we remove the `_op_translation` folder? I think having the folder is better for tracking and maintenance, especially when we start to support more and more versions that ONNX will release.

The folder is invisible to setup.py. Let me see how I can keep the folder while still be able to pack the wheel correctly, I am guessing it's because the underscore?

**Comment by waytrue17** [comment]
> > Why would we remove the `_op_translation` folder? I think having the folder is better for tracking and maintenance, especially when we start to support more and more versions that ONNX will release.
> 
> The folder is invisible to setup.py. Let me see how I can keep the folder while still be able to pack the wheel correctly, I am guessing it's because the underscore?

Yeah, maybe we can try changing the folder name

**Review by waytrue17 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
