### PR TITLE
Update Ubuntu images used on CI to 20.04

### PR DESCRIPTION
**Pull request by leezu**
Update Ubuntu CI version to 20.04 and Cuda 11.1. This helps ensure MXNet to work well on recent Linux distributions (while ensuring it continues to work well on ancient distributions based on the CentOS7 CI pipeline)

Thanks to @josephevans who unblocked this update via https://github.com/apache/incubator-mxnet/pull/19017

### CODE REVIEW

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

https://github.com/apache/incubator-mxnet/issues/19623

**Review by szha — APPROVED** [review]

**Comment by QueensGambit** [comment]
Hi @leezu .
This PR deleted `option(USE_CPP_PACKAGE "Build C++ Package" OFF)` from CMakeLists.txt which is a breaking change.
I tried for two days to build MXNet from source on Windows, only to find out that my given `USE_CPP_PACKAGE=1` does not exists anymore.

Building the cpp-package on Linux and Mac via the makefile still works.
Was this intended or done by accident?

**Comment by leezu** [comment]
@QueensGambit the CPP package was removed as part of https://github.com/apache/incubator-mxnet/commit/2fbec60e0da8832d71f7e3f93d4407dbca745e51 as it relied on deprecated APIs. It's pending refactor to be compatible with the supported C APIs. You can follow https://github.com/apache/incubator-mxnet/pull/20131 for status

This PR removed USE_CPP_PACKAGE as it was missed in 2fbec60e0da8832d71f7e3f93d4407dbca745e51

**Comment by QueensGambit** [comment]
Thanks for the info @leezu .
However, I am a bit confused because I was still able to build the CPP-Package with Intel-MKL back-end on Linux and Mac for MXNet 1.8.0 (2fc0706874531fdfdbe49819eae0c88f8016eee3).

**Comment by leezu** [comment]
You can still use the `v1.x` branch if you want to have backwards compatibility. For the master branch, contributions are very welcome. You can see #20131 for a current PR that implements the CPP package in the master branch.

**Pull request merged**
