### PR TITLE
MKL-DNN RNN checks NDArray version

### PR DESCRIPTION
**Pull request by zixuanweeei**
## Description ##
This should fix ISSUE #16037. A member variable `weights_version` is added to `RNNOp` class. Besides, instead of using `Storage::Handle` to hold the temp space, this PR turns to use `NDArray` for the management of temp space. @ciyongch @PatricZhao @TaoLv @ZhennanQin 

### Changes ###
- [x] Weights version (`NDArray.version()`) check, unit test added
- [x] `Storage::Handle` -> `NDArray`

### CODE REVIEW

**Comment by zixuanweeei** [comment]
Hi, @matteosal. This PR aims to fix the problem filed by #16037. Hope it could work. Would you mind checking on this branch to see whether it works for your cases? It will be very helpful. Thanks.

**Comment by matteosal** [comment]
Tested, it fixes the issue

**Comment by zixuanweeei** [comment]
> Tested, it fixes the issue

Thanks a lot 🙂.

**Comment by zixuanweeei** [comment]
CI passed. Please take a look @PatricZhao @ciyongch

**Comment by pengzhao-intel** [comment]
@ciyongch please help take a reveiw

**Pull request merged**
