### PR TITLE
[docs] Fix runtime feature detection documentation

### PR DESCRIPTION
**Pull request by larroy**
## Description ##

as title. 

Documentation was not appearing in the index nor sidebar.
Adds usage example to mxnet.runtime

@ThomasDelteil @aaronmarkham

### CODE REVIEW

**Comment by larroy** [comment]
@aaronmarkham @zachgk @lanking520  can we merge this?

**Comment by larroy** [comment]
@ChaiBapchya does CPP affect the library build?

**Comment by aaronmarkham** [comment]
> @ChaiBapchya does CPP affect the library build?

You have to build from source with that flag in order to use CPP. You can't just take a lib you built without the flag and setup the binding (like you do with the other lang bindings)... if that's what you're asking... At least, this is my understanding.

**Comment by larroy** [comment]
That's a good call for contributions in that case.

**Pull request merged**
