### PR TITLE
Add cuda rtc module

### PR DESCRIPTION
**Pull request by piiswrong**
@yzhang87

### CODE REVIEW

**Comment by piiswrong** [comment]
@sergeykolychev Do you know why the perl gpu test failed?

**Comment by sergeykolychev** [comment]
@piiswrong 
This is the error:#   Failed test 'use AI::MXNet;'
#   at t/AI-MXNet.t line 4.
#     Tried to use 'AI::MXNet'.
#     Error:  Can't load '/workspace/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/AI/MXNetCAPI/MXNetCAPI.so' for module AI::MXNetCAPI: libcuda.so.1: cannot open shared object file: No such file or directory at /usr/lib/perl/5.18/DynaLoader.pm line 184, <DATA> line 207.

**Comment by piiswrong** [comment]
usually /usr/lib64/libcuda.so

**Comment by sergeykolychev** [comment]
@piiswrong 
I compiled the library on your branch on AWS P2.xlarge instance with Ubuntu 16 and can't reproduce this bug
Here's what I've got:
```
ubuntu@ip:~/rtc_gpu$ ldd perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/AI/MXNetCAPI/MXNetCAPI.so |grep libcuda.so.1
        libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f406996f000)
ubuntu@ip:~/rtc_gpu$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
Could this be a problem with the GPU docker container ? It is possible to see if libcuda.so.1 is present within this container ?
One thing I noticed that libmxnet.so on gluon branch (which is equivalent to master) is not dependent on libcuda.so.1
```
ubuntu@ip:~/gluon_mxnet/mxnet/lib$ ldd libmxnet.so |grep libcuda.so
ubuntu@ip:~/gluon_mxnet/mxnet/lib$
```
The changes in your branch introduce the linkage, but may be docker lacks this lib ?
Or just try to rerun tests :-)

**Comment by sergeykolychev** [comment]
@piiswrong see this please
https://github.com/piiswrong/mxnet/pull/6

**Comment by sergeykolychev** [comment]
@piiswrong updated the pull against your branch to make it less hacky.

**Comment by piiswrong** [comment]
It's weird to install a specific version of cuda inside the install script.

I'll mark perl gpu failures as ignored and merge this first.

**Comment by sergeykolychev** [comment]
@piiswrong yeah it's weird but is not weird that ldd libmxnet.so shows libcuda.so.1 as linked lib and docker container does not have this file ? If your tests pass that means linking to the lib was unnecessary ? Why linking to it then in the first place ?

**Comment by piiswrong** [comment]
I think libcuda.so is necessary. Does it compile without libcuda?

**Comment by sergeykolychev** [comment]
libcuda.so does not exist in the /usr/local/cuda/lib , it only exists in /usr/local/cuda/lib/stubs/
libcuda.so.1 does not exist in /usr/local/cuda
when you link to it you actually link to the version that is installed from the libcuda1 ubuntu package.
Also before this pull request ldd libmxnet.so does NOT show dependency on libcuda.so.1 
I believe that linking to libcuda.so.1 is unnecessary.

**Comment by gautamkmr** [comment]
As mentioned before this commit is causing the perl gpu test failure 
https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/435/pipeline/299

Error message is Can't load '/workspace/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/AI/MXNetCAPI/MXNetCAPI.so' for module AI::MXNetCAPI: libcuda.so.1: cannot open shared object file: No such file or directory at /usr/lib/perl/5.18/DynaLoader.pm line 184, <DATA> line 207.

**Comment by sergeykolychev** [comment]
@gautamkmr @piiswrong I am debugging this issue via https://github.com/apache/incubator-mxnet/pull/8053
However the CI jenkins does not function properly failing before it gets to perl tests so I can't see the output of the ldd command.
Hopefully tomorrow jenkins will start working and I'll understand where that missing lib is located in the jenkins env.

**Pull request merged**
