### PR TITLE
[MXNET-703] Update onnx-tensorrt for int8/fp16 support

### PR DESCRIPTION
**Pull request by KellenSunderland**
## Description ##
Update onnx-tensorrt with new support for different data types, including (importantly for v100) fp16.  This will not fully enable int8/fp16 inference yet, but lays the groundwork for further updates.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-work-in-progress]
Thanks for your contribution @KellenSunderland

**Comment by KellenSunderland** [comment]
@mxnet-label-bot update [pr-awaiting-review]

**Comment by sandeep-krishnamurthy** [comment]
@Roshrini @vandanavk @marcoabreu - Can you please take a look at this PR?

**Comment by KellenSunderland** [comment]
18 days, no review, closing.

**Comment by ankkhedia** [comment]
@Roshrini @vandanavk ping for review!

**Comment by anirudhacharya** [comment]
@KellenSunderland can you please elaborate on how this enables fp16 inference, and the changes involved? and why the change in the dockerfile build

**Comment by karan6181** [comment]
@KellenSunderland  can you please address the review comments?

@Roshrini @vandanavk Can you please review it? 

Thanks!

**Comment by abhinavs95** [comment]
@vandanavk @Roshrini Could you please help review? Thanks

**Comment by piyushghai** [comment]
@vandanavk @Roshrini Ping...

**Pull request closed without merging**
