### PR TITLE
[MXNET-722][WIP][DO NOT MERGE] Maven publish pipeline demo

### PR DESCRIPTION
**Pull request by lanking520**
## Description ##
https://github.com/apache/incubator-mxnet/issues/11933
Hi @marcoabreu @KellenSunderland @szha @nswamy ,

This PR will show off the ways that we can use CI to publish Scala package to Maven. As we discussed earlier in the mailing list, the publish process should be done in a restricted node with AWS credential provided.

Be aware, this package will be formed into a pure dynamically-linked way which means no dependencies will be wrapped together into a single piece.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by lanking520** [comment]
Since there are some dependencies installation required in docker, I think I should create a new `dockerfile` for these changes.

**Comment by kalyc** [comment]
Thanks for your contribution @lanking520 
@mxnet-label-bot[pr-awaiting-testing, pr-work-in-progress]

**Comment by vandanavk** [comment]
@lanking520 Is this PR still WIP?

**Comment by lanking520** [comment]
Close this since @zachgk is working based on this.

**Pull request closed without merging**
