### PR TITLE
[v1.7] Backport #17702 and #17872 to v1.7 branch (#18038)

### PR DESCRIPTION
**Pull request by stu1130**
## Description ##
Backport #17702 and #17872 to v1.7 branch which fix the LSTM issue

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by stu1130** [comment]
@zixuanweeei I help you cherry-pick the commit to v1.7

**Comment by leezu** [comment]
Should this go to 1.x instead? https://lists.apache.org/thread.html/rca8c8a9ac11e24197b4ee536e8432dd97b67424b5ee2f31c68b2958c%40%3Cdev.mxnet.apache.org%3E

**Comment by stu1130** [comment]
@leezu It is already in 1.x. We need the fix to build temporarily libmxnet

**Comment by stu1130** [comment]
close the PR as Ciyong will sync up 1.7 with 1.x on 0417

**Pull request closed without merging**
