### PR TITLE
[MXNET-848] Pin dockcross base images in CI

### PR DESCRIPTION
**Pull request by KellenSunderland**
## Description ##
This PR will pin our dockcross base images to known working versions.  Pinning these images is necessary as we've had cases where following the 'latest' tag in dockerhub leads us to picking up broken, or incompatible images.  Though the dockcross images are generally high-quality we'd like to avoid these issues from blocking our CI in the future.

The disadvantage here is that we will lose visibility in valid failures for things like new cmake versions that potentially break on ARM builds.  We feel that these test should be done independently of PR validation, and would be best suited for the nightly test runs.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by KellenSunderland** [comment]
@marcoabreu

**Comment by lebeg** [comment]
We need to enable OpenMP for other arm platforms, I've build the right dockcross images, once they are uploaded to dockerhub we can update the versions in this change and add armv7 to it.

**Comment by KellenSunderland** [comment]
@lebeg: nice!  The images in these PR are the exact same images we were using prior to pining.  I'd recommend we initially stick with them, then give your fixed images new tags and test them thoroughly on the dev CI.  We can then slowly roll them out to prod (and should be able to easily roll them back).  What do you think?

**Comment by lebeg** [comment]
@KellenSunderland good idea, let's do that

**Comment by lebeg** [comment]
https://github.com/apache/incubator-mxnet/pull/12272 Enable armv7 with pinned docker images

**Pull request merged**
