### PR TITLE
update cub commit for license issue

### PR DESCRIPTION
**Pull request by roywei**
fix https://github.com/apache/incubator-mxnet/issues/15569

updated cub to latest commit which the author updated license header.

cc @PatricZhao @TaoLv

### CODE REVIEW

**Comment by lanking520** [comment]
How was the status now?

**Comment by ciyongch** [comment]
Hi @roywei, is there any updates for this issue? As we're now preparing for v1.7.x release (roadmap: https://github.com/apache/incubator-mxnet/issues/16864), do you think we still need the fix in this release, thanks!

**Comment by ciyongch** [comment]
Gentle ping @roywei , what's he current status? May I know if it's still needed in v1.7.0 release, thanks!

**Comment by roywei** [comment]
@ciyongch Hi I don't think it's a hard requirement as the author already stated he allows us to use it. It's seem there are some code update included that breaks mxnet operator.
I'm currently packed and not able to fix the break now. It will be great if someone else can help take a look on the code change.
Closing this PR.

**Pull request closed without merging**
