### PR TITLE
[WIP] Fixes test_nccl_pushpull flaky test

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
#11707

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
CI doesn't have build with NCCL yet. cc @marcoabreu

**Comment by vandanavk** [comment]
@mxnet-label-bot [pr-work-in-progress]

**Comment by perdasilva** [comment]
@lebeg do you know if multiple gpus are required to reproduce the flakyness here? I haven't been able to reproduce on my single 1080 Ti (too poor to run dual T_T)

**Comment by lebeg** [comment]
@perdasilva  Yes, I was. In fact if you look closer to the test than you realise that it would pass only in the case you have 1 GPU :) WIP fix is here https://github.com/apache/incubator-mxnet/pull/12477

**Comment by perdasilva** [comment]
@lebeg I'm sorry I came in too late for the game. I'll close this PR and look for another flaky test =D

**Pull request closed without merging**
