### PR TITLE
upgrade sphinx and autodocsumm

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
Back-porting a patch for Julia and Python docs building.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@mxnet-bot run ci website

**Comment by aaronmarkham** [comment]
@mxnet-bot run ci [website]

**Comment by aaronmarkham** [comment]
@ChaiBapchya Why did it run all of the tests? I thought it was supposed to only run the one I requested.

**Comment by aaronmarkham** [comment]
Website test blocked by #17920

**Comment by ChaiBapchya** [comment]
Auto-triggers hasn't been disabled yet (due to few members raising concerns for this drastic change in functionality) [Refer : [mail thread](https://lists.apache.org/thread.html/rcd66041eb7e94f1f03c8511e8fedf0f593e47670106339744ef575a1%40%3Cdev.mxnet.apache.org%3E)].
Thus, for every commit, CI will be auto-triggered.
Hence all the jobs have been triggered once.
Website has been built twice (second time because of your command)

Makes sense? @aaronmarkham

**Comment by aaronmarkham** [comment]
> Auto-triggers hasn't been disabled yet (due to few members raising concerns for this drastic change in functionality) [Refer : [mail thread](https://lists.apache.org/thread.html/rcd66041eb7e94f1f03c8511e8fedf0f593e47670106339744ef575a1%40%3Cdev.mxnet.apache.org%3E)].
> Thus, for every commit, CI will be auto-triggered.
> Hence all the jobs have been triggered once.
> Website has been built twice (second time because of your command)
> 
> Makes sense? @aaronmarkham
@ChaiBapchya 
Yep, but the message from the bot doesn't make that clear, so instead of reducing runs, I added one.
Maybe update the bot's message to say what's happening now? 
"All tests are already queued to run once. If tests fail, you can trigger one or more tests again with the following command."

**Comment by connorgoggins** [comment]
When I incorporated the changes from this PR into v1.6.x, I still ran into the Julia build issue (dependency problem, markdown must be >=3.2). However, when I bumped the version from 3.1 to 3.2, I received an error indicating that there was no such version available, with the highest-order version being 3.1.1 (see error [here](http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/docs%2Fconnor-website-build-master/detail/connor-website-build-master/26/pipeline)). Exploring more potential fixes now.

**Comment by aaronmarkham** [comment]
> When I incorporated the changes from this PR into v1.6.x, I still ran into the Julia build issue (dependency problem, markdown must be >=3.2). However, when I bumped the version from 3.1 to 3.2 in the Julia Makefile, I received an error indicating that there was no such version available, with the highest-order version being 3.1.1 (see error [here](http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/docs%2Fconnor-website-build-master/detail/connor-website-build-master/26/pipeline)). Exploring more potential fixes now.

https://pypi.org/project/Markdown/
I think it's because it is Python 3 only. And the build switched over to that recently... so... *sigh*... we'd have to switch the 1.6.x build flow to use Python3. Not sure how much effort that is...

**Comment by connorgoggins** [comment]
Agreed, that seems to be the root of the problem. With this in mind, it might make sense to also pull the master Julia docs into the static artifact for v1.6 (same as with R docs).

**Comment by aaronmarkham** [comment]
I'm working on a patch for Julia and Python that I hope will resolve this... but still no idea about the R issue (#17920).

**Comment by aaronmarkham** [comment]
I tested updating the docs generation to Python 3 and found it's bound with other parts of CI that would also require the updates. I think the only way to fix 1.6.x is to deploy the CI updates for Python3 AND fix whatever regression was introduced with the back-porting of updates to `mxnet.metric`. I'm calling off (my) further investigation into running these old docs packages. If on-call has the cycles to go back and fix these issues, then we can try running these doc sets again.

**Comment by ChaiBapchya** [comment]
@aaronmarkham makes sense.
The current bot message (was for the older proposal whereby we would remove auto-trigger and just have manual trigger using this bot)
Good point. Fixed it.
@aaronmarkham now the bot will comment this for a new PR : https://github.com/apache/incubator-mxnet/pull/17937#issuecomment-606139184

**Pull request closed without merging**
