### PR TITLE
Revert "[MXNET-1198][DO NOT MERGE] MXNet Java API"

### PR DESCRIPTION
**Pull request by lanking520**
Reverts apache/incubator-mxnet#13162 to be fair for everyone who commits to this one

### CODE REVIEW

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by marcoabreu** [comment]
Is it intentional that you are reverting two commits?

**Comment by lanking520** [comment]
> Is it intentional that you are reverting two commits?

@marcoabreu I am not sure, this just came up when I click the `revert` button. But it looks like +0 and -0.

**Comment by lanking520** [comment]
Please don't merge it for now until figuring out how to merge commit with all commits history of a branch

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-work-in-progress]

**Comment by lanking520** [comment]
Close this since have the new one https://github.com/apache/incubator-mxnet/pull/13309

**Pull request closed without merging**
