### PR TITLE
Relaxing type requirements for reshape_like op

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Similarly to #14097, reshape_like op should also not dictate the type of its second argument (since only shape metadata is used there). 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by vandanavk** [comment]
@mxnet-label-bot add [Operator, pr-awaiting-review]

**Comment by vandanavk** [comment]
@ChaiBapchya @zhreshold for review

**Comment by zhreshold** [comment]
Please let me know ci goes green, I can merge right after.

**Comment by vandanavk** [comment]
@mxnet-label-bot update [Operator, pr-awaiting-merge]

@zhreshold PR ready for merge

**Pull request merged**
