### PR TITLE
Contributing VGG models to model zoo

### PR DESCRIPTION
**Pull request by abhinavs95**
## Description ##
Contributing VGG models to gluon model zoo - 16, 16_bn, 19, 19_bn. Models are trained with Gluon using script from [here](https://gluon-cv.mxnet.io/model_zoo/index.html#image-classification).

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Updated docs to reflect new accuracies and sources
- Updated hashes for the model files

### CODE REVIEW

**Comment by abhinavs95** [comment]
@hetong007 could you please review and approve? Thanks!

**Comment by hetong007** [comment]
Please also push your scripts and logs to gluoncv, we'd like to have results reproducible.

**Comment by abhinavs95** [comment]
@hetong007 I used the script `train_imagenet.py` from gluoncv for training.

Also, I only have the train command containing the hyper parameters and the accuracy plots with me, not the full training logs. The results can be reproduced using the same script and hyperparameters.

**Comment by hetong007** [comment]
Please have your training command pushed to gluon-cv at: https://github.com/dmlc/gluon-cv/blob/master/docs/model_zoo/index.rst

Or you can also post it here and I'll verify it. Thanks.

**Pull request merged**
