### PR TITLE
[v1.4.x] mkldnn s8 conv API change for 1.4.x branch

### PR DESCRIPTION
**Pull request by ZhennanQin**
## Description ##
This is extracted from #13697, to make API change for 1.4.x branch.
@KellenSunderland  @pengzhao-intel 
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-awaiting-review]
Thanks for your contribution @ZhennanQin

**Comment by pengzhao-intel** [comment]
@KellenSunderland could you help take a review this PR? The deadline of 1.4 is very near :(

**Comment by pengzhao-intel** [comment]
@TaoLv please help take a review too :)

**Comment by srochel** [comment]
Please review and merge asap, this is the last PR blocking 1.4.0.rc1. Please keep an eye on builds and CI.

**Comment by szha** [comment]
@zheng-da @reminisce @eric-haibin-lin ping for review.
@srochel this change concerns what API to expose in 1.4.0 so please allow some time to get it right.

**Comment by KellenSunderland** [comment]
Having a more detailed look now ...

**Comment by ZhennanQin** [comment]
@szha , A better design is isolating public API with internal API, which is, create a new ndarray wrapper class that only exposes public API. But this probably can't be done within 1.4.x. Consider there're many mkldnn APIs already existing in ndarray.h, e.g.

https://github.com/apache/incubator-mxnet/blob/3165262f1f4c94aaf9bb9a333f32d4c94fddf293/include/mxnet/ndarray.h#L722-L745

so I think it's fine for this time.

**Pull request merged**
