### PR TITLE
Fix for #11339

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
As title, fix the typo in convolution.cu found by #11339 

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Correct type in convolution.cu

## Comments ##
Related tests pass more than 10000 times on my local machine.

### CODE REVIEW

**Comment by marcoabreu** [comment]
I think there is another PR that already fixes this typo and also introduces compilation into CI

**Comment by haojin2** [comment]
@marcoabreu So is this PR still needed?

**Comment by marcoabreu** [comment]
I don't think so, but I can't find the PR right now :/

**Comment by marcoabreu** [comment]
#11470

**Comment by haojin2** [comment]
@marcoabreu Did not notice that, closing this.

**Pull request closed without merging**
