### PR TITLE
im2rec.py output labels.txt file for use in inference.

### PR DESCRIPTION
**Pull request by dwSun**
## Description ##
im2rec.py can create some lst files for training, but the label file used in inference is not generated.

### Essentials ###
- [ Y ] Passed code style checking (`make lint`)
- [ Y ] Changes are complete
- [ N ] All changes have test coverage
- [ Y ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [ N ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ 1 ] output labels.txt file for use in inference.

## Comments ##
- output labels.txt file for use in inference.

### CODE REVIEW

**Comment by piiswrong** [comment]
This is usually called synset.

**Comment by dwSun** [comment]
File name changed.

**Comment by piiswrong** [comment]
Is the output consistent with imagenet's synset file?

**Comment by dwSun** [comment]
I think it is not. The output is a list of ordered category names.

**Pull request closed without merging**
