### PR TITLE
Support CUDA11.0 on CD

### PR DESCRIPTION
**Pull request by waytrue17**
## Description ##
Enable CUDA 11.0 on CD nightly pipeline and release pipeline
Remove CUDA 9.2 and CUDA 10.0 from CD

### CODE REVIEW

**Comment by waytrue17** [comment]
@leezu @szha can you please review, thanks.

**Review by leezu — COMMENTED** [review]
`centos7_gpu_cu92` is still listed in `Jenkins_steps.groovy` for testing "oldest supported cuda". As Cuda 11 is now supported, you need to replace it with `centos7_gpu_cu102`.

**Review by leezu — APPROVED** [review]
Thank you @waytrue17

**Comment by Zha0q1** [comment]
the base image `nvidia/cuda:11.2-cudnn8-devel-ubuntu16.04` does not exist, so we probably need to try another image

**Pull request merged**
