### PR TITLE
[MXNET-978] Higher Order Gradient Support `logp1`, `expm1`, `square`.

### PR DESCRIPTION
**Pull request by kshitij12345**
## Description ##
PR intends to add support for higher order gradient for `logp1`, `expm1`, `square`.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA-978 issue](https://issues.apache.org/jira/browse/MXNET-978) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] higher order gradient for a `logp1`, `expm1`, `square`.
- [x] unit test for the same.

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by karan6181** [comment]
@kshitij12345 Could you please resolve the merge conflicts? Thanks

**Comment by kshitij12345** [comment]
I guess we should wait till #15531 is in.

**Comment by kshitij12345** [comment]
@apeforest @larroy @sxjscience 
Gentle Ping for Review.

**Pull request merged**
