### PR TITLE
Fix python micro-site table of content bugs

### LINKED ISSUE #16349: [Website] Table of contents bug
For this page - https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html
From top of the page to Neural network section, the right table of contents works as expected
[responsive]

After scrolling down below Neural network section, starting from Contributed routines
https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/routines.html#module-mxnet.ndarray.contrib 
Table of content to right hand side seems to be 
a. unresponsive (can't scroll it down, doesn't highlight based on which part of document we are at)
b. leaks over to the footer
image

### PR DESCRIPTION
**Pull request by ys2843**
## Description ##
fix #16349, mentioned in #17982, the table of content on Python microsite overlaps with footer when scrolling down to the bottom. @ChaiBapchya 

Bugfix: add z-index to footer so that it covers the table of content to avoid overlapping.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:

### Changes ###
- [x] Fixed Python site table of content overlapping with footer

## Comments ##
- Preview: http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/

### CODE REVIEW

**Comment by ys2843** [comment]
@mxnet-label-bot add [Website, pr-awaiting-review]

**Comment by ys2843** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by ChaiBapchya** [comment]
@ys2843 any update?

**Comment by ys2843** [comment]
> @ys2843 any update?

Q1:  Is it expected to disappear when you scroll into the footer?
+ I think hide the toc is an acceptable fix without touching many other css and js. 
Q2: Autodiff header isn't working? 
+ Fixed the underlying JS logic in the follow up commit, please verify in preview. Thanks.
Q3: Moreover clicking on auto-diff brings back the shift anchor tag issue
+ Fixed, other anchor shift issues please verify this PR #18674

**Comment by ys2843** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
unix-gpu fails with test_npx_batch_norm here as you can see here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18664/6/pipeline

Searching on apache/incubator-mxnet issues: https://github.com/apache/incubator-mxnet/issues/18687
This got fixed by a PR: #18688 

So you'll have to rebase this PR on master [so that your branch contains the commit which fixed it]
To rebase

1. Add upstream
```
git remote add upstream https://github.com/apache/incubator-mxnet
```
2. Sync fork master with upstream master
```
git checkout master
git fetch upstream master
git merge upstream/master
git push origin master
```
3. Sync feature branch
```
git checkout <branchname>
git rebase master
git push -f origin <branchname>
```
Other alternative to rebase would be to merge it [this results in a new commit which says "Merge..." and thus doesn't require a "force push"
```
git checkout <branchname>
git merge master
git push origin <branchname>
```

**Pull request merged**
