### PR TITLE
[DOC] fix installation page cpu pip install

### PR DESCRIPTION
**Pull request by zhreshold**
## Description ##
Fix the wrong installation instruction for linux-cpu-pip

This PR also removes the 1.4.0 version which is no longer needed.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by zhreshold** [comment]
Screenshot from 2019-07-26 22-12-22

@aaronmarkham @roywei @mli 

Please review and merge ASAP so we won't block the 1.5.0 website.

**Comment by zhreshold** [comment]
record
@ChaiBapchya See gif.
Basically in index.md you have to make sure there's no orphaned versions and dangling `div`s. In this case v1-4-1 divs only appeared once.

**Comment by ChaiBapchya** [comment]
Yes. This is fine when the branch is `master`
But when the branch is Version 1.5.0, it all goes awry.

See this.
Animated GIF-downsized_large-6

**Comment by ChaiBapchya** [comment]
Basically
1. http://100.24.115.165 (landing page)
2. select 1.5.0 in Versions(master) (which is - http://100.24.115.165/versions/1.5.0/index.html )
3. Then when you go to install

This is the issue - http://100.24.115.165/versions/1.5.0/install/index.html?platform=Linux&language=Python&processor=CPU

**Comment by aaronmarkham** [comment]
@zhreshold I think it's fixed now... do we still need this?

**Pull request closed without merging**
