### PR TITLE
[MXNET-1291] solve pylint errors in examples with issue no.12205

### PR DESCRIPTION
**Pull request by cchung100m**
## Description ##
solve pylint errors in examples with issue #12205 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by cchung100m** [comment]
I will open PR after finishing all parts of commits

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

@vandanavk for review

**Comment by vandanavk** [comment]
the changes LGTM. could you fix the conflict - example/bayesian-methods/bdk_demo.py?

**Comment by cchung100m** [comment]
@vandanavk 
> the changes LGTM. could you fix the conflict - example/bayesian-methods/bdk_demo.py?
I solve the conflict of bdk_demo.py and re-trigger the CI. thank you for the suggestions. :)

**Comment by vandanavk** [comment]
@sandeep-krishnamurthy for review

**Comment by cchung100m** [comment]
@marcoabreu ,

Thanks for the prompt reply. You make me a great progress on participating open source community. (laugh) Thanks again.

Best regards,

**Comment by cchung100m** [comment]
Hi @sandeep-krishnamurthy @marcoabreu 

I complete the rebase and [re-test](https://gist.github.com/cchung100m/31d67eefa9fb1c50c76a536d192419b6), I will appreciate if you can help to review/merge, thanks.

**Comment by cchung100m** [comment]
Hi @sandeep-krishnamurthy 

Thanks for the prompt reply, and CI test passes.

**Pull request merged**
