### PR TITLE
Bug fixed: https://github.com/apache/incubator-mxnet/issues/13485

### PR DESCRIPTION
**Pull request by devymex**
## Description ##
Fixed a bug described in https://github.com/apache/incubator-mxnet/issues/13485

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Bug fixed

## Comments ##
- Tiny change without any document

### CODE REVIEW

**Comment by marcoabreu** [comment]
Hi, please add a test to verify your solution.

**Comment by pinaraws** [comment]
@mxnet-label-bot [pr-awaiting-merge]

**Comment by marcoabreu** [comment]
Sorry @pinaraws but I don't agree with that status.

**Comment by pinaraws** [comment]
@marcoabreu Sorry I missed your comment
@devymex Please add tests as requested by @marcoabreu

**Comment by abhinavs95** [comment]
@devymex Ping for update!

**Comment by piyushghai** [comment]
@devymex Gentle ping....

**Comment by Roshrini** [comment]
@devymex You can add test for your change in this file: https://github.com/apache/incubator-mxnet/blob/master/tools/caffe_converter/test_converter.py

**Comment by roywei** [comment]
Hi @devymex, could you help add a unit test in the file above, you can use the example you provided in the issue.

**Comment by pinaraws** [comment]
Hi @devymex, could you help add a unit test in the file above, you can use the example you provided in the issue.

**Comment by abhinavs95** [comment]
@devymex Gentle ping for an update

**Comment by piyushghai** [comment]
@devymex Gentle ping....

**Comment by Roshrini** [comment]
@devymex Any update on this PR?

**Comment by karan6181** [comment]
@devymex Could you please address the review comments from above for adding the unittest?
There is no activity for 90+ days. Could you please provide an update?

**Comment by abhinavs95** [comment]
Can a committer close this? There has been no response from the requester for more than 4 months.

**Pull request closed without merging**
