### PR TITLE
[Website] adjust website structure

### PR DESCRIPTION
**Pull request by szha**
## Description ##
adjust website structure to reflect the new modules and deprecation

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] Code is well-documented: 
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] adjust website structure to promote np/npx, and deprecate ndarray/symbol and other legacy modules.

### CODE REVIEW

**Comment by ys2843** [comment]
Preview link: http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/

**Comment by szha** [comment]
@ys2843 many thanks! @sxjscience @eric-haibin-lin @leezu @szhengac please take a look and see if the changes look good to you.

**Comment by eric-haibin-lin** [comment]
the caffe2mxnet page leads to 404: 
image

**Comment by szha** [comment]
@eric-haibin-lin since it's deprecated, I will remove it

**Comment by szha** [comment]
@mxnet-bot run ci [unix-cpu, windows-gpu]

**Comment by ys2843** [comment]
Here is the updated preview: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/index.html

**Comment by szha** [comment]
Looks like there are still many problems in the API cards. I will work on this in the next day or two.

**Comment by szha** [comment]
issues found so far:
in http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/index.html
ndarray card: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/ndarray/index.html
normalization block: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/data/normalization/normalization.html
naming no longer relevant: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/blocks/naming.html
custom loss: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/loss/custom-loss.md
gotchas: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/ndarray/gotchas_numpy_in_mxnet.md

in http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/image/index.html
image recognition with pretrained models: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/packages/gluon/image/pre-trained_models.html

in http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/performance/index.html
TRT: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/performance/backend/tensorrt/tensorrt.html
data parallel: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/faq/multi_device

in http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/deploy/index.html
text color orange
cpp inference: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/deploy/inference/cpp.html
cloud weird format: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/deploy/run-on-aws/use_ec2.html

**Comment by szha** [comment]
also most of the API docs are missing as the autodoc doesn't seem to work properly.

**Comment by marcoabreu** [comment]
Did you specifically request my review? If yes, let me know when it's ready to be reviewed

**Comment by szha** [comment]
@marcoabreu I think you were looped in through code owner as I'm updating the CI installation to fix the website [build problem](https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/website/branches/PR-18839/runs/5/nodes/78/steps/124/log/?start=0)
```
OSError: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
```

**Comment by ys2843** [comment]
Preview link: ec2-34-219-134-42.us-west-2.compute.amazonaws.com

**Comment by StevenJokes** [comment]
@sza 
Thanks. I have saw http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/versions/1.6/api/python/docs/tutorials/getting-started/to-mxnet/pytorch.html#Variable-wrapper-vs-autograd-scope
I will close #18943

**Comment by szha** [comment]
@StevenJokes no worries!

**Pull request merged**
