### PR TITLE
Fix dtype inference in arange_like operator

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##

Remove the dtype argument from parameter structure and use ElemwiseType instead.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
@eric-haibin-lin @fhieber

**Comment by TaoLv** [comment]
@eric-haibin-lin Did you observe any crash with fp16 input? With below code snippet, it doesn't seem to crash but just gives numpy.float32 output:

```python
import mxnet as mx
import numpy as np

x = mx.sym.Variable('x', dtype=np.float16)
y = mx.sym.reshape(x, shape=(0, 0, -1))
z = mx.sym.contrib.arange_like(y, axis=-1)

mod = z.simple_bind(ctx=mx.gpu(0), x=(3, 4, 5, 6), graph_req='null')

mod.arg_arrays[0][:] = np.random.normal(size=mod.arg_arrays[0].shape).astype(np.float16)
out = mod.forward(is_train=False)
print(out[0].dtype)
```

**Comment by eric-haibin-lin** [comment]
No I didn't expect a crash. I expect it copies dtype attribute like other xx_like ops

**Comment by TaoLv** [comment]
@eric-haibin-lin  do you think the below code snippet can be used as a test case?

```python
import mxnet as mx
import numpy as np

dtypes = [np.float16, np.float32, np.float64]

for t in dtypes:
    x = mx.sym.Variable('x', dtype=t)
    y = mx.sym.reshape(x, shape=(0, 0, -1))
    z = mx.sym.contrib.arange_like(y, axis=-1)

    mod = z.simple_bind(ctx=mx.gpu(0), x=(3, 4, 5, 6), graph_req='null')

    mod.arg_arrays[0][:] = np.random.normal(size=mod.arg_arrays[0].shape).astype(t)
    out = mod.forward(is_train=False)
    assert out[0].dtype == np.float32
```

**Comment by eric-haibin-lin** [comment]
Yes

**Comment by wkcn** [comment]
I hope to reserve the dtype attribution, and there is a default action when dtype is None.

**Comment by TaoLv** [comment]
> I hope to reserve the dtype attribution, and there is a default action when dtype is None.

Just want to provide the same user experience for `ones_like`, `zeros_like` and `arange_like`.

**Pull request merged**
