### PR TITLE
LBSGD documentation fix

### PR DESCRIPTION
**Pull request by anirudhacharya**
## Description ##
LBSGD documentation fix

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] added correct information for the optimizer update rules

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@eric-haibin-lin does this fix this https://github.com/apache/incubator-mxnet/issues/12171 
the same issue exists in the new beta website and I think this PR will fix that.

**Comment by eric-haibin-lin** [comment]
Thanks for the fix

**Comment by vandanavk** [comment]
@mxnet-label-bot  update [Doc, pr-awaiting-merge]

**Comment by vandanavk** [comment]
@mxnet-label-bot remove [pr-awaiting-review]

**Comment by vandanavk** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by ChaiBapchya** [comment]
Job failed, looks like another CI issue?

**Pull request merged**
