### PR TITLE
Make make lint compatible with python3 (don't call python2 explicitly)

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] For user-facing API changes, API doc string has been updated.
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by mbaijal** [comment]
Hi @larroy I think you need to rebase this PR with latest master to make it pass unit tests.
Thanks!

**Comment by larroy** [comment]
@piiswrong  please merge

**Comment by larroy** [comment]
@mli @piiswrong  can we get this merged please? has been here lingering for a month

**Comment by mbaijal** [comment]
A new build got triggered (says PR updated?)
So now it needs to pass the build again before it can get merged i think

**Pull request merged**
