### PR TITLE
[DO NOT REVIEW] Bring nnvm::Tuple to mxnet::Tuple

### PR DESCRIPTION
**Pull request by junrushao1994**
*This is not a PR to master branch, so nothing will be affected.*

This PR brought `nnvm::Tuple` and `nnvm::TShape` to mxnet, for future improvement of TShape.

CC: @reminisce

### CODE REVIEW

**Comment by roywei** [comment]
@mxnet-label-bot add[Backend, pr-awaiting-review]

**Comment by junrushao1994** [comment]
Most of the migration is done except for the PlanMemory pass, which blocked us from passing CI.

**Comment by reminisce** [comment]
Is it because PlanMemory expects `nnvm::TShape`? We need to copy that pass from NNVM to MXNet anyway, so I think you can make a copy of that to pass the CI.

**Comment by junrushao1994** [comment]
Will send this to master's branch. So closing it for now.

**Pull request closed without merging**
