### PR TITLE
[mkldnn]Mkldnn bn opt backport from master to 1.7x

### PR DESCRIPTION
**Pull request by rongzha1**
## Description ##
[mkldnn]Mkldnn bn opt backport from master to 1.7x

@TaoLv @pengzhao-intel @ciyongch 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ciyongch** [comment]
Assume you're going to backport this PR to v1.x branch, but currently you choose master branch. Please double check the target branch.

**Comment by leezu** [comment]
I edited the target branch accordingly

**Comment by rongzha1** [comment]
> I edited the target branch accordingly

thank you very much.

I have just re-pr it to 1.7.x a minites ago

**Comment by rongzha1** [comment]
@mxnet-bot run ci [all]

**Comment by ciyongch** [comment]
Adding this to 1.7.0 roadmap https://github.com/apache/incubator-mxnet/issues/16864

**Comment by rongzha1** [comment]
@mxnet-bot run ci [all]

**Comment by rongzha1** [comment]
@mxnet-bot run ci  unix-gpu

**Comment by rongzha1** [comment]
@mxnet-bot run ci [unix-gpu]

**Pull request merged**
