### PR TITLE
[1.8] Include oneDNN gemm fix

### PR DESCRIPTION
**Pull request by leezu**
Include fix for https://github.com/apache/incubator-mxnet/pull/19185#issuecomment-700603056

Thank you @pioy

Fix verified via CI run in https://github.com/apache/incubator-mxnet/pull/19185: https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-cpu/detail/PR-19185/2/pipeline/

### CODE REVIEW

**Comment by TaoLv** [comment]
Hi @leezu, are you trying to include a unreleased version of oneDNN to MXNet v1.8? Or you just want to verify the fix? We're asking oneDNN team for a v1.6.4 patch release.

**Comment by leezu** [comment]
Could you provide more details on what fixes are missing from https://github.com/oneapi-src/oneDNN/commit/5ce95efe6f5e86cddbf704b637063cd8dc914125 that will go into 1.6.4?

I think it's up to @samskalicky as release manager to decide if he just includes https://github.com/oneapi-src/oneDNN/commit/5ce95efe6f5e86cddbf704b637063cd8dc914125 or wait for 1.6.4 (or don't include the fix at all)

**Comment by samskalicky** [comment]
Other than waiting for 1.6.4 patch release, what are our options for avoiding the issue in 1.8? Will reverting any/all of #18822 #18867 #19161 help?

**Review by samskalicky — COMMENTED** [review]
Do we have a test now that is passing with this fix?

**Comment by leezu** [comment]
We don't have a test in 1.x branch. One can construct a test by first calling `'tests/python/unittest/test_contrib_intgemm.py::test_contrib_intgemm_multiply[api1-16-192-4]'` followed by a different test calling a hybridized Dense layer and ensuring that the output doesn't contain `NaN`, as per https://github.com/apache/incubator-mxnet/pull/19185#issuecomment-697995138

**Comment by samskalicky** [comment]
> We don't have a test in 1.x branch. One can construct a test by first calling `'tests/python/unittest/test_contrib_intgemm.py::test_contrib_intgemm_multiply[api1-16-192-4]'` followed by a different test calling a hybridized Dense layer and ensuring that the output doesn't contain `NaN`, as per [#19185 (comment)](https://github.com/apache/incubator-mxnet/pull/19185#issuecomment-697995138)

Ok, np. did we verify the fix actually fixes the issue in 1.8.x manually?

**Comment by pioy** [comment]
Let's see if #19260 results can show that the fix really fixes the issue.

**Comment by samskalicky** [comment]
Thanks @leezu do you plan to open another PR for this fix on v1.x as well?

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by bartekkuncer** [comment]
@leezu The number of tags has changed so for the test to pass you have to change it from 205 to 219 in MemFormat test (103 line in mkldnn_test.cc file).
If that is not a problem I will create PR for v1.x branch.

**Comment by samskalicky** [comment]
@bartekkuncer @pioy looks like the CI is passing now. Is this PR ready to merge? Can you review/approve it?

**Comment by bartekkuncer** [comment]
> @bartekkuncer @pioy looks like the CI is passing now. Is this PR ready to merge? Can you review/approve it?

@samskalicky Change looks good now. Ready to be merged.

**Comment by leezu** [comment]
This change is included in v1.x as part of https://github.com/apache/incubator-mxnet/pull/19276

**Comment by samskalicky** [comment]
> This change is included in v1.x as part of #19276

Thanks @leezu for the tracking!

**Pull request merged**
