### PR TITLE
Fixes not being able to target an older CUDAs when multiple versions are present

### PR DESCRIPTION
**Pull request by fran6co**
## Description ##
When multiple versions of CUDA are present the current CMake was always selecting the newest version regardless of what the user specifies.

## Comments ##
- The change in `CMAKE_GENERATOR_TOOLSET ` happens too late, by that time CMake already looked for the newest CUDA version
- It's deprecated behaviour to call `find_package(CUDA)` and when using first language support in CMake for CUDA
- Now the user can select the proper CUDA version by running CMake with `-T cuda=<version>` as specified by CMake documentation
- CUDNN was ignoring CUDNN_ROOT provided in CMake directly in favour of env settings

### CODE REVIEW

**Comment by nswamy** [comment]
@lebeg could you please take a look?

**Comment by lupesko** [comment]
@lebeg @larroy @rahul003 can you guys please review?

**Comment by lupesko** [comment]
Bouncing for review: @lebeg @anirudh2290

**Comment by lebeg** [comment]
@fran6co 
> Now the user can select the proper CUDA version by running CMake with -T cuda=<version> as specified by CMake documentation

Which version of the documentation you are referring to? This is important, since maybe it would require raising the minimal cmake version in the [CMakeLists.txt](https://github.com/apache/incubator-mxnet/pull/11943/files#diff-af3b638bc2a3e6c650974192a53c7291R1)

Checkout some other problems with CUDA listed here https://github.com/apache/incubator-mxnet/issues/12107

**Comment by vandanavk** [comment]
@sandeep-krishnamurthy  Please change label to pr-awaiting-response

**Comment by vrakesh** [comment]
@fran6co Requesting an response @lebeg 's review

**Comment by fran6co** [comment]
@vrakesh sorry but I don't have time to get back to this PR. Should I close it?

**Comment by Roshrini** [comment]
@fran6co Can you close this PR if you cannot work on it now?
Feel free to reopen whenever you can. Thanks!

**Comment by ankkhedia** [comment]
@fran6co Could you please close the PR now and reopen when you can?

**Pull request closed without merging**
