### PR TITLE
[BUGFIX]Fix the regular expression in RTC code

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
This PR makes the regular expression in the legacy RTC code path more efficient.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Instead of checking for arbitrary number of whitespace character in the regular expression, I strip the input so that only a single whitespace is left between matched groups and modify the regular expression accordingly.

FYI @josephevans @szha @TristonC

### CODE REVIEW

**Review by szha — APPROVED** [review]
Thanks for the change!

**Review by marcoabreu — APPROVED** [review]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [unix-cpu, website, windows-gpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by szha** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by TristonC** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by ptrendx** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by josephevans — APPROVED** [review]
CI has finally passed! LGTM!

**Pull request merged**
