### PR TITLE
[operator] Fix expand_dims

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Operator expand_dims falls back to old API

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu, unix-gpu, windows-cpu]

**Review by szha — APPROVED** [review]
Thanks!

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu, windows-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-cpu, unix-gpu, windows-cpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-cpu]

**Pull request merged**
