### PR TITLE
[MXNET-1287] Fix test memory with ResourceScope

### PR DESCRIPTION
**Pull request by zachgk**
## Description ##
Adds ResourceScope to various tests to avoid memory leaks. Otherwise, it is possible to run out of memory on smaller machines. Contains a part of #13995.

@lanking520 @andrewfayres 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by zachgk** [comment]
@mxnet-label-bot add [Scala, pr-awaiting-review]

**Comment by lanking520** [comment]
Try to clean up this:
`NDArrayCollector` introduced in 1.2, we can use ResourceScope to replace them now.

**Comment by zachgk** [comment]
This PR now removes all usages of NDArrayCollector throughout the code. It also officially deprecates it as of 1.5. I also improved the ResourceScope to recursively move NDArrays to outer scope when in hierarchical structure of Traversables (list, set, map, etc.) and Products (tuples).

**Comment by nswamy** [comment]
@zachgk can you please move this to a separate PR along with tests for this chanage?

> I also improved the ResourceScope to recursively move NDArrays to outer scope when in hierarchical structure of Traversables (list, set, map, etc.) and Products (tuples).

**Comment by zachgk** [comment]
By recommendation of @nswamy, this PR no longer contains the deprecation of NDArrayCollector and improvements to ResourceScope as they have been moved to #14780.

**Comment by vandanavk** [comment]
@nswamy is this PR good to go?

**Comment by lanking520** [comment]
@nswamy I believe this one is good to go. Please take a look

**Pull request merged**
