### PR TITLE
Fixes #13388 Adds Clojure to MXNet installation docs

### LINKED ISSUE #13388: [Clojure] - Add Clojure to the main website docs install
Currently Clojure doesn't appear as an option on the main install page of MXNet https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Scala&processor=CPU

installing_mxnet_ _mxnet_documentation

But the default install option should be almost exactly like Scala since it is a maven package 
https://search.maven.org/search?q=clojure%20mxnet

The documentation to be modified is found here https://raw.githubusercontent.com/apache/incubator-mxnet/master/docs/install/index.md

To test out the results of the change and see what it looks like seehttps://github.com/apache/incubator-mxnet/tree/master/docs/build_version_doc

There is also a Dockerfile to build the website that might be useful
https://github.com/apache/incubator-mxnet/blob/master/docs/build_version_doc/Dockerfile

### PR DESCRIPTION
**Pull request by anujsrc**
## Description ##
Adds Clojure installation docs to MXNet website

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Enables Clojure installation docs for Linux CPU and GPU
- [x] Enables Clojure installation docs for MacOS CPU
- [x] Adds placeholder for MacOS GPU and Windows installation docs

## Comments ##
- To validate the changes, built the docs in Python virtual environment via ``make docs USE_OPENMP=1``
- Here are the screenshots for Clojure tab placement and related docs:

#### MXNet-Clojure Linux CPU
mxnet-clojure-linux-cpu

#### MXNet-Clojure Linux GPU
mxnet-clojure-linux-gpu

#### MXNet-Clojure MacOS CPU
mxnet-clojure-macos-cpu

#### MXNet-Clojure MacOS GPU
mxnet-clojure-macos-gpu

#### MXNet-Clojure Windows CPU
mxnet-clojure-windows-cpu

#### MXNet-Clojure Windows GPU
mxnet-clojure-windows-gpu

### CODE REVIEW

**Comment by gigasquid** [comment]
Awesome! Thanks for this contribution. It will help Clojure users to get started much easier than before. 🥇 

@aaronmarkham - Could you take a look at this and please give any feedback?

**Comment by anujsrc** [comment]
@gigasquid - it looks like an issue with Docker image. It fails for me as well locally but ``make docs USE_OPENMP=1`` works fine and generates the docs. Do I need to look into that as well or is it a known issue?

**Comment by gigasquid** [comment]
I've retrigged the CI - I "think" the failure is unrelated - fingers crossed this time :)

**Comment by anujsrc** [comment]
@gigasquid @aaronmarkham - I am not sure why the instructions show up twice for MacOS - Clojure - CPU on the released website - https://mxnet.incubator.apache.org/install/index.html?platform=MacOS&language=Clojure&processor=CPU

mxnet-macos-cpu-install

On the staging version it was fine- http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13393/2/install/index.html?platform=MacOS&language=Clojure&processor=CPU

**Comment by aaronmarkham** [comment]
Probably from my merge. I went through on my version and made sure it was right, but git decided it still had conflicts and doubled up stuff.  There's so much duplication of content required for that selector it can be hard to see.  
Anyways, I can try to fix it tomorrow or Monday.

**Comment by aaronmarkham** [comment]
Oh, or it could be what I reported last week, where the selector gets broken and displays two or more sets of content when it should not. I was trying another patch to limit the view by version and I couldn't get it to work... It would display things it shouldn't. All version divs would display at once...

**Comment by anujsrc** [comment]
Thanks @aaronmarkham - Let me know if I need to do any changes from my side

**Pull request merged**
