### PR TITLE
[IR-Patch] IR Bridge

### PR DESCRIPTION
**Pull request by junrushao1994**
@sxjscience @szha @yzhliu @tqchen @zheng-da @eric-haibin-lin

### CODE REVIEW

**Comment by junrushao1994** [comment]
hmmm I have no idea why the lint fails on an irrelevant file, [full message](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fsanity/detail/PR-16290/5/pipeline).

```
+ make pylint
python3 -m pylint --rcfile=/work/mxnet/ci/other/pylintrc --ignore-patterns=".*\.so$,.*\.dll$,.*\.dylib$" python/mxnet tools/caffe_converter/*.py
************* Module caffe_proto_utils
tools/caffe_converter/caffe_proto_utils.py:199:18: E1121: Too many positional arguments for method call (too-many-function-args)
************* Module convert_mean
tools/caffe_converter/convert_mean.py:45:18: E1121: Too many positional arguments for method call (too-many-function-args)

------------------------------------
Your code has been rated at 10.00/10

Makefile:665: recipe for target 'pylint' failed
make: *** [pylint] Error 2
```

**Comment by junrushao1994** [comment]
rebased

**Comment by junrushao1994** [comment]
Two issues:
1) Amalgamation fails, because TVM doesn't provide amalgamation
2) Julia fails with the following error message `LLVM ERROR: out of memory`. Looks like llvm conflicts. I will try static linking...

**Comment by junrushao1994** [comment]
Okay the Julia thing has been fixed via some creepy tricks...let’s then deal with amalgamation

**Comment by marcoabreu** [comment]
@iblis17

**Comment by iblis17** [comment]
well, which version of LLVM is required by TVM?

**Comment by junrushao1994** [comment]
@iblis17 either LLVM 6.0 or 8.0 works. No worries, the issue is caused by symbol conflicts between Julia’s LLVM and TVM’s LLVM, and has been fixed by tweaking TVM’s symbols :-)

**Comment by junrushao1994** [comment]
should be good to go

**Pull request merged**
