### PR TITLE
Fix GetMKLDNNData for delay alloc

### PR DESCRIPTION
**Pull request by ZhennanQin**
Should fix https://github.com/apache/incubator-mxnet/pull/16555#issuecomment-545892144
Let's merge this in master, and then rebase mkldnn-1.0.

@pengzhao-intel @TaoLv 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
@marcoabreu thanks to reviewing the PR. As I mentioned in dev, we have to repeat to retrigger the CI multiple times and each run cost us about 5+hours.

**Comment by marcoabreu** [comment]
That's interesting, I'd be curious about the failure rates. It might be subjective, but I've got the feeling that the mkldnn 1.0 branch is quite a bit more flaky than master. Have you had a chance to check if the numeric stability has decreased with 1.0?

Adjacent to CI talking a long time, could you elaborate in how far adding a test correlates to that? To develop the test, it still can be run locally first and thus in a fast environment. 

But I totally agree that such a high failure rate is not acceptable.

**Comment by ZhennanQin** [comment]
@marcoabreu Thanks for reviewing. This is to fix a bug reported at https://github.com/apache/incubator-mxnet/pull/16555#issuecomment-545892144. Basically, we can use the reported case as a test. But from the bug report, network is loaded from json file, which contains a subgraph. I don't know how to reproduce it with python symbol API. Do you agree with adding a test with loading network from json? Otherwise I need some expert's help to rewrite that into a test.

For CI failure rate, this PR is based on master, not mkldnn-1.0. And as you seen, it already re-triggered for 5 times. I don't think it's a acceptable developer experience.

**Comment by pengzhao-intel** [comment]
> That's interesting, I'd be curious about the failure rates. It might be subjective, but I've got the feeling that the mkldnn 1.0 branch is quite a bit more flaky than master. Have you had a chance to check if the numeric stability has decreased with 1.0?
> 
> Adjacent to CI talking a long time, could you elaborate in how far adding a test correlates to that? To develop the test, it still can be run locally first and thus in a fast environment.
> 
> But I totally agree that such a high failure rate is not acceptable.

We have fully tested the 1.0 branch in local and I don't see the numerical issues till now.
Your feeling is correct since previously the codebase is not maturity and lots of PR was still merging.
This week we will finish all PR in 1.0 and I think everything will work very well.

**Comment by marcoabreu** [comment]
Ideally we would have a unit test, but I understand that this might be a bit difficult to reverse engineer. How about time boxing it? If you can't figure it out, I'd be fine with making it an integration test by loading the json.

I will leave it at your discretion as how to move forward - to speed up the process, feel free to consider adding a test in a separate PR since I trust that you have properly validated the fix.

**Comment by pengzhao-intel** [comment]
Merging now. Thanks to the review and great suggestions :)

**Pull request merged**
