### PR TITLE
[CMake] Fix OSX double compilation and add static library

### LINKED ISSUE #9494: We are building the sources twice on OSX with CMake
## Description
We build 371 files instead of 197 since we build the static and dynamic library with separate object files on OSX

## Environment info (Required)
OSX

Cmake build:
```
mkdir -p build && cd build
cmake -DUSE_CPP_PACKAGE=ON -DUSE_CUDA=OFF -DUSE_OPENMP=OFF -DUSE_OPENCV=OFF -DCMAKE_BUILD_TYPE=Debug -GNinja ..
ninja -v
```

### PR DESCRIPTION
**Pull request by larroy**
Fixes #9494
Simplifies OSX building logic

### CODE REVIEW

**Comment by cjolivier01** [comment]
@de-vri-es Can you please review?

**Comment by cjolivier01** [comment]
please note that "incorrect" is not a valid description.  Please replace "incorrect" with an actual description of why you believe it to be "incorrect".

**Comment by larroy** [comment]
@cjolivier01 I linked the issue which explains it. Removed the word non grata "incorrect". Any additional comments?

**Comment by larroy** [comment]
@marcoabreu I can't reproduce the jenkins build failure in ec2 with:

ubuntu@ip-172-31-36-119:~/devel/mxnet$ tests/ci_build/ci_build.sh build_cuda make -j$(nproc)

Any ideas?

**Comment by marcoabreu** [comment]
@larroy See the following error:
```
make[2]: *** No rule to make target 'libmxnet.a', needed by 'libmxnet.so'.  Stop.
make[1]: *** [CMakeFiles/mxnet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by larroy** [comment]
@marcoabreu thanks, it's a problem. Looking into it but it's hard to solve in a way it works in all the cases.

**Pull request merged**
