### PR TITLE
[1.x] Enable CUDA Graphs for TRT 

### PR DESCRIPTION
**Pull request by Kh4L**
## Description ##
This PR enables CUDA Graphs for TRT FP32 and FP16.
CUDA Graph for INT8 requires more complex work and will be added in a future PR.

### CODE REVIEW

**Review by samskalicky — APPROVED** [review]
LGTM

**Comment by xxxpsyduck** [comment]
Sorry if commenting here is inappropriate. But I'm looking for a document about how to use mxnet (1.7) with tensorrt but I can't find it anywhere. Can you give me a quick guide?

**Comment by samskalicky** [comment]
> Sorry if commenting here is inappropriate. But I'm looking for a document about how to use mxnet (1.7) with tensorrt but I can't find it anywhere. Can you give me a quick guide?

Hi @xxxpsyduck heres the docs page for TensorRT: https://mxnet.apache.org/versions/1.7/api/python/docs/tutorials/performance/backend/tensorrt/tensorrt.html If you have any more questions, please file a separate GitHub issue with the questions and we'll discuss more there. Good luck!

**Comment by xxxpsyduck** [comment]
thanks a lot!

**Pull request merged**
