### PR TITLE
[1.7] MXNet Extension PRs (#17623, #17569, #17762)

### PR DESCRIPTION
**Pull request by samskalicky**
Cherry pick MXNet Extension PRs into 1.7.x:
- Dynamic subgraph compile #17623
- CustomOp Sparse support #17569
- CustomOp RNG support #17762

### CODE REVIEW

**Comment by samskalicky** [comment]
@mxnet-bot run ci [website, unix-gpu]

**Comment by ciyongch** [comment]
Adding this to 1.7.0 roadmap https://github.com/apache/incubator-mxnet/issues/16864.

**Comment by ciyongch** [comment]
@samskalicky I realize that you're committing the patch into v1.7.x instead of v1.x branch, are these patches already in v1.x branch? If not, please help to backport them to v1.x as well, thanks!
My original plan is to backport all the necessary PRs into v1.x firstly, and then rebase v1.7.x to latest v1.x.

**Comment by samskalicky** [comment]
@ciyongch sorry for the confusion, i created https://github.com/apache/incubator-mxnet/pull/18069 also for the v1.x branch.

**Comment by ciyongch** [comment]
@samskalicky got it, that's fine, thanks for the update :)

**Pull request merged**
