### PR TITLE
[v1.7] Cherry pick Increase staggered build timeout (#18568)

### PR DESCRIPTION
**Pull request by josephevans**
* Increase staggered build timeout to 180 min, since sanity build has 180 min timeout.

* Decrease timeout so everyone is happy.

Co-authored-by: Joe Evans <joeev@amazon.com>

### CODE REVIEW

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
Hi @josephevans , please help to re-trigger the `unix-gpu` job as it's stuck.
The modification increases the full time from 30min to 60 min, while decrease the sanity time from 180min to 60min, seems not align to the description?

**Comment by josephevans** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by josephevans** [comment]
> Hi @josephevans , please help to re-trigger the `unix-gpu` job as it's stuck.
> The modification increases the full time from 30min to 60 min, while decrease the sanity time from 180min to 60min, seems not align to the description?

Hi @ciyongch, we actually increased the overall "full" job which first triggers sanity build, then if it passes we run the rest of the jobs. But since it doesn't make sense to have a longer timeout for sanity build than the "full" build, we made them the same. If the sanity build timed out, the full build would have already timed out of the timeout is longer.

**Comment by ciyongch** [comment]
Thanks for the update @josephevans . Ping @leezu @marcoabreu @aaronmarkham to have a review and help merge. Thanks!

**Comment by ciyongch** [comment]
Hi @leeze @ChaiBapchya @marcoabreu @aaronmarkham , can you help to take a review and merged. The corresponding one https://github.com/apache/incubator-mxnet/pull/18568 to v1.x branch is already merged.

**Pull request merged**
