### PR TITLE
[CI] Add Simple GitHub-Action Based License Checker

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Add a simple license checker based on github action([apache/skywalking-eyes](https://github.com/apache/skywalking-eyes))

Note: For config file, I just copied [rat-excludes](https://github.com/apache/incubator-mxnet/blob/master/rat-excludes) into .licenserc.yaml. Will complete the config later. 

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, website]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [website]

**Review by leezu — COMMENTED** [review]
I noticed you remove the ASF header from the np files. Could you explain the rational?

> The term "third-party work" refers to a work not submitted directly to the ASF by the copyright owner or owner's agent. This includes parts of a work submitted directly to the ASF for which the submitter is not the copyright owner or owner's agent.
> Do not modify or remove any copyright notices or licenses within third-party works.
> Make sure that every third-party work includes its associated license, even if that requires adding a copy of the license from the third-party download site into the distribution.
> Do not add the standard Apache License header to the top of third-party source files.
> Minor modifications/additions to third-party source files should typically be licensed under the same terms as the rest of the third-party source for convenience.
> The project's PMC should deal with major modifications/additions to third-party source files on a case-by-case basis.

https://www.apache.org/legal/src-headers.html#3party

As there are major modifications/additions to the source files to integrate with MXNet, ASF header was previously added. Of course we can revisit this decision and relicense. Can you document why?

**Comment by barry-jin** [comment]
> I noticed you remove the ASF header from the np files. Could you explain the rational?
> 
> > The term "third-party work" refers to a work not submitted directly to the ASF by the copyright owner or owner's agent. This includes parts of a work submitted directly to the ASF for which the submitter is not the copyright owner or owner's agent.
> > Do not modify or remove any copyright notices or licenses within third-party works.
> > Make sure that every third-party work includes its associated license, even if that requires adding a copy of the license from the third-party download site into the distribution.
> > Do not add the standard Apache License header to the top of third-party source files.
> > Minor modifications/additions to third-party source files should typically be licensed under the same terms as the rest of the third-party source for convenience.
> > The project's PMC should deal with major modifications/additions to third-party source files on a case-by-case basis.
> 
> https://www.apache.org/legal/src-headers.html#3party
> 
> As there are major modifications/additions to the source files to integrate with MXNet, ASF header was previously added. Of course we can revisit this decision and relicense. Can you document why?

As stated in the MXNet1.9.0 rc7 [voting thread](https://lists.apache.org/thread.html/r5789f5d93716d9d710b855775e71e4892fd37e41338c70c0855958ad%40%3Cgeneral.incubator.apache.org%3E), np_einsum_op.cc, np_einsum_op-inl.h and np_einsum_path_op-inl.h are adapted from numpy and they should stay under original license. 

https://www.apache.org/legal/src-headers.html#3party
...
3. Do not add the standard Apache License header to the top of third-party source files.
...

**Comment by barry-jin** [comment]
This pull request is also addressing some additional license issues listed in #20616

**Comment by leezu** [comment]
> It depends on what you mean by significant, usually changes made to 3rd party files stay under the original license. See [1] on this, note that "Do not add the standard Apache License header to the top of third-party source files.”. If the license was to change, and the headers replaced then that needs to be noted in NOTICE. Please make sure that the license is noted in LICENSE.

https://lists.apache.org/thread.html/r4010c53f976819c94f3450469db8b936f7c15cb046a61f0d488674d3%40%3Cgeneral.incubator.apache.org%3E

**Comment by szha** [comment]
Nice work!

**Pull request merged**
