### PR TITLE
support auto mode for BatchNorm use_global_stats 

### PR DESCRIPTION
**Pull request by YutingZhang**
This PR is to make BatchNorm support "auto" mode for `use_global_stats`. When `autograd.is_training()==True`, it `use_global_stats=False`; otherwise, `use_global_stats=True`.

### CODE REVIEW

**Comment by wkcn** [comment]
Could you please add the related document?

**Comment by YutingZhang** [comment]
> Could you please add the related document?

Sure. Done. Thanks for the review!

**Comment by YutingZhang** [comment]
> This would not take effect when hybridized.

Why?
When `hybrid_forward` is called with the context of `autograd.is_training()`, this will work. And when `hybridize()` is not called again, the block's behavior is not expected to change. Is it not it the expected behavior?

**Comment by YutingZhang** [comment]
Based on the offline discussion with @szha, an implementation at the operator-level will be preferable. I will use this pull request as a temporary hack for my project and send a feature request for an operator-level implementation.

**Pull request closed without merging**
