### PR TITLE
Add quantized batch norm operator fused with ReLU

### PR DESCRIPTION
**Pull request by hankaj**
This PR adds quantized batch norm operator fused with ReLU.
Benchmarking results:
|                                 | Top1 Accuracy |  Top5 Accuracy | Overall throughput (image/sec) | Latency per batch per instance (ms) |
| --------------------- | ---------------- | ----------------- | ---------------------------------- | --------------------------------------- |
| fused int8 full entropy | 0.734875 | 0.91575 | 1197.98 | 106.85 |
| int8 full entropy | 0.711625 | 0.902 | 1161.07 | 110.24 |

### CODE REVIEW

**Comment by hankaj** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by hankaj** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by hankaj** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by bgawrych — APPROVED** [review]
LGTM

**Pull request merged**
