### PR TITLE
Cherry-pick of #17995 and #17937 to 1.x branch

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Cherry pick of #17995 and #17937 to 1.x branch. 

FYI, @ciyongch

### CODE REVIEW

**Comment by ptrendx** [comment]
@ChaiBapchya seems that v1.x branch needs the backport of your fix to TLS handhsake problem.

**Comment by ciyongch** [comment]
@ptrendx  Thanks for the notice, I've already added these two PR in the roadmap, and will update the status later.

**Comment by ChaiBapchya** [comment]
Added : https://github.com/apache/incubator-mxnet/pull/18044
@ptrendx thanks for pointing out!

**Comment by ptrendx** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
