### PR TITLE
Small fix default parameter `--thresh` on SSD example demo.py

### PR DESCRIPTION
**Pull request by higumachan**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by piiswrong** [comment]
@zhreshold

**Comment by zhreshold** [comment]
what's the reason to change the default one from 0.5 to 0.6? @higumachan

**Comment by higumachan** [comment]
@zhreshold 
Because, help text of this argument is written by "help='object visualize score threshold, default 0.6" (written next line of that diff).

**Comment by piiswrong** [comment]
@zhreshold Updates?

**Comment by zhreshold** [comment]
I will update with argparse options, hard coded default values are no longer a good practice. Closing for this reason.

**Pull request closed without merging**
