### PR TITLE
Add support for networks with multiple outputs in ONNX exporter

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Add support for networks with multiple outputs to ONNX exporter

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by nswamy** [comment]
@Roshrini

**Comment by lupesko** [comment]
Thanks for the contribution @ptrendx !
@anirudhacharya @vandanavk - to take a look as well.

**Comment by stu1130** [comment]
@ptrendx bounce again! Could you please add a test! Thanks

**Comment by BobLiu20** [comment]
Waiting for this PR! Thanks.

**Comment by Roshrini** [comment]
@ptrendx ping again :)

**Comment by ankkhedia** [comment]
@ptrendx Thanks for the contribution! :)
Could you please look into the review comments?

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-review]

**Comment by vandanavk** [comment]
@ptrendx Sina submitted a PR https://github.com/apache/incubator-mxnet/pull/13390 for multi outputs. Please have a look

**Comment by ptrendx** [comment]
Closing then since it achieves the same thing.

**Pull request closed without merging**
