### PR TITLE
[MXNET-287] ARMv6 build with 8-10 times bigger file size

### PR DESCRIPTION
**Pull request by lebeg**
## Description ##

Debug information and examples were included in the build.

### Essentials ###
- [x] The PR title starts with [MXNET-287](https://issues.apache.org/jira/projects/MXNET/issues/MXNET-287)
- [x] Changes are complete
- [x] To the my best knowledge, examples are not affected by this change

### Changes ###
- [x] Removed debug info
- [x] Removed examples

### Comments ###

Size went down from 318M to 33M for libmxnet.so.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Wow, I didn't expect this to grow the file size THAT big! Thanks a lot!

**Comment by larroy** [comment]
yes, but not in the lib or?

**Comment by lebeg** [comment]
@larroy what do you mean?

**Comment by larroy** [comment]
LGTM

**Comment by msurguy** [comment]
Can confirm that the size went down a lot and even more after libomp was removed:
screen shot 2018-04-11 at 3 34 58 pm

Thanks @lebeg !

**Pull request merged**
