### PR TITLE
[MXNET-346] Fix flaky test for hard_sigmoid

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
As title.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-346]
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Fix the too large eps for check_numeric_gradient and loosen atol

### CODE REVIEW

**Comment by haojin2** [comment]
@piiswrong

**Comment by marcoabreu** [comment]
Did you try running this test in a loop?

**Comment by haojin2** [comment]
I manually ran this for quite a few times already, but I'll give another try with loops, thanks for the advice!

**Comment by marcoabreu** [comment]
@DickJC123 didn't you introduce something that allows to loop tests? Could you help us out here?

**Comment by DickJC123** [comment]
Try something like:

$ MXNET_TEST_COUNT=10000 nosetests --logging-level=DEBUG --verbose -s test_module.py:test_op3

**Comment by marcoabreu** [comment]
Thank you, @DickJC123! Is this variable documented somewhere?

**Comment by DickJC123** [comment]
I owe you that.  For now, documentation is at https://github.com/apache/incubator-mxnet/pull/9791

**Comment by haojin2** [comment]
@marcoabreu I've run this 10000 times now and it passes all of those

**Comment by marcoabreu** [comment]
Awesome, thanks a lot!

**Pull request merged**
