### PR TITLE
NumPy-compatible Mean, Std and Var

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
As title.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] NumPy-compatible mean operator
- [ ] Unit test

### CODE REVIEW

**Comment by reminisce** [comment]
@marcoabreu I would like to disable test coverage build that failed in this PR. Let me know if you are not okay with it. Thanks.

**Comment by haojin2** [comment]
@marcoabreu gentle ping for feedback on disabling TEST_COVERAGE build on Clang 3.9 MKLDNN build.

**Comment by wkcn** [comment]
Hi @haojin2 @reminisce , I have a question: do we need Welford algorithm to compute the variance?
"It is often useful to be able to compute the variance in a single pass, inspecting each value x_i only once"

https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance

**Comment by haojin2** [comment]
@wkcn I think this is an interesting algorithm, I’ll revisit this later, from my perspective the current solution is an easier to understand one and also with less loss of precision. But calculating with one one pass could save some memory when the input is really large.

**Pull request merged**
