### PR TITLE
Back port the PR #17672:boolean indexing to branch v1.x 

### PR DESCRIPTION
**Pull request by Alicia1529**
## Description ##
Back port the PR #17672:boolean indexing from master to branch v1.x 
@ciyongch

### CODE REVIEW

**Comment by ciyongch** [comment]
@Alicia1529 , please help to re-trigger the failed CI, thanks!

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [website, clang, edge, miscellaneous, unix-cpu, unix-gpu]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge, unix-cpu]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
Hi @ciyongch, I've retriggered the test [edge] for several times.  Can we consider tweak the tolerance a little bit?

**Comment by ciyongch** [comment]
Hi @Alicia1529 , there's a PR https://github.com/apache/incubator-mxnet/pull/18339 targeting to fix the failed CI `edge` job, let's hold on for a while and retry when it's get merged. Thanks.

**Comment by ciyongch** [comment]
Hi @Alicia1529 , https://github.com/apache/incubator-mxnet/pull/18375 which fixed the `edge` CI failure was merged in v1.x branch, please help to re-trigger the `edge` job, which should be passed now. Thanks.

**Comment by Alicia1529** [comment]
@mxnet-bot run ci [edge]

**Comment by Alicia1529** [comment]
Hi @ciyongch, this pr has passed all the tests and is ready to be merged.

**Comment by ciyongch** [comment]
Thanks @Alicia1529 , we get all the CI tests passed finally :)
@TaoLv @pengzhao-intel @leezu please help to take a look and merge it.

**Pull request merged**
