### PR TITLE
[DOC] fix warnings in tutorials and turn on -W

### PR DESCRIPTION
**Pull request by szha**
## Description ##
fix warnings in tutorials

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] fix warnings in tutorials and turn on -W

### CODE REVIEW

**Comment by leezu** [comment]
```
[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/symbol.py:docstring of mxnet.contrib.symbol.sldwin_atten_context:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/symbol.py:docstring of mxnet.contrib.symbol.sldwin_atten_context:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/symbol.py:docstring of mxnet.contrib.symbol.sldwin_atten_mask_like:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/symbol.py:docstring of mxnet.contrib.symbol.sldwin_atten_mask_like:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/symbol.py:docstring of mxnet.contrib.symbol.sldwin_atten_score:14: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/ndarray.py:docstring of mxnet.contrib.ndarray.sldwin_atten_context:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/ndarray.py:docstring of mxnet.contrib.ndarray.sldwin_atten_context:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/ndarray.py:docstring of mxnet.contrib.ndarray.sldwin_atten_mask_like:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/ndarray.py:docstring of mxnet.contrib.ndarray.sldwin_atten_mask_like:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/contrib/ndarray.py:docstring of mxnet.contrib.ndarray.sldwin_atten_score:14: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] WARNING: failed to import mxnet.gluon.contrib.rnn

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/image/info_gan.ipynb:363: WARNING: Duplicate substitution definition name: "gif".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/loss/loss.ipynb:431: WARNING: Undefined substitution referenced: "triplet_loss".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/loss/loss.ipynb:441: WARNING: Undefined substitution referenced: "ctc_loss".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:140: WARNING: Undefined substitution referenced: "normalizatio n nchw bn".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:140: WARNING: Undefined substitution referenced: "normalizatio n ntc bn".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:377: WARNING: Undefined substitution referenced: "normalizatio n nchw ln".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:377: WARNING: Undefined substitution referenced: "normalizatio n ntc ln".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:454: WARNING: Undefined substitution referenced: "normalizatio n nchw in".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/packages/gluon/training/normalization/index.ipynb:454: WARNING: Undefined substitution referenced: "normalizatio n ntc in".

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/getting-started/to-mxnet/pytorch.ipynb:645: WARNING: Inline literal start-string without end-string.

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/getting-started/to-mxnet/pytorch.ipynb:655: WARNING: Inline literal start-string without end-string.

[2020-12-03T20:31:38.575Z] /work/mxnet/docs/python_docs/python/build/tutorials/getting-started/to-mxnet/pytorch.ipynb:725: WARNING: Inline literal start-string without end-string.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/symbol/contrib.py:docstring of mxnet.symbol.contrib.sldwin_atten_context:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/symbol/contrib.py:docstring of mxnet.symbol.contrib.sldwin_atten_context:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/symbol/contrib.py:docstring of mxnet.symbol.contrib.sldwin_atten_mask_like:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/symbol/contrib.py:docstring of mxnet.symbol.contrib.sldwin_atten_mask_like:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/symbol/contrib.py:docstring of mxnet.symbol.contrib.sldwin_atten_score:14: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/ndarray/contrib.py:docstring of mxnet.ndarray.contrib.sldwin_atten_context:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/ndarray/contrib.py:docstring of mxnet.ndarray.contrib.sldwin_atten_context:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/ndarray/contrib.py:docstring of mxnet.ndarray.contrib.sldwin_atten_mask_like:9: WARNING: Unexpected indentation.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/ndarray/contrib.py:docstring of mxnet.ndarray.contrib.sldwin_atten_mask_like:10: WARNING: Block quote ends without a blank line; unexpected unindent.

[2020-12-03T20:31:38.575Z] /work/mxnet/python/mxnet/ndarray/contrib.py:docstring of mxnet.ndarray.contrib.sldwin_atten_score:14: WARNING: Unexpected indentation.

```

**Comment by szha** [comment]
yeah I missed them due to unclean build. I'm working on them

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-gpu, centos-gpu, website]

**Comment by szha** [comment]
finally green

**Pull request merged**
