### PR TITLE
[scala-package][master] bump up project version

### PR DESCRIPTION
**Pull request by CodingCat**
## Description ##
bump up project version to 1.2.0-SNAPSHOT

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
Why? 1.1 release is not final yet

**Comment by CodingCat** [comment]
I just realized we will release several RC versions before the final version? why that is needed?

**Comment by eric-haibin-lin** [comment]
We need at least one release candidate. If rc0 passes the vote, the candidate itself becomes the final release. If rc0 fails, we need to prepare a rc1.

**Comment by CodingCat** [comment]
Yes, that’s what I have seen and since rc0 has passed and been tagged, isn’t it a good time for changing the version number for the next release?

**Comment by eric-haibin-lin** [comment]
The voting has only passed on dev@. Now the voting is going on on general@. We'll know the voting result this Sunday.

**Comment by CodingCat** [comment]
oh, going to general is a requirement for incubating project only?

**Comment by eric-haibin-lin** [comment]
I’m not sure about that. For MXNet it is required. 

On 2018年2月1日, at 13:04, Nan Zhu <notifications@github.com> wrote:

oh, going to general is a requirement for incubating project only?

**Comment by yzhliu** [comment]
Duplicate #9840 
Thanks for PR anyway.

**Pull request closed without merging**
