### PR TITLE
[HOLD] 1.3.0 release website updates

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
This PR updates the website for the 1.3.0 release.
Please do not merge until after the release.

After merging this PR:
1. Merge https://github.com/dmlc/web-data/pull/119 (updates the pip packages graphic)
2. Update Jenkins CI restricted website build job 
    - to have `v1.3.0` listed in the `tags_to_build` field
    - to have `1.3.0` is the `tag_list` (for what to display on the site)
3. Enable both the build and the publish jobs (turned off right now due to the tvm issue with the 1.2.0 branch)

## Preview
http://34.201.8.176/versions/1.3.0_release/

http://34.201.8.176/versions/1.3.0_release/install/index.html?platform=Linux&language=Python&processor=CPU

http://34.201.8.176/versions/1.3.0_release/install/download.html

### CODE REVIEW

**Comment by TaoLv** [comment]
Hi @aaronmarkham , thanks for your effort. Given MKL-DNN backend is already GA in 1.3.0 release, if it is possible to promote how to build it from source, especially for CPU platform? Currently, I didn't find any content about that on the [install from source webpage](https://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Python&processor=CPU) for either 1.2.1 or master.

**Comment by lupesko** [comment]
Thanks @aaronmarkham !

@TaoLv I do not think MKL-DNN is GA in 1.3.0. I am aware of ongoing work on master to complete test coverage. Regardless, I think this is a good suggestion to add an explanation for that on the install web page. Would be great if you can contribute this!

**Comment by lupesko** [comment]
@aaronmarkham code change looks good, but since this involves UI updates, would be great if you have a host that runs the code to share. Thanks!

**Comment by TaoLv** [comment]
Thanks for your clarification, @lupesko. I read the message about MKL-DNN GA from here: https://cwiki.apache.org/confluence/display/MXNET/Apache+MXNet+%28incubating%29+1.3.0+Release+Status
I think this decision was disscussed on dev@ and can reflect the status of MKL-DNN backend as well as those effort from the community.

Regarding the doc change, can you kindly point out which source file maps to the install web page?

**Comment by aaronmarkham** [comment]
@lupesko - I added preview links to the description. The one thing that isn't showing is the pip table. I could add a new image and change the links to point to that if we want to see the real preview of that too...

**Comment by lupesko** [comment]
Thanks @aaronmarkham - looks good.
I'm wondering if it may be desired to replace/refresh the "Introducing the Scala Inference API" box from 1.2 with something new released with MXNet 1.3.0? Options include Clojure API, ONNX export, TensorRT. WDYT?

**Comment by aaronmarkham** [comment]
@lupesko what if we point to the medium post and mention all three...

**Comment by Roshrini** [comment]
Is this PR ready to go now?

**Comment by aaronmarkham** [comment]
@Roshrini - yes, the latest preview is up with new news: http://34.201.8.176/versions/1.3.0_release/

**Pull request merged**
