### PR TITLE
Fix R GPU flaky test

### PR DESCRIPTION
**Pull request by ankkhedia**
## Description ##
This PR fixes the flakiness in R GPU test seen in CI.
The code-cov for R packages use json file created while running CPU and GPU tests.  Since both the tests run in parallel, there is contention for the file which leads to test failures sometimes. This PR fixes contention issue.

The failure can be seen in the following line from 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13170/9/pipeline/
```
Rscript -e 'res<-covr:::package_coverage("R-package");fileConn<-file("r-package_coverage.json");writeLines(covr:::to_codecov(res), fileConn);close(fileConn)'
```
Error: Failure in `/tmp/RtmpNVFcdR/R_LIBS94a78c10d14/mxnet-commands.Rout.fail`
which seems to be while writing to the file.
This also happens only for GPU tests and not CPU tests.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
This PR changes the filename for both runs so that there is no resource contention.
Also, the coverage remains same so codecov doesn't get affected by the change.

### CODE REVIEW

**Comment by ankkhedia** [comment]
@anirudhacharya

**Comment by ankkhedia** [comment]
added.

**Comment by kalyc** [comment]
As per your PR description, this should also be resolved right? https://github.com/apache/incubator-mxnet/issues/13274 with the fix?

**Comment by ankkhedia** [comment]
@kalyc The above issue is different. This is fix for GPU failures happening here
 http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13170/9/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13194/3/pipeline

**Comment by kalyc** [comment]
You have mentioned that there is a contention of files - "Since both the tests run in parallel, there is contention for the file which leads to test failures sometimes."

**Comment by ankkhedia** [comment]
@kalyc both the tests write on a file r-package_coverage.json. If one of the tests is already holding on the file, the other test will not able to get write access to that file and it will throw error. This is what I meant by resource contention.

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
