### PR TITLE
[MXNET-431] Get physical cores

### PR DESCRIPTION
**Pull request by azai91**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by anirudh2290** [comment]
Do we need to include all these files ? Can we pull out the code required for `cpuinfo_initialize` and `cpuinfo_get_cores_count`.

**Comment by piiswrong** [comment]
Another route is to include cpuinfo as a submodule

**Comment by pengzhao-intel** [comment]
Do you plan to add the KMP_AFFILITY setting in this PR?

**Comment by cjolivier01** [comment]
@pengzhao-intel  Does Intel OMP look at the KMP environment variables after startup, or do you have to make an API call?

**Comment by pengzhao-intel** [comment]
@cjolivier01 I think both approaches are works for OMP.

**Comment by szha** [comment]
@azai91 could you please resolve conflicts? Thanks.

**Comment by eric-haibin-lin** [comment]
looks like build test didnt pass

**Comment by lupesko** [comment]
@azai91 looks like CI tests aren't passing - can you take a look?

**Comment by lupesko** [comment]
@azai91 - bounce...

**Comment by azai91** [comment]
This pr is contingent on making cmake our default build system which it isn't. Will close this pr until cmake migration occurs.

**Comment by azai91** [comment]
This pr is contingent on making cmake our default build system which it isn't. Will close this pr until cmake migration occurs.

**Pull request closed without merging**
