### PR TITLE
[MXNET-413] Fixing the broken links - Week of 5/7

### PR DESCRIPTION
**Pull request by kpmurali**
## Description ##
Fixing the second set of broken links in the MXNet site.

### Changes ###
- [ x ] Fixing the broken link in the install download page
- [ x ] Fixing the scala-packages links

### CODE REVIEW

**Comment by szha** [comment]
Triggered build again. @anirudh2290 @aaronmarkham should 1.2.0 be listed too?

**Comment by aaronmarkham** [comment]
Yes, may as well add it now. @kpmurali can you add 1.2.0 to the downloads page and resubmit?

**Comment by kpmurali** [comment]
@aaronmarkham  Just to confirm, you mean the docs/install/download.html file right?

**Comment by anirudh2290** [comment]
@szha good point. @kpmurali can you please add the source files from here: https://github.com/apache/incubator-mxnet/releases/tag/1.2.0. Note that we don't have md5 hashes anymore, since they are deprecated for apache releases.

**Comment by aaronmarkham** [comment]
@kpmurali Yes, download.html.

**Comment by kpmurali** [comment]
Then should I remove the MD5 download column from all the previous versions in the download page? 
http://mxnet.incubator.apache.org/install/download.html

**Comment by kpmurali** [comment]
Also, would this mean the current 1.1.0 links have to be made to point to archive links like the other older versions?

**Comment by anirudh2290** [comment]
@kpmurali since we have sha512 i think its okay to remove md5 column. And you can move 1.1.0 to the archive link.

**Pull request merged**
