### PR TITLE
[Website] Add DJL to ecosystem

### PR DESCRIPTION
**Pull request by Zha0q1**

### CODE REVIEW

**Comment by sandeep-krishnamurthy** [comment]
Thanks, can you please put a snapshot of the website rendering with this image?

**Comment by Zha0q1** [comment]
Should look something like this : )
Screen Shot 2021-02-28 at 8 41 12 PM

**Comment by Zha0q1** [comment]
@sandeep-krishnamurthy

**Review by access2rohit — APPROVED** [review]
LGTM

**Pull request merged**
