### PR TITLE
Remove inline keyword from methods we want to generate code for.

### PR DESCRIPTION
**Pull request by craftit**
When linking to a larger c++ project we want to generate code for all the methods in the .hpp files, the inline keyword prevents this and causes undefined symbols. The compiler normally uses it's own heuristics for inlining code, so this is unlikely to have any impact on the code generated.

### CODE REVIEW

**Comment by piiswrong** [comment]
I doubt this will compile without the inline. This will cause multiple definitions.

@lx75249 Why are definitions in header file?

**Comment by lx75249** [comment]
@piiswrong It was intended to be a header-only lightweight package.

@craftit If we want to reuse the generated binaries, maybe we need to refactor the whole project to seperate declarations in header files and defintions in source files.

**Comment by craftit** [comment]
The definitions are in the .hpp,  the normal head files have extension .hh the files are kept separate to avoid creating a library for the c++ client code.   The current code works because all the examples are compiled with a single file per executable.   I have tested this change and need it to link cpp-package into a larger project.

**Comment by craftit** [comment]
Essentially the hpp files could be renamed .cpp files.  To use this library I just include all the .hpp header files into a single source file in my project.   In many ways that works quite well.

**Pull request closed without merging**
