### PR TITLE
[master] New version of clang-format

### PR DESCRIPTION
**Pull request by mozga-intel**
## Description ##
The clang-format tool is bumped up to v11.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [miscellaneous,unix-cpu, unix-gpu ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu ]

**Comment by Tolkien1985** [comment]
> @mxnet-bot run ci [miscellaneous, unix-gpu ]

**Pull request closed without merging**
