### PR TITLE
[TEST] upgrade dmlc-core

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
Upgrade the dmlc-core dependency to the latest commit. 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
- relevant fixes for MXNet: https://github.com/dmlc/dmlc-core/pull/511 https://github.com/dmlc/dmlc-core/commit/8afbca699d9d9b720024e32d47a49f29b59c4c9e thanks to @hcho3 
- required by #14173

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
Looks like the CMakeFile in dmlc-core has been changed in multiple PRs that causes amalgamation to break:
- https://github.com/dmlc/dmlc-core/pull/476" error: sys/endian.h: No such file or directory"
- https://github.com/dmlc/dmlc-core/pull/495 "error: 'backtrace_symbols' was not declared in this scope" 
- https://github.com/dmlc/dmlc-core/pull/470   error: "Shlwapi.h: No such file or directory"

**Comment by pinaraws** [comment]
@mxnet-label-bot add[pr-awaiting-merge]

**Comment by hcho3** [comment]
@eric-haibin-lin Platform-specific headers such as `Shlwapi.h` should have been wrapped with platform-specific macros (`_WIN32` etc). Does amalgamation not honor platform-specific macros?

**Comment by hcho3** [comment]
@eric-haibin-lin This patch should fix amalgamation:

```patch
diff --git a/amalgamation/amalgamation.py b/amalgamation/amalgamation.py
index 0a4be02b8..edf01941d 100644
--- a/amalgamation/amalgamation.py
+++ b/amalgamation/amalgamation.py
@@ -46,7 +46,13 @@ if platform.system() != 'Darwin':
 if platform.system() != 'Windows':
     blacklist.append('windows.h')
     blacklist.append('process.h')
+    blacklist.append('Shlwapi.h')

+if platform.system() == 'Windows':
+    blacklist.append('unistd.h')
+
+if 'freebsd' not in sys.platform:
+    blacklist.append('sys/endian.h')

 def get_sources(def_file):
     sources = []
@@ -94,6 +100,7 @@ def find_source(name, start, stage):

 re1 = re.compile('<([./a-zA-Z0-9_-]*)>')
 re2 = re.compile('"([./a-zA-Z0-9_-]*)"')
+re3 = re.compile('DMLC_EXECINFO_H')

 sysheaders = []
 history = set([])
@@ -129,6 +136,9 @@ def expand(x, pending, stage):
     with open(x, 'rb') as x_h:
         for line in x_h.readlines():
             uline = line.decode('utf-8')
+            if '#define DMLC_LOG_STACK_TRACE 1' in uline.strip():
+                # Do not enable stacktrace logging
+                continue
             if uline.find('#include') < 0:
                 out.write(line)
                 continue
@@ -138,10 +148,15 @@ def expand(x, pending, stage):
             m = re1.search(uline)
             if not m:
                 m = re2.search(uline)
-            if not m:
-                print(uline + ' not found')
-                continue
-            path = m.groups()[0]
+            if m:
+                path = m.groups()[0]
+            else:
+                m = re3.search(uline)
+                if m:
+                    path = 'execinfo.h'
+                else:
+                    print(uline + ' not found')
+                    continue
             h = path.strip('./') if "../3rdparty/" not in path else path
             if h.endswith('complex.h') and x.endswith('openblas_config.h'):
                 source = ''
```

**Comment by eric-haibin-lin** [comment]
Amalgamation test passed

**Comment by hcho3** [comment]
Somehow upgrading dmlc-core breaks Julia?

**Pull request merged**
