### PR TITLE
[DOC] Add Flower to MXNet ecosystem

### PR DESCRIPTION
**Pull request by mariaboerner1987**
## Description ##
Add Flower description and logo to ecosystem.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Add Flower to ecosystem (title, text, icon, link)
- [x] Add image ti assets/img/
- [x] Add name to contributor list

### Comments ###
- Use Flower to run MXNet federated

### CODE REVIEW

**Comment by mariaboerner1987** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-gpu]

**Comment by mariaboerner1987** [comment]
@aaronmarkham and @szha 
The CI jobs are failing. Is there any action required from my side?

**Review by szha — APPROVED** [review]
Thanks and welcome to the community!

**Comment by szha** [comment]
We will merge the change once We resolve the CI issue

**Comment by szha** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-cpu]

**Comment by szha** [comment]
@mxnet-bot run ci [centos-cpu, unix-cpu]

**Comment by tanertopal** [comment]
@mxnet-bot run ci [unix-cpu]

**Pull request merged**
