### PR TITLE
[CI] Disable builds based on ubuntu 14.04 as Ubuntu 14 is EOL and the…

### PR DESCRIPTION
**Pull request by larroy**
… container can't be built right now.

### CODE REVIEW

**Comment by larroy** [comment]
@mseth10 @samskalicky @lanking520

**Comment by larroy** [comment]
See errors here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/master/1339/pipeline

**Comment by leezu** [comment]
Do you plan to re-enable this test based on Ubuntu 16.04 shortly after?

**Comment by leezu** [comment]
If we want to continue using 14.04, we may need to sign up for https://ubuntu.com/esm ?

**Comment by leezu** [comment]
@larroy actually it is sufficient to disable the requirement for "ci/jenkins/mxnet-validation/unix-cpu" to pass on the Github side. Then it doesn't matter if the test fails or passes.
It's impossible to merge this PR anyways before disabling "ci/jenkins/mxnet-validation/unix-cpu" requirement

**Comment by marcoabreu** [comment]
Instead of turning them off, we can also just adjust the sources file which tells Apt where to grab the packages (replace live with archive repo). It's normal that the main distribution servers get turned off once something goes into EOL. But since we still rely on 1404 for binary distribution, we need to keep checking or update.

See https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release for instructions.

**Comment by leezu** [comment]
@larroy how to move forward with this? All PR's are currently blocked by this issue.

**Comment by larroy** [comment]
@leezu we are working on this.

**Comment by larroy** [comment]
@marcoabreu feel free to open a PR.  

@marcoabreu cache refresh is failing again, and you blocked a previous PR that helped me diagnose (the one about output) again it's me having to fix this. 

There's 3 jobs failing now on master which prevent PRs from being merged, unix_gpu centos and cache refresh which is also impacting builds.

**Comment by larroy** [comment]
Trying to repro this in EC2 and seems to run, so I might have to get the CI environment AMI to reproduce. Weird.

**Pull request closed without merging**
