### PR TITLE
updating MXNet version to 1.6.0 in base.h for C APIs

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
updating MXNet version to 1.6.0 in base.h for C APIs
https://github.com/apache/incubator-mxnet/issues/16904

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

**Comment by access2rohit** [comment]
@lanking520

**Comment by access2rohit** [comment]
> This is a key problem with the publish, we should bump it once we make the release

yes

**Comment by access2rohit** [comment]
@ptrendx

**Comment by samskalicky** [comment]
@access2rohit shouldnt we be changing master to 1.7?

**Comment by access2rohit** [comment]
> ?

@samskalicky Sure! I think we should first bump master to 1.6 and then again to 1.7. Does that makes sense ?

**Comment by ptrendx** [comment]
@access2rohit Since the 1.6.x branch is already diverged from master, there is no need to do this 1.6 step I think - we should just go directly to 1.7 (which I believe requires changes in more places).

**Comment by access2rohit** [comment]
> @access2rohit Since the 1.6.x branch is already diverged from master, there is no need to do this 1.6 step I think - we should just go directly to 1.7 (which I believe requires changes in more places).

Yes it requires changes in more places. IMO we should follow proper progression by moving from 1.5->1.6->1.7 to keep the change history in master clean and consistent. 
@ptrendx do you agree ?

**Pull request merged**
