### PR TITLE
Update website, README and NEWS with 1.6.0

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Update website, README and NEWS with 1.6.0 links.

### CODE REVIEW

**Comment by leezu** [comment]
@szha what is the status / plan for versioned website?
Currently we don't have a website for MXNet 1.6

**Comment by astonzhang** [comment]
@ptrendx It seems that the 1.6.0 does not work on MacOS. I `pip install mxnet==1.6.0` on my macOS Mojave, then `import mxnet` will show errors. My friends also encounter the same problem on their macOS. Can you double check it on your side?

Details of error:

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/astonz/.local/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/Users/astonz/.local/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/Users/astonz/.local/lib/python3.7/site-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/Users/astonz/.local/lib/python3.7/site-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/Users/astonz/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/astonz/.local/lib/python3.7/site-packages/mxnet/libmxnet.so, 6): no suitable image found.  Did find:
	/Users/astonz/.local/lib/python3.7/site-packages/mxnet/libmxnet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/astonz/.local/lib/python3.7/site-packages/mxnet/libmxnet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
>>> exit()
```

**Comment by ptrendx** [comment]
Ok, I believe it should be ready for review.

I updated:
 - README, 
 - NEWS.md (including fixing multiple not working links there)
 - Getting started webpage

@szha @aaronmarkham @ThomasDelteil @roywei Please review

**Comment by ptrendx** [comment]
I was wondering about this 1-5-0 too, but (at least on chrome, I did not check other browsers) it seems to work ok.

**Comment by ptrendx** [comment]
Actually I see now what you are talking about. Yes, that needs to be changed.

**Comment by ptrendx** [comment]
> Get Started for Windows is not covered in this PR. So users visiting https://mxnet.apache.org/get_started?version=v1.6.0&platform=windows&language=python&processor=gpu&environ=pip& would see empty content.
> 
> Could you include a paragraph about pip package for 1.6.0 not being available yet? That will be better than showing blank instructions.

What is the timeline for getting Windows pip packages ready?

**Comment by leezu** [comment]
> What is the timeline for getting Windows pip packages ready?

They need to be built manually. @yajiedesign was helping with that.
@yajiedesign do you have an ETA?

**Comment by leezu** [comment]
Retriggered windows gpu pipeline

**Comment by ptrendx** [comment]
Ok, since we did not hear from @yajiedesign about the ETA of Windows pip wheels yet, I will go ahead and change the Windows text to say that those are not yet available, according to suggestion from @leezu.

**Comment by ptrendx** [comment]
@leezu Could you review again?

**Comment by ptrendx** [comment]
@leezu Do you know when will the website refresh? I want to send the announcement email once that happens.

**Comment by leezu** [comment]
I haven't verified it, but my assumption is that you can check the status of the jenkins jobs at https://github.com/apache/incubator-mxnet/commits/master
One of them should publish the website?

**Comment by leezu** [comment]
Seems http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwebsite/detail/master/1697/pipeline builds the website

**Pull request merged**
