### PR TITLE
fixed the tag_list ordering to enable right ordered add link mapping

### PR DESCRIPTION
**Pull request by thinksanky**
## Description ##
During refactoring the build_doc.sh, I had swapped the order in the code which caused an issue of having version links added for wrong n-1 versions.
Fixed the order

### CODE REVIEW

**Comment by thinksanky** [comment]
Locally mac build is not completing, as the system is churning with high CPU when it builds. I could get much further, after doing
* make clean
* git submodule update
* make docs
Can someone please checkout my branch and build. The changes in this PR is not related to any make docs at all!

**Comment by thinksanky** [comment]
After merging this run the build-site job again.
- Currently the build job is failing during compilation. I am not sure why this should fail as this is nothing different from build 91 which successfully ran. The branch used is still 1.1.0

**Comment by thinksanky** [comment]
Got the build working.
updated the script to use 
git submodule update --init --recursive

**Comment by CodingCat** [comment]
Hi, the community has passed to vote about associating the code changes with JIRA (https://lists.apache.org/thread.html/ab22cf0e35f1bce2c3bf3bec2bc5b85a9583a3fe7fd56ba1bbade55f@%3Cdev.mxnet.apache.org%3E)

We have updated the guidelines for contributors in https://cwiki.apache.org/confluence/display/MXNET/Development+Process, please ensure that you have created a JIRA at https://issues.apache.org/jira/projects/MXNET/issues/ to describe your work in this pull request and include the JIRA title in your PR as [MXNET-xxxx] your title where MXNET-xxxx is the JIRA id

Thanks!

**Comment by szha** [comment]
looks like a duplicate of #10099

**Pull request closed without merging**
