### PR TITLE
[API] clean up gluon contrib

### PR DESCRIPTION
**Pull request by szha**
## Description ##
clean up gluon contrib

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] add mx.np.random.seed
- [x] remove gluon.contrib.text
- [x] remove mx.contrib.autograd
- [x] promote IntervalSampler, SyncBatchNorm, Concurrent as Concatenate, HybridConcurrent as HybridConcatenate, Identity, DeformableConvolution, ModulatedDeformableConvolution, PixelShuffle1D, PixelShuffle2D, PixelShuffle3D, VariationalDropoutCell, LSTMPCell, Conv1DRNNCell, Conv2DRNNCell, Conv3DRNNCell, Conv1DLSTMCell, Conv2DLSTMCell, Conv3DLSTMCell, Conv1DGRUCell, Conv2DGRUCell, Conv3DGRUCell
- [ ] numpy equivalent tests

## Comments ##
- cc @zhreshold for cv block changes, @sxjscience for convrnn changes

### CODE REVIEW

**Comment by szha** [comment]
ready for review. rnn cell may need some design change and I intend to submit it separately.

**Comment by sxjscience** [comment]
Do we need to test the RNNCells under mx.np? (We may make another PR for this purpose since it may make the PR be too large)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by szha** [comment]
rnn cells haven't been refactored to use np yet. will follow that up in a separate PR.

**Review by sxjscience — APPROVED** [review]
LGTM. It promotes the layers inside contrib to main API.

**Review by zhreshold — APPROVED** [review]
Looks good, thanks for putting all together!

**Pull request merged**
