### PR TITLE
Reduce overhead in sg_onednn_fully_connected for floats

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
Subgraph fully connected implementation introduces overhead in float execution path - this change removes this overhead:

Benchmark on GPT-2 sample generation from gluon-nlp scripts on AWS.c6i.x12large
image

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Review by bartekkuncer — APPROVED** [review]
LGTM

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge, miscellaneous, unix-cpu, windows-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by anko-intel — APPROVED** [review]

**Pull request merged**
