### PR TITLE
[v1.4.x] export exception handling APIs in MXNet

### PR DESCRIPTION
**Pull request by apeforest**
## Description ##
Export this header file to catch exceptions thrown in MXNet elegantly in 3rd party application that uses MXNet libraries. One use case of this is MXNet integration in Horovod.

### Essentials ###
Please feel free to remove inapplicable items for your PR.eated (except PRs with tiny changes)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- [X] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Exporting header file c_api_error.h

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by yuxihu** [comment]
LGTM

**Comment by apeforest** [comment]
@eric-haibin-lin @anirudh2290 could you please help to merge this PR before the 1.4.0 code freeze? thanks!

**Comment by apeforest** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
