### PR TITLE
make slice operator 20x faster on GPU

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
The current slice kernel is slow on GPU as each thread in the warp accesses different memory address in the output. 

@reminisce @haojin2 @safrooze 
 
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

```
import mxnet as mx
import time

a = mx.nd.ones((512, 8192), ctx=mx.gpu())
for i in range(10):
    b = a.slice(begin=(None, 4), end=(None, None))

mx.nd.waitall()
t0 = time.time()
for i in range(1000):
    b = a.slice(begin=(None, 4), end=(None, None))

mx.nd.waitall()
t1 = time.time()
print(t1 - t0)
```

Time on K80
* before: 11.9892659187 (s)
* after: 0.497007131577 (s)

### CODE REVIEW

**Comment by BiranLi** [comment]
No acceleration on the V100.

**Comment by BiranLi** [comment]
@safrooze I have tested in V100 between mxnet_0.12 and mxnet_1.3. 
before: 0.09s
after:0.08s

**Comment by eric-haibin-lin** [comment]
@BiranLi i'm using this test code:
```
import mxnet as mx
import time

a = mx.nd.ones((512, 8192), ctx=mx.gpu())
for i in range(10):
    b = a.slice(begin=(None, 4), end=(None, None))

mx.nd.waitall()
t0 = time.time()
for i in range(1000):
    b = a.slice(begin=(None, 4), end=(None, None))

mx.nd.waitall()
t1 = time.time()
print(t1 - t0)

```
What did you use? Are you on slack?

**Comment by eric-haibin-lin** [comment]
Oh I didn't compare with mxnet 0.12. Maybe it was a regression between 0.12 and 1.2

**Pull request merged**
