### PR TITLE
[v1.9.x] Export attributes of transformer operators

### PR DESCRIPTION
**Pull request by PawelGlomski-Intel**
Backport of #20555

### CODE REVIEW

**Comment by PawelGlomski-Intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [website]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [website]

**Review by bgawrych — APPROVED** [review]
LGTM

**Comment by bgawrych** [comment]
@josephevans Can it be merged to 1.9?

**Pull request merged**
