### PR TITLE
stable sum

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by szha** [comment]
Do you plan on using Kahan's summation on regular sum too? Our mean is using that as the reduce function.

**Comment by piiswrong** [comment]
Which file/function are you talking about?

**Comment by szha** [comment]
https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/broadcast_reduce_op_value.cc#L81-L88

**Comment by szha** [comment]
I didn't realize that it was already added to mshadow. never mind https://github.com/dmlc/mshadow/blame/master/mshadow/base.h#L672-L685

**Comment by szha** [comment]
Looks like square sum needs updating too:

https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/square_sum-inl.h#L127-L130

https://github.com/apache/incubator-mxnet/blob/master/src/operator/tensor/square_sum-inl.h#L148-L151

**Comment by eric-haibin-lin** [comment]
@anirudh2290 make sure you use the stable sum to implement sum(csr)

**Pull request merged**
