### PR TITLE
MKLDNN fallback when not recording gradients and calling backwards

### PR DESCRIPTION
**Pull request by azai91**
## Description ##
PR to address (https://github.com/apache/incubator-mxnet/issues/10994). There is a case where users may want to run the backwards pass but not record any gradients (https://mxnet.incubator.apache.org/api/python/autograd/autograd.html#mxnet.autograd.record - this should be addressed in a later PR as it does not make sense). MKLDNN does not handle this case and instead we will fallback.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by azai91** [comment]
This PR is waiting merge of https://github.com/apache/incubator-mxnet/pull/12019

**Comment by stu1130** [comment]
@azai91 #12019 was merged. Is it still WIP?

**Comment by azai91** [comment]
still working in progress. working with customer on different issue. will fix this next.

**Comment by vandanavk** [comment]
@mxnet-label-bot [pr-work-in-progress]

**Comment by vrakesh** [comment]
@azai91 requesting an update on this PR.

**Comment by Roshrini** [comment]
@azai91 Any update on this PR?

**Comment by ankkhedia** [comment]
@azai91 Thanks for the contribution!
Could you please update this PR?

**Comment by anirudhacharya** [comment]
@azai91 any update on this PR. you could close it and reopen the PR once the changes are ready.

@sandeep-krishnamurthy @anirudh2290

**Comment by stu1130** [comment]
@azai91 could you address the CI failure?

**Comment by vandanavk** [comment]
@mxnet-label-bot add [pr-awaiting-testing]

**Comment by azai91** [comment]
still investigating. this PR goes beyond the the original issue I was addressing.

**Comment by azai91** [comment]
addressed original problem with issuse (https://github.com/apache/incubator-mxnet/issues/10994). However, I discovered another issue and created a new PR to address (https://github.com/apache/incubator-mxnet/issues/13445).

**Comment by roywei** [comment]
@azai91 Thanks for taking the time to dive into the issue, could you resolve the conflict and trigger CI if still working on this?

**Comment by sandeep-krishnamurthy** [comment]
@azai91 - can you please rebase and fix CI issues? @pengzhao-intel - You may be interested in this PR?

**Comment by pengzhao-intel** [comment]
Actually, this is a system-level issue that how do we handle the situation the backward is called with the `is_train=False`. I think it doesn't can be done by the simple bypass. 

We will have the offline discussion first and back later @TaoLv .

**Comment by Roshrini** [comment]
@azai91 Can you please rebase this PR?

**Comment by stu1130** [comment]
@azai91 ping again!

**Comment by pengzhao-intel** [comment]
IMO, this usage and default behavior is not clear even in the original path.
@azai91 @stu1130 could you help get a clear picture first and then we can discuss how to handle it by MKLDNN backend?

**Comment by sandeep-krishnamurthy** [comment]
@apeforest - @TaoLv raised a good question here. Can you please help us answer -

>> What's the expectation in mxnet if backward is called with is_train=false? What's the grad_output >> for backward function and if needed, what's the workspace for backward function?

**Comment by pengzhao-intel** [comment]
ping, any update @azai91

**Comment by abhinavs95** [comment]
@azai91 Could you please rebase and fix the CI issues?

**Comment by abhinavs95** [comment]
@mxnet-label-bot update [pr-awaiting-response, pr-work-in-progress]

**Pull request closed without merging**
