### PR TITLE
Updated recommenders example

### PR DESCRIPTION
**Pull request by ThomasDelteil**
## Description ##

Updated recommender system example:
- Merged notebook 1 and 2 into a single one, simpler to follow
- Removed negative sampling notebook, pointing to GluonNLP implementation that contains ImportanceSampling, NoiseContractiveLoss and NegativeSampling.
- Removed manual sparse implementation, replaced with embedding layers
- Updated DSSM model with modernized Gluon version
- Replaced BagOfWordRandomProjection with Gluon version, though it really should only be used in very specific cases, added warning about that in the notebook and used embedding + lstm instead.

### CODE REVIEW

**Comment by ankkhedia** [comment]
@ThomasDelteil Thanks for the contribution
@mxnet-label-bot [ pr-awaiting-testing, Example ]

**Comment by ankkhedia** [comment]
@aaronmarkham @thomelane @safrooze Could you please take a look ?

**Comment by ThomasDelteil** [comment]
@Ishitori thanks, looks like my last minute changes broke everything :)
Doing one last full run and will push the changes

**Comment by ThomasDelteil** [comment]
@Ishitori updated

**Comment by Ishitori** [comment]
Yes, not notebooks work fine. LGTM!

**Comment by ThomasDelteil** [comment]
@indhub can you please merge this? Thanks!

**Comment by kalyc** [comment]
@ThomasDelteil thanks for the contribution! Could you re-trigger CI with an empty commit?

**Comment by ThomasDelteil** [comment]
@indhub @nswamy @sandeep-krishnamurthy can you please merge this? Thanks!

**Comment by kalyc** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
