### PR TITLE
Resolve minor docs issues

### PR DESCRIPTION
**Pull request by ekdnam**
## Description ##
(Brief description on what this PR is about)
solves: https://github.com/apache/incubator-mxnet/issues/18988, https://github.com/apache/incubator-mxnet/issues/18990, https://github.com/apache/incubator-mxnet/issues/18999, https://github.com/apache/incubator-mxnet/issues/19000, https://github.com/apache/incubator-mxnet/issues/19001
### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ekdnam** [comment]
@mxnet-bot run ci [all]

**Comment by szha** [comment]
@ekdnam thanks for the fixes! Looks like your branch contained the changes from last PR that hasn't been rebased yet. In the future, for branch management, we recommend using separate feature branches for each PR so that it's easier to manage and sync with upstream (see https://github.com/apache/incubator-mxnet/blob/master/docs/static_site/src/pages/community/git_howto.md#how-to-manage-branches)

**Comment by ekdnam** [comment]
Okay will do so from the next time

**Comment by szha** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by DNXie** [comment]
Hi, thank you for fixing this. However, it seems that in [this commit](https://github.com/apache/incubator-mxnet/pull/19062/commits/68b185c2219b74ca558776bc50434f1d48c6af83#diff-1ee0c1604acabe9a5beed1cca829127ef007306cc30a0847550acc8056ecdce1), only the document of  `mxnet.ndarray.contrib.isnan` is fixed, but not `mxnet.ndarray.contrib.isfinite` and `mxnet.ndarray.contrib.isinf`. Would you mind taking a look? Thank you!

**Pull request merged**
