### PR TITLE
Revert "[MXNET-696] Define cmp() in Python 3 for line 222"

### PR DESCRIPTION
**Pull request by marcoabreu**
Reverts apache/incubator-mxnet#12191

We reverted the underlying change and thus this PR is not necessary (and is no longer compatible)

### CODE REVIEW

**Comment by marcoabreu** [comment]
@piyushghai @cclaus fyi

**Comment by haojin2** [comment]
Just wonder why are you also reverting a bunch of other un-related changes?

**Comment by marcoabreu** [comment]
I just pressed the revert but, I don't know what GitHub is doing there ._.

Have a look at the diff, it looks good to me

**Comment by marcoabreu** [comment]
I'm only on my phone right now, so I can't make a revert with the command line. In the end, the commits will be squashed so it should not make much of a difference as long as the diff is good

**Comment by haojin2** [comment]
@marcoabreu Could you do a double-check please? Cause one of the commits on the list shows that it's reverting an important fix for the next release.

**Comment by piyushghai** [comment]
The file diff looks good as it was the only change in that PR. 
Not sure, why the other commits are showing up here.

**Comment by piyushghai** [comment]
Check PR #12231 . 
That includes just one commit required. 
@marcoabreu Feel free to close this one.

**Comment by marcoabreu** [comment]
Thank you!

**Pull request closed without merging**
