### PR TITLE
Correct Inception Reference for Pertained Model

### PR DESCRIPTION
**Pull request by lou-k**
## Description ##
Update Model Zoo Documentation

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Remove 'v3' from reference documentation
- [x] Update research bias link

## Comments ##
I noticed that the symbols and parameters in the model zoo are in fact from https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/symbols/inception-bn.py, which is not inception v3. It is inception + batch normalization. 

In this commit, I update the documentation and link to the correct research basis.

### CODE REVIEW

**Comment by stu1130** [comment]
@mxnet-label-bot add [pr-awaiting-review]
Thanks for your contribution @lou-k

**Comment by vandanavk** [comment]
@aaronmarkham for review

@lou-k could you check the failing CI?

**Comment by lou-k** [comment]
@vandanavk it looks like the CI check was canceled:

```
ERROR: Queue task was cancelled
Finished: FAILURE
```

I rebased and push to trigger a new build.

**Comment by lou-k** [comment]
@vandanavk CI passed. thanks for your eyes on this!

**Comment by vandanavk** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
