### PR TITLE
Restore missing FAQ tutorial from website migration 

### PR DESCRIPTION
**Pull request by ys2843**
As check fails, I am going to close this PR and create a new one 
## Description ##
According to Lin Yuan,  https://github.com/apache/incubator-mxnet/pull/15517 was deleted from mxnet website and faq during the website migration. Restored this file in this PR.

### Essentials ###
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Restore missing tutorial `Use TensorInspector to Help Debug Operators` of FAQ
- [x] First PR - add my name to `CONTRIBUTORS.md`

### Comments
+ Preview (temporarily broke, fixing): http://ec2-3-14-28-87.us-east-2.compute.amazonaws.com/ 
+ Should have checkout to separate branch apart from master, will do in future PRs

### CODE REVIEW

**Comment by ys2843** [comment]
@mxnet-bot run ci [website, windows-gpu]

**Comment by ys2843** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [Website]

**Comment by connorgoggins** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by ys2843** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request closed without merging**
