### PR TITLE
Fix test_subgraph skipif

### PR DESCRIPTION
**Pull request by leezu**
Fix a typo in #18252

### CODE REVIEW

**Comment by mseth10** [comment]
@mxnet-bot run ci [miscellaneous, centos-gpu, unix-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [miscellaneous, centos-gpu, unix-gpu]

**Comment by leezu** [comment]
@mxnet-bot run ci [miscellaneous]

**Comment by mseth10** [comment]
@leezu can we merge this?

**Pull request merged**
