### PR TITLE
Add hinge loss for svm

### PR DESCRIPTION
**Pull request by yuruofeifei**
Added hinge loss for SVM:

svm_loss

#6466

### CODE REVIEW

**Comment by piiswrong** [comment]
Let's call it HingeLoss

**Comment by eric-haibin-lin** [comment]
@yuruofeifei any update? could you sync with most recent version of master? Could you add a test case for this?

**Comment by yuruofeifei** [comment]
ok, haibin. I will work on it next Monday.

**Comment by piiswrong** [comment]
closing due to inactive. Please reopen after addressing comments

**Pull request closed without merging**
