### PR TITLE
[WIP] Fix precision issue of test case test_rnnrelu_bidirectional and test_rnnrelu_sym

### PR DESCRIPTION
**Pull request by lihaofd**
## Description ##
In this PR, it fixed precision issue of test case #11410 test_rnnrelu_bidirectional and test_rnnrelu_sym. @pengzhao-intel, @TaoLv

### New features ###
- Fixed issue of precision issue of test case #11410 test_rnnrelu_bidirectional and test_rnnrelu_sym.  Sometimes, the data comparison will fail because of tolerance of precision, like 0.043388 and 0.04405. In our testing environment, the biggest testing result deviation is around difference between 0.027... and 0.037... sometimes. Adjust the tolerance to fix the issue. 

## Checklist ##
 - [X] Passed code style checking (make lint).
 - [X] All changes have test coverage.
 - [ ] Code is well-documented.

### CODE REVIEW

**Comment by vandanavk** [comment]
@lihaofd any reason was closing this PR?

**Comment by lihaofd** [comment]
@vandanavk. We are still looking into the issue and check if there is other way to fix it.  @TaoLv @pengzhao-intel

**Comment by vandanavk** [comment]
Any pointers so far? 

The issue is always reproducible with seed 272273578, FusedRNN with 2 layers and bidirectional=True. I tried out a few experiments - the issue doesn't occur with 3 layers in test_rnnrelu_bidirectional or when the FusedRNN is unfused.

**Comment by vandanavk** [comment]
@lihaofd do you think we could temporarily submit this PR and in parallel, debug to find the fix?

**Comment by pengzhao-intel** [comment]
@vandanavk, agree, we can submit this PR first and debug in the same time.

@lihaofd  please reopen this PR.

**Comment by lihaofd** [comment]
The PR can't be reopened as my local branch has been recreated. Submit new one on https://github.com/apache/incubator-mxnet/pull/12099. Thanks!

**Pull request closed without merging**
