### PR TITLE
Disable ENABLE_TESTCOVERAGE on CentOS 7 build

### PR DESCRIPTION
**Pull request by leezu**
Causes significant slowdown in connection with the system (devtoolset) provided OpenMP libraries.
https://github.com/apache/incubator-mxnet/pull/17559 starts pulling in the system OpenMP in addition to the `3rdparty/openmp` causing the slowdown to materialize after the merge of https://github.com/apache/incubator-mxnet/pull/17559.

Fixes https://github.com/apache/incubator-mxnet/issues/19502

Let's still fix the issue of intgemm pulling a second openmp @kpuatamazon

With this PR

```
[2020-11-10T00:14:44.881Z] ============================= slowest 50 durations =============================

[2020-11-10T00:14:44.881Z] 467.92s call     tests/python/unittest/test_random.py::test_random

[2020-11-10T00:14:44.881Z] 74.58s call     tests/python/unittest/test_operator.py::test_image_normalize

[2020-11-10T00:14:44.881Z] 74.46s call     tests/python/unittest/test_random.py::test_randint_generator

[2020-11-10T00:14:44.881Z] 53.77s call     tests/python/unittest/test_random.py::test_shuffle

[2020-11-10T00:14:44.881Z] 29.70s call     tests/python/unittest/test_gluon.py::test_slice_pooling2d_slice_pooling2d

[2020-11-10T00:14:44.881Z] 19.73s call     tests/python/unittest/test_random.py::test_dirichlet

[2020-11-10T00:14:44.881Z] 15.36s call     tests/python/unittest/test_sparse_operator.py::test_sparse_mathematical_core

[2020-11-10T00:14:44.881Z] 10.90s call     tests/python/unittest/test_gluon.py::test_slice_pooling2d

[2020-11-10T00:14:44.881Z] 10.63s call     tests/python/unittest/test_operator.py::test_big_transpose

[2020-11-10T00:14:44.881Z] 10.30s call     tests/python/unittest/test_sparse_operator.py::test_sparse_square_sum

```
Without this PR
```
[2020-11-09T22:46:33.281Z] ============================= slowest 50 durations =============================

[2020-11-09T22:46:33.281Z] 599.70s call     tests/python/unittest/test_gluon.py::test_slice_pooling2d_slice_pooling2d

[2020-11-09T22:46:33.281Z] 246.20s call     tests/python/unittest/test_random.py::test_randint_generator

[2020-11-09T22:46:33.281Z] 219.33s call     tests/python/unittest/test_gluon.py::test_slice_pooling2d

[2020-11-09T22:46:33.281Z] 182.46s call     tests/python/unittest/test_random.py::test_random

[2020-11-09T22:46:33.281Z] 143.63s call     tests/python/unittest/test_sparse_operator.py::test_cast_storage_ex

[2020-11-09T22:46:33.281Z] 125.78s call     tests/python/unittest/test_sparse_operator.py::test_sparse_square_sum

[2020-11-09T22:46:33.281Z] 88.98s call     tests/python/unittest/test_random.py::test_negative_binomial_generator

[2020-11-09T22:46:33.281Z] 69.17s call     tests/python/unittest/test_random.py::test_poisson_generator

[2020-11-09T22:46:33.281Z] 63.23s call     tests/python/unittest/test_gluon.py::test_slice_batchnorm

[2020-11-09T22:46:33.281Z] 62.36s call     tests/python/unittest/test_gluon.py::test_slice_batchnorm_reshape_batchnorm

```

### CODE REVIEW

**Review by mseth10 — APPROVED** [review]
Verified that centos-cpu duration reduces to ~50mins from ~100mins after this commit. Thanks for the fix @leezu

**Comment by leezu** [comment]
@mseth10 any idea about the difference in `tests/python/unittest/test_random.py::test_random`?

**Comment by mseth10** [comment]
Seems to be an outlier, all other tests run faster. Should we re-trigger centos-cpu for a second datapoint?

**Comment by leezu** [comment]
I think we can merge the PR and observe the performance on the master branch.

**Pull request merged**
