### PR TITLE
Fix memory leaks in Gluon

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Previously the _BlockScope keeps references to the parameter ndarrays, preventing memory from being freed if a Block is not used anymore. Among other problems, this causes memory usage to increase constantly in unittests (due to testing different blocks and disposing them at the end of the test) until the garbage collector kicks in (which can be too late and the system can run OOM as the parameter arrays can be large).

### CODE REVIEW

**Comment by leezu** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Comment by sxjscience** [comment]
@Jerryzcn I think this is also related to your previous benchmark.

**Comment by leezu** [comment]
@ciyongch should we backport this to 1.7?

**Comment by ciyongch** [comment]
Hi @leezu , if the issue also appears in 1.7 then please help to backport to 1.7 and 1.x branches and tag me to the new PR, thanks!

**Comment by leezu** [comment]
This issue is present in all versions of Gluon. OK, let's backport the fix.

**Comment by leezu** [comment]
@ciyongch I created the backport PRs

**Comment by ciyongch** [comment]
Thanks @leezu to help backport the PR.

**Comment by apeforest** [comment]
@ChaiBapchya @access2rohit This may also fixed our out-of-memory issue in large tensor nightly test when running them in sequence.

**Pull request merged**
