### PR TITLE
Revert PR 17767 for fixing GPU memory usage regression

### PR DESCRIPTION
**Pull request by rondogency**
Revert PR #17767 for fixing #18280 GPU memory usage regression

Tested locally and observed GPU memory decreasing after reverting

Resolved revert conflict in elemwise_binrary_ops.h and test_operators.py

### CODE REVIEW

**Comment by apeforest** [comment]
@rondogency could you change the description to "... fixes #18280". Only if you use the "fix" or "fixes", it will auto close the issue. Thanks

**Comment by apeforest** [comment]
@ptrendx Are you okay with this revert? Thanks!

**Comment by ptrendx** [comment]
Yes, I'm fine with it, although I would not want this PR to close that issue, as there is discussion happening there on an actual fix.

**Comment by rondogency** [comment]
I agree with @ptrendx that we should not close the issue, also I noticed that this one is picked into 1.7 release, we should revert it also

**Comment by rondogency** [comment]
@mxnet-bot run ci [all]

**Comment by rondogency** [comment]
@mxnet-bot run ci [centos-cpu, miscellaneous, unix-gpu, windows-gpu, windows-cpu, unix-cpu, centos-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by leezu** [comment]
As @ptrendx targets having runtime compilation for cuda kernels in 2.0, I wonder if this should be reverted on 1.x branch only?

**Comment by rondogency** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, windows-cpu]

**Comment by rondogency** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by rondogency** [comment]
@leezu we need to resolve the current regression first and ptrendx would work on a fix

**Comment by rondogency** [comment]
@ptrendx can you help to merge it, thanks!

**Comment by rondogency** [comment]
@ciyongch Can you help to cherry-pick this into 1.x and 1.7 release, as this addresses a memory regression fix

**Comment by ciyongch** [comment]
Thanks @rondogency , do you mind to create a PR to 1.7 as well, as it's already merge/created in master/v1.x now :)

**Comment by rondogency** [comment]
@ciyongch yes I will do it shortly

**Pull request merged**
