### PR TITLE
[R] Fix incorrect website title for Symbol API in R

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
~~1. `mx.nd.copyto` doesnt exist~~
mx.nd.copyto exists for R API [but not for Python API]
2. website title shows ndarray instead of symbol

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by ChaiBapchya** [comment]
@leezu @access2rohit plz review/merge

**Comment by leezu** [comment]
@mxnet-bot run ci [miscellaneous]

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
