### PR TITLE
[1.x] Pass args fix2

### PR DESCRIPTION
**Pull request by samskalicky**
## Description ##
Cherry pick #18232 (#18237 in v1.7.x branch) and #18177

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
https://github.com/apache/incubator-mxnet/blob/80baab83775d54b1805a72254992a0fa87bd2f49/ci/docker/install/requirements#L30-L31

This has already been resolved in my PR #18220 

https://github.com/apache/incubator-mxnet/pull/18220/commits/18e2014004eb52e34db926d47202f1add5ff817f

@samskalicky  please rebase.

**Comment by ciyongch** [comment]
HI @samskalicky  , please help to rebase to remove the conflicts :)

**Comment by samskalicky** [comment]
@ciyongch thanks for the reminder, I merged

**Comment by samskalicky** [comment]
@mxnet-bot run ci [edge, windows-gpu, centos-cpu, centos-gpu]

**Comment by samskalicky** [comment]
@ciyongch looks like the CI is currently broken for 1.x per @leezu 

does this block the 1.7 release?

**Comment by ciyongch** [comment]
Hi @samskalicky , there's several PRs struggling with the CI failure so far. @waytrue17 is working on the fix of `edge` job (`NVidia Jetson / ARMv8`). While for the `centos-gpu` and `centos-cpu` jobs in this PR failed for `Cannot open: https://centos7.iuscommunity.org/ius-release.rpm. Skipping.`, can you help to take a check? thanks!

**Comment by samskalicky** [comment]
According to https://github.com/iusrepo/announce/issues/18 we need to change the path we use to install python in ci/docker/install/centos7_python.sh from https://centos7.iuscommunity.org/ius-release.rpm to https://repo.ius.io/ius-release-el7.rpm. Ive updated it, lets see if it passes CI now.

**Comment by leezu** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by ciyongch** [comment]
Hi @samskalicky , probably rename the title to [1.x] instead of [1.7] for this PR? Thanks.

**Comment by samskalicky** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

@ciyongch I updated the title, @leezu ready to merge!

**Pull request merged**
