### PR TITLE
Skip CI pipelines unaffected by code changes. [WIP][Do not merge]

### PR DESCRIPTION
**Pull request by ifeherva**
This PR tries to reduce CI load by adding logic to each pipeline which will skip all stages when changes would not affect the outcome.

### CODE REVIEW

**Comment by Roshrini** [comment]
@ifeherva Thanks for working on this!
@mxnet-label-bot Add [CI, pr-work-in-progress]

**Comment by stu1130** [comment]
@ifeherva is it good to review?

**Comment by pinaraws** [comment]
@ifeherva Do you have any updates? Do you need any help?

**Comment by ifeherva** [comment]
Still working on it, but got caught up with other tasks. I mostly figured out the technical part, the question is still when to skip what. I started writing a doc on it, but it is far from finished yet. Interested what others think on when to skip CI steps.

**Comment by piyushghai** [comment]
@ifeherva Were you able to revisit this PR ?

**Comment by ifeherva** [comment]
@piyushghai sorry, not yet :(

**Comment by karan6181** [comment]
@ifeherva It would be really helpful if you post a frequent updates on this PR about your thoughts so that the other community members gets more understanding on CI pipelines and the work you are doing. Thanks!

**Comment by ifeherva** [comment]
@karan6181 Sorry, I could/can not find time to work on this lately. I think I will close this PR until I manage to find time.

**Pull request closed without merging**
