### PR TITLE
Revert "Sphinx failure fixes"

### PR DESCRIPTION
**Pull request by vdantu**
Reverts apache/incubator-mxnet#

### CODE REVIEW

**Comment by szha** [comment]
Why was #13213 merged in the first place? Did the contributor or committer check the preview?

**Comment by vdantu** [comment]
It generated the HTML file locally when I tested it. I will check for the preview to see if this broke the docs after the tests are complete.

**Comment by vdantu** [comment]
I reverted only my PR. This shows other commits in its log. This might need rebasing.

**Comment by vdantu** [comment]
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13230/1/api/python/ndarray/ndarray.html

**Comment by nswamy** [comment]
I don't see any other files reverted except the revert of Sphinx Doc Errors. Merging

**Pull request merged**
