### PR TITLE
[v1.x] Add image segmentation end-to-end tests and expand object classification tests

### PR DESCRIPTION
**Pull request by josephevans**
## Description ##
Add new image segmentation tests to test suite, and expand object classification tests to test all supported models.

### CODE REVIEW

**Comment by josephevans** [comment]
I added the test images to the incubator-mxnet-ci repo and will update this PR to reflect the new URLs once this is merged: https://github.com/apache/incubator-mxnet-ci/pull/35

**Comment by Zha0q1** [comment]
> I added the test images to the incubator-mxnet-ci repo and will update this PR to reflect the new URLs once this is merged: https://github.com/apache/incubator-mxnet-ci/pull/35

Is that pr ready to merge?

**Review by Zha0q1 — APPROVED** [review]
LGTM!

**Review by waytrue17 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
