### PR TITLE
[WIP]: ensure when one dimension is zero the shape is inferred

### PR DESCRIPTION
**Pull request by access2rohit**
## Description ##
Fixes issue #11635 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by junrushao1994** [comment]
Thanks for the contribution! We have been talking about this issue for a while @reminisce

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-work-in-progress]

**Comment by ZhennanQin** [comment]
Thanks for fixing this. Could you please apply the change to quantized_concat as well?

**Comment by pinaraws** [comment]
@access2rohit Could you please address the comment by @ZhennanQin ?

**Comment by apeforest** [comment]
Please provide more information in the description to help people to review

**Comment by access2rohit** [comment]
Hi All,
    This PR is still WIP and I will address comments

**Comment by piyushghai** [comment]
@access2rohit Did you get a chance to revisit this PR ?

**Comment by karan6181** [comment]
@access2rohit Did you get a chance to work on this PR? If you are unable to work on this PR at the moment, you may want to consider closing it, and resubmitting once you have the bandwidth to work on it. Thanks!

**Pull request closed without merging**
