### PR TITLE
Fix scale bug in quantized batch_dot

### PR DESCRIPTION
**Pull request by DominikaJedynak**
## Description ##
Small fixes:
- corrected mistake by changing min_calib_range to max_calib_range
- deleted repeated comment

### CODE REVIEW

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu, website]

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [miscellaneous, unix-gpu, website]

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [unix-gpu, website]

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [unix-gpu, website]

**Review by bartekkuncer — APPROVED** [review]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-gpu, website]

**Pull request merged**
