### PR TITLE
[PERFORMANCE] Improve shuffle implementation

### PR DESCRIPTION
**Pull request by anko-intel**
## Description ##
Improve performance of random.shuffle implementation.

Results on c6i.8xlarge instance ( Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz ) of the follwing script

```
import mxnet as mx
from benchmark.opperf.utils.benchmark_utils import run_performance_test

shapes = [
    (  10, 1),
    ( 32, 9999),
    (4096,   1),
    (4096,  500),
    (4096, 4096),
    (4096, 1024, 32)]

print("\nnot-in-place (mx.nd.random.shuffle):")
for shape in shapes:
    s_res = run_performance_test(mx.nd.random.shuffle, run_backward=False, inputs=[{"data": (shape)}])
    print(s_res)

print("\nin-place (mx.np.random.shuffle):")
for shape in shapes:
    s_res = run_performance_test(mx.np.random.shuffle, run_backward=False, inputs=[{"x": (shape)}])
    print(s_res)
```

shows following improvments:

- not-in-place (mx.nd.random.shuffle):

|    Shape         | Before [ms] | After [ms]  | Improvement |
|-----------------:|------------:|------------:| ----------:|
| (10, 1)}         |    0.0038   |      0.0024 |    37%     |
| (32, 9999)       |    0.168    |      0.0795 |    53%     |
| (4096, 1)}       |    0.0463   |      0.0328 |    29%     |
| (4096, 500)      |    1.1972   |      0.6511 |    46%     |
| (4096, 4096)     |  15.5678    |      8.8016 |    43%     |
| (4096, 1024, 32) |  139.1404   |     74.0476 |    47%     |

- in-place (mx.np.random.shuffle):

|    Shape         | Before [ms] | After [ms]  | Improvement |
|-----------------:|------------:|------------:| ----------:|
| (10, 1)}         |  0.0023     |    0.0022   |     4%     |
| (32, 9999)       |  0.0852     |    0.0406   |    52%     |
| (4096, 1)}       |  0.0436     |    0.0404   |     7%     |
| (4096, 500)      |  0.6643     |    0.4317   |    35%     |
| (4096, 4096)     |  6.778      |    3.7478   |    45%     |
| (4096, 1024, 32) | 89.1249     |    41.931   |    53%     |

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### CODE REVIEW

**Comment by anko-intel** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu, unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu, centos-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu, centos-gpu, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Review by bgawrych — APPROVED** [review]

**Pull request merged**
