### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by piiswrong**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] For user-facing API changes, API doc string has been updated.
- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Intersting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@mseeger Do you have an idea why these tests fail on gpu? Did you register new backward ops on gpu, too?

**Comment by mseeger** [comment]
@eric-haibin-lin 

No sorry, I forgot that. One has to add the following to elemwise_unary_op_basic.cu:

NNVM_REGISTER_OP(_backward_log*)
.set_attr<FCompute>("FCompute<gpu>", ElemwiseBinaryOp::Compute<
  gpu, unary_bwd<mshadow_op::log*_grad> >);

Where * is {10, 2}

I hope that all unit tests pass. I was in the middle of making sure they do, when this was already merged into dev. It is complete AFAI am concerned, given the ops are registered for GPU, and all my new unit tests pass (once they do, their output can be commented out).

**Comment by mseeger** [comment]
@piiswrong Some of my unit tests still fail even on a CPU case. I even see a nan.

This needs some more work. Feel free to roll back on my changes for now, I still have the branch.

If you insist, we could do the fixes to log10, log2, but for me would be simpler to get it all done in one go.

**Comment by mseeger** [comment]
@piiswrong , @eric-haibin-lin 

Maybe a simpler idea is if you just comment out the following tests in
test_operator.py:
- test_unary_math_operators
- test_binary_math_operators

and bring it into master. I will then fix the tests shortly, and send another PR for them.

Note this still leaves the existing tests for these operators, it is just about the new ones I added.

**Comment by piiswrong** [comment]
Ok. I'll revert your PR. Please send your complete work to master later

**Comment by piiswrong** [comment]
Keep in mind we are shipping 0.12 before monday morning PST

**Pull request closed without merging**
