### PR TITLE
[scala] Make accuracy idependant of output size (fix #8226)

### LINKED ISSUE #8226: [scala] Accuracy precision is too low
## Description
When using the Accuracy EvalMetric, it is very easy to fall in cases where `EvalMetric.sumMetric` has a too low precision.

## Environment info (Required)
ubuntu, scala (not relevant).

## Build info (Required if built from source)
MXNet commit hash: 0449cc646a9f5d76e6c9fb01659e771bf1237233

## Description
In EvalMetric.scala, sumMetric is defined as:
```scala
  protected var sumMetric: Float = 0.0f
```
and the Accuracy metric does:
```scala
      for ((labelElem, predElem) <- label.toArray zip predLabel.toArray) {
        if (labelElem == predElem) {
          this.sumMetric += 1
        }
      }
```
Because sumMetric is a float, if it becomes bigger than ~10^7, then `this.sumMetric += 1` will have no effect and sumMetric will not be updated anymore. It is quite easy to get big numbers in sumMetric while solving, for example, image segmentation tasks (with output size of ~ 800x800, it will take about 50 output to get to 10^7). This won't throw any warning or error.

## Solutions
I worked around this issue by

1. summing all elements of one output before adding the result to sumMetric
2. dividing the sum by the number of elements

### 1) summing element before adding the result to sumMetric
To lower the difference of magnitude between this.sumMetric and 1, i replaced
```scala
      for ((labelElem, predElem) <- label.toArray zip predLabel.toArray) {
        if (labelElem == predElem) {
          this.sumMetric += 1
        }
      }
```
by
```scala
val ok = labe.toArrayl.zip(predLabel.toArray)
           .filter{ case (lElem: Float, pElem: Float) => lElem == pElem }.size.toFloat
this.sumMetric += s
```
s being (in my case) far bigger than 1, this change push back the problem. However, it doesn't solve it and that was not enough in my case.

### 2) Divide the sum by the number of elements
It would be better if the Accuracy doesn't depend on the size of the output. Hence, I divided the sum by the number of elements
 ```scala
val la = label.toArray
val size = label.size.toFloat
val ok = la.zip(predLabel.toArray)
            .filter{ case (lElem: Float, pElem: Float) => lElem == pElem }.size.toFloat
this.sumMetric += ok / size
```
With this change, I was able to train my network with about 50k inputs.

## Additional better (?) solution
We could use a `double` for this.sumMetric of EvalMetric, which would likely be enough for most case. The `get` function could still return a casted float if the EvalMetric API cannot easily be changed. 

I can provide a PR for the fix 1) and 2).
I am waiting for comments and feedbacks regarding the use of double for sumMetric.

My PR would also fix #8129 if @Ldpe2G (who found the solution) did not do it in the meantime. 

(By the way, am I the only one using Accuracy this way in Scala?)

### PR DESCRIPTION
**Pull request by benqua**
## Description ##
This PR change EvalMetric.sumMetric from Float to Double.

Fix #8226

### CODE REVIEW

**Comment by javelinjs** [comment]
Thanks @benqua , I think a better way is to change `sumMetric` to `Double`. The fix here changes the definition of Acc.

**Comment by benqua** [comment]
@javelinjs , you're right, it changes the definition of accuracy for output.size > 1.
What is the exact definition of Accuracy? I couldn't find a clear definition.

This change provides a definition of accuracy that match the one from wikipedia for binary classification, that says: 
_the accuracy is the proportion of true results (both true positives and true negatives) among the total number of cases examined_
(https://en.wikipedia.org/wiki/Accuracy_and_precision#In_binary_classification).

It seems weird (at least to me :) ) that the accuracy depends on the output dimension and can grow to very large numbers. By dividing by the label dimension, we keep the accuracy between 0 and 1, which is the expected range of a "proportion".

**Comment by javelinjs** [comment]
We should keep it the same as other language bindings, especially python. What if we make it Double in EvalMetric API?

**Comment by benqua** [comment]
It can be done, but it would break the API for people calling EvalMetric.get (https://github.com/apache/incubator-mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/EvalMetric.scala#L52) .

**Comment by javelinjs** [comment]
We can convert it back to Float when calling `EvalMetric.get`

**Comment by benqua** [comment]
@javelinjs ok, I updated the PR as you suggested. 
(I should maybe have done a new one because the comment thread is now difficult to understand)
What do you think?

**Comment by benqua** [comment]
Ho, it seems there is a build issue. Not sure it is related to my code (something about the windows gpu build), but I will check this week-end.

**Comment by javelinjs** [comment]
LGTM.
The CI seems to have some problems these days. Lets try again this weekend.

**Comment by javelinjs** [comment]
@benqua could you rebase the pr and re-trigger the CI build?

**Comment by benqua** [comment]
Rebased. Waiting for the CI to complete.

**Comment by javelinjs** [comment]
@piiswrong Could you help to do a force merge?

**Comment by benqua** [comment]
I tried again, still no luck.
The message from the CI doesn't help to understand if it is still a CI issue or a PR one.

**Comment by javelinjs** [comment]
Sorry to see that. Please rebase again, I think the CI is OK now.

**Comment by benqua** [comment]
done. let's see...

**Comment by benqua** [comment]
It fails with:
```
FAIL: test_operator_gpu.test_svmoutput_with_type

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "c:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\test_operator_gpu.py", line 999, in test_svmoutput_with_type

    check_consistency(sym, ctx_list)

  File "c:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 1338, in check_consistency

    raise e

AssertionError: 

Items are not equal:

Error 5.000000 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(18, 3), a=0.000000, b=1.000000

 a: array([[-1.,  1.,  1., ...,  1.,  1.,  1.],

       [-1.,  1.,  0., ...,  0.,  1.,  1.],

       [-1.,  1.,  1., ...,  1.,  1.,  1.],...

 b: array([[-1.,  1.,  1., ...,  1.,  1.,  1.],

       [-1.,  1.,  0., ...,  0.,  1.,  1.],

       [-1.,  1.,  1., ...,  1.,  1.,  1.],...

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 2 vs ctx 0 at svmoutput_data


--------------------- >> end captured stdout << ----------------------


----------------------------------------------------------------------

Ran 243 tests in 1392.034s


FAILED (SKIP=5, failures=1)


(py2) c:\jenkins_slave\workspace\ut-python-gpu>IF 1 NEQ 0 exit /b 1 

script returned exit code 1
```

will investigate when I find time. idea, help welcome :)

**Comment by marcoabreu** [comment]
I've encountered the same error with test_operator_gpu.test_svmoutput_with_type on my setup. Please check our internal wiki, @KellenSunderland @mbaijal @larroy

**Comment by marcoabreu** [comment]
@benqua Did you try to rebase?

**Comment by benqua** [comment]
@javelinjs , Finally, the PR passes all tests.
Do you think it can be merged?

**Comment by javelinjs** [comment]
Thanks.

**Pull request merged**
