### PR TITLE
Fix link to array-api documentation

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
Link check fails in multiple PR's, e.g.:
https://github.com/apache/incubator-mxnet/pull/20772 - https://github.com/apache/incubator-mxnet/runs/4467893604?check_suite_focus=true
https://github.com/apache/incubator-mxnet/pull/20713 - https://github.com/apache/incubator-mxnet/runs/4458865888?check_suite_focus=true

### CODE REVIEW

**Review by barry-jin — APPROVED** [review]
Thanks for the fix!

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-gpu]

**Review by agrabows — APPROVED** [review]

**Review by bartekkuncer — APPROVED** [review]

**Comment by bgawrych** [comment]
@barry-jin Do you know if something has change in the infrastructure of CI that can causing these timeouts in mkl continuous build? I belive it's not caused by any recent commit

**Comment by barry-jin** [comment]
> @barry-jin Do you know if something has change in the infrastructure of CI that can causing these timeouts in mkl continuous build? I belive it's not caused by any recent commit

Looks like it is caused by macos-latest virtual-environment in github actions is using macOS-11 (previously macOS-10.5)

**Comment by bgawrych** [comment]
I have noticed this also - I will prepare PR to use latest working version to unblock CI and create issue tracker for this
Thanks @barry-jin

**Comment by barry-jin** [comment]
> I have noticed this also - I will prepare PR to use latest working version to unblock CI and create issue tracker for this Thanks @barry-jin

I have created the quick fix https://github.com/apache/incubator-mxnet/pull/20777

**Pull request merged**
