### PR TITLE
Fix weird hang bug due to cuInit sometimes calls fork

### PR DESCRIPTION
**Pull request by piiswrong**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [ ] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@ptrendx any idea why fork was called by `cuinit`?

**Comment by ptrendx** [comment]
I did not see such behavior before (cuinit calling fork), but the PR itself seems fine and should not affect anything negatively.

**Comment by bhavinthaker** [comment]
Thanks ptrendx@ for the quick review.

**Comment by larroy** [comment]
👍 as a hotfix I think it's ok but I think we should refactor this code, I don't like what we are doing  at pthread_atfork, looks very dangerous and brittle as it has been surfaced by the bug. I would be favorable to refactor this code.

**Pull request merged**
