### PR TITLE
Reorganize the tutorials index page.

### PR DESCRIPTION
**Pull request by indhub**
## Description ##
Merge [changes](https://github.com/apache/incubator-mxnet/pull/9033) to tutorials index from 1.0 branch

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by indhub** [comment]
@aaronmarkham

**Comment by indhub** [comment]
@piiswrong Could you please elaborate on that? 
1. Are you saying you don't want tutorials on symbolic interface and Gluon on the same page? 
2. Are you saying the way it is structured now is better? If not, how do you propose to restructure?

**Comment by indhub** [comment]
@piiswrong 

Here is the rationale behind the restructure:

First of all dividing the MXNet tutorials page into 

1. Gluon
2. MXNet

is like dividing a page on automobiles into 

1. Cars 
2. Automobiles. 

It doesn't make sense. That is what prompted the restructure. 

Following the reasons why it is restructured the way it is restructured now:

1. NDArray is common to both the imperative and symbolic interface. It is also the most basic tutorials. So, that goes first. 

2. After learning to use NDArray, user can use Autograd to automatically compute gradients. Autograd is independent from Gluon and can be used without Gluon. So, Autograd is the next tutorial. 

3. Between Gluon and the symbolic interface, Gluon is the easier and more intuitive interface. So, gluon tutorials comes next.

4. Symbolic interface naturally follows since Imperative (Gluon) and Symbolic are the two ways to write MXNet code. 

5. Hybrid blocks comes next because user needs to understand gluon and symbolic interface before user can understand Hybrid blocks. 

6. Sparse operations, large scale classifications and GAN are advanced topics and hence placed at the end.

Please let me know what if any you would like to change and why.

**Comment by aaronmarkham** [comment]
These changes were already accepted as part of the v1.0.0 release, but for "reasons" they're not showing up on the website. 
I plan to build on top of this version by adding the recently fixed tutorials, so let's pass this one and begin iterating on it. 
@piiswrong if you have specific suggestions, I'll be happy to incorporate your feedback moving forward for subsequent versions.

**Comment by piiswrong** [comment]
These changes where merged before I had a chance to look at them.

Now that I see it, I think the original organization was better. Since it was showing on website anyway I suggest we revert it.

**Comment by piiswrong** [comment]
If you actually read the tutorials carefully, you'll notice that although the gluon tutorials and old mxnet tutorials overlap on topic, they have different focus.

If you want to combine tutorials to achieve better user experience, I suggest you read the tutorials carefully and combine their contents. Simply moving them around doesn't help users.

**Comment by indhub** [comment]
@piiswrong 

While I agree there is a lot of work that needs to be done for the tutorials, we need to take incremental steps towards better contents organised better.

Dividing MXNet tutorials page into (1) Gluon and (2) MXNet gives the impression that Gluon and MXNet are separate things. Dividing a page on X into Y and X is illogical for any given X and Y. It is like dividing a page on Gluon tutorials into (1) RNN with Gluon (2) Gluon. I don't see how the existing organization is better; I think the existing organization is embarrassing for the reason stated above.

**Comment by madjam** [comment]
This change is a improvement over what we have today. I believe this change walks the user through a series of concepts that are in roughly logical order. 
This doesn't mean it ends here. We can iterate to make it better.

**Comment by piiswrong** [comment]
I disagree. I think these changes are making things worse.

For example, with old mxnet and module, you don't need mxnet.autograd.
If a user wants to use module, he/she would be confused by the autograd chapter

**Comment by indhub** [comment]
Closing this since there is no consensus to merge this.

**Pull request closed without merging**
