### PR TITLE
Support 3D input for MKL-DNN softmax operator

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
1. to support 3D softmax layers in GluonNLP BERT (need #14783 for better performance)
2. fix in-place softmax
3. remove ctx.is_train check so the cpp test for softmax can work
4. enhance the checks in SupportMKLDNNSoftmax

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
@pengzhao-intel @juliusshufan

**Comment by pengzhao-intel** [comment]
@TaoLv thanks for the PR. 

Is there a test for the 1D softmax and could you show the performance of MKL-DNN primitive against original implementation?

**Comment by TaoLv** [comment]
Tests should be covered by
https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L4697
and
https://github.com/apache/incubator-mxnet/blob/master/tests/cpp/operator/mkldnn_operator_test.cc#L1288.
I used below code snippet for performance benchmarking:
```python
def test_performance():
    shapes = [(1024,), (96, 512), (96, 128, 128), (96, 256, 256), (1, 8, 1024, 1024)]
    for sh in shapes:
        a = mx.nd.random.uniform(shape=sh)
        # warm up
        b = mx.nd.softmax(a, axis=-1)
        b.wait_to_read()

        tic = time.time()
        for i in range(1000):
            b = mx.nd.softmax(a, axis=-1)
            b.wait_to_read()

        toc = time.time()
        print("softmax %s, take %f ms" % (sh, (toc - tic)/1000*1000.0))
```
Some performance numbers as following:
mxnet==1.5.0b20190426
```
softmax (1024,), take 0.103340 ms
softmax (96, 512), take 0.127465 ms
softmax (96, 128, 128), take 1.655400 ms
softmax (96, 256, 256), take 6.369653 ms
softmax (1, 8, 1024, 1024), take 11.450656 ms
```
This PR with MKL-DNN backend:
```
softmax (1024,), take 0.062743 ms
softmax (96, 512), take 0.104104 ms
softmax (96, 128, 128), take 0.385350 ms
softmax (96, 256, 256), take 0.463220 ms
softmax (1, 8, 1024, 1024), take 1.704757 ms
```

**Comment by TaoLv** [comment]
Pending on MKL-DNN update for better performance~

**Comment by TaoLv** [comment]
Fallback all softmax operations when axis != last dimension because they are not optimized in MKL-DNN.

**Comment by pengzhao-intel** [comment]
@TaoLv I have merged the MKL-DNN 0.19 and please rebase the code and see if everything is OK :)

**Comment by pengzhao-intel** [comment]
@TaoLv please rebase and retrigger again the CI issue is fixed now.

**Comment by pengzhao-intel** [comment]
Merging now :) Thanks for your contribution.

**Pull request merged**
