### PR TITLE
Update MKL-DNN submodule to v0.19

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
This PR updates the MKL-DNN submodule to v0.19. Currently it's still a release candidate. Will update to the final release commit once it's released.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
Hi @iblis17, may I have you comments on the failure of Julia tests?

**Comment by iblis17** [comment]
Hi @TaoLv ,
please consider rebase your PR, there is a related patch merged recently: https://github.com/apache/incubator-mxnet/pull/14776

**Comment by TaoLv** [comment]
Thank you @iblis17 . Will try!

**Comment by roywei** [comment]
@mxnet-label-bot add[MKLDNN, pr-work-in-progress]

**Comment by eric-haibin-lin** [comment]
What's the pending item for this PR?

**Comment by TaoLv** [comment]
@eric-haibin-lin Finally MKL-DNN 0.19 was just released today. This PR is updated accordingly.

**Comment by pengzhao-intel** [comment]
@TaoLv please rebase the code since the TRT failure is disabled now.

**Comment by pengzhao-intel** [comment]
Merging now, thanks for your contribution.

**Pull request merged**
