### PR TITLE
[BUGFIX] Improve compile/use of nvmlDeviceGetComputeRunningProcesses()

### PR DESCRIPTION
**Pull request by guanxingithub**
## Description ##
This PR is filed to solve the issue reported in https://github.com/apache/incubator-mxnet/issues/20467 as well as https://github.com/apache/incubator-mxnet/issues/20863. For fixing this issue, an initial solution was provided in #20499 by @khaotik.  This PR, with a fix from @DickJC123, adds more compilation robustness across drivers and both settings of the NVML_NO_UNVERSIONED_FUNC_DEFS cmake flag.

In this PR, we would like to merge these two solutions and find a general solution that avoids compilation errors no matter which signature of the nvmlDeviceGetComputeRunningProcesses() function is enabled in the code.
### Essentials ###
This PR is 
Dick Carter finished coding on this PR
All changes are fully tested by Guanxin Li
Code is well-documented

### Changes ###
The change reduce the possibly versioned variant of nvmlProcessInfo_t* expected
as the 3rd arg of nvmlDeviceGetComputeRunningProcesses().

## Comments ##
 This change is a backward incompatible change, without this change, mxnet can't be compiled in cuda11 450.x driver

### CODE REVIEW

**Comment by guanxingithub** [comment]
This PR is filed to solve the issue reported in  #20467 as well as #20863. For fixing this issue, the solutions are provided in  #20499 and #20866 by @szha and @DickJC123 .

In this PR, we would like to merge these two solutions and find a general solution that avoids compilation errors no matter which signature of the nvmlDeviceGetComputeRunningProcesses() function is enabled in the code.

Really appreciate your reviews, from  @szha,  @DickJC123!

**Comment by guanxingithub** [comment]
Add reviewers: @szha and @ptrendx

**Review by ptrendx — APPROVED** [review]
Moving my approval from #20866

**Review by DickJC123 — APPROVED** [review]
Based on the signature of the nvmlDeviceGetComputeRunningProcesses() function (as dictated by the driver include file and the NVML_NO_UNVERSIONED_FUNC_DEFS cmake flag), we want the local variable `infos` vector to have an element type compatible with the 3rd arg of that function.  This PR uses template meta-programming to deduce that.  LGTM.

**Pull request merged**
