### PR TITLE
add infer_type for regression ops, fix issues#9847

### PR DESCRIPTION
**Pull request by ZiyueHuang**
## Description ##
fix https://github.com/apache/incubator-mxnet/issues/9847

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by cjolivier01** [comment]
How did unit test test_operator.py test_regression() test work without the error?

**Comment by marcoabreu** [comment]
Yes, please track down why the test did not catch this issue

**Comment by ZiyueHuang** [comment]
Unittest is written in symbolic mode while the issue is in imperative mode. In symbolic mode, infer_type pass has a default infer function `SameType` https://github.com/apache/incubator-mxnet/blob/master/src/executor/infer_graph_attr_pass.cc#L403-L408, but in imperative mode, there is no default infer type function https://github.com/apache/incubator-mxnet/blob/master/src/imperative/imperative_utils.h#L123. So this is an inconsistent behaviour between symbolic mode and imperative mode. Should we correct it? cc @reminisce @eric-haibin-lin

**Comment by ZiyueHuang** [comment]
By the way, `L2NormalizationOp` and `InstanceNormOp` don't have an infer_type function.

**Comment by cjolivier01** [comment]
Makes sense.

**Comment by marcoabreu** [comment]
Very nice catch, @ZiyueHuang! Sounds like a good idea.

**Comment by cjolivier01** [comment]
Please feel free to add infer type for the other ones if you like (not required for this PR, however).

**Comment by ZiyueHuang** [comment]
Is this good to merge? @piiswrong

**Comment by eric-haibin-lin** [comment]
@piiswrong any special reason for missing default inference function in imperative mode?

**Comment by piiswrong** [comment]
We can add a default for imperative later

**Pull request merged**
