### PR TITLE
Fix cmake installation failed (Fix #13578)

### LINKED ISSUE #13578: [CMake] Make install / ninja install failing [dmlc-core]
## Description
install target fails:

```
-- Up-to-date: /usr/local/include/gtest/internal/gtest-filepath.h
-- Up-to-date: /usr/local/include/gtest/internal/gtest-param-util-generated.h.pump
-- Up-to-date: /usr/local/include/gtest/internal/custom
-- Up-to-date: /usr/local/include/gtest/internal/custom/gtest.h
-- Up-to-date: /usr/local/include/gtest/internal/custom/gtest-port.h
-- Up-to-date: /usr/local/include/gtest/internal/custom/gtest-printers.h
-- Up-to-date: /usr/local/include/gtest/gtest-printers.h
-- Up-to-date: /usr/local/include/gtest/gtest_pred_impl.h
-- Up-to-date: /usr/local/include/gtest/gtest-param-test.h
-- Up-to-date: /usr/local/include/gtest/gtest-death-test.h
-- Up-to-date: /usr/local/include/gtest/gtest-test-part.h
-- Up-to-date: /usr/local/lib/libdmlc.a
-- Up-to-date: /usr/local/./include
-- Installing: /usr/local/./include/dmlc
CMake Error at 3rdparty/dmlc-core/cmake_install.cmake:40 (file):
  file INSTALL cannot set permissions on "/usr/local/./include/dmlc"
Call Stack (most recent call first):
  cmake_install.cmake:68 (include)
  


Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1

```

## Reproduction

Build with CMake, do make install

```
./dev_menu.py build
cd build && ninja install
```

# Environment
Ubuntu 16.04

@lebeg

### PR DESCRIPTION
**Pull request by sl1pkn07**
## Description ##
fix installation when use cmake

https://github.com/apache/incubator-mxnet/issues/13578

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by sl1pkn07** [comment]
super ugly quick workground

~~~
# Not install dmlc-core docs in /
  sed '/doc/s/^/#/g' \
    -i 3rdparty/dmlc-core/CMakeLists.txt \
    -i 3rdparty/tvm/3rdparty/dmlc-core/CMakeLists.txt
~~~
but this sould be fixed in upstream

**Comment by sl1pkn07** [comment]
pushed PR to upstream (https://github.com/dmlc/dmlc-core/pull/528)

**Comment by larroy** [comment]
I tried both PRs together and I have errors:

```
-- Could NOT find Gperftools (missing: GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR)
-- Using JEMalloc malloc
--  OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs
-- OpenCV 3.2.0 found (/usr/share/OpenCV)
USE_LAPACK is ON
CMake Error at 3rdparty/dmlc-core/3rdparty/googletest/googletest/cmake/internal_utils.cmake:149 (add_library):
  add_library cannot create target "gtest" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "/home/piotr/mxnet_cmake/3rdparty/googletest/googletest".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  3rdparty/dmlc-core/3rdparty/googletest/googletest/cmake/internal_utils.cmake:172 (cxx_library_with_type)
  3rdparty/dmlc-core/3rdparty/googletest/googletest/CMakeLists.txt:90 (cxx_library)


CMake Error at 3rdparty/dmlc-core/3rdparty/googletest/googletest/cmake/internal_utils.cmake:149 (add_library):
  add_library cannot create target "gtest_main" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory
  "/home/piotr/mxnet_cmake/3rdparty/googletest/googletest".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  3rdparty/dmlc-core/3rdparty/googletest/googletest/cmake/internal_utils.cmake:172 (cxx_library_with_type)
  3rdparty/dmlc-core/3rdparty/googletest/googletest/CMakeLists.txt:91 (cxx_library)

```

**Comment by larroy** [comment]
LGTM, the issues listed are related to dmlc-core not to mxnet. I suggest we merge this and follow up on posterior PRs as it improves the current state.

**Comment by larroy** [comment]
@mxnet-label-bot update [build,cmake,pr-awaiting-merge]

**Comment by sl1pkn07** [comment]
the steps seems:

apply the dmcl-core PR in upstream -> update the dmcl-core submodule in mxnet point to updated dmlc-core, and then apply this pr in mxnet

**Comment by wkcn** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
