### PR TITLE
fix transformer optimization for gpt-2

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
When enabling CPU optimizations for GPT-2 = it crashes with following error:
`mxnet.base.MXNetError: MXNetError: Required parameter heads of int is not presented, in operator _sg_onednn_selfatt_qk(name="_sg_onednn_selfatt_qk_0")`

One more constraint was added to fuse.

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by agrabows — APPROVED** [review]
LGTM

**Comment by bgawrych** [comment]
@mxnet-bot run ci [all]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [all]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
