### PR TITLE
Fix softmax_cross_entropy list input names

### PR DESCRIPTION
**Pull request by kevinthesun**
1. Add FListInputNames attribute to softmax_cross_entropy operator.
2. Add softmax_cross_entropy unit test.

### CODE REVIEW

**Comment by geoalgo** [comment]
Thanks for fixing this, I am also impacted by this problem and look forward for your patch.

**Comment by wielandbrendel** [comment]
Thanks for the fix @kevinthesun! What is holding this PR back?

**Comment by kevinthesun** [comment]
@piiswrong Do we still need this fix?

**Comment by wielandbrendel** [comment]
I came across this error when compiling the current master, and so I needed to manually pull this PR locally to fix this problem.

**Comment by eric-haibin-lin** [comment]
Moved to https://github.com/apache/incubator-mxnet/pull/8254/

**Pull request closed without merging**
