### PR TITLE
Fix quote on LBSGD docs

### PR DESCRIPTION
**Pull request by ThomasDelteil**
## Description ##
fix doc in https://github.com/apache/incubator-mxnet/issues/12171

### CODE REVIEW

**Comment by sandeep-krishnamurthy** [comment]
@ThomasDelteil - Thanks for fixing this
Can you please paste a snapshot of doc with this change?

**Comment by szha** [comment]
This comment is ignored: https://github.com/apache/incubator-mxnet/issues/12171#issuecomment-415178244

**Comment by vandanavk** [comment]
@mxnet-label-bot update [Doc, pr-awaiting-merge]

**Comment by Roshrini** [comment]
@ThomasDelteil The issue mentioned https://github.com/apache/incubator-mxnet/issues/12171 talks about doc fix needed and the bug in optimizer. This PR only takes care of doc fix. 
Can you remove "fix #12171" from description or maybe fix the bug as well to merge this PR and close the issue?

**Comment by ankkhedia** [comment]
@ThomasDelteil Could you please take a look into comments by @Roshrini

**Comment by eric-haibin-lin** [comment]
I've updated the description. The issue is left open.

**Pull request merged**
