### PR TITLE
Add handling for grad req type other than kNullOp for indices

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
Fix for #11599.

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Additional handling of more req types for `indices` in take

## Comments ##
@anirudh2290 @eric-haibin-lin @reminisce Please give a review when you have time!
@junrushao1994 This should fix your issue.

### CODE REVIEW

**Comment by junrushao1994** [comment]
@eric-haibin-lin I guess we could include the example provided here https://github.com/apache/incubator-mxnet/issues/11599

**Comment by eric-haibin-lin** [comment]
Thanks @junrushao1994 It will be great if unit test is in place so it's repeatedly tested in CI.

**Comment by junrushao1994** [comment]
@haojin2 Could you help integrate that example into unittests?

**Comment by haojin2** [comment]
@junrushao1994 @eric-haibin-lin I don't think Junru's script makes a good unit test, I'm currently looking for other ways(shorter code and run faster) to reproduce the same issue.

**Comment by junrushao1994** [comment]
@haojin2 Nice! (this is the shortest one from which I could trigger this bug though)

**Comment by eric-haibin-lin** [comment]
any update?

**Comment by haojin2** [comment]
@eric-haibin-lin Tangled by higher priority tasks last week, will complete the unit test and push code later this week.

**Comment by haojin2** [comment]
@eric-haibin-lin Done with the unit test, I still have to borrow @junrushao1994 's example.

**Comment by eric-haibin-lin** [comment]
@haojin2  could you create a github issue asking for test utils for different reqs? Thanks

**Pull request merged**
