### PR TITLE
[CI][URGENT] Fix permissions of ci/docker/install/ubuntu_publish.sh

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
see title

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by marcoabreu** [comment]
Waiting with merge until Kellen gives his green light, considering his open question.

**Comment by larroy** [comment]
ubuntu 14 docker image is failing across the board due to the permissions in this script.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-docker-cache-refresh/detail/master/1192/pipeline

**Comment by larroy** [comment]
Check any recent build from the docker cache, or right now from master.

**Comment by KellenSunderland** [comment]
Don't consider my comments blocking, I just didn't have enough context to merge.  Merge away if it looks good to you @marcoabreu.

**Comment by KellenSunderland** [comment]
@larroy Right now on master I see a problem saying:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fsanity/detail/master/204/pipeline
```
+ apt-get update
Ign:1 http://cran.rstudio.com/bin/linux/ubuntu trusty/ InRelease
Hit:2 http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release
Get:3 http://apt.llvm.org/xenial llvm-toolchain-xenial-3.9 InRelease [4207 B]
Get:4 http://apt.llvm.org/xenial llvm-toolchain-xenial-6.0 InRelease [4236 B]
Get:6 http://apt.llvm.org/xenial llvm-toolchain-xenial-3.9/main amd64 Packages [6693 B]
Hit:7 https://cran.rstudio.com/bin/linux/ubuntu xenial/ InRelease
Get:8 http://apt.llvm.org/xenial llvm-toolchain-xenial-6.0/main amd64 Packages [6570 B]
Err:8 http://apt.llvm.org/xenial llvm-toolchain-xenial-6.0/main amd64 Packages
  Hash Sum mismatch

Hit:9 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:10 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:11 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:12 http://archive.ubuntu.com/ubuntu xenial-backports InRelease

Fetched 21.7 kB in 0s (34.2 kB/s)

Reading package lists...

E: Failed to fetch http://apt.llvm.org/xenial/dists/llvm-toolchain-xenial-6.0/main/binary-amd64/Packages.gz  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

+ wget https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/7654135f0cbd155c285fd2a37d87e27e4fff3071/clang-tidy/tool/run-clang-tidy.py -O /usr/lib/llvm-6.0/share/clang/run-clang-tidy.py

/usr/lib/llvm-6.0/share/clang/run-clang-tidy.py: No such file or directory

The command '/bin/sh -c /work/ubuntu_clang.sh' returned a non-zero code: 1

Traceback (most recent call last):

  File "ci/build.py", line 582, in <module>

    sys.exit(main())

  File "ci/build.py", line 495, in main

    num_retries=args.docker_build_retries, no_cache=args.no_cache)

  File "ci/build.py", line 162, in build_docker

    run_cmd()

  File "/home/jenkins_slave/workspace/sanity-lint/ci/util.py", line 77, in f_retry

    return f(*args, **kwargs)

  File "ci/build.py", line 160, in run_cmd

    check_call(cmd)

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['docker', 'build', '-f', 'docker/Dockerfile.build.ubuntu_cpu', '--build-arg', 'USER_ID=1001', '--build-arg', 'GROUP_ID=1001', '--cache-from', 'mxnetci/build.ubuntu_cpu', '-t', 'mxnetci/build.ubuntu_cpu', 'docker']' returned non-zero exit status 1
```

Which does not seem related.

**Comment by larroy** [comment]
Yes this is another issue, with failing download of clang tidy script. Both are valid.

**Comment by larroy** [comment]
Since docker cache is not working well (This fixes it) we have docker image being rebuilt in PRs and master CI checks, can we please merge this then fix other things step by step? thanks.

**Comment by KellenSunderland** [comment]
Can you guys verify this fixed what you wanted it to?  I see two builds in master broken for task restricted-docker-cache-refresh with the error:

@larroy @marcoabreu 

```
docker_cache.py: 2019-01-16 03:05:12,704 Failed to generate publish.ubuntu1604_cpu
```

**Comment by larroy** [comment]
@KellenSunderland works for me: http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-docker-cache-refresh/

**Pull request merged**
