### PR TITLE
op.h was changed to operator.h without updating includes

### PR DESCRIPTION
**Pull request by dtmoodie**

### CODE REVIEW

**Comment by piiswrong** [comment]
@lx75249  When was this changed?

**Comment by lx75249** [comment]
@piiswrong I believe @dtmoodie misunderstood something.. Current headers are correct.

**Comment by dtmoodie** [comment]
How are current headers correct?
https://github.com/apache/incubator-mxnet/tree/master/cpp-package/include/mxnet-cpp
Does not have an op.h file.
https://github.com/apache/incubator-mxnet/blob/master/cpp-package/include/mxnet-cpp/optimizer.hpp#L37

**Comment by lx75249** [comment]
You mean there is no op.h? Because it's generated when you build the package. See the tutorial. http://mxnet.io/tutorials/c++/basics.html

**Comment by dtmoodie** [comment]
Neat, I didn't know that because I've never had cpp-package build correctly, so I've been using it as a header copy/paste drop in.
The following is the error I get when building with USE_CPP_PACKAGE=1:

cpp-package/example/mlp_cpu.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/mlp_cpu.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/mlp_cpu.cpp:45:61: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1 ? fc : Activation(fc, ActivationActType::kRelu);
                                                             ^
cpp-package/example/mlp_cpu.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);
                                             ^
cpp-package/example/test_score.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/test_score.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/test_score.cpp:45:60: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1? fc : Activation(fc, ActivationActType::kRelu);
                                                            ^
cpp-package/example/test_score.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);
                                             ^
cpp-package/example/mlp_gpu.cpp: In function 'mxnet::cpp::Symbol mlp(const std::vector<int>&)':
cpp-package/example/mlp_gpu.cpp:44:16: error: 'FullyConnected' was not declared in this scope
       layers[i]);
                ^
cpp-package/example/mlp_gpu.cpp:45:61: error: 'ActivationActType' has not been declared
     outputs[i] = i == layers.size()-1 ? fc : Activation(fc, ActivationActType::kRelu);
                                                             ^
cpp-package/example/mlp_gpu.cpp:48:45: error: 'SoftmaxOutput' was not declared in this scope
   return SoftmaxOutput(outputs.back(), label);

**Comment by lx75249** [comment]
Let's open an issue instead of discussing in pull request.

**Comment by dtmoodie** [comment]
Done 7493

**Pull request closed without merging**
