### PR TITLE
Revert "Dynamic Library Loading Support"

### PR DESCRIPTION
**Pull request by marcoabreu**
Reverts apache/incubator-mxnet#15489

Reason is the fact that this change poses a security risk: https://github.com/apache/incubator-mxnet/pull/15489/files#diff-e73d371c303c4adefa9914b6c5a6db8cR36 

It allows arbitrary code execution on any computer that executes unit tests. This means it's potentially harmful for our CI system as well as our users. 

I will merge this PR at 7pm GMT on 8/6/2019.

### CODE REVIEW

**Comment by wkcn** [comment]
Does it avoid the risk to build the dynamic library in CI rather than download?

**Comment by marcoabreu** [comment]
Yes

JackieWu <notifications@github.com> schrieb am Di., 6. Aug. 2019, 01:27:

**Comment by wkcn** [comment]
Maybe we can only disable the related test.

**Comment by wkcn** [comment]
Hi @mseth10 , I merge this PR because of the security risk as @marcoabreu mentioned.
https://github.com/apache/incubator-mxnet/pull/15489/files#diff-e73d371c303c4adefa9914b6c5a6db8cR36

Hope you reopen a new PR, which builds the dynamic library in CI building process : )
Thank you so much!

**Pull request merged**
