### PR TITLE
[v1.x] backport remove upper bound (#18857)

### PR DESCRIPTION
**Pull request by wkcn**
## Description ##
Backport #18857 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by wkcn** [comment]
CI Error
```
[2020-08-12T04:00:34.354Z] + wget https://mirror.clarkson.edu/gnu/binutils/binutils-2.27.tar.gz

[2020-08-12T04:00:34.354Z] --2020-08-12 04:00:34--  https://mirror.clarkson.edu/gnu/binutils/binutils-2.27.tar.gz

[2020-08-12T04:00:34.354Z] Resolving mirror.clarkson.edu (mirror.clarkson.edu)... 128.153.145.19, 2605:6480:c051:100::1

[2020-08-12T04:00:34.354Z] Connecting to mirror.clarkson.edu (mirror.clarkson.edu)|128.153.145.19|:443... connected.

[2020-08-12T04:00:34.608Z] HTTP request sent, awaiting response... 403 Forbidden

[2020-08-12T04:00:34.608Z] 2020-08-12 04:00:34 ERROR 403: Forbidden.
```

**Comment by wkcn** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu, windows-cpu]

**Comment by wkcn** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Comment by samskalicky** [comment]
@wkcn can you rebase? There were a few fixes that went into the v1.x branch in the past few days that may fix the two CI failures

**Comment by wkcn** [comment]
@mxnet-bot run ci [unix-cpu, unix-gpu]

**Pull request merged**
