### PR TITLE
[master][optimization] std::unordered_map was replaced by flat_hash_map

### PR DESCRIPTION
**Pull request by mozga-intel**
## Description ##
This pull-request contains a small replacement of standard std::unorder_map by a parallel hashmap. The parallel hashmap has lower space requirements and might be used from multiple threads with high levels of concurrency. 

### What is new here: ###
1. Parallel-hash map was added to 3rdparty
2. For OneDNN files, std::unorderd_map was replaced by a flat hashmap

## How to measure ##
Basically: ways used to measure the impact on (a few of them), as follows:

1. The first thing to measure is memory consumption. 
2. Performance for NLP models: i.e BERT

## Memory consumption: settings ##
1. Total bytes used for element storage: `__container__.size() * sizeof(M::type)`
2. Total byers used for the flat_hash_table bucket:  `__container__ .bucket_count()* sizeof(M::type)`

### Memory consumption: results [1] ### 
- Model: BERT
- Operator: mkldnn_fully_connected

```
 Case           Before        After
---------------------------------------
Table bucket       39760        **28672 
```
 ** This container uses almost `O(sizeof(M::type) + 1) + __container__ .bucket_count()` bytes

## Perfroamcne results [2] ##
```
 Case                    After
--------------------------------------------
Case [Infrence BERT]      [0.5 - 1]% 
```

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu]

**Review by leezu — COMMENTED** [review]
Please update the LICENSE file re 3rdparty/parallel-hasmap

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-cpu ]

**Comment by mozga-intel** [comment]
@mxnet-bot run ci [centos-gpu]

**Pull request closed without merging**
