### PR TITLE
[Issue #11912] throw mxnet exceptions when decoding invalid images.

### PR DESCRIPTION
**Pull request by lgov**
## Description ##
Check for invalid images before we pass them to OpenCV and throw a normal exception. Exceptions we can handle, OpenCV assertions not.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X ] Changes are complete (i.e. I finished coding on this PR)
- [ X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Raise an excption when passing an empty buffer to imdecode.
- Raise an exception when passing an invalid data buffer to imdecode.

### CODE REVIEW

**Comment by lgov** [comment]
This change seems to confict with a similar fix committed a couple of days ago. I’ll review tomorrow as soon as I have time.

**Comment by lgov** [comment]
I propose the replace the python specific check to ensure a non-empty buffer is passed to imdecode  (added in 96df2c5760ce9a1c1238f1f41228486a583de7ff) by the test added in this changeset which is also applicable to the other language bindings.

**Comment by ankkhedia** [comment]
@lgov Thanks for your contribution!
@mxnet-label-bot [pr-awaiting-review, Data-loading]
@sandeep-krishnamurthy @anirudhacharya Could you please help review the PR

**Comment by sandeep-krishnamurthy** [comment]
@anirudh2290

**Comment by lupesko** [comment]
@anirudh2290 can you please help review/merge? thanks!

**Pull request merged**
