### PR TITLE
Fix incorrect variable name in tutorial code

### PR DESCRIPTION
**Pull request by wongjoel**
## Description ##
Fix the incorrect variable name raised in issue #13051

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)

### Changes ###
- [x] variable name in code snippet corrected

## Comments ##
- N/A

### CODE REVIEW

**Comment by wongjoel** [comment]
@ankkhedia Thanks - I have no idea why there is a CI failure for `GPU: CMake MKLDNN` - the commit should have only changed the documentation. Is there any way to trigger the CI to run again?

**Comment by ankkhedia** [comment]
@wongjoel you can do an empty commit to retrigger CI

**Comment by lanking520** [comment]
please do `git pull --rebase upstream master` to get update with master branch.
Note: upstream in here means the `https://github.com/apache/incubator-mxnet`.
You can do `git add remote upstream https://github.com/apache/incubator-mxnet` to add a remote in your local git.

**Comment by wongjoel** [comment]
Okay, I did a rebase as requested, though was that supposed to end up with all these other commits being shown in this pull request?

Thanks for the guidance on this (trivial) pull request - I've been learning a lot about how a pull request is supposed to work.

**Comment by lanking520** [comment]
@wongjoel Hmm, looks like you make some mistakes... two options: keep fixing this. Or open another branch that sync up with apache master and then sends this PR. Or you can create another branch locally that overwrite this PR.

**Comment by wongjoel** [comment]
I think I managed to fix this pull request. Thanks for the advice.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy Could you please merge this PR if it looks good

**Comment by lupesko** [comment]
@wongjoel seems that the OSX Travis CI fails. Can you look into it? once it passes, we can move to merge.

**Comment by nswamy** [comment]
Travis CI is doing only some basic checks and does not block merge currently since it is still experimental. Merging this as its a simple fix.

**Pull request merged**
