### PR TITLE
Experiment with CI cudnn versions [Do not merge]

### PR DESCRIPTION
**Pull request by DickJC123**
## Description ##
While trying to track down rnn test flakiness that surfaced in PR#15741, I noticed that the CI for the unix-gpu runners is running against cudnn 7.5, while the libmxnet.so was built against 7.6.  This PR is an attempt to see if the flakiness is correlated with the cudnn lib version.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by zixuanweeei** [comment]
Seems CI was stuck. And I have resolved several conflicts in PR #15741. Would you mind rebasing on it and triggering CI again? Thanks.

BTW, I also found that `test_operator_gpu.test_laop_6` and `test_operator_gpu.test_convolution_multiple_streams` have failed once or twice. I have no knowledge of what caused these problems.

**Comment by zixuanweeei** [comment]
Any updates on this or CI versions irrelevant, pls?

**Comment by DickJC123** [comment]
Thanks for your patience on this.  I began working on the issues of your PR with the commit 'bump cudnn version..." and found that the CI passed for the platform that was causing you trouble.  However, I could not get a passing CI due to a number of issues.  Those issues I finally fixed with merged PR https://github.com/apache/incubator-mxnet/pull/15922.  I am currently out-of-the-office this week. If you don't mind pursuing a remedy on your own, I suggest you re-merge your PR with master (to pick up 15922), then cherry-pick my 'bump cudnn version..." commit.   Please let me know if that stabilizes your PR.

**Comment by zixuanweeei** [comment]
@DickJC123 Sure. I will have a try. Thanks for your reply.

**Comment by zixuanweeei** [comment]
With CuDNN 7.6.0.4, CI also failed for several times.

test_operator_gpu.test_lstm_bidirectional
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-15741/33/pipeline

test_gluon_gpu.test_rnn_layer
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15741/33/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15741/32/pipeline

**Pull request closed without merging**
