### PR TITLE
Enable MKL support for full pooling

### PR DESCRIPTION
**Pull request by adstraw**

### CODE REVIEW

**Comment by piiswrong** [comment]
@ykim362

**Comment by ykim362** [comment]
Hi @piiswrong , I am double-checking with @adstraw for this change. Thanks.

**Comment by adstraw** [comment]
Young identified an issue with this commit.  I am working to debug.  Shall I close this pull request while debugging or leave it open?

**Comment by piiswrong** [comment]
@ykim362 Could you confirm?

**Comment by ykim362** [comment]
@piiswrong  Yes, it passes all the CI tests. 
And, it passes a specific test case we got fails before (with MKL 'full' pooling) which @adstraw will put here.

**Pull request merged**
