### PR TITLE
[MXNET-1174]Support np.longlong on Linux and Fix issue #12843

### PR DESCRIPTION
**Pull request by wkcn**
## Description ##
On Linux x64, `str(numpy.longlong)` is "<class 'numpy.int64'>", however `numpy.longlong != numpy.int64`.
Their in-build numpy types are different.

`np.int64 == np.longlong` is True on Windows, False on Linux.
`np.dtype(np.longlong).char` is 'q' on Windows x64 and Linux x64.
`np.dtype(np.int64).char` is 'q' on Windows x64, 'l' on Linux x64.

In fact, the C types of `np.longlong` and `np.int64` are the same.

For the following code,
```python
import mxnet as mx
import numpy as np
a = mx.nd.array([1,2,3], dtype=np.longlong)
print (a, a.dtype)
```
MXNet will raise the exception:
```
  File "/home/wkcn/proj/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 139, in _new_alloc_handle
    ctypes.c_int(int(_DTYPE_NP_TO_MX[np.dtype(dtype).type])),
KeyError: <type 'numpy.int64'>
```
And there is an issue #12843 , SciPy returns a ndarray whose type is `np.longlong`, so MXNet raises a exception.

I use `np.dtype(data_type).name` to get the name of C type to solve the problem.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Adding `_TYPE_NAME_NP_TO_MX`
- [x] Adding the related unit-test

### CODE REVIEW

**Comment by roywei** [comment]
@wkcn Thanks for the contribution! 
@eric-haibin-lin @zheng-da could you take a look? thanks!
@mxnet-label-bot [pr-awaiting-review,NDArray]

**Comment by wkcn** [comment]
@roywei Thank you! I have added the test case in the issue #12843 .

**Comment by wkcn** [comment]
Hi! I submit an [issue](https://github.com/numpy/numpy/issues/12264) to `NumPy`.
This PR will be useless if the members of `NumPy` consider it a bug.

**Comment by wkcn** [comment]
@eric-haibin-lin Thanks. I will fix it.

**Comment by ankkhedia** [comment]
@eric-haibin-lin It seems the comments has been addressed. Could you please take a look?

@wkcn Could you please rebase and resolve conflicts so that the changes passes CI.

**Comment by wkcn** [comment]
@ankkhedia Thanks! I have resolved the conflicts.

**Comment by eric-haibin-lin** [comment]
I'm a bit concerned that by c standard longlong requires at least 64 bit and there's no guarantee it's always mapped to `int64_t` in the future (although most implementations map it to int64..)

**Comment by wkcn** [comment]
@eric-haibin-lin 
it is related to NumPy.
If  c_longlong is 128 bits,  I think that np.dtype(np.longlong).name will be int128.

**Comment by anirudhacharya** [comment]
@wkcn @eric-haibin-lin any update on the above issue? pinging for another round of review

**Comment by wkcn** [comment]
@anirudhacharya 
Thank you!
I don't know whether the PR is required.
The PR can solve the issue #12843 
However, the bug is caused by SciPy rather than MXNet.
The PR will allow to write some confused script like `mx.nd.array([1,2,3], dtype=np.longlong)`, which is not strict.

**Comment by stu1130** [comment]
@wkcn Thanks for doing this. Since the issue is not caused by mxnet, could you close the PR?
@eric-haibin-lin feel free to reopen the PR if you have a different opinion once it is closed

**Comment by wkcn** [comment]
@stu1130 Thank you!

**Pull request closed without merging**
