### PR TITLE
Fix convenient method for np.sum

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
As title

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Fix and test coverage

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by haojin2** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by haojin2** [comment]
@mxnet-bot run ci [all]

**Comment by leezu** [comment]
@haojin2 please link the issue you're fixing to avoid duplicate work https://github.com/apache/incubator-mxnet/pull/18152

**Comment by haojin2** [comment]
I thought @sxjscience was well aware of this fix 2 days ago (he approved this PR 2 days ago), have you guys not synced at all on this issue? I guess maybe you need to communicate with issue author a bit before actually delivering a fix in the future ;-)

**Comment by leezu** [comment]
@haojjin2 this issue does also affect more people besides @sxjscience. Given there is no communication on the issue and the issue was blocking my work, I implemented a fix. Suggest you follow the best practice in the future..

**Pull request merged**
