### PR TITLE
make rat-excludes compliant with apache release policy

### PR DESCRIPTION
**Pull request by szha**
## Description ##
make rat-excludes compliant with apache release policy

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] remove md

## Comments ##
- https://lists.apache.org/thread.html/51e9ab05edae2089c74a253000a92d5aa5c6406f54e5bd0a0b3c3879@%3Cgeneral.incubator.apache.org%3E feedback from @lresende

### CODE REVIEW

**Comment by szha** [comment]
Here's the Markdown files currently not in compliance
```
CONTRIBUTORS.md
MKLDNN_README.md
NEWS.md
README.md
amalgamation/README.md
ci/README.md
ci/publish/README.md
ci/qemu/README.md
contrib/clojure-package/README.md
contrib/clojure-package/testing.md
contrib/clojure-package/examples/captcha/README.md
contrib/clojure-package/examples/cnn-text-classification/README.md
contrib/clojure-package/examples/gan/README.md
contrib/clojure-package/examples/imclassification/README.md
contrib/clojure-package/examples/infer/imageclassifier/README.md
contrib/clojure-package/examples/infer/objectdetector/README.md
contrib/clojure-package/examples/infer/predictor/README.md
contrib/clojure-package/examples/module/README.md
contrib/clojure-package/examples/multi-label/README.md
contrib/clojure-package/examples/neural-style/README.md
contrib/clojure-package/examples/pre-trained-models/README.md
contrib/clojure-package/examples/profiler/README.md
contrib/clojure-package/examples/rnn/README.md
contrib/clojure-package/examples/tutorial/README.md
contrib/clojure-package/examples/visualization/README.md
cpp-package/README.md
cpp-package/example/README.md
cpp-package/example/feature_extract/README.md
cpp-package/example/inference/README.md
example/README.md
example/adversary/README.md
example/autoencoder/README.md
example/autoencoder/variational_autoencoder/README.md
example/bayesian-methods/README.md
example/bi-lstm-sort/README.md
example/caffe/README.md
example/capsnet/README.md
example/captcha/README.md
example/cnn_chinese_text_classification/README.md
example/cnn_text_classification/README.md
example/ctc/README.md
example/deep-embedded-clustering/README.md
example/distributed_training/README.md
example/dsd/README.md
example/fcn-xs/README.md
example/gluon/audio/urban_sounds/README.md
example/gluon/dc_gan/README.md
example/gluon/embedding_learning/README.md
example/gluon/sn_gan/README.md
example/gluon/style_transfer/README.md
example/gluon/tree_lstm/README.md
example/gluon/word_language_model/README.md
example/kaggle-ndsb1/README.md
example/kaggle-ndsb2/README.md
example/model-parallel/matrix_factorization/README.md
example/module/README.md
example/multi-task/README.md
example/multivariate_time_series/README.md
example/named_entity_recognition/README.md
example/nce-loss/README.md
example/neural-style/README.md
example/neural-style/end_to_end/README.md
example/numpy-ops/README.md
example/profiler/README.md
example/rcnn/README.md
example/recommenders/README.md
example/reinforcement-learning/a3c/README.md
example/reinforcement-learning/ddpg/README.md
example/reinforcement-learning/parallel_actor_critic/README.md
example/restricted-boltzmann-machine/README.md
example/rnn/README.md
example/rnn/bucketing/README.md
example/rnn/old/README.md
example/rnn/word_lm/README.md
example/sparse/factorization_machine/README.md
example/sparse/linear_classification/README.md
example/sparse/matrix_factorization/README.md
example/sparse/wide_deep/README.md
example/speech_recognition/README.md
example/ssd/README.md
example/ssd/dataset/pycocotools/README.md
example/ssd/model/README.md
example/ssd/symbol/README.md
example/ssd/tools/caffe_converter/README.md
example/stochastic-depth/README.md
example/svm_mnist/README.md
example/svrg_module/README.md
example/vae-gan/README.md
julia/LICENSE.md
julia/NEWS.md
julia/README-DEV.md
julia/README.md
julia/examples/char-lstm/README.md
julia/plugins/README.md
matlab/README.md
perl-package/README.md
perl-package/AI-MXNet/examples/gluon/style_transfer/README.md
perl-package/AI-MXNet/examples/sparse/matrix_factorization/README.md
perl-package/AI-MXNet/examples/sparse/wide_deep/README.md
plugin/caffe/README.md
python/README.md
python/minpy/README.md
scala-package/README.md
scala-package/memory-management.md
scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/objectdetector/README.md
scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/predictor/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/benchmark/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/cnntextclassification/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/customop/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/gan/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/imageclassifier/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/objectdetector/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/neuralstyle/README.md
scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/README.md
scala-package/mxnet-demo/java-demo/README.md
scala-package/mxnet-demo/scala-demo/README.md
scala-package/native/README.md
scala-package/packageTest/README.md
scala-package/spark/README.md
tests/README.md
tests/nightly/README.md
tests/nightly/apache_rat_license_check/README.md
tests/nightly/broken_link_checker_test/README.md
tests/nightly/model_backwards_compatibility_check/README.md
tests/nightly/straight_dope/README.md
tests/python/README.md
tools/accnn/README.md
tools/bandwidth/README.md
tools/caffe_converter/README.md
tools/caffe_translator/README.md
tools/caffe_translator/build_from_source.md
tools/caffe_translator/faq.md
tools/cfn/Readme.md
tools/coreml/README.md
tools/dependencies/README.md
tools/staticbuild/README.md
```

**Comment by szha** [comment]
Markdown license headers have been added.

**Comment by ankkhedia** [comment]
@szha Thanks for your contribution!
@mxnet-label-bot add [pr-awaiting-review]

**Comment by lanking520** [comment]
API docs are breaking:
http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-14142/9/index.html

**Comment by aaronmarkham** [comment]
@szha as [I said on the dev list](https://lists.apache.org/thread.html/be85b556f1c3f96c70f59b6535215b6d70236736fa10eb463b7b9d99@%3Cdev.mxnet.apache.org%3E), adding license headers to the markdown isn't required and might break the website. You also had that comment from Justin that referred to the same policy. I realize you're getting mixed signals on the general list. The policy clearly states we don't need to add licenses for information files and for the website. 

If you check your preview, you'll see that the site is broken.
I just cancelled the website publish job that was going to push these changes to production. If you revert this PR, we can avoid publishing a broken website. 
Thanks.

**Comment by szha** [comment]
@aaronmarkham adding license header is required. I'm happy to submit patch to fix the website but we should not take a backward step.

**Comment by gigasquid** [comment]
The Beam project seems to embed the licenses in their markdown files. Maybe we can do the same thing? 
Example: https://raw.githubusercontent.com/apache/beam/88acc8eb84c128bab6f8c655cdbba9270f44b94c/website/src/get-started/quickstart-go.md

**Comment by gigasquid** [comment]
Oh I see this PR has the license embedded in the same way as the Beam project. They are using https://github.com/apache/beam/tree/master/website Jekyll though for generation.

**Comment by szha** [comment]
It might have been caused by unpaired number of dashes in the comment. I'm verifying this assumption in the PR above.

**Pull request merged**
