### PR TITLE
Remove deepnumpy reference and move Numpy tutorials to top level

### PR DESCRIPTION
**Pull request by ys2843**
## Description ##
fix https://github.com/apache/incubator-mxnet/issues/18566#issuecomment-663901184 and https://github.com/apache/incubator-mxnet/pull/18691#discussion_r460479156. Remove deepnumpy reference and move numpy tutorials to package top level.

### Changes ###
- [x] Removed "deepnumpy" reference
- [x] Move numpy tutorials to top level

In additions
- [x] Refactored python website layout (removed the duplicate drawer and bundled js)
- [x] Replace NDArray with np.ndarray.

## Comments ##
- Preview: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/

### CODE REVIEW

**Comment by ys2843** [comment]
@mxnet-label-bot add [Website]

**Comment by ys2843** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu]

**Comment by ys2843** [comment]
@szha

**Comment by szha** [comment]
Thanks for the update and for pinging.

image

Two issues that would be great to fix:
- Notice the wasted space on the right. it would be good if the cards utilize that space instead of hardcoding two cards per row.
- NDArray will be deprecated. Please replace it with np.ndarray.

**Comment by szha** [comment]
Also, consider introducing "Edit on GitHub" button that replaces "Show source" in the top right. See the example from GluonNLP:

image

This, in combination with PR website preview, will make it a lot easier to address website issues.

**Comment by ys2843** [comment]
@szha Thanks for reviewing. I have made following changes and updated the preview: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/

+ Refactored the layout of python website body so that the cards are positioned flexibly.
+ Replaced NDArray with np.ndarray.

**Comment by szha** [comment]
thank you. somehow it still doesn't make the use of the space on the right:

image

**Comment by ys2843** [comment]
> thank you. somehow it still doesn't make the use of the space on the right:
> 

Please **clean the cache** and see the preview: http://ec2-18-236-134-13.us-west-2.compute.amazonaws.com/api/python/docs/tutorials/getting-started/index.html

Extended the width to 100% for high resolution devices, this is the most we can do, because there is still a table of content widget on the right.

**Comment by szha** [comment]
nice! thanks for the updates.

**Pull request merged**
