### PR TITLE
[MXNET-601] Disable Caffe converter (disable #11407)

### PR DESCRIPTION
**Pull request by marcoabreu**
## Description ##
Disable Caffe converter test due to https://github.com/apache/incubator-mxnet/issues/11407. 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by larroy** [comment]
LGTM

**Comment by ThomasDelteil** [comment]
can we not just upload the image to dmlc/web-data ?

**Comment by marcoabreu** [comment]
@ThomasDelteil I'm out this evening now. Would you mind driving the fix?

**Comment by ThomasDelteil** [comment]
ok

**Comment by marcoabreu** [comment]
Is it the same image for sure?

**Comment by larroy** [comment]
If CI is failing, first would be propper to send the quick fix, then address the issue with the image. Not the other way around.

**Comment by ThomasDelteil** [comment]
I agree but in that case I'd argue that replacing 3 urls is as quick as commenting out 5 lines and actually fixes the problem

**Comment by ThomasDelteil** [comment]
We can merge that one if you want and then revert it once the other one is merged I don't mind

**Comment by cjolivier01** [comment]
jpg is up there ^

**Comment by marcoabreu** [comment]
Thanks @ThomasDelteil

**Comment by KellenSunderland** [comment]
Still getting occasional failures pulling from github.  

Sample output:
```
INFO:root:getting image https://github.com/dmlc/web-data/raw/master/mxnet/doc/tutorials/python/predict_image/cat.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
Traceback (most recent call last):
  File "tools/caffe_converter/test_converter.py", line 109, in <module>
    main()
  File "tools/caffe_converter/test_converter.py", line 103, in main
    test_model_weights_and_outputs(m, args.image_url, gpus[0])
  File "tools/caffe_converter/test_converter.py", line 77, in test_model_weights_and_outputs
    mean_diff_allowed=1e-03, max_diff_allowed=1e-01)
  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 120, in convert_and_compare_caffe_to_mxnet
    img_rgb = read_image(image_url, image_dims, caffe_mean)
  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 51, in read_image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

**Pull request closed without merging**
