### PR TITLE
Fix data-apis links

### PR DESCRIPTION
**Pull request by bgawrych**

### CODE REVIEW

**Comment by DickJC123** [comment]
Not surprisingly, this is affecting all PRs.  Hoping for a quick merge since this PR appears to have corrected the linkcheck failure.

**Comment by bgawrych** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by DickJC123 — APPROVED** [review]
Given this is a non-functional change to the documentation, and appears to correct the CI failure it targets,  I approve this PR.

**Comment by DickJC123** [comment]
Hope you don't mind- triggered the windows-gpu job again hoping for a clean CI (I'd like to see this merged to help the link check failures across all PRs).

**Comment by bgawrych** [comment]
Merged

**Pull request merged**
