### PR TITLE
julia/ndarray: fix flaky test cases for `clamp`

### PR DESCRIPTION
**Pull request by iblis17**
ref: #14757 

CI build: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14757/2/pipeline

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
The CI is blocked. Thanks to work on this @iblis17

**Comment by larroy** [comment]
Thanks for the PR.

**Comment by larroy** [comment]
@mxnet-label-bot add [Julia, Flaky]

**Comment by larroy** [comment]
@mxnet-label-bot add [Test]

**Pull request merged**
