### PR TITLE
[BACKPORT]Add option to build with shared c runtime on windows (#19409)

### PR DESCRIPTION
**Pull request by access2rohit**
Co-authored-by: vlado <vlado@indicalab.com>

Backport #19409 as a part of effort #19911

### CODE REVIEW

**Comment by access2rohit** [comment]
@vladoovtcharov @szha can you review ?

**Comment by access2rohit** [comment]
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, windows-cpu]

**Comment by access2rohit** [comment]
@yajiedesign please review

**Comment by vladoovtcharov** [comment]
I'm not a reviewer, but looks like the commit got backported correctly

**Pull request merged**
