### PR TITLE
[MXNET-137]fix parameters name inconsistent for Proposal OP and Multi Proposal OP

### PR DESCRIPTION
**Pull request by wkcn**
## Description ##
Hi, there.
There is parameters name inconsistent in Proposal OP and Multi Proposal OP.
Proposal OP:
[cls_prob](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal-inl.h#L160) vs [cls_score](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal.cc#L462)

Multi Proposal OP:
[cls_prob](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/multi_proposal-inl.h#L162) vs [cls_score](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/multi_proposal.cc#L500)

It seems that the parameter name should be `cls_prob` rather than `cls_score`.
[The parameter prompt](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal-inl.h#L107)
[Faster R-CNN example](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/symbol/symbol_resnet.py#L193)

So I replace `cls_score` with `cls_prob`, and I change the parameter name in the unittest for Proposal OP and Multi Proposal OP.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Replace the parameter name `cls_score` with `cls_prob` in Proposal OP and Multi Proposal OP
- [x] Change the parameter name `cls_score` in the unit-test for Proposal OP and Multi Proposal OP

### CODE REVIEW

**Comment by piiswrong** [comment]
This breaks API compatibility. We can only change this if and when we decide to move these ops out of contrib. 
Please put a comment in there as reminder

**Comment by wkcn** [comment]
@piiswrong 
Thank you!
But I found a problem.
When using `mx.nd.Proposal` or `mx.nd.MultiProposal`, the parameter name is `cls_score`.
When using `mx.sym.Proposal` or `mx.sym.MultiProposal`, the parameter name is `cls_prob`.

**Comment by piiswrong** [comment]
that's strange. Are you sure?

**Comment by wkcn** [comment]
@piiswrong 
Yes. I use the test case, [code](https://gist.github.com/wkcn/8015feae59a63956884d1ef8b9fbb743)
If I replace `cls_score` with `cls_prob` in the code, it will raise the error:
```
Traceback (most recent call last):
  File "/home/wkcn/proj/testpy/testmxp.py", line 95, in <module>
    test(rpn_pre_nms_top_n, rpn_post_nms_top_n)
  File "/home/wkcn/proj/testpy/testmxp.py", line 58, in test
    rpn_min_size = rpn_min_size, output_score = True)
  File "<string>", line 82, in Proposal
  File "/home/wkcn/proj/mxnet/python/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/wkcn/proj/mxnet/python/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Cannot find argument 'cls_prob', Possible Arguments:
```

But it's right to use `cls_prob` in mx.sym.contrib.Proposal in [the code](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/symbol/symbol_resnet.py#L193)

The reason is that the function `ListArguments()` in [proposal-inl.h](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal-inl.h#L160) returns `{"cls_prob", "bbox_pred", "im_info"}`, it's used in symbol.
However, `.add_argument("cls_score", "NDArray-or-Symbol", "Score of how likely proposal is object.")` in [proposal.cc](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal.cc#L462) is used in ndarray.

**Comment by piiswrong** [comment]
ok...
I think we should make them consistent by using the sym version

**Comment by piiswrong** [comment]
@wkcn ping

**Comment by wkcn** [comment]
@piiswrong 
Hi! 
The document shows that [the sym version](https://mxnet.incubator.apache.org/api/python/symbol/contrib.html?highlight=proposal#mxnet.symbol.contrib.Proposal) of Proposal OP uses **cls_score**.
However, [the Faster R-CNN example](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/symbol/symbol_resnet.py#L193) uses **cls_prob**.

If making them consistent by using the sym version(cls_score), the old example and other detection projects([Deformable-ConvNets](https://github.com/msracver/Deformable-ConvNets/blob/master/faster_rcnn/symbols/resnet_v1_101_rcnn.py#L741), [mx-rcnn](https://github.com/precedenceguo/mx-rcnn/blob/master/rcnn/symbol/symbol_resnet.py#L100)) will be an error of parameter.

I think using `cls_prob` is better. [mxnet.ndarray.contrib.MultiBoxDetection](https://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=multibox#mxnet.ndarray.contrib.MultiBoxDetection) uses `cls_prob` too.

**Comment by WalterMa** [comment]
Same strange issue: symbol and ndarray proposal operator api are inconsistent.
@wkcn Do you try change symbol parameter to `cls_score` that would not break API compatibility?

**Comment by wkcn** [comment]
@WalterMa 
Yes.
If you replace cls_prob with cls_score in [this line](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/proposal-inl.h#L160), the symbol parameter will change to cls_score.

**Comment by WalterMa** [comment]
@wkcn 
Thanks a lot!

Just personal opinion:
Would it be better to replace `cls_prob` with `cls_score`, since in both sym and nd API docs its parameter name is cls_score.
https://mxnet.incubator.apache.org/api/python/ndarray/contrib.html#mxnet.ndarray.contrib.Proposal
https://mxnet.incubator.apache.org/api/python/symbol/contrib.html#mxnet.symbol.contrib.Proposal

But In fact this will also break API compatibility, such as these [code](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/symbol/symbol_vgg.py#L245) in example/rcnn. 
Don't know what to do...

**This issue has a direct impact on hybrid_forward in gluon that cannot hybridize network used Proposal operator.** 
Hope it be addressed soon.

**Pull request merged**
