### PR TITLE
[MXNET-16] Move mshadow/ps-lite/dlpack to 3rdparty #10132

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@cjolivier01 @szha @marcoabreu please review this PR. Moving nnvm & dmlc-core is much more tricky as many places in amalgamation will be broken. That will be addressed in another PR.

**Comment by eric-haibin-lin** [comment]
@mbaijal please review license changes

**Comment by mbaijal** [comment]
@eric-haibin-lin 
dlpack and mshadow should still be included in the LICENSE file. Only the paths to the license txt should change.

**Comment by eric-haibin-lin** [comment]
@mbaijal  I see. will do

**Comment by marcoabreu** [comment]
Could you elaborate on the Amalgamation part? If it breaks due to this change, why does CI pass?

**Comment by eric-haibin-lin** [comment]
@marcoabreu  This PR doesn't move nnvm nor dmlc-core. I attempted to move them in #10122 but amalgamation would break.

**Comment by marcoabreu** [comment]
Ah I see

**Comment by eric-haibin-lin** [comment]
@marcoabreu does CI test CMake with dist-kvstore=ON? @rahul003 complained that this PR breaks cmake build

**Comment by rahul003** [comment]
@eric-haibin-lin Sorry looks like I was wrong. It is fine. I'm not sure what happened when I tried earlier. 

But I just looked at CI commands and wow none of the environments build with USE_DIST_KVSTORE.
@marcoabreu IMO we should enable this for all of them. What do you think @eric-haibin-lin ? 
This build flag requires a few dependencies. So that needs to be tested.

**Comment by marcoabreu** [comment]
@rahul003 yes, these are the right commands. Feel free to add it. Just for clarification: This does not require multiple GPUs or nodes, right? What hardware requirements does it have?

Does the behaviour change if that flag is enabled or is just an additional feature? In case of the former, please only add it to a few builds. In case of the latter, feel free to add it to all test cases.

**Pull request merged**
