### PR TITLE
[example/sparse/factorization_machine/]add auc and fix the typo in re…

### PR DESCRIPTION
**Pull request by burness**
add the auc in fm metric.py and fix the "train-data"/"test-data" to "data-train"/"data-test"

### CODE REVIEW

**Comment by szha** [comment]
ping

**Comment by burness** [comment]
I will do some fixes later

**Comment by eric-haibin-lin** [comment]
do you mind merging with the latest master? it looks like the base version of your branch has some flaky test.
git remote add upstream https://github.com/dmlc/mxnet
git fetch upstream master
git merge upstream/mater

**Comment by burness** [comment]
@eric-haibin-lin  It seems that your criteo dataset from  https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#criteo, all of the test dataset has the label 0, you can check the dataset and kdd2012 is the better one

**Pull request merged**
