### PR TITLE
[1.7.x] Fix memory leaks in Gluon

### PR DESCRIPTION
**Pull request by leezu**
Backport https://github.com/apache/incubator-mxnet/pull/18328

### CODE REVIEW

**Comment by leezu** [comment]
@mxnet-bot run ci [all]

**Comment by ciyongch** [comment]
@TaoLv @pengzhao-intel please take a review and help to merge it :)

**Comment by TaoLv** [comment]
Please also make sure it's fixed on branch v1.x.

**Comment by ciyongch** [comment]
@TaoLv here's the PR for v1.x branch: https://github.com/apache/incubator-mxnet/pull/18359

**Comment by leezu** [comment]
@zhreshold should we revert this PR on the 1.7 and 1.x branch as weakref doesn't work with  deepcopy?

https://github.com/dmlc/gluon-cv/blob/428ee05d7ae4f2955ef00380a1b324b05e6bc80f/gluoncv/data/transforms/presets/yolo.py#L144

(Though I'm surprised that `copy.deepcopy` worked in the first place)

**Comment by zhreshold** [comment]
@leezu Fix to mem leak is nice to have and I don't see any problem with this pariticular PR, however, `deepcopy` of a full network isn't a rare usecase which means a fix to deepcopy is needed anyway. 

In fact, the behavior of `__deepcopy__` of a `Block` has to be overrided with the `_BlockScope` being renewed in the new `Block`, and the suspicious copy behavior of parameters has to be verified and secured.

**Pull request merged**
