### PR TITLE
fix bug in TryCrop()

### PR DESCRIPTION
**Pull request by cypw**
The conditions for the TryCrop() is incorrect.

### CODE REVIEW

**Comment by zhreshold** [comment]
All conditions must be true.

**Comment by zhreshold** [comment]
Make sense. LGTM.

**Comment by cypw** [comment]
Thank you.

btw, please note that the settings of `rand_crop_samplers` in [example/ssd/config/config.py \(Line56\)](https://github.com/apache/incubator-mxnet/blob/master/example/ssd/config/config.py#L56) are meaningless before this bug fixed, since some of the conditions are not true.

**Comment by piiswrong** [comment]
The logic in this entire if section looks weird.
@zhreshold Could you verify its working as intended?

**Comment by zhreshold** [comment]
The cropping is verified working as intended, however, I reckon some of the presets should be updated because I found some rule have to be satisfied in random cropping to provide better behaviors.
If anyone as more suggestions to this part, please let me know.

**Pull request merged**
