### PR TITLE
[DOC] Consistent capitalization: mxnet -> MXNet, scala -> Scala

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by karan6181** [comment]
@mxnet-label-bot add [Doc, pr-awaiting-review]

**Comment by terrytangyuan** [comment]
Travis failure is unrelated since this is just a simple doc change

**Comment by szha** [comment]
@terrytangyuan feel free to retry the build if that's the case. To retry, you can click on the Details button of the failed checks, click login in the upper-right corner, and then click the retry button at the top the page (the one next to the Artifacts stub).

**Comment by terrytangyuan** [comment]
Thanks @szha. @ChaiBapchya Yes it’s already there.

**Comment by terrytangyuan** [comment]
@ChaiBapchya Your approval won’t work since you are not a committer.

@szha Could you approve this?

**Pull request merged**
