### PR TITLE
Remove out-dated examples using mx.module

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
After https://github.com/apache/incubator-mxnet/pull/18394/files, we have removed the `mx.model.Feedforward` API and related examples. Following https://github.com/apache/incubator-mxnet/issues/17676, there will be a series of PRs that enhances Gluon execution & removing mx.module API for mxnet 2.0. In this PR, I am removing most of the examples that 
1. use `mxnet.module.Module` APIs for model training, and
2. are not actively maintained for the past few releases 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
While we remove the outdated examples [as module api is no longer supported], would it be a good idea to update these examples to use the correct API [replacement of module] instead of removing these examples altogether?

**Comment by ChaiBapchya** [comment]
Right. One issue MXNet users face is the lack of examples & documentation around it.
Removing existing examples without substituting with working equivalent code would only exacerbate. I'm not sure if MXNet users come to Github repo for these examples & what was the purpose of pushing examples in this repository. 

Makes sense to create a Github Issue to call for contributions from the community.

**Comment by eric-haibin-lin** [comment]
created an issue https://github.com/apache/incubator-mxnet/issues/18458

**Comment by leezu** [comment]
@ChaiBapchya I think another issue is the prevalence of outdated examples. As developers can always access the outdated examples via the git history and the list of examples is tracked in https://github.com/apache/incubator-mxnet/issues/18458, let's merge this PR

**Comment by yifeim** [comment]
> @ChaiBapchya as you can see the number of examples affected is large and it requires lots of efforts to rewrite all of them. While I am happy to create a github issue listing them and welcome contribution from the community, one problem is that **these examples are not really tested in the CI pipeline**, which makes it hard to maintain

Isn't **this** the problem to solve?

**Comment by ChaiBapchya** [comment]
Testing all these examples in CI is
- big task in itself
- quite expensive [as currently we don't have a smart way of testing in CI [selective testing based on code coverage for starters]. We can't expect to test every example for every single PR sent to the repository.

Having said that, if someone in the community is willing to volunteer to 
a. Add the working version of the dropped examples to repository
b. Add corresponding tests in CI
c. [Preferably] Find a way to only test these examples when corresponding code is changed
Then that's a silver bullet!

**Comment by yifeim** [comment]
> Testing all these examples in CI is
> 
> * big task in itself
> * quite expensive [as currently we don't have a smart way of testing in CI [selective testing based on code coverage for starters]. We can't expect to test every example for every single PR sent to the repository.
> 
> Having said that, if someone in the community is willing to volunteer to
> a. Add the working version of the dropped examples to repository
> b. Add corresponding tests in CI
> c. [Preferably] Find a way to only test these examples when corresponding code is changed
> Then that's a silver bullet!

* run all examples once and index the code blocks that are executed.
* build a reverse index for new codes submitted.
* update the reverse index after the codes are merged.
* rinse and repeat as a general library.

If people haven't built it, it seems to be a useful tool to have.

**Pull request merged**
