### PR TITLE
Fix build with system's openmp

### PR DESCRIPTION
**Pull request by hubutui**
## Description ##
This pr fix build with openmp by:
1. find openmp using `FindOpenMP` module from cmake
2. if not found, use build openmp from source using 3rd party submodule.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

This pr is a minor modification of `CMakeLists.txt`, simply find openmp firstly in the system, and then build from source if not found.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Sounds less like a fix but rather a change in the logic if I'm not mistaken.

It would be good to have performance numbers before we move forward with this PR.

@larroy @lebeg @cjolivier01

**Comment by lebeg** [comment]
I'm afraid that this change is rather a complicated one due to long discussions that have not ended yet. You can find more info on the dev mailing list: [[Discussion] Remove bundled llvm OpenMP](https://lists.apache.org/thread.html/4827f0f742b6e7e070da350ea81226d059401527f3072ce8b33c1fdf@%3Cdev.mxnet.apache.org%3E). Initially the proposed change was in this PR [#12160: Remove conflicting llvm OpenMP from cmake builds ](https://github.com/apache/incubator-mxnet/pull/12160).

We have already provided performance data on this, you can find and announcement on dev [here](https://lists.apache.org/thread.html/53030388434c90552d8dbed13488e25c1b153c53fc5970369f715e48@%3Cdev.mxnet.apache.org%3E) and the document [here](https://cwiki.apache.org/confluence/x/2wclBg).

That was not enough, for reasons that are unclear to me, to convince everybody on validity and necessity of this change.

Latest discussions happen in following dev threads: [OMP](https://lists.apache.org/thread.html/a4435d48f4253c85821e19828e57f706582926f70cd9f73cbe2dc080@%3Cdev.mxnet.apache.org%3E) and [[VOTE] Remove conflicting OpenMP from CMake builds](https://lists.apache.org/thread.html/f9897d76cd073f7a83cf6837ccacaf70670a592d727f0c2baa7a503b@%3Cdev.mxnet.apache.org%3E).

@hubutui If you feel motivated enough to proceed with this change you can join the debate.

**Comment by hubutui** [comment]
@lebeg Hmm, actually, do user really care that much about performance affected by different OpenMP? As a packager's opinion, I want a good way to create this package. Maybe we could give user an option to choose the OpenMP, just like BLAS.

**Comment by lebeg** [comment]
Yes, it might be a good idea, but the numbers as stated in the performance doc don't differ that much. Managing this dependency within MXNet isn't a good idea at all in my opinion.

**Comment by hubutui** [comment]
It's been a long time since the discussion. I'll remove `3rdparty/openmp` before building, so that cmake would use openmp from system instead.

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by larroy** [comment]
@hubutui would it be possible to add a CMake option to choose the OpenMP implementation that one wishes for?  There's three options, MKL, 3rdparty OpenMP and the one found in the platform. So I think the pr goes in the good direction but we would need a commandline option.

**Comment by cjolivier01** [comment]
I don't think this is a good idea. we should standardize on one
implementation.  Like I have pointed out, the default make build uses
llvm/intel version.  cmake builds us llvm/intel version.  if libgomp is
still being included, removing it should be investigated.  Trying to
flip-flop between them on a whim is asking for trouble, and currently I
know of no advantage to using libgomp.

**Comment by hubutui** [comment]
@cjolivier01 #9686 suggests transitioning fully to cmake, it would help a lot. Maybe dropping the Makefile someday?

**Comment by cjolivier01** [comment]
Using cmake is another subject altogether.
How is this PR not basically what was already blocked?

**Comment by cjolivier01** [comment]
This is basically a duplicate of turning on llvm openmp.

**Comment by larroy** [comment]
But we are distributing pip wheels with libgomp, at least we should be able to replicate that for development purposes.

**Comment by szha** [comment]
the reason is that there is mismatch between cmake and make builds. pip is currently using make for building libmxnet. for now if you want to replicate that you can use make

**Comment by larroy** [comment]
@szha understood. it would be beneficial to be able to replicate that with CMake by having a selector for the openmp lib until then.

**Pull request closed without merging**
