### PR TITLE
Fixing unintentional variable overloading

### LINKED ISSUE #14439: Recommender example is broken
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Symbol used for enumeration in for loops is unintentionally overridden within the loop, which replaces the integer value with an mx.nd.array.  This value is used in the return to scale the results, so it throws an exception.

## Environment info (Required)
Ubuntu 16.01.

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
Python

## Steps to reproduce
Run the example.

## What have you tried to solve it?
Submitted #14438

### PR DESCRIPTION
**Pull request by zjost**
## Description ##
In the recommender example, the for loop uses `i` for enumeration, but then `i` is also used within the loop for list comprehensions, which breaks their utility.  Instead of being an integer, `i` becomes an mx.nd.array

resolves #14439

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Changed from symbol `i` to `idx` in loop within `matrix_fact.evaluate_network` 
- [x] Changed from symbol `i` to `idx` in loop within `matrix_fact.train`

### CODE REVIEW

**Comment by zjost** [comment]
Done, thanks!

**Comment by karan6181** [comment]
@mxnet-label-bot add [Example, Bug, Python, pr-awaiting-testing]

**Comment by karan6181** [comment]
@zjost Thank you for your contribution!

Could you please look into the CI test failure? Thanks!

**Comment by zjost** [comment]
Looks like something related to a clojure artifact.  This should have nothing to do with my changes.

**Comment by zachgk** [comment]
@zjost Cool trick: If you edit the PR description and add `resolves #14439`, then it will automatically resolve the issue when the PR is merged (https://help.github.com/en/articles/closing-issues-using-keywords). Otherwise, it is good to at least mention the issue from the PR.

Your PR is breaking on the clojure test due to an unrelated issue (#14448). You should rebase your commit onto master (git pull --rebase) so the fix to that issue is applied to your commit. It should pass the CI after that

**Comment by zjost** [comment]
`The command '/bin/sh -c /work/ubuntu_publish.sh' returned a non-zero code: 100`

**Comment by anirudh2290** [comment]
@zjost you can push an empty commit to retrigger the test. also can you rebase the latest master onto your branch.

**Comment by zjost** [comment]
If the code leading to the test failures is already in master, what's the harm of merging my rather innocuous changes to the example?  Presumably the code I'm needing to rebase against is failing the same tests.

**Comment by zjost** [comment]
Sweet, thanks!

**Comment by szha** [comment]
@zjost thanks for the patch!

**Pull request merged**
