### PR TITLE
moveaxis operator now accepts negative indices and sequence of ints as well.

### PR DESCRIPTION
**Pull request by ifeherva**
## Description ##
The moveaxis operator is now numpy compatible by accepting negative indices and tuples as well. Added a series of unit tests based on the original numpy repo.

Adds request from https://github.com/apache/incubator-mxnet/issues/13563

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)

- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Comment by vandanavk** [comment]
@ifeherva could you check the CI failures and re-trigger the build?

**Comment by ifeherva** [comment]
@vandanavk the error messages do not really make sense to me, they look unrelated to the content of this PR. Can someone retrigger CI please?

**Comment by ifeherva** [comment]
Tests are very flaky, none of them related to this PR.

**Comment by wkcn** [comment]
Sorry that I wrote a typo, which should be retrigger.

**Comment by wkcn** [comment]
I do not know why this CI always fail.

**Comment by ifeherva** [comment]
Strange that the same GPU test fail though I am puzzled how these changes contribute to CUDA errors.

**Comment by wkcn** [comment]
Could we disable the new testcase to track the error?

**Comment by wkcn** [comment]
I guess assert_exception has some problems.

**Comment by wkcn** [comment]
Current MXNet Does not support zero size tensor, so I modified the testcase.

**Comment by wkcn** [comment]
Great! Glad to merge it.
Thanks for your contribution!

**Comment by ifeherva** [comment]
Thanks for figuring out the error!

**Pull request merged**
