### PR TITLE
[MXNET-711] Added updated logos to the powered by page and iot select fix

### PR DESCRIPTION
**Pull request by kpmurali**
## Description ##
Updating logos to the powered by page. Added Clojure to the navigation list for APIs.

### Changes ###
- [x] Added updated logos to the powered by page
- [x] Added Clojure to the navigation list for APIs.
- [x] IOT selector fix in the install page.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
Clojure API preview:
http://54.225.32.15/api/clojure/index.html

Powered By (logos update) preview:
http://54.225.32.15/community/powered_by.html

**Comment by aaronmarkham** [comment]
@gigasquid

**Comment by aaronmarkham** [comment]
@szha Can you take a look. This fixes several things on the site. Adds Clojure and updates logos...

**Comment by szha** [comment]
image

**Comment by szha** [comment]
I see the above. I'm on OSX with a Chrome 67.0. and who's powered by who again?

**Comment by aaronmarkham** [comment]
FYI, I'm working on fixing the footer issue and will break these features out into different PRs.

**Comment by aaronmarkham** [comment]
I looked at this along with SK and we were not able to figure out how to fix the footer properly. Basically, there's some last minute client-side injection going on with the Sphinx theme. It takes the right toolbar content and appends it to the left making for just one Sphinx toolbar. This is done *after* bootstrap initializes and knows what's on the page. Because that toolbar div is longer now, it didn't push the footer down as expected. We tried a variety of hacks, but basically the Sphinx toolbar "modification" on the left nav pretty much broke things. That would likely need to be undone to fix bootstrap and to fix the footer properly.

@sandeep-krishnamurthy - I saw in the history you might know what's going on here with the Sphinx left side toolbar.

**Comment by lebeg** [comment]
The bug visible only for narrow screen:
screen shot 2018-09-03 at 10 50 51

Otherwise it looks alright:
screen shot 2018-09-03 at 10 51 02

**Comment by lupesko** [comment]
@kpmurali - are you still actively working on this PR?

**Comment by vrakesh** [comment]
@aaronmarkham Is this PR good to close?

**Comment by aaronmarkham** [comment]
@vrakesh Yes, please close it.

**Pull request closed without merging**
