### PR TITLE
[MXNET-649] [R] CNN Tutorial Fix

### PR DESCRIPTION
**Pull request by anirudhacharya**
## Description ##
Fix the Cats vs Dogs tutorial for R API.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by vrakesh** [comment]
@anirudhacharya Requesting to look into the build failure

@mxnet-label-bot [pr-awaiting-review, Docs]

**Comment by Roshrini** [comment]
Hi @anirudhacharya, Its very difficult to review this PR. Do you mind cleaning it up? Also, can you look into the CI failure?

**Comment by anirudhacharya** [comment]
@Roshrini apologies for the delay, will make the required changes.

**Comment by roywei** [comment]
ping @anirudhacharya, any updates on this PR?

**Comment by anirudhacharya** [comment]
will reopen this PR once I update it.

**Pull request closed without merging**
