### PR TITLE
Fix broken unit test compilation

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
Fixes unit tests compilation which is broken. (Has to be enabled in CI, C++ unit tests have to be enabled on CI)
Fixes CMake build. 

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by marcoabreu** [comment]
Feel free to add a jenkins job for the C++ tests so this PR can be verified

**Comment by piiswrong** [comment]
there is `using namespace mxnet` in the begining

**Comment by larroy** [comment]
@piiswrong which is the reason why we get the compilation error, as there's an ambiguous namespace. What are you trying to say?

**Comment by larroy** [comment]
@piiswrong I think this one broke the tests by having using namespace mshadow on a header:

https://github.com/apache/incubator-mxnet/commit/34a51959bd2bc21c6cfa93f5fe0e079ef5268261

**Comment by larroy** [comment]
https://github.com/dmlc/mshadow/pull/317

**Comment by larroy** [comment]
@tqchen

**Comment by larroy** [comment]
@szha

**Comment by larroy** [comment]
@piiswrong ready

**Pull request merged**
