### PR TITLE
Add CPU optimized docker which will be compiled with MKL-DNN

### PR DESCRIPTION
**Pull request by ykim362**
## Description ##
Adding a new docker input file (mkl) to be utilized for making CPU optimized docker file.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Added a new docker input file. (docker/Dockerfiles/Dockerfile.in.lib.mkl). Ran the command './tool.sh build python mkl'

## Comments ##
- This is backward compatible.

### CODE REVIEW

**Comment by ykim362** [comment]
@kimjanik @ashokei

**Comment by ykim362** [comment]
@marcoabreu , When I tested it, it worked fine for both cpu/mkl with python. If needed, we could update ubuntu version and etc. 

In order to provide CPU optimized docker instances to the community, we'd like to create a new tag (mkl), here. https://hub.docker.com/r/mxnet/python/tags/ 
The page indicates https://github.com/apache/incubator-mxnet/tree/master/docker .

If there's any way to provide a cpu optimized tag, outside of these docker directory, could you please advise me so that I can add an instance?

**Comment by kimjanik** [comment]
Actually, I am setting up the infrastructure to utilize these dockerfiles for CI and test coverage.  If the dockerfiles need updating, I think it would make more sense to get them up-to-date and make them be useful again.

**Comment by CodingCat** [comment]
Hi, the community has passed to vote about associating the code changes with JIRA (https://lists.apache.org/thread.html/ab22cf0e35f1bce2c3bf3bec2bc5b85a9583a3fe7fd56ba1bbade55f@%3Cdev.mxnet.apache.org%3E)

We have updated the guidelines for contributors in https://cwiki.apache.org/confluence/display/MXNET/Development+Process, please ensure that you have created a JIRA at https://issues.apache.org/jira/projects/MXNET/issues/ to describe your work in this pull request and include the JIRA title in your PR as [MXNET-xxxx] your title where MXNET-xxxx is the JIRA id

Thanks!

**Comment by marcoabreu** [comment]
I can really only speak from a CI perspective, maybe @eric-haibin-lin or @szha could shed a bit of light into the situation with the other dockerfiles.

In terms of CI we are using the dockerfiles at tests/ci_build, but they will be migrated as soon as https://github.com/apache/incubator-mxnet/pull/9995 is merged.

**Comment by piiswrong** [comment]
closing due to inactivity. looks like @marcoabreu thinks we don't need this

**Pull request closed without merging**
