### PR TITLE
Cherrypick Fix nightly large_vector test caused by incorrect with_seed path (#18178)

### PR DESCRIPTION
**Pull request by ChaiBapchya**
@ciyongch @leezu 
This unblocks the v1.7.x nightly test for binaries pipeline.

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
Hangs after np_empty. Known issue.
Retriggering @mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
Yet another hang at np empty test.
@mxnet-bot run ci [unix-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [pr-awaiting-merge, pr-awaiting-review]

**Comment by samskalicky** [comment]
@ChaiBapchya any reason this wasnt committed to 1.x branch?

**Comment by ChaiBapchya** [comment]
Missed it. Thanks for catching.

**Pull request merged**
