### PR TITLE
Updated dockerfiles to get the dockcross images from mxnetcipinned

### PR DESCRIPTION
**Pull request by jlcontreras**
Updating the dockerfiles, as the dockcross images moved to mxnetcipinned on Docker Hub.
https://hub.docker.com/u/mxnetcipinned/

### CODE REVIEW

**Comment by larroy** [comment]
what is that docker repo and what's the difference with the previous? Does this also update cuda? I find this PR confusing.

**Comment by jlcontreras** [comment]
The dockcross images are no longer in the old repo (mxnetci), they moved to mxnetcipinned, but as far as I know they should be the same.

The cuda update was there by mistake, removed.  

Also added your changes from  https://github.com/apache/incubator-mxnet/pull/13532 to fix Jetson builds.

**Comment by Roshrini** [comment]
@jlcontreras Can you please check the CI failure? Thanks!

**Comment by Roshrini** [comment]
@mxnet-label-bot Update [pr-awaiting-response]

**Comment by anirudhacharya** [comment]
@jlcontreras please rebase your PR

**Comment by jlcontreras** [comment]
Why is the rebase needed? AFAIU this already points to the head of v1.3.x. Jetson still needs fixing though, but I'm not sure if I'll have time for it in the coming weeks.

**Comment by sandeep-krishnamurthy** [comment]
@marcoabreu - Can this PR be merged?

**Comment by vandanavk** [comment]
@mxnet-label-bot update [pr-awaiting-testing]

**Comment by larroy** [comment]
LGTM

**Comment by jlcontreras** [comment]
Had to add a minor fix to one of the tests so the PR passes CI

**Comment by marcoabreu** [comment]
Merging since the deploy failure is unrelated and will be addressed in #14163 - we have a clash here and have to merge one first.

**Pull request merged**
