### PR TITLE
nano instructions

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##

This PR adds instructions on how to setup MXNet on a Jetson Nano.

I had a previous PR, #14855, that also added the Nano to CI, but this is stuck. So, I'm decoupling the working instructions from the failing CI part.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@lebeg @larroy @KellenSunderland - please review this version. Hopefully we can at least get the instructions published and worry about testing MXNet on the Nano later.

**Comment by Roshrini** [comment]
@KellenSunderland @lebeg Can you take a look at this PR?

**Comment by aaronmarkham** [comment]
So there's still one issue that needs to be resolved. The pip wheel I have mentioned in the guide doesn't have the write .so file in it. I tried to swap it out with the one that works from the build from source route, but ran into other issues. So I'm sort of stuck. Can anyone help update that wheel? I don't want to publish this guide without that wheel working out of the box. Or I need to remove that option from this guide.

**Comment by larroy** [comment]
Let's look at this next week ?

**Comment by aaronmarkham** [comment]
@larray - I have some working wheels now which are now in the guide. The other PR related to this I'll close, but we really need to get CI going and hopefully automate the generation of wheels for this arch.  Right now we only have 1.4.0 wheels... but that's better than nothing!

**Comment by ptrendx** [comment]
@aaronmarkham The instructions do not render correctly for me here: http://mxnet.incubator.apache.org/versions/master/install/install-jetson.html
Content ends at the end of Python prerequisites.
Looking at the source, the end of comment `-->` got changed into `&#8211;&gt;`

**Comment by aaronmarkham** [comment]
@ptrendx Thanks for letting me know... I have a PR to fix this.

**Pull request merged**
