### PR TITLE
[v1.4.x] Backport disabled flaky test_softmin (#13758)

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
Backports disabling of flaky test_softmin. 
Original PR: #13758
GitHub Issue: #13600

Recent failure: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/v1.4.x/56/pipeline/

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by karan6181** [comment]
@mxnet-label-bot add [Test, Python, pr-awaiting-review]

**Comment by piyushghai** [comment]
@marcoabreu Can you review this PR ?

**Comment by vandanavk** [comment]
Is this PR still required?

**Comment by perdasilva** [comment]
I have no idea

**Comment by roywei** [comment]
If we are going to keep 1.4.x nightly CI running, and this fix the failure, we should merge it.

**Comment by karan6181** [comment]
@perdasilva @roywei steps for merging this PR?

**Comment by piyushghai** [comment]
@perdasilva What's the path forward for this PR ?

**Comment by perdasilva** [comment]
I'll close it for now. It's been open for months with no action. If it looks like it is needed again, I can re-open.

**Pull request closed without merging**
