### PR TITLE
MXNet-to-CoreML module: Fixed KeyError for Reshape

### PR DESCRIPTION
**Pull request by Prasad9**
## Description ##
While converting your saved params and symbol.json file to Apple CoreML mlmodel file, for the `Reshape` layer, there used to come `KeyError`. This has been fixed with this commit.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] For user-facing API changes, API doc string has been updated.
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Feature1, tests, (and when applicable, API doc)
- [x] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Intersting edge cases to note here

### CODE REVIEW

**Comment by piiswrong** [comment]
It should be attrs now

**Comment by piiswrong** [comment]
@tqchen right?

**Comment by tqchen** [comment]
Yes

**Comment by Prasad9** [comment]
@tqchen , @piiswrong , I am making using of MXNet 0.12.0 version. When I am saving the symbol file in JSON format, I get the output in this format for various types of layers:

```
      {
      "op": "Convolution", 
      "name": "convolution5", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "16", 
        "stride": "(1, 1)"
      }, 
      "inputs": [[6, 0, 0], [7, 0, 0], [8, 0, 0]]
    }, 
    {
      "op": "Activation", 
      "name": "activation7", 
      "attr": {"act_type": "relu"}, 
      "inputs": [[9, 0, 0]]
    }, 
     {
      "op": "Activation", 
      "name": "activation8", 
      "attr": {"act_type": "relu"}, 
      "inputs": [[15, 0, 0]]
    }, 
    {
      "op": "FullyConnected", 
      "name": "fullyconnected5", 
      "attr": {"num_hidden": "2"}, 
      "inputs": [[16, 0, 0], [17, 0, 0], [18, 0, 0]]
    }, 
    {
      "op": "Reshape", 
      "name": "reshape1", 
      "attr": {"shape": "(0, 2)"}, 
      "inputs": [[19, 0, 0]]
    }, 
    {
      "op": "transpose", 
      "name": "transpose0", 
      "attr": {"axes": "(1, 0)"}, 
      "inputs": [[20, 0, 0]]
    }, 
    {
      "op": "SoftmaxOutput", 
      "name": "softmax", 
      "inputs": [[22, 0, 0], [23, 0, 0]]
    }
```
So all this layers currently are making use of keyword `attr` while generating the symbol file in MXNet 0.12.0 version. I checked the [_layers.py](https://github.com/apache/incubator-mxnet/blob/master/tools/coreml/converter/_layers.py) in various branches like dev, master, ci-test, mli-patch-1, all the branches for other layers (i.e. transpose, softmax etc) seem to be using `attr` only. I am not getting why you want it to be replaced with `attrs`.

Or else please do let me know if you are referring to some other `attr` which has to be replaced with `attrs`.

**Comment by kkk669** [comment]
Why don't you use `_get_attrs()`? It supports both `attr` and `attrs` key.

**Comment by piiswrong** [comment]
@Prasad9 Is this still relevant? Could you rebase and test on master?

**Comment by eric-haibin-lin** [comment]
@Prasad9 any update?

**Comment by piiswrong** [comment]
I think is has been fixed in another PR. Closing

**Pull request closed without merging**
