### PR TITLE
[MXNET-1033] Fix a bug in MultiboxTarget GPU implementation

### PR DESCRIPTION
**Pull request by apeforest**
## Description ##
Fix issue https://github.com/apache/incubator-mxnet/issues/9733
The contrib.MultiBoxTarget operator unnecessarily checks for number of labels > 2 in the GPU implementation. The CPU implementation does not check this.
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
Bugfix

### CODE REVIEW

**Comment by apeforest** [comment]
@zhreshold Please help to review. Thanks

**Comment by samskalicky** [comment]
@apeforest Can you provide more info on why this code was there originally? or why it wasnt there in the CPU implementation? What is the problem with the check and why do you have to remove it?

**Comment by zhreshold** [comment]
The check was there to ensure the buffer is large enough for cuda merge sort implementation. I double checked the buffer is actually from the temp space https://github.com/apache/incubator-mxnet/blob/9c78437d895e9035ef1f30e247ffd0d9b4231829/src/operator/contrib/multibox_target-inl.h#L119 that has at least (11 - 4) * batch size * num_anchor (since I am using temp_space[4] as the buffer), it is safe to remove the check IMO. 

But I would like to see a test case covering this. @apeforest Could you help me verify that with a unittest?

**Comment by Roshrini** [comment]
@apeforest CI seems to have failed. Can you retrigger this build?
@mxnet-label-bot [Operator, pr-awaiting-testing]

**Comment by Roshrini** [comment]
@zhreshold Can you take a look again and merge if looks good? Thanks!

**Comment by zhreshold** [comment]
merged, thank you @apeforest

**Pull request merged**
