### PR TITLE
Imagenet inference to nightly fix

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
PR #16577  was introduced to move imagenet inference to nightly
However, I made the PR prematurely (without testing it completely)

As it so happened (https://github.com/apache/incubator-mxnet/pull/16577/files#r337663583)
Jenkins CI (NightlyTestForBinaries) failed coz of issue in file getting access to the imagenet_inference binary
http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/move_imagenet_inference_nightly/20/pipeline/72

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Verified this works correctly here - http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/shared_library_nightly_fix/3/pipeline

**Comment by marcoabreu** [comment]
"Skipped INT8 test because mkldnn was not found which is required for running inference with quantized models."

Can you take care of that as well please?

**Comment by ChaiBapchya** [comment]
Oh I didn't get you. Should I comment it? Remove it? Handle it?

**Comment by marcoabreu** [comment]
That's output from the test. Can you make sure that this test case is not skipped

**Comment by ChaiBapchya** [comment]
MKLDNN passes
```
+ ls -a ../../../lib

++ grep -oE mkldnn

++ tail -1

+ lib_name=mkldnn

+ [[ -n mkldnn ]]

+ [[ mkldnn =~ mkldnn ]]

>>> INFO: INT8 dummy data

+ echo '>>> INFO: INT8 dummy data'

+ LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:../../../lib

+ ./imagenet_inference --symbol_file ./model/resnet50_v1_int8-symbol.json --batch_size 1 --num_inference_batches 500 --benchmark

[23:12:52] cpp-package/example/inference/imagenet_inference.cpp:302: Loading the model from ./model/resnet50_v1_int8-symbol.json


[23:12:52] src/executor/graph_executor.cc:2014: Subgraph backend MKLDNN is activated.

[23:12:52] cpp-package/example/inference/imagenet_inference.cpp:424: Running the forward pass on model to evaluate the performance..

[23:13:09] cpp-package/example/inference/imagenet_inference.cpp:439:  benchmark completed!

[23:13:09] cpp-package/example/inference/imagenet_inference.cpp:440:  batch size: 1 num batch: 500 throughput: 29.8719 imgs/s latency:33.4763 ms

```

Here - http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/shared_library_nightly_fix/7/pipeline/72

**Comment by ChaiBapchya** [comment]
@aaronmarkham pointed out the discrepancy in function naming convention 

Although the function name is different

original - build_ubuntu_gpu_cuda101_cudnn7
new - build_ubuntu_gpu_mkldnn

Build flags don't mention "version" of CUDA or cuDNN

So although the new function name is build_ubuntu_gpu_mkldnn
It still runs for cuda101 and cudnn7 (just like original function) + mkldnn enabled


http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/NightlyTestsForBinaries/branches/shared_library_nightly_fix/runs/7/nodes/72/steps/243/log/?start=0

Verified both versions are correct
"Step 1/45 : FROM nvidia/cuda:10.1-devel-ubuntu16.04"
"Step 37/45 : ENV CUDNN_VERSION=7.6.0.64"

**Pull request merged**
