### PR TITLE
bilinear_sampler corner cases amendment

### PR DESCRIPTION
**Pull request by xmyqsh**
Deal with the corner cases, such as the operations around the edge of the feature map, correctly, without extra condition jump statement.

### CODE REVIEW

**Comment by sxjscience** [comment]
What's wrong with the original implementation?

**Comment by xmyqsh** [comment]
@sxjscience 
try to calculate the value at pixel (31.9, 30.1) in an image with size (32, 32) using 
```
if (between(top_left_x, 0, i_w-1) && between(top_left_y, 0, i_h-1))
  top_left_v = *(data + data_index);
if (between(top_left_x + 1, 0, i_w-1) && between(top_left_y, 0, i_h-1))
  top_right_v = *(data + data_index + 1);
if (between(top_left_x, 0, i_w-1) && between(top_left_y + 1, 0, i_h-1))
  bottom_left_v = *(data + data_index + i_w);
if (between(top_left_x+1, 0, i_w-1) && between(top_left_y + 1, 0, i_h-1))
  bottom_right_v = *(data + data_index + i_w + 1);
```
and
```
*(out+out_index) = top_left_v * top_left_y_w * top_left_x_w +
                          top_right_v * top_left_y_w * (1.0 - top_left_x_w) +
                          bottom_left_v * (1.0 - top_left_y_w) * top_left_x_w +
                         bottom_right_v * (1.0 - top_left_y_w) * (1.0 - top_left_x_w);
```
it gives 
```
*(out+out_index) = top_left_v * 0.1 * 0.9 + top_right_v * 0.1 * (1.0 - 0.9)
```
but I think 
```
*(out+out_index) = top_left_v * 0.9 + top_right_v * (1 - 0.9)
```
is more appropriate.

**Comment by sxjscience** [comment]
@xmyqsh Can you check with the torch implementation? If we consider that the outside pixels are all zero, the current implementation should be correct.

**Comment by xmyqsh** [comment]
@sxjscience 
yeah, the implementation in torch is also assumed the outside pixels is zero.

**Comment by sxjscience** [comment]
@xmyqsh So the current implementation should be consistent with torch's implementation.

**Pull request closed without merging**
