### PR TITLE
[BUGFIX] Assure NDArray.reshape does not change the array size

### PR DESCRIPTION
**Pull request by r3stl355**
## Description ##
Solves [#18886](https://github.com/apache/incubator-mxnet/issues/18886)

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by r3stl355** [comment]
@mxnet-bot run ci [unix-cpu,unix-gpu]

**Comment by r3stl355** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by r3stl355** [comment]
Can anyone review this please so I can implement the same against 1.x branches? It looks like it now has some conflicts, should I resolve those locally and re-submit?

**Comment by szha** [comment]
@r3stl355 we deprecated contrib text in master. could you rebase?

**Comment by r3stl355** [comment]
Sure, will do

**Review by szha — APPROVED** [review]
thank you for the fix!

**Comment by r3stl355** [comment]
@mxnet-bot run ci [windows-gpu]

**Pull request merged**
