### PR TITLE
[BUGFIX] Fix Mxnet2.0 crashcourse format

### PR DESCRIPTION
**Pull request by vidyaravipati**
Signed-off-by: Vidya Sagar Ravipati <ravividy@amazon.com>

## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
Fix formatting issues

### CODE REVIEW

**Comment by vidyaravipati** [comment]
@mxnet-bot run ci edge

**Comment by leezu** [comment]
@mxnet-bot run ci [edge]

**Comment by leezu** [comment]
@mxnet-bot run ci [edge]

**Comment by vidyaravipati** [comment]
@mxnet-bot run ci [edge]

**Pull request merged**
