### PR TITLE
[2.0] Adopt interleaved_matmul_* into npx namespace

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Part1 of feature request #20373

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ptrendx** [comment]
Would it be more beneficial to have the full multihead attention primitive exposed in the API instead (it could still be implemented by the interleaved matmuls)? Both Keras and pyTorch have it as a layer, and this could make the usage easier. What do you think @barry-jin?

**Comment by fhieber** [comment]
> Would it be more beneficial to have the full multihead attention primitive exposed in the API instead (it could still be implemented by the interleaved matmuls)? Both Keras and pyTorch have it as a layer, and this could make the usage easier. What do you think @barry-jin?

Can we have both? We'd like to upgrade Sockeye to MX2 without changing too many things at the same time.

**Comment by barry-jin** [comment]
@ptrendx Thanks for bringing it up. It's a good idea to have multihead attention layer in gluon and I will add it in this PR. 
@fhieber Yes, we can have both, a high level multihead attention layer and low level interleaved_matmul_* operators in `npx` name space.

**Review by Zha0q1 — APPROVED** [review]
thanks for bring the interleaved matmul ops into npx! We have them in mx2onnx

**Comment by fhieber** [comment]
Can this be merged?

**Pull request merged**
