### PR TITLE
32 to 64 bit toolchain for windows-gpu build

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Changes
1. Switch from 32 to 64bit toolchain
Trying out @snnn suggestion : 
https://github.com/apache/incubator-mxnet/pull/17711#issuecomment-604659219

2. Update dmlc-core to include the latest master (fix VS 2019 in dmlc)
3. Switch from 2015 to 2019 VS

### CODE REVIEW

**Comment by leezu** [comment]
It's essentially the same as https://github.com/apache/incubator-mxnet/pull/17912. The Windows AMI used by CI is kind of broken, preventing this simple toolchain change. So to fix this it's better to deploy the new AMI

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by josephevans** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [windows-cpu, windows-gpu]

**Comment by marcoabreu** [comment]
It seems like you are using the CI to develop a solution instead of verifying it. Would it make more sense to spin up a VM and develop the changes in there? Our setup is made so it so it can be reproduced on a VM, so I'd rather recommend that than trial and error in CI - especially considering the cost focus of your team at the moment.

**Comment by ChaiBapchya** [comment]
Yes. We're testing on VM and making changes @vexilligera can confirm.

It passes on Windows VM but fails on the CI for some reason (for eg x86_64 bat file change to x64). So had to push it here and check on CI to verify if it is working or not.

Agreed its an abuse of CI to check it but because of above mentioned reason I did that.

**Comment by ChaiBapchya** [comment]
Switching the toolchain from 32bit to 64bit alone doesnt fix the windows-gpu build issue.
Closing in favor of https://github.com/apache/incubator-mxnet/pull/17808 which has all the required fixes for windows-gpu build issue

**Pull request closed without merging**
