### PR TITLE
cmake: don't build PTX and 3.5 arch if cuda arch detection fails

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Currently, if `USE_CUDA=ON` but architecture detection fails due to building on a machine without GPU, we will build for `3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX`. Thereby we create too large object files, triggering https://github.com/apache/incubator-mxnet/issues/16852.

Thus, this PR introduces patched `select_compute_arch.cmake`, such that the fallback arches are `3.0;5.0;5.2;6.0;6.1;7.0;7.5`, ie. dropping PTX and 3.5 so that #16852 is not triggered.
We don't need 3.5, because code compiled for 3.0 also runs on 3.5 hardware and 3.5 hardware is 7 years old. If someone really cares about performance on 3.5, they can still manually set `MXNET_CUDA_ARCH=3.5`.

Upstream bug https://gitlab.kitware.com/cmake/cmake/issues/20275

### Changes ###
- [X] cmake: don't build PTX and 3.5 arch if cuda arch detection fails

### CODE REVIEW

**Comment by ptrendx** [comment]
`We don't need 3.5, because code compiled for 3.0 also runs on 3.5 hardware` - I do not believe that is the case, those archs are not binary compatible. I would say that the better choice would be to remove SM3.0 (as SM3.5 is still accessible via p2 AWS instance). We do not need PTX for 7.0 if we include PTX for 7.5.

**Comment by ptrendx** [comment]
Not including PTX at all would make it impossible to run MXNet on future GPUs without recompilation.

**Comment by leezu** [comment]
> `We don't need 3.5, because code compiled for 3.0 also runs on 3.5 hardware` - I do not believe that is the case, those archs are not binary compatible. I would say that the better choice would be to remove SM3.0 (as SM3.5 is still accessible via p2 AWS instance). We do not need PTX for 7.0 if we include PTX for 7.5.

Why is this wrong? Binary forward compatibility is explicitly described in Nvidia docs https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#binary-compatibility

**Comment by leezu** [comment]
> Not including PTX at all would make it impossible to run MXNet on future GPUs without recompilation.

That's true, but given the amount of cuda code in MXNet, PTX JIT compilation does not provide a good user experience (program will hang very long?) and is thus not enabled in the Makefile builds as well AFAIK.

**Comment by leezu** [comment]
ping @ptrendx

**Comment by leezu** [comment]
Ping @ptrendx

**Comment by ptrendx** [comment]
Ok, I think you are right that 3.0 will in fact work for 3.5. That said, again, do we actually care about SM 3.0 (and 5.0 for that matter, as it was used only in a few GPUs)?

**Comment by leezu** [comment]
> Ok, I think you are right that 3.0 will in fact work for 3.5. That said, again, do we actually care about SM 3.0 (and 5.0 for that matter, as it was used only in a few GPUs)?

I'm not sure if we have any data about the distribution of SMs of our users. Thus my main motivation here is to preserve backwards compatibility. 

Also, this change does not affect our binary distribution (python wheels), but just the default for manual build-from-source builds. So I expect if performance is important to whomever is doing the build, they will figure out to set the right architecture. Thus choosing a conservative default would be fine?

Is there any data about how large the performance difference is between running 3.0 binary compared to 3.5 binary on a 3.5 architecture?

**Comment by ptrendx** [comment]
I see. There should not be much difference - the only difference in the generated instructions could be usage of `ldg` in SM_35 case, but I checked and it is used only in 2 places in MXNet.

**Comment by leezu** [comment]
Thanks for checking. Given the small difference between SM 3 and 3.5, let's keep the default to 3.0?

Do you have any further suggestions for the PR? I still need to figure out why the license check is failing, but once that is done can I go ahead to merge?

**Comment by leezu** [comment]
@ptrendx let's merge this PR as is? Without it users can run into #16852 easily.

**Pull request merged**
