### PR TITLE
Move AMP from contrib to core

### PR DESCRIPTION
**Pull request by mk-61**
## Description ##
This PR moves AMP from contrib to the top-level.
The patch itself is just a mechanical part of https://github.com/apache/incubator-mxnet/issues/18896 - moving files around and updating import paths.

### Essentials ###
- [X] Changes are complete (i.e. I finished coding on this PR)

@ptrendx

### CODE REVIEW

**Comment by mk-61** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ptrendx** [comment]
There is also AMP tutorial which needs updating (tutorial are tested in nightly builds only, which is why CI passed): https://github.com/apache/incubator-mxnet/blob/master/docs/python_docs/python/tutorials/performance/backend/amp.md

**Comment by mk-61** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, edge, unix-cpu, unix-gpu, website]

**Comment by mk-61** [comment]
@mxnet-bot run ci [all]

**Comment by mk-61** [comment]
@mxnet-bot run ci [all]

**Comment by mk-61** [comment]
@mxnet-bot run ci [all]

**Comment by mk-61** [comment]
@mxnet-bot run ci [edge, unix-cpu]

**Comment by mk-61** [comment]
@mxnet-bot run ci [edge]

**Review by sxjscience — APPROVED** [review]
LGTM

**Pull request merged**
