### PR TITLE
[Clojure] Remove unneeded test files

### PR DESCRIPTION
**Pull request by gigasquid**
## Description ##
Removes unneeded test files from https://github.com/apache/incubator-mxnet/pull/14800

### Essentials ###
Please feel free to remove inapplicable items for your PR.

- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by gigasquid** [comment]
@Chouffe please take a look 👀

**Comment by Chouffe** [comment]
Should we add those two files in the .gitignore - similar to what we do for the following files:
```
test/test-ndarray.clj
test/test-ndarray-api.clj
test/test-symbol.clj
test/test-symbol-api.clj
```

**Comment by Chouffe** [comment]
Also, not sure how to deal with @kedarbellare great feedback
```
1. DRY the code a bit (to share as much as possible between symbol/ndarray api and random api)
2. call the scala SymbolRandomAPI and NDArrayRandomAPI
3. unify the random_ and sample_ methods (and remove them from the ndarray/symbol api namespaces)
4. add unit tests
```
```
1. Done
2. I could not get this to work when calling directly the `NDArrayRandomAPI` and the `SymbolRandomAPI`
3. This is not done yet. I am not entirely sure how to do that. Can it be done in a subsequent PR?
4. Done
```
Should we open issues for the things that were not done yet an tackle them in a subsequent PR? @gigasquid and @kedarbellare?

**Comment by gigasquid** [comment]
@Chouffe the adding the file to .gitignore is a great idea.

I'm totally cool with opening issues new PR to address the rest of the feedback from @kedarbellare as long as he is cool with it :)

**Comment by kedarbellare** [comment]
+1 to adding the `test-*` files to `.gitignore`. i did the same with the `ndarray-api` files. 

For the `NDArrayRandomAPI` part, it took some time but you can do something like:
```clojure
(import '(org.apache.mxnet NDArrayOrScalar))

;; this calls random_exponential
(util/coerce-return
  (NDArrayRandomAPI/exponential
    (util/->option 1.0) ; lam
    (util/->option (mx-shape/->shape [2 1])) ; shape
    (util/->option nil) ; ctx
    (util/->option nil) ; dtype
    (util/->option nil) ; out
    (NDArrayOrScalar. true) ; input lambda is ndarray or scalar?
    nil ; class type
  ))
;; returns 2 x 1 randomly sampled ndarray

;; this calls sample_exponential (concurrent sampling)
(util/coerce-return
  (NDArrayRandomAPI/exponential
    (util/->option (ndarray/ones [3])) ; lam
    (util/->option (mx-shape/->shape [2 1])) ; shape
    (util/->option nil) ; ctx
    (util/->option nil) ; dtype
    (util/->option nil) ; out
    (NDArrayOrScalar. false) ; input lambda is ndarray or scalar?
    nil ; class type
  ))
;; returns 3 x 2 x 1 concurrently sampled ndarray
```
you can ignore my comment about unifying random/sample or come up with the clojure way of doing this (e.g. using `defmulti` and `defmethod`).

doing it in a subsequent PR is fine by me :smiley:

**Comment by Chouffe** [comment]
alright then! @gigasquid you can add the files in the `.gitignore` and merge. I will tackle @kedarbellare comments in subsequent PRs then!

**Comment by roywei** [comment]
@mxnet-label-bot add[Clojure, Test]

**Pull request merged**
