### PR TITLE
[v1.x] Backport edge pipeline 

### LINKED ISSUE #18298: [v1.x] CI pipeline for NVIDIA Jetson fails with "unsupported GNU version"
## Description

The CI pipeline for NVIDIA Jetson uses the following container:  https://hub.docker.com/r/dockcross/linux-arm64/
It was recently updated to use GCC 8:
https://github.com/dockcross/dockcross/commit/37c54a369441edbe98ef65a026d8704574cf086d

However, CUDA 9 doesn't support GCC versions above 6, so the CI pipelines are currently failing with the following message:

### Error Message

```
error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-18268/3/pipeline/43

## To Reproduce

Run a CI pipeline on the v1.x branch.

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

### PR DESCRIPTION
**Pull request by nickguletskii**
## Description ##

Cherry pick commits from #17984 onto v1.x to fix #18298

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Cherry pick 36c87c3521a227d978e06f95a1a1447121feb967
- [x] Cherry pick 104074a3ebf442d1660d50e101afd68db9fa89a1
- [x] Updated the link to the IUS repository to fix CI jobs on CentOS: https://github.com/iusrepo/infrastructure/issues/14
- [x] Cherry pick 6d1d1220bb4b59b51640729ad7593d11b477fb44
- [x] Remove the parts of the backported commits that depend on C++17.
- [x] Cherry pick b1dd13cbb9b64717bb403097f2f83c42d77930ed
- [x] Fix compilation errors related to the missing `-stdlib` flag.
- [x] Verify that the new QEMU tutorial works.

## Comments ##
- This PR is not just about the Jetson pipeline: the Android ARM pipelines were also upgraded.
- The changes to RNNs mean that the same random seeds will produce different results before and after this patch.

### CODE REVIEW

**Comment by nickguletskii** [comment]
@mxnet-bot run ci [sanity]

**Comment by leezu** [comment]
@nickguletskii thank you for your help fixing the 1.x pipeline!

To address the current Jetson related failure, it would be sufficient to backport only the jetson changes (ie Dockerfile.build.jetson and the corresponding cmake files). @waytrue17 is attempting to do that in https://github.com/apache/incubator-mxnet/pull/18339 for the 1.7 branch.

However, backporting more of the changes (as in your PR) will help the CI stability. So once your PR passes CI, it's great to merge it. Thanks!

**Comment by leezu** [comment]
@mxnet-bot run ci [all]

**Comment by nickguletskii** [comment]
@mxnet-bot run ci [centos-gpu]

**Comment by ChaiBapchya** [comment]
@leezu looks like edge pipeline passes CI
Good to merge?

**Comment by ChaiBapchya** [comment]
And in that case should 1.7.x branch have this PR cherry-picked or https://github.com/apache/incubator-mxnet/pull/18339 merged?

**Comment by leezu** [comment]
@nickguletskii thank you for your work on this PR!

@ChaiBapchya this would be up to @ciyongch given that AFAIK there is already a code-freeze for 1.7 and this PR is not a "minimal fix" but rather a more complete backport from the master branch.

**Comment by ciyongch** [comment]
Yes, I agree with @leezu , for the current v1.7.x branch, let's keep the main code base and with necessary minimal fix to make the release process moving forward, as this PR seems to be quite a large one :)

**Comment by ChaiBapchya** [comment]
Makes sense! Thanks @leezu @ciyongch

**Pull request merged**
