### PR TITLE
Change gluon link

### PR DESCRIPTION
**Pull request by kevinthesun**

### CODE REVIEW

**Comment by piiswrong** [comment]
Can we change this to .. Gluon: style node?

**Comment by kevinthesun** [comment]
Change the link text?

**Comment by piiswrong** [comment]
Change to a note that looks like the note here: https://mxnet.incubator.apache.org/api/python/index.html

**Comment by piiswrong** [comment]
@kevinthesun Updates?

**Comment by kevinthesun** [comment]
@piiswrong  Fixed

**Pull request merged**
