### PR TITLE
Fix document build

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
This PR removes MKL-DNN from document build and reverts #13887 to re-enable website testing.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by larroy** [comment]
Does it fix the issues with the website build?

**Comment by larroy** [comment]
What was the problem? Is not clear to me what was the problem and what is it solved :-)

**Comment by aaronmarkham** [comment]
Refer to https://github.com/apache/incubator-mxnet/issues/13875
The docs build process uses Python's `subprocess`, and for some reason, when MXNet is built with MKL-DNN, this no longer works.

**Comment by TaoLv** [comment]
Thank you @aaronmarkham for linking the issue here. I would like to explain a little more. @larroy 

Document build enabled MKL-DNN since MKL-DNN backend became default on the master branch and Intel OMP would be used then. I guess the issue is related to fork() in Intel OMP and it can be mitigated by setting `KMP_INIT_AT_FORK` as what we proved in the issue. Since MKL-DNN backend is not really used in document build so I just disable it in this PR and it will also help to reduce the build time for it.

**Pull request merged**
