### PR TITLE
[MXNET-1095] [WIP] Support higher order gradient for cos,sin,negative,mul

### PR DESCRIPTION
**Pull request by sxjscience**
## Description ##
For context, please refer https://github.com/apache/incubator-mxnet/issues/10002

Support higher order gradient for cos, sin, negative, mul. I'll add the test later. For now, you may use the following code to test the correctness:

```python
import mxnet.ndarray as nd
from mxnet import autograd
from mxnet.test_utils import assert_almost_equal

x = nd.array([3.0])
x.attach_grad()
with autograd.record():
    y = nd.sin(x)
    y_grad = autograd.grad(y, x, create_graph=True, retain_graph=True)[0]
    z = y_grad * y_grad # Should be cos(x)^2
z.backward()
print(x.grad) # Should be - 2 * cos(x) * sin(x)
gt_grad = - 2 * nd.cos(x) * nd.sin(x)
assert_almost_equal(x.grad.asnumpy(), gt_grad.asnumpy())
```

```
[0.2794155]
<NDArray 1 @cpu(0)>
```

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] higher-order gradient of sin,cos,negative,mul, tests

## Comments ##
- Need to support more OPs.

### CODE REVIEW

**Comment by sxjscience** [comment]
Need to benchmark the performance though. (I feel that the performance should be similar.)

**Comment by Roshrini** [comment]
@mxnet-label-bot [pr-work-in-progress, Operator]

**Comment by anirudhacharya** [comment]
@sxjscience pinging for update on this PR :)

**Comment by stu1130** [comment]
@sxjscience  ping again
feel free to close it and reopen it once you have time

**Comment by sxjscience** [comment]
I'll continue working on it next week.

**Comment by roywei** [comment]
@sxjscience Thanks for the contribution, do you have any documentations to link? It will help othert contributors adding more operators. Thanks!

**Comment by sandeep-krishnamurthy** [comment]
@apeforest - FYI

**Comment by stu1130** [comment]
@sxjscience any plan to work on this? Thanks

**Comment by sxjscience** [comment]
I’m working on a paper these days. May find some time when the paper is submitted.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pinaraws** [comment]
@sxjscience Any updates? Are you still planning to continue to work on this PR?

**Comment by sxjscience** [comment]
No. @apeforest will continue working on that.

________________________________

**Comment by piyushghai** [comment]
@sxjscience Can this PR be closed if the work is being followed up in another PR by @apeforest as commented above ?

**Comment by sxjscience** [comment]
Yes, it can be closed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
