### PR TITLE
fix on the python3 hash randomization issue #8658

### PR DESCRIPTION
**Pull request by wonghang**
## Description ##
Fix on issue #8658

### CODE REVIEW

**Comment by piiswrong** [comment]
@wonghang Sorry for overlooking this. Could you rebase?

**Comment by piiswrong** [comment]
@eric-haibin-lin Please track.

**Comment by eric-haibin-lin** [comment]
@wonghang do you mind syncing the branch with master? Our CI has been updated recently.

**Comment by wonghang** [comment]
hi. I am somewhat busy on my own job and I am not very familiar with git. I
am just a user of those deep learning framework.

My patch is just changing two lines of the code.
Maybe you guys can just change it and take the credit. I don’t mind.

Thanks

「Haibin Lin <notifications@github.com>」在 2017年12月20日 週三，10:20 寫道：

**Comment by piiswrong** [comment]
@eric-haibin-lin Please take over an do the update

**Pull request closed without merging**
