### PR TITLE
[1.x] Add BatchNormWithReLU fp32/bf16

### PR DESCRIPTION
**Pull request by xinyu-intel**
## Description ##
@pengzhao-intel @TaoLv 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [sanity, unix-gpu]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [sanity]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [sanity]

**Comment by szha** [comment]
how is the change tested?

**Comment by xinyu-intel** [comment]
forget to cherry-pick #17679 from master and test added.

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [edge, macosx-x86_64]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [edge, centos-gpu]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by xinyu-intel** [comment]
@szha can you help take a look at the ci?

**Comment by szha** [comment]
there are some issues on the 1.x CI and the team is working on it. once resolved, we can trigger the CI for this PR again.

**Comment by pengzhao-intel** [comment]
> there are some issues on the 1.x CI and the team is working on it. once resolved, we can trigger the CI for this PR again.

Thanks a lot!

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, edge, unix-cpu, unix-gpu, windows-gpu]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-gpu, windows-gpu]

**Comment by xinyu-intel** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by xinyu-intel** [comment]
@pengzhao-intel ready to merge now:)

**Pull request merged**
