### PR TITLE
(Please don't merge) Debug BatchNorm with MKLDNN

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
In order to root-cause issues in new BN operator, need to trigger Jenkins tests.

### Essentials ###
- [ ] Passed code style checking (`make lint`)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
It said there were illegal instructions. So how can I get the dumped core file?
```
test_forward.test_consistency ... [09:48:49] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...

[09:48:49] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!

tests/ci_build/with_the_same_user: line 30: 86367 Illegal instruction     (core dumped) sudo -u "#${CI_BUILD_UID}" --preserve-env "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" "HOME=${CI_BUILD_HOME}" ${COMMAND[@]}

script returned exit code 132
```

**Comment by eric-haibin-lin** [comment]
@marcoabreu I wonder if CI can be configured so that core dump files are preserved and accessible by developers? That's definitely helpful for debugging issues that are not easily reproducible

**Comment by marcoabreu** [comment]
This is in the backlog but we will have to check back with AppSec if this is okay or if it could possible leak some confidential information.

**Comment by TaoLv** [comment]
@eric-haibin-lin @marcoabreu Many thanks. Seems the problem is root caused and fixed by Da. I will close this PR now.

**Pull request closed without merging**
