### PR TITLE
Add license headers to R-package

### PR DESCRIPTION
**Pull request by anirudhacharya**
## Description ##
Add license headers to all files in R-package. 

Current [MXNet release instructions](https://cwiki.apache.org/confluence/display/MXNET/Release+Process#ReleaseProcess-Step1.9.Createartifactsforthereleaseandpushtothedistfolder) requires all files in the R-package to be removed until licensing issues are resolved, before we build the tar file. This PR is to resolve those licensing issues.

## Comments ##
- @hetong007 @ankkhedia @lupesko @sandeep-krishnamurthy

### CODE REVIEW

**Comment by sandeep-krishnamurthy** [comment]
Thanks @anirudhacharya 
Please add Apache 2.0 license header to all examples under demo/
We need to update the R-Package LICENSE file as well

**Comment by ankkhedia** [comment]
> @anirudhacharya The R-Package folder also contains a LICENSE file, which is not an Apache2.0 license. How are we addressing it?

Should we just remove that license and make after adding Apache license to every folder.

**Comment by ankkhedia** [comment]
> @ankkhedia why should we remove the file? scala, clojure and cpp package also have LICENSE files.
But python don't have. I don't mind it having over there just that if adding headers  to all the files suffices do we need an extra file?
Maybe @lupesko and @sandeep-krishnamurthy can comment on it.

**Comment by sandeep-krishnamurthy** [comment]
@ankkhedia - I do not have a strong opinion but it is good to have in the base package folder.

**Pull request merged**
