### PR TITLE
[1.x] Backport of LSTM and GRU fix (#17898) and RNN op (#17632)

### PR DESCRIPTION
**Pull request by bgawrych**
## Description ##
Fix for LSTM and GRU layers without DNNL enabled give wrong gradients #17898
[Large Tensor] Fixed RNN op #17632

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
- This PR is backport of #18203 and #17632

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [edge]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu, unix-cpu, unix-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-cpu, centos-gpu]

**Comment by ciyongch** [comment]
Hi @bgawrych , I found recently there's a PR https://github.com/apache/incubator-mxnet/pull/18437 which delete the `ln -s /usr/bin/ninja-build /usr/bin/ninja` from the ci script file. 
So the new code base will not run into such failure, please try rebase your code. Thanks.
I've create another PR for fixing the issue for v1.7.x branch.

**Comment by bgawrych** [comment]
@mxnet-bot run ci [all]

**Comment by bgawrych** [comment]
> Hi @bgawrych , I found recently there's a PR #18437 which delete the `ln -s /usr/bin/ninja-build /usr/bin/ninja` from the ci script file.
> So the new code base will not run into such failure, please try rebase your code. Thanks.
> I've create another PR for fixing the issue for v1.7.x branch.

@ciyongch Done, but there is only 1 check now. Tried to retrigger all jobs, but no effect

**Comment by ciyongch** [comment]
@bgawrych , it's good, all the tests got passed now :)

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by bgawrych** [comment]
I thinnk it's ready too
cc @ciyongch @pengzhao-intel @TaoLv

**Pull request merged**
