### PR TITLE
add ccache to docs build

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
see title

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by marcoabreu** [comment]
Can you also try ```build_ccache_wrappers```?

**Comment by larroy** [comment]
What's the advantage?

**Comment by marcoabreu** [comment]
It's the recommended way to do it by ccache

**Comment by larroy** [comment]
Both methods are supported: https://ccache.samba.org/manual/latest.html

**Comment by marcoabreu** [comment]
My personal experience was that the environment variable was ofzen not considered and the softlink had a higher success rate, but I'll leave it up to you

**Comment by larroy** [comment]
Works like this. If it gives problems we can switch.

**Comment by larroy** [comment]
@mxnet-label-bot update [pr-awaiting-merge]

**Pull request merged**
