### PR TITLE
Julia: add binding for runtime feature detection

### PR DESCRIPTION
**Pull request by iblis17**
Ref: #13549
```julia
julia> mx.features_enabled()
8-element Array{MXNet.mx.MXFeatures.Feature,1}:
 CPU_SSE::Feature = 5   
 CPU_SSE2::Feature = 6  
 CPU_SSE3::Feature = 7  
 CPU_SSE4_1::Feature = 8
 CPU_SSE4_2::Feature = 9
 CPU_AVX::Feature = 11  
 F16C::Feature = 15     
 LAPACK::Feature = 21

julia> mx.features_enabled(Symbol)
8-element Array{Symbol,1}:
 :CPU_SSE
 :CPU_SSE2
 :CPU_SSE3
 :CPU_SSE4_1
 :CPU_SSE4_2
 :CPU_AVX
 :F16C
 :LAPACK

julia> mx.features_enabled(String)
"CPU_SSE, CPU_SSE2, CPU_SSE3, CPU_SSE4_1, CPU_SSE4_2, CPU_AVX, F16C, LAPACK"

```

### CODE REVIEW

**Comment by larroy** [comment]
Let's merge this first, https://github.com/apache/incubator-mxnet/pull/13964  the enum is now internalized.

**Comment by vandanavk** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by larroy** [comment]
https://github.com/apache/incubator-mxnet/pull/13964

**Comment by iblis17** [comment]
so... `features_enabled` has gone?

**Comment by iblis17** [comment]
New API:
```julia
julia> mx.libinfo_features()
30-element Array{MXNet.mx.MXRuntime.LibFeature,1}:
 ✖      CUDA          
 ✖      CUDNN         
 ✖      NCCL          
 ✖      CUDA_RTC      
 ✖      TENSORRT      
 ✔      CPU_SSE       
 ✔      CPU_SSE2      
 ✔      CPU_SSE3      
 ✔      CPU_SSE4_1    
 ✔      CPU_SSE4_2    
 ✖      CPU_SSE4A     
 ✔      CPU_AVX       
 ✖      CPU_AVX2      
 ✖      OPENMP        
 ✖      SSE           
 ✔      F16C          
 ✖      JEMALLOC      
 ✖      BLAS_OPEN     
 ✖      BLAS_ATLAS    
 ✖      BLAS_MKL      
 ✖      BLAS_APPLE    
 ✔      LAPACK        
 ✖      MKLDNN        
 ✖      OPENCV        
 ✖      CAFFE         
 ✖      PROFILER      
 ✖      DIST_KVSTORE  
 ✖      CXX14         
 ✖      SIGNAL_HANDLER
 ✖      DEBUG         
```

**Comment by iblis17** [comment]
And I want to add a comparison method like:

```julia
:CUDA in mx.libinfo_features()
```
 to let user check a feature enabled or not.

**Comment by larroy** [comment]
What is ":CUDA" in Julia? is it an atom like in erlang?

**Comment by larroy** [comment]
Yes the new API just returns a list of struct with boolean field indicating enabled or not.

**Comment by iblis17** [comment]
yeah, `:CUDA` is a `Symbol` in Julia, exactly the same as atom in Erlang.

**Comment by larroy** [comment]
LGTM % I don't know Julia.

**Comment by iblis17** [comment]
Finally, I decide to make this:
```julia
julia> mx.isenabled(:CUDA)
false

julia> mx.isenabled(:CPU_SSE)
true
```

**Comment by larroy** [comment]
I guess this can be resumem  when you have some bandwidth.

**Comment by iblis17** [comment]
okay, I updated it.

**Comment by larroy** [comment]
Needs rebase

**Comment by iblis17** [comment]
rebased

**Comment by iblis17** [comment]
well, the ci status blocks the merge button.

**Comment by szha** [comment]
could you try another rebase? CI had a hiccup a couple of days ago.

**Comment by iblis17** [comment]
sure

**Pull request merged**
