### PR TITLE
Enable possibility of disabling particular graph pass

### PR DESCRIPTION
**Pull request by anko-intel**
## Description ##
There was no possibility to disable particular fusing pass via
environment variable when use optimize_for function.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by DominikaJedynak — APPROVED** [review]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by bgawrych — APPROVED** [review]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [centos-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [uniux-cpu, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu, windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [clang]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by anko-intel** [comment]
@mxnet-bot run ci [clang]

**Pull request merged**
