### PR TITLE
Skip adding control_deps if nodes are the same

### PR DESCRIPTION
**Pull request by reminisce**
The following code would fail before this PR due to introducing a cycle into the gradient graph. See this issue for analysis: https://github.com/apache/incubator-mxnet/issues/8029. This PR also fixes this issue of the same root cause: https://github.com/apache/incubator-mxnet/issues/7956.

```python
data = mx.symbol.Variable('data')
res = data + data + data + data + data + data + data + data
res.simple_bind(ctx=mx.cpu(), data=(1,))
```

@piiswrong @tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
LGTM, can you backport this to nnvm? Thanks

**Comment by piiswrong** [comment]
@tqchen Do you remember why the inplace_sum_cap was there? Can we remove it?

**Comment by reminisce** [comment]
@tqchen Could you specify where in nnvm I should backport this fix to?

**Comment by tqchen** [comment]
@reminisce nevermind, this logic is only in mxnet

**Comment by tqchen** [comment]
inplace sum is used to rewrite normal sum to a chain of inplace sum, which saves more space. Since if we do an explicit sum for weight gradient of RNN, we cost O(timestep) memory

**Pull request merged**
