### PR TITLE
[Numpy] Fix flaky tests in einsum

### LINKED ISSUE #16616: [Flaky] test_numpy_op.test_np_einsum
## Description
```
======================================================================

FAIL: test_numpy_op.test_np_einsum

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/python/mxnet/util.py", line 315, in _with_np_shape

    return func(*args, **kwargs)

  File "/work/mxnet/python/mxnet/util.py", line 499, in _with_np_array

    return func(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_numpy_op.py", line 3524, in test_np_einsum

    assert_almost_equal(out_mx.asnumpy(), expected_np, rtol=rtol, atol=atol)

  File "/work/mxnet/python/mxnet/test_utils.py", line 627, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.669922 exceeds tolerance rtol=1.000000e+00, atol=1.000000e-01 (mismatch 25.000000%).

Location of maximum error: (0, 1), a=0.24609375, b=0.02963257

 ACTUAL: array([[156.    ,   0.2461],

       [433.2   , -30.8   ]], dtype=float16)

 DESIRED: array([[156.     ,   0.02963],

       [433.2    , -30.72   ]], dtype=float16)

-------------------- >> begin captured stdout << ---------------------


*** Maximum errors for vector of size 4:  rtol=1.0, atol=0.1


  1: Error 1.669922  Location of error: (0, 1), a=0.24609375, b=0.02963257


--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1120100586 to reproduce.

--------------------- >> end captured logging << ---------------------
```

## Occurrences
Unrelated PR - #16599 

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16599/5/pipeline

## What have you tried to solve it?
Nothing

### PR DESCRIPTION
**Pull request by hzfan**
## Description ##
Disable float16 tests for einsum temporarily to handle #16616

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by marcoabreu** [comment]
Please add a comment with the issue link

**Comment by reminisce** [comment]
@marcoabreu Since the flakiness has been blocking the development work on the master branch, I'm going to merge the PR as is. @hzfan Will note down your comment and submit it with another PR. Thanks for your understanding.

**Comment by ChaiBapchya** [comment]
@reminisce @marcoabreu 
Nitpicky but still : Shouldn't this be more like "Disable flaky test" rather than "Fix flaky test" coz the PR doesn't fix it.

**Comment by marcoabreu** [comment]
Agree, I only changed the description but forgot the tithe title. Sorry

**Pull request merged**
