### PR TITLE
Modify R package gitignores

### PR DESCRIPTION
**Pull request by terrytangyuan**
Added some additional files often auto created that should be ignored.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@mxnet-jenkins Test this please

**Comment by terrytangyuan** [comment]
@cjolivier01 Could you help take a look? PR-head seems to be the only one that’s failing.

**Comment by terrytangyuan** [comment]
@cjolivier01 Thanks but my question is that this PR cannot merged until it’s passing. It seems like there’s issue with CI.

**Comment by marcoabreu** [comment]
I have retriggered the build, seems like the windows slave had some issues

**Comment by cjolivier01** [comment]
I am not in charge of CI -- they just used my ID because they needed a committer ID

**Comment by terrytangyuan** [comment]
Cool. Thanks guys! @marcoabreu Is @mxnet-jenkins working?

**Comment by marcoabreu** [comment]
I don't know that account

**Pull request merged**
