### PR TITLE
Adds additional CUDA build environments

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
This PR adds additional CUDA _build_ environments for use by developers as well as CI and CD job.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
Adds CUDA build environments for CUDA versions 8.0, 9.0, 9.2, and 10.0

## Comments ##

I've deleted the Dockerfile.build.ubuntu_gpu environment and created a symlink from Dockerfile.build.ubuntu_gpu -> Dockerfile.build.ubuntu_gpu_cu100

### CODE REVIEW

**Comment by vandanavk** [comment]
@mxnet-label-bot add [pr-work-in-progress, CI]

**Comment by perdasilva** [comment]
@mxnet-label-bot remove [pr-work-in-progress]

**Comment by perdasilva** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by perdasilva** [comment]
@lanking520 Not at the moment. Although, I do test them in our release automation pipelines. Having them here not only ensures the build environment follows the code, but also gives developers an easy way to build against these cuda version (e.g. with ci/build.py). 

Doesn't mean that we couldn't add those in though...and this would be the first step for that ^^

**Comment by perdasilva** [comment]
@lanking520 I will also need to backport these to v1.4.x - due to release automation =S
But I would like to test out on master first ^^

**Pull request merged**
