### PR TITLE
MXNET-884 - Clojure with-resources macro for Improved Memory Handling

### PR DESCRIPTION
**Pull request by gigasquid**
## Description ##

This adds a `with-resources` macro to the Clojure package to provide an idiomatic way, (similar to `with-open`), to explicitly dispose of resources with a `.dispose` call.

It works with any Scala object that has a `.dispose` method -  NDArray, Symbol, Executor, Iterators, etc..

Usage is:

```clojure 
(util/with-resources [a (ndarray/ones [3])
                      b (ndarray/ones [3])]
    (ndarray/+ a b))
```
Any resources in the binding vector will be disposed. Result resources will not.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [X] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [X] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
- The Scala package uses scopes with an NDArrayCollector. However, scopes do not mesh well with the Clojure language and the macro pattern for `with-open` for resources is well established and idiomatic in Clojure.
- This will allow users to better control the resources and memory management, however it is not a full solution. There is still investigation into other avenues ongoing with the Scala package.
- Applications of with-resources to the examples will happen in a separate PR

### CODE REVIEW

**Comment by iperdomo** [comment]
This is an improvement that looks more _idiomatic_. Our current approach is to remember to call `.dispose` on those `NDArray` objects we create, something like:
```clojure
(let [a (ndarray/ones [3])
      b (ndarray/ones [3])
      result (ndarray/+ a b)]
  (doseq [nd a]
    (.dispose ^NDArray nd))
  (doseq [nd b]
    (.dispose ^NDArray nd))
  result)
```
With some discipline you can remember to do it, however our current main issues are `NDArray` objects created at the Scala API that we can't _reach_ and call `.dispose` on them.

**Comment by gigasquid** [comment]
@iperdomo Thanks for the feedback. This PR is a step in the direction of improved memory handling but I agree it does not solve your larger issue. I'm continuing to look into solutions with the Scala package.

**Comment by gigasquid** [comment]
@nswamy thoughts on merging this PR or waiting until the largest memory management effort?

The pro for merging would be that it might be a minor help right now and doesn't harm anything
The con would be if we are changing direction and won't be using `close` and we would have to deprecate later

**Comment by nswamy** [comment]
The work I am doing is here
https://github.com/nswamy/incubator-mxnet/blob/using-handle/scala-package/core/src/main/scala/org/apache/mxnet/NativeResource.scala
https://github.com/nswamy/incubator-mxnet/blob/using-handle/scala-package/core/src/main/scala/org/apache/mxnet/ResourceScope.scala
https://github.com/nswamy/incubator-mxnet/blob/using-handle/scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala#L566-L570

Do you think it makes sense to wait for these changes to get merged ? but i'll be fine if you want give this interim solution to users, however suggest to mark it experimental so you have the flexibility to modify.

I am adding the NativeResource class so all the MXNet Objects that have native Resources can extend be automatically taken taken care of. NativeResource also implements AutoCloseable - is that something that Clojure can see?

**Comment by gigasquid** [comment]
@nswamy Thanks for the explanation. I'm not sure about the visibility of traits themselves to Clojure, but it can work with Scopes. I think I'm going to go ahead and close this PR since Clojure uses can use `dispose` or java interop with the NDArrayCollector if they need to solve immediate problems and I'll wait for your work to land to integrate the better solution.

**Pull request closed without merging**
