### PR TITLE
python/setup.py modified to accept a package name argument.

### PR DESCRIPTION
**Pull request by jlcontreras**
## Description ##
python/setup.py modified to accept a package name argument. This way, platform-specific packages such as mxnet-jetson can be created automatically. 

Modified ci/docker/runtime_fuctions.sh so that build_jetson() calls python/setup.py using mxnet-jetson as name.

## Usage info ##

These changes are useful when calling build.py with jetson as target platform. 

`./build.py -p jetson`

The output wheel will have `mxnet-jetson` as package name, instead of `mxnet`.  This way, it can be uploaded to PyPi as a Jetson-specific package. 

### Essentials ###
- [X ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by lupesko** [comment]
@szha bouncing this for your review

**Comment by lupesko** [comment]
Bouncing for review: @sandeep-krishnamurthy @vandanavk @Roshrini

**Comment by vandanavk** [comment]
LGTM.
Adding @aaronmarkham for review as well.

**Comment by aaronmarkham** [comment]
@jlcontreras Can you provide some usage info that would go into the docs? Would users need to know how to use this?
Should it be mentioned on the CI readme? https://github.com/apache/incubator-mxnet/tree/master/ci#buildpy

Or mentioned in the install section for jetson? https://github.com/apache/incubator-mxnet/blob/master/docs/install/index.md#nvidia-jetson-tx-family

**Comment by vandanavk** [comment]
Thank you for your contributions @jlcontreras, awaiting your response on review comments.

@marcoabreu for review

**Comment by vrakesh** [comment]
@jlcontreras Requesting an response on the PR review comments.

**Comment by jlcontreras** [comment]
Sorry for the late reply, I'm away until the beginning of next week and then I'll answer everything!

**Comment by jlcontreras** [comment]
@aaronmarkham thanks for the review. I added some extra information to the description.

I would say there is no need to add anything to the docs, as users are not expected to use this directly. It is only a behind-the-scenes change to the resulting package name so it does not conflict with the main package when uploading to Pypi.

**Comment by Roshrini** [comment]
@jlcontreras Thanks for making this change. LGTM. 
@aaronmarkham I don't think we need to add it to the main docs. 

@nswamy Can you take a look once?

**Comment by roywei** [comment]
Thanks for this option! LGTM!
ping  @nswamy @sandeep-krishnamurthy could you take a look and merge this?

**Comment by sandeep-krishnamurthy** [comment]
@aaronmarkham - Are your comments addressed?
@szha - Will this have any impact on PyPi?

**Comment by aaronmarkham** [comment]
Shouldn't the info in this PR's description be added to https://github.com/apache/incubator-mxnet/tree/master/ci or captured in some way? We seem to have a lot of tribal knowledge hidden in the code without any references in docs to how things work. Another place could be in developer wiki.

**Pull request closed without merging**
