### PR TITLE
fix Makefile for rpkg

### PR DESCRIPTION
**Pull request by jeremiedb**
This is to fix rpkg build. #13062

### CODE REVIEW

**Comment by marcoabreu** [comment]
Thanks for the fix! Would you mind finding out why CI hasn't caught this?

**Comment by jeremiedb** [comment]
@marcoabreu Looking at the various jenkins job, I can't see any R-package job. That would explain why!

**Comment by marcoabreu** [comment]
Damn! Did I accidentally deleted it when I split the pipelines? ._.

**Comment by roywei** [comment]
@jeremiedb Thanks for the contribution, could you take a look at the unit test failed?
ping @anirudhacharya @ankkhedia for review

**Comment by roywei** [comment]
@mxnet-label-bot [R, pr-awaiting-review]

**Comment by jeremiedb** [comment]
It's a python-gpu test that crashes, so I can't see any sort of link between this PR and the test failure. Flaky test maybe?

**Comment by roywei** [comment]
@jeremiedb let's try rebase or push an empty commit to trigger CI again. Thanks!

**Comment by roywei** [comment]
@mxnet-label-bot add [R, pr-awaiting-review]

**Comment by sandeep-krishnamurthy** [comment]
@anirudhacharya / @ankkhedia - FYI

**Comment by szha** [comment]
@marcoabreu I assume you'd be adding R back to the CI?

**Pull request merged**
