### PR TITLE
remove mx.module.* APIs for MXNet 2.0

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
This PR removes the mx.module APIs for MXNet 2.0. The API will be still supported and maintained in the 1.x branch. 

This PR also removes all examples depending on `mx.module`. For documentation that mentions both Gluon and Module usages, the description about Module usage is removed. 

#17676 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
FYI, this is a broken change and quantization features will not work again.

**Comment by eric-haibin-lin** [comment]
@pengzhao-intel yes I am aware of that. For users who need quantization features, they need to access it via MXNet 1.x

**Comment by RuRo** [comment]
@eric-haibin-lin can you explain, why did you remove the conversions for `Add`, `Sub`, `Mul` and `Div` operators from onnx to mxnet? Just because it uses the Module API? Isn't this a bit of an overkill? :confused:

AFAIK, the module API is used here just to infer the shapes of inputs, so it should be probably possible to replace the `get_input_shape` call with the newer `get_inputs(..., with_shape=True)` function, which doesn't use the Module API.

**Comment by eric-haibin-lin** [comment]
@RuRo my apologies. I didn't realize that it just uses Module API to get the shape. It probably should just use `Symbol.infer_shape` API instead. Let me create an issue to track this and get back to this issue later once I'm done with my current task. 
Regarding the `test_models` test - I am afraid that there will be more work to rewrite all tests without using Module, which will be deprecated in mxnet 2.0. And in fact, there are many tests that require such rewrites and help from the community. Let me create a github issue to track all features impacted, and call for contributions. It will also be great if you have the bandwidth to help

**Comment by leezu** [comment]
Ping @eric-haibin-lin regarding the tracking issue

**Pull request merged**
