### PR TITLE
julia: bump Windows prebult binary version to v1.5.0

### PR DESCRIPTION
**Pull request by iblis17**
- remove file REQUIRE, it's stale for Pkg3.jl
- this patch has been included in the Julia package v1.5.x branch (https://github.com/dmlc/MXNet.jl/commit/73e0fba911539bf074ee9de71d09541ec5368480)

### CODE REVIEW

**Comment by marcoabreu** [comment]
Sorry, but it seems like we're breaking the Apache rules regarding releases and code ownership here. 

Could you elaborate why you're referencing an external repository and explain how the code ownership of the Julia package is looking like exactly. I was under the impression that the Julia package is now completely part of the Apache Incubator and thus the DMLC repository is only acting as mirror for legacy reasons.

**Comment by iblis17** [comment]
Hi @marcoabreu, the discussion is here:
 http://mail-archives.apache.org/mod_mbox/mxnet-dev/201901.mbox/%3cc3eb9aa6-889a-6e32-b443-99d41dcd4b37@hs.ntnu.edu.tw%3e

I selected that old MXNet.jl repo as the release channel for Julia package.

**Comment by iblis17** [comment]
This branch (https://github.com/dmlc/MXNet.jl/tree/v1.5.x) is created by `git-subtree` command mentioned in the mailing list.

**Comment by marcoabreu** [comment]
Ah I remember, thanks. Go ahead :)

**Comment by iblis17** [comment]
BTW, if I want to backport this patches to [v1.5.x branch](https://github.com/apache/incubator-mxnet/tree/v1.5.x), what is the backport process?

**Comment by marcoabreu** [comment]
You can choose the target branch when you edit the PR. It's at the top.

**Comment by iblis17** [comment]
I want this PR get merged into both master and v1.5.x branch. I think it's not possible in single PR... Is there a backport process developed?

**Comment by marcoabreu** [comment]
Correct, you have to make two separate prs.

As far as the process is define, we only prepend "[1.5.x]" to the PR title and set the target branch. Then we wait for CI to pass and one approval.

**Comment by marcoabreu** [comment]
Ah, and we cherry pick commits from master if possible.

**Comment by iblis17** [comment]
ah, okay!

**Comment by iblis17** [comment]
I think the CI failures are unrelated. 
Reopen PR to rerun CI.

**Pull request merged**
