### PR TITLE
Fix Sphinx error in ONNX file

### PR DESCRIPTION
**Pull request by vandanavk**
## Description ##

Fixes https://github.com/apache/incubator-mxnet/issues/12947

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- Fix indentation

## Comments ##

### CODE REVIEW

**Comment by vandanavk** [comment]
@frankfliu @aaronmarkham @nswamy for review

**Comment by nswamy** [comment]
Can you paste the preview link once the build passes?

**Comment by vandanavk** [comment]
@nswamy http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-13251/1/api/python/contrib/onnx.html?#mxnet.contrib.onnx.onnx2mx.import_model.get_model_metadata

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-awaiting-merge]

**Pull request merged**
