### PR TITLE
[v1.x]Enhance license checker to cover multiple license header and md files

### PR DESCRIPTION
**Pull request by ciyongch**
## Description ##
Backport https://github.com/apache/incubator-mxnet/pull/18478 and https://github.com/apache/incubator-mxnet/pull/18541 to enhance the current tools/icense_header.py, the main changes are listed as below:
1. Enhance the current license checker to cover multiple license header and the *.md files.
2. Add the statement in top level LICENSE for einsum and modulated_deformable_im2col related files.
3. Add license for the md files which missed the header.

@szha @leezu @TaoLv @pengzhao-intel

### CODE REVIEW

**Comment by ciyongch** [comment]
[centos-cpu] [centos-gpu][windows-gpu] jobs failed due to numpy 1.19.0 is used in CI, which is a known issue reported in https://github.com/apache/incubator-mxnet/issues/18600.

@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
Hi @szha , may I have your suggestion for the failed numpy UTs, 

1. add constraint to numpy version (<1.19.0) on 1.x CI 
2. disable the relative UTs
3. wait for the fix on numpy version compatible PR to get this merged?

**Comment by szha** [comment]
+1 for option 1 since the integration indeed needs fix. Thanks for driving this.

**Comment by ciyongch** [comment]
https://github.com/apache/incubator-mxnet/pull/18651 was created as described in option 1.

**Comment by ciyongch** [comment]
@mxnet-bot run ci [unix-gpu]

**Comment by ciyongch** [comment]
Hi @leeze, @szha please help to review and merge.

**Pull request merged**
