### PR TITLE
Update PR Template

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
Removed code style checking from the template. It is checked by the CI anyway. No PR can be merged without passing this.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Could we add checkboxes to all items in the list? 

```- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)```
would become
```- [ ] Unit tests are added for small changes to verify correctness (e.g. adding a new operator)```

**Comment by szha** [comment]
I think the list items are intended as enumeration of possible situations. They usually don't apply all at once.

**Comment by eric-haibin-lin** [comment]
+1 on sheng's comment

**Comment by lebeg** [comment]
Could we add a note that not applicable items should be removed from the description? It's sometimes hard to see the actual message between the default text lines

**Comment by eric-haibin-lin** [comment]
Done

**Comment by szha** [comment]
@eric-haibin-lin would you add an item to remind the committers to check the API doc of the PR? See details in #9928. It should read like:
Committers should check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html. (e.g. [link](http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-9928/25/index.html))

**Comment by rahul003** [comment]
@szha That is nice! Didn't know we were building API docs for each PR. 
+1 for adding that

**Comment by eric-haibin-lin** [comment]
Done

**Comment by marcoabreu** [comment]
Could we also add an item to remind people linking the JIRA issue?

**Comment by eric-haibin-lin** [comment]
Done. Although I'm a little bit worried that all these reminders make the template kind of heavy

**Comment by marcoabreu** [comment]
Agree, we might have to do a proper cleanup of that template and make it more lightweight.

**Pull request merged**
