### PR TITLE
[MXNET-1443] Change gluon contrib base event handlers to mixins

### PR DESCRIPTION
**Pull request by ehsanmok**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
incubator-mxnet/python/mxnet/gluon/contrib/estimator/event_handler.py
incubator-mxnet/python/mxnet/gluon/contrib/estimator/estimator.py

incubator-mxnet/tests/python/unittest/test_gluon_event_handler.py
incubator-mxnet/tests/python/unittest/test_gluon_estimator.py

incubator-mxnet/docs/python_docs/python/tutorials/packages/gluon/training/fit_api_tutorial.md

### CODE REVIEW

**Comment by ehsanmok** [comment]
@szha Mixins show users don't need to care about MRO when inheriting from multiple classes. So this change is a technical correction.

**Comment by leezu** [comment]
I agree the new name is more self-explanatory, but changing may break user code. This is experimental API, so changes are fine if needed. Would such docstring be sufficient without introducing breakage? `"""BatchEnd Mixin."""`

**Comment by ehsanmok** [comment]
@leezu Since contrib would likely become stable at some point, I'm in favor of changing them sooner from both dev and user sides.

**Comment by leezu** [comment]
CC @liuzh91 who wrote code that would break.

**Comment by ehsanmok** [comment]
@szha Sounds good to me!

**Pull request closed without merging**
