### PR TITLE
[mkldnn-v1.0] Use memcpy instead of set_handle with unidirectional 1-layer RNN

### PR DESCRIPTION
**Pull request by zixuanweeei**
## Description ##
Fix the issue filed by https://github.com/apache/incubator-mxnet/pull/16555#issuecomment-547000155. Previously, we don't need `Concat` to concatenate pieces of weights to a continuous space with unidirectional 1-layer RNN. Thus, `mkldnn::memory::set_data_handle(ptr)` is directly used to fetch the weights, and `ptr` is the pointer of weights shifted from `NDArray`. When it runs into `gru` mode, a swap mechanism of gates is used to swap weights of the reset gate and the update gate. If we use `set_data_handle` here, it will crash the naive memory from `NDArray`.  As a result, the gru operator swaps the naive memory every iteration when `is_train=True`. It will then give inconsistent results. We should use `memcpy` here.

### Changes ###
- [x] Move `set_data_handle` to `memcpy`.

@ciyongch @pengzhao-intel @TaoLv

### CODE REVIEW

**Comment by ZhennanQin** [comment]
This change will impact performance. Why v0.20 doesn't have this issue? Is there any solutions other than memcpy?

**Comment by zixuanweeei** [comment]
> This change will impact performance. Why v0.20 doesn't have this issue? Is there any solutions other than memcpy?

v0.20 swaps the GRU memory on native NDArray space and then swaps back to the original layout. It may have more overhead over the first iteration. Thus, v1.0 uses a different mechanism that directly adjusts `mkldnn::memory`. Previously, we use OpenMP for-loop to apply the swap and copy. I have had an experiment measuring the performance of the operator from stl and the one wrapped by OpenMP. It seems that `std::memcpy` needs another ~4 milliseconds (clx-8280) to finish the operation with 1e7 long float array. It may not severely impact the performance in the inference procedure, as we copy and swap the memory only once at the first iteration. Honestly, it is not true in forward_training and backward. There are lots of `memcpy` to deliver the gradients of weights. I will try to simplify and accelerate them in this PR.

**Comment by pengzhao-intel** [comment]
@zixuanweeei take a look for the CI failure

**Comment by zixuanweeei** [comment]
`IMPERATIVE.FullyConnectedOp` failed again. @pengzhao-intel

**Pull request merged**
