### PR TITLE
Fix sparse L2Norm's fallback regression

### PR DESCRIPTION
**Pull request by haojin2**
## Description ##
Fix for #16060 in 1.6

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Fix incorrect condition check

## Comments ##
test coverage already exists so no extra tests added.

### CODE REVIEW

**Comment by ptrendx** [comment]
What is the commit in master that corresponds to this fix?

**Comment by haojin2** [comment]
@ptrendx There's no fix in master yet, would you prefer this being PRed to master first?

**Comment by eric-haibin-lin** [comment]
@ptrendx the PR to the master branch was merged https://github.com/apache/incubator-mxnet/pull/17149

**Comment by haojin2** [comment]
@leezu Edge build is failing, probably you should also port your change to the CI to v1.6.x branch

**Comment by eric-haibin-lin** [comment]
Opened another PR with this fix that passes CI: https://github.com/apache/incubator-mxnet/pull/17146

**Pull request closed without merging**
