### PR TITLE
[BUGFIX] Fix numpy pad operator

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
Fix issue #19777 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Broadcast pad_width to (ndim, 2). 

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by barry-jin** [comment]
@mxnet-bot run ci [miscellaneous, windows-gpu]

**Comment by barry-jin** [comment]
@mxnet-bot run ci [miscellaneous, windows-gpu]

**Comment by szha** [comment]
@josephevans any idea about the docker build failure in the misc pipeline?

**Comment by leezu** [comment]
It's a legacy container build and I don't think anyone is maintaining it. I'm not even sure it's still used, so I suggest to delete it to unblock the current PR https://github.com/apache/incubator-mxnet/pull/19801

**Comment by barry-jin** [comment]
@mxnet-bot run ci [windows-gpu]

**Comment by szha** [comment]
@barry-jin thanks for the fix!

**Pull request merged**
