### PR TITLE
Fix data-api links

### PR DESCRIPTION
**Pull request by bgawrych**
Fix for broken link check
e.g. https://github.com/apache/incubator-mxnet/runs/5038874788?check_suite_focus=true

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-gpu, unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [unix-cpu]

**Review by leezu — APPROVED** [review]

**Comment by leezu** [comment]
@mxnet-bot run ci [unix-cpu]

**Pull request merged**
