### PR TITLE
[scala-package] fix the bug in parent section of pom files

### PR DESCRIPTION
**Pull request by CodingCat**
Sorry for introducing this bug several weeks ago

Actually, Maven cannot parse any variable in parent section

I have changed those project.version back and validate in my local maven, working fine now

### CODE REVIEW

**Comment by javelinjs** [comment]
Scala build fails

**Comment by javelinjs** [comment]
@CodingCat I provided a script `scala-package/dev/change-proj-version.sh` which help to change version easily.

**Comment by CodingCat** [comment]
looks like a maven version mismatch in my test environment and jenkins....fixing it

**Comment by CodingCat** [comment]
I just noticed that script @javelinjs 

so, I will revert changes here

**Pull request merged**
