### PR TITLE
New Website: Remove Old Content [2/3]

### PR DESCRIPTION
**Pull request by ThomasDelteil**
This specific commit can be reviewed here in isolation here for better readability: https://github.com/ThomasDelteil/incubator-mxnet/pull/5

- [x] https://github.com/apache/incubator-mxnet/pull/15884 merged

This removes the old website

New website visible here: https://mxnet-beta.staged.apache.org/

Merging this will disable website validation on PRs and any updates to the website until the follow-up PR is merged to add CI for the new docs and website: https://github.com/apache/incubator-mxnet/pull/15883

### CODE REVIEW

**Comment by zachgk** [comment]
Can you rebase onto master to isolate the new commits from the commits that were part of New Website PR 1?

**Comment by ThomasDelteil** [comment]
@zachgk way too many merge conflicts when trying to rebase sorry, let's try that way for now

**Comment by mikeobr** [comment]
There's a tutorial I was looking for that seems to be removed in this PR, here it is on 1.4.0: https://github.com/apache/incubator-mxnet/blob/1.4.0/docs/tutorials/vision/cnn_visualization.md

Where did this get moved to?

**Comment by szha** [comment]
@aaronmarkham @ThomasDelteil 👆

**Comment by ThomasDelteil** [comment]
Yes there is a PR to add a few missing tutorials I'll double check this one is included, as soon as the CI is more stable we'll get it in.

**Pull request merged**
