### PR TITLE
fixed broken links and added jenkins info

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
Some links to the other docs were broken, so now they're updated. I also added instructions on how to run Jenkins jobs to deploy a site update.

### CODE REVIEW

**Comment by aaronmarkham** [comment]
@lanking520

**Comment by lanking520** [comment]
Awesome! 👍

**Comment by ThomasDelteil** [comment]
Is the Dockerfile in /docs still relevant in any ways?

**Comment by aaronmarkham** [comment]
@ThomasDelteil The Dockerfile should have the latest deps so that you can make the docs in Docker if you wish.

**Comment by ThomasDelteil** [comment]
I don't think that is true anymore Aaron? The file hasn't changed since 11 months ago and does not have Scala dependencies to start with.

**Comment by aaronmarkham** [comment]
@ThomasDelteil you're right. I made one in build_version_doc that is up to date. 
The one in docs was for folks that wanted to build locally and for just their current fork/branch, but is was/is broken.

**Pull request merged**
