### PR TITLE
[v1.x] Update unittests for object detection models

### PR DESCRIPTION
**Pull request by waytrue17**
## Description ##
To address the prediction mismatching due to different implementations of `nms` operator between mxnet and onnx.
### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by waytrue17** [comment]
@mxnet-bot run ci [sanity]

**Comment by waytrue17** [comment]
run ci [centos-gpu, edge]

**Review by josephevans — APPROVED** [review]
LGTM, thanks!

**Comment by waytrue17** [comment]
@mxnet-bot run ci [edge]

**Pull request merged**
