### PR TITLE
Remove model parallelism references from FAQ

### PR DESCRIPTION
**Pull request by ThomasDelteil**
## Description ##
Remove from the FAQ outdated references to model parallelism.
Model parallelism should be avoided as it is less performant than data parallelism, better accumulate gradients through multiple mini batches of small batch size rather than splitting the model to move bigger batches across GPUs.

- [x] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

**Comment by aaronmarkham** [comment]
I just fixed the broken links in that FAQ. :expressionless:
I think content should removed if it is "bad" information, however wouldn't it be better to provide a disclaimer at the top saying **This is considered less performant that x y and z and we recommend you look at [this other amazing tutorial](#) before you try the following model parallel approach.** Even talk a lot more about the reasoning and provide references... but then leave the content. What if someone has some super massive model and they really, really want to do it this way anyway?

**Comment by ThomasDelteil** [comment]
@aaronmarkham I agree, after a previous PR[1] where @indhub had written a Model parallelism tutorial, we had an offline discussion and decided that the penalty incurred by doing model parallelism when you should actually be doing data parallelism outweighed the benefit for the few users that would actually need model parallelism.

[1] https://github.com/apache/incubator-mxnet/pull/10568/files

**Comment by sandeep-krishnamurthy** [comment]
@ThomasDelteil - I think the content is not bad like @aaronmarkham  said. It is only communicating the pros/cons and setting the right context of when is this applicable or not.
Is there any strong  need to remove this?

**Comment by lupesko** [comment]
Agree with @sandeep-krishnamurthy comment.
@ThomasDelteil maybe you want to refine the doc a bit?

**Comment by ThomasDelteil** [comment]
@sandeep-krishnamurthy @aaronmarkham @lupesko closing for now, will follow up with other stakeholders and see if we actually need to remove. For the records, I don't think either strongly that we should remove this FAQ

**Pull request closed without merging**
