### PR TITLE
Improve CMake handling of sse2 and sse3 and fix compile error

### LINKED ISSUE #14304: error: inlining failed in call to always_inline 'float _cvtsh_ss(short unsigned int)': target specific option mismatch
## Description
Fail build

## Environment info (Required)

```
└───╼  python diagnose.py 
----------Python Info----------
Version      : 3.7.3
Compiler     : GCC 8.2.1 20181127
Build        : ('default', 'Mar 26 2019 21:43:19')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 19.0.3
Directory    : /usr/lib/python3.7/site-packages/pip
----------MXNet Info-----------
Version      : 1.5.0
Directory    : /usr/lib/python3.7/site-packages/mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Linux-5.0.7-arch1-1-ARCH-x86_64-with-arch
system       : Linux
node         : sL1pKn07
release      : 5.0.7-arch1-1-ARCH
version      : #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019
----------Hardware Info----------
machine      : x86_64
processor    : 
Arquitectura:                        x86_64
modo(s) de operación de las CPUs:    32-bit, 64-bit
Orden de los bytes:                  Little Endian
Tamaños de las direcciones:          46 bits physical, 48 bits virtual
CPU(s):                              48
Lista de la(s) CPU(s) en línea:      0-47
Hilo(s) de procesamiento por núcleo: 2
Núcleo(s) por «socket»:              12
«Socket(s)»                          2
Modo(s) NUMA:                        2
ID de fabricante:                    GenuineIntel
Familia de CPU:                      6
Modelo:                              79
Nombre del modelo:                   Genuine Intel(R) CPU 0000 @ 2.20GHz
Revisión:                            0
CPU MHz:                             2195.548
CPU MHz máx.:                        2200,0000
CPU MHz mín.:                        1200,0000
BogoMIPS:                            4392.19
Virtualización:                      VT-x
Caché L1d:                           32K
Caché L1i:                           32K
Caché L2:                            256K
Caché L3:                            30720K
CPU(s) del nodo NUMA 0:              0-11,24-35
CPU(s) del nodo NUMA 1:              12-23,36-47
Indicadores:                         fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0482 sec, LOAD: 0.8302 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0692 sec, LOAD: 0.9474 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0727 sec, LOAD: 0.8147 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0573 sec, LOAD: 1.2127 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0534 sec, LOAD: 0.7349 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0460 sec, LOAD: 0.2825 sec.
```

## Compiler (gcc/clang/mingw/visual studio):
gcc 8.3.0

CUDA 10.1.105
OpenCV 4.1.0
CuDNN 7.5.0.56
NCCL 2.4.6
OpenBLAS 0.3.5
lapack 3.8.0

## MXNet commit hash:
42e929bcb35d2d0a7cff4b09aa6e392976e75acc

## Build config:
```
  mkdir -p build

  cd incubator-mxnet

  # cython fix
  git pull --no-edit origin pull/10951/head

  git config submodule.3rdparty/mshadow.url "${srcdir}/mshadow"
  git config submodule.3rdparty/dmlc-core.url "${srcdir}/dmlc-core"
  git config submodule.3rdparty/dlpack.url "${srcdir}/dlpack"
  git config submodule.3rdparty/nvidia_cub.url "${srcdir}/cub"
  git config submodule.3rdparty/tvm.url "${srcdir}/tvm"
  git submodule update --init 3rdparty/mshadow 3rdparty/dmlc-core 3rdparty/dlpack 3rdparty/nvidia_cub 3rdparty/tvm

  pushd 3rdparty/tvm &> /dev/null
  git config submodule.dmlc-core.url "${srcdir}/dmlc-core"
  git config submodule.HalideIR.url "${srcdir}/HalideIR"
  git config submodule.dlpack.url "${srcdir}/dlpack"
  git submodule update --init 3rdparty/dmlc-core 3rdparty/HalideIR 3rdparty/dlpack
  popd &> /dev/null

  # Don't install lib when run 'python setup.py install'
  sed '/data_files/s/^/#/g' \
    -i python/setup.py

  # Add /usr/lib to search path in the python module
  sed -e '23aimport sysconfig' \
      -e "s|'\.\.\/\.\.\/\.\.\/'|sysconfig\.get_config_var\('LIBDIR'\)|g" \
      -i python/mxnet/libinfo.py

  # Disable gtest
  sed -e '/GTEST/s/^/#/g' \
      -e '/GTest/s/^/#/g' \
      -e '/CTest/s/^/#/g' \
      -e '/unittest/s/^/#/g' \
      -i CMakeLists.txt \
      -i 3rdparty/dmlc-core/CMakeLists.txt \
      -i 3rdparty/tvm/3rdparty/dmlc-core/CMakeLists.txt

  # Not install dmlc-core docs in /
  sed '/doc/s/^/#/g' \
    -i 3rdparty/dmlc-core/CMakeLists.txt \
    -i 3rdparty/tvm/3rdparty/dmlc-core/CMakeLists.txt

  # Add project version, VERSION and SOVERSION
  _ver="$(cat docs/_static/mxnet-theme/index.html | grep -m1 '<h3>MXNet' | cut -d ' ' -f10 | tr - .)"
  sed -e "2aset(_PROJECT_VERSION \"${_ver%.*}\")\n" \
      -e '711aset_target_properties(mxnet PROPERTIES VERSION "${_PROJECT_VERSION}")' \
      -e '711aset_target_properties(mxnet PROPERTIES SOVERSION \"0\")' \
      -i CMakeLists.txt

  # Fix typo (?) in cpp-package/CMakeLists.txt. https://github.com/apache/incubator-mxnet/issues/10742
  sed 's|NOT DO_NOT_BUILD_EXAMPLES|BUILD_CPP_EXAMPLES|' -i cpp-package/CMakeLists.txt

  cd build
  cmake ../incubator-mxnet \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_INSTALL_DOCDIR=share/doc/mxnet \
    -DBUILD_SHARED_LIBS=ON \
    -DCUDA_SDK_ROOT_DIR=/opt/cuda \
    -DUSE_CPP_PACKAGE=ON \
    -DUSE_CUDNN=ON \
    -DUSE_NCCL=ON \
    -DUSE_OPENCV=ON \
    -DUSE_OPENMP=ON \
    -DUSE_MKLDNN=OFF \
    -DUSE_LAPACK=ON \
    -DUSE_JEMALLOC=OFF \
    -DUSE_GPERFTOOLS=OFF \
    -DBUILD_CPP_EXAMPLES=OFF


  LC_ALL=C make VERBOSE=1
```

## Error Message:
```
[  4%] Building CXX object CMakeFiles/mxnet_static.dir/src/common/utils.cc.o
/usr/bin/g++-7  -DCUB_MKL=1 -DDMLC_USE_CXX11 -DDMLC_USE_CXX11=1 -DMSHADOW_IN_CXX11 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_CUDA=1 -DMSHADOW_USE_CUDNN=1 -DMSHADOW_USE_MKL=0 -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_BLAS_OPEN=1 -DMXNET_USE_CUDA=1 -DMXNET_USE_LAPACK=1 -DMXNET_USE_MKLDNN=1 -DMXNET_USE_NCCL=1 -DMXNET_USE_OPENCV=1 -DMXNET_USE_OPENMP=1 -DMXNET_USE_OPERATOR_TUNING=1 -DNDEBUG=1 -DUSE_CUDNN -DUSE_MKL=1 -I/tmp/makepkg/sl1-mxnet-git/src/build/mklml/mklml_lnx_2019.0.1.20180928/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/mkldnn/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src -I/opt/cuda/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/mshadow -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/cub -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/tvm/nnvm/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/tvm/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/dmlc-core/include -I/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/3rdparty/dlpack/include -isystem /usr/include/opencv4  -Wall -Wno-unknown-pragmas -Wno-sign-compare -O3 -msse2 -std=c++11 -fopenmp -std=c++0x -fPIC   -o CMakeFiles/mxnet_static.dir/src/common/utils.cc.o -c /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src/common/utils.cc
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/include/immintrin.h:87:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/include/x86intrin.h:48,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/././half.h:13,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/./base.h:278,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/tensor.h:16,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mxnet/./base.h:33,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mxnet/engine.h:34,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src/common/./utils.h:31,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src/common/utils.cc:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/include/f16cintrin.h: In member function 'mshadow::half::half_t::operator float() const':
/usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/include/f16cintrin.h:38:1: error: inlining failed in call to always_inline 'float _cvtsh_ss(short unsigned int)': target specific option mismatch
 _cvtsh_ss (unsigned short __S)
 ^~~~~~~~~
In file included from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/./base.h:278:0,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/tensor.h:16,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mxnet/./base.h:33,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mxnet/engine.h:34,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src/common/./utils.h:31,
                 from /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/src/common/utils.cc:25:
/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/././half.h:79:30: note: called from here
     return T(_cvtsh_ss(half_));   /* NOLINT(*)*/                          \
                              ^
/tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/include/mshadow/././half.h:126:3: note: in expansion of macro 'MSHADOW_HALF_CONVERSIONOP'
   MSHADOW_HALF_CONVERSIONOP(float)
   ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mxnet_static.dir/build.make:193: CMakeFiles/mxnet_static.dir/src/common/utils.cc.o] Error 1
make[2]: Leaving directory '/tmp/makepkg/sl1-mxnet-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/mxnet_static.dir/all] Error 2
make[1]: Leaving directory '/tmp/makepkg/sl1-mxnet-git/src/build'
make: *** [Makefile:130: all] Error 2
```

## Minimum reproducible example
try to build in updated archlinux

## Steps to reproduce
see build config section

## What have you tried to solve it?
`-DUSE_F16C=OFF` seems "fix" the issue

### PR DESCRIPTION
**Pull request by larroy**
## Description ##
This fixes a problem when compiling when F16C is enabled but the flag is missing for the compiler.
Fix #14304 where CFLAGS were overriden instead of appended to.
Improve CMake handling of sse2 and sse3 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by larroy** [comment]
@mxnet-label-bot add [CMake, build, Bug]

**Comment by larroy** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by larroy** [comment]
@iblis17 any ideas?

**Comment by iblis17** [comment]
I rewrite that flaky test case: https://github.com/apache/incubator-mxnet/pull/14776

**Comment by larroy** [comment]
@lebeg please help review.

**Comment by lebeg** [comment]
It would be better to have a separate module for SSE in general, but it looks good now as well

**Pull request merged**
