### PR TITLE
Manually check node existence in CachedOp

### PR DESCRIPTION
**Pull request by junrushao1994**
## Description ##
Constructing a weird `CachedOp` directly in C++, in rare cases might lead to rebuilding `full_graph` in `CachedOp` without updating `bwd_ograd_dep_`. This potentially causes crash when `OpReqType` of one of `outputs` of `grad_graph_` is `OpReqType::kNullOp`. This PR enhances the capability of `CachedOp` to handle this case.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Manually check node existence in CachedOp

## Comments ##
- This change is fully backward compatible.

### CODE REVIEW

**Comment by junrushao1994** [comment]
@zheng-da @piiswrong Could you help review this PR? Thanks!

**Comment by junrushao1994** [comment]
@szha I will change `std::numeric_limits<uint32_t>::max()` to `kEidNotExist`

**Comment by zheng-da** [comment]
@junrushao1994 Please write a unit test that fails without this fix.

**Comment by junrushao1994** [comment]
@zheng-da Thank you for the tips! I added the testcase just now.

**Pull request merged**
