### PR TITLE
[MXNET-530] Remove install page artifacts

### PR DESCRIPTION
**Pull request by kpmurali**
## Description ##
Removing the install page artifacts and the changes to incorporate them into the build process

### Changes ###
- [ x ] Remove the update_install function
- [ x ] Remove the references to the above function

### CODE REVIEW

**Comment by aaronmarkham** [comment]
We need this so the new version selector for install doesn't get overwritten! Looks good!

**Comment by aaronmarkham** [comment]
Please merge ASAP!

**Comment by aaronmarkham** [comment]
@eric-haibin-lin @szha Bueller? Can you please merge this?

**Comment by aaronmarkham** [comment]
@marcoabreu Can you possibly merge this? It's really messing with all of our work on the install page. As in none of it showing up until this goes through.

**Comment by marcoabreu** [comment]
Won't this leave the website in a broken state until a follow-up PR has been merged?

**Comment by aaronmarkham** [comment]
No, these artifacts are in fact overwriting the install page. It will fix the site.

**Comment by marcoabreu** [comment]
Alright, I trust you on that one :)

**Pull request merged**
