### PR TITLE
Fix isnan usage in RTC

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Fixes problem reported in #18622, where the non-templated version of `isnan` was used inside min and max functions, causing failures for integer types.

### CODE REVIEW

**Comment by marcoabreu** [comment]
I mean we discovered a clear case where it fails, so why not add a test?

**Comment by sxjscience** [comment]
Currently it's triggered if we train the ELECTRA-small model in GluonNLP: https://github.com/dmlc/gluon-nlp/tree/master/scripts/pretraining, which is somehow complicated.

**Comment by marcoabreu** [comment]
Maybe @ptrendx can extract the relevant part and create a unit test out of it?

**Comment by ptrendx** [comment]
Yes, I can and will add a test (sorry for not answering it earlier).

**Comment by ptrendx** [comment]
I added testing of integer datatype to maximum and minimum functions - currently `test_np_binary_funcs` by default only checks floating point types.

**Comment by marcoabreu** [comment]
Thanks!

**Comment by ptrendx** [comment]
@mxnet-bot run ci [centos-gpu, windows-cpu]

**Comment by ptrendx** [comment]
@marcoabreu Do you think this PR is good to go?

**Pull request merged**
