### PR TITLE
Check for version artifacts in website pipeline

### PR DESCRIPTION
**Pull request by Zha0q1**
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-website-build-master/detail/restricted-website-build-master/1495/pipeline/151/

Refer to the above link. There are four stages in the website pipeline: build, build docs, prepare, and publish.

In the prepare stage we need to check if the docs artifacts are successfully fetched (from the s3 bucket) for the mxnet version we are defaulting to before moving on to publish the website. This is critical because if the artifacts are missing then the website will be unavailable. 

Specifically, we want to extract the website redirect information (default mxnet version) here https://github.com/apache/incubator-mxnet/blob/179262b1e357f3ed7bd2825a5a16259b45a2c40f/docs/static_site/src/.htaccess#L30, and check if in our docker there is already the folder `/versions/{version}/api`.

The added commands will 1. check if `.htaccess` exists (return 1 if so) 2. match the version number 3. check if there are multiple version numbers (return 1 if so) 4. check if the version is empty (return 1 if so) 5. check if the directory exists (return 1 if NOT so)

we use `sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')` to match the version number. Example:
input
```
RewriteRule ^(.*)$ /versions/1.7/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/2.0/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/2.1/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/1.8/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/0.0.0/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/2.1.12321/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/1.a/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/a.b/$1 [r=307,L]
RewriteRule ^(.*)$ /versions/a.1.b/$1 [r=307,L]
```
output 
```
1.7
2.0
2.1
1.8
0.0.0
2.1.12321
1
```
Of course in reality there must only be one and only one match.

TODO:
we need to test if `exit 1` will stop/fail the pipeline. If not we probably need to catch the return val in https://github.com/apache/incubator-mxnet/blob/1f158197aa1fbd3a31c67581537bc1ee37e11dd0/ci/jenkins/Jenkins_steps.groovy#L1096 and find command to stop the pipeline there

@mseth10 @ys2843  @waytrue17

### CODE REVIEW

**Review by access2rohit — APPROVED** [review]

**Comment by ys2843** [comment]
I tested this PR on Jenkins and `prepare` stage didn't succeed. 
`20:05:38  .htaccess file does not exist. Exiting 1`,  http://jenkins.mxnet-ci-dev.amazon-ml.com/job/docs/job/yang-website-build-master/202/

Current CI doesn't run `prepare` for each PR (only website publish pipeline does), so to test it you could get access to jenkins dev server and run website prepare

**Comment by Zha0q1** [comment]
> I tested this PR on Jenkins and `prepare` stage didn't succeed.
> `20:05:38 .htaccess file does not exist. Exiting 1`, http://jenkins.mxnet-ci-dev.amazon-ml.com/job/docs/job/yang-website-build-master/202/
> 
> Current CI doesn't run `prepare` stage for each PR (only website publish pipeline does), to test your changes, you could get access to Jenkins dev server and run website prepare stage

Thanks Yang! I might be lacking context on this. So do we have a machine that can be leveraged for the test or do I need to set up a replica of the website publish pipeline? Also pinging @mseth10

**Review by mseth10 — APPROVED** [review]
LGTM

**Comment by mseth10** [comment]
The website build dev pipeline has succeeded: http://jenkins.mxnet-ci-dev.amazon-ml.com/blue/organizations/jenkins/docs%2Fyang-website-build-master/detail/yang-website-build-master/205/pipeline/149/

@ys2843 can you please help review/ merge this PR. Thanks!

**Comment by Zha0q1** [comment]
Update: 
The "TODO" has been confirmed: exit 1 does stop the pipeline

**Review by ys2843 — APPROVED** [review]

**Pull request merged**
