### PR TITLE
update mkldnn to 0.16

### PR DESCRIPTION
**Pull request by azai91**
## Description ##
update mkldnn submodule to 0.16

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] update mkldnn submodule to 0.16

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by TaoLv** [comment]
Hi Alex, thanks for bring this up. So far as I know, mkl-dnn introduced in padding format for better performance recently and it would require more memory for computation, compared with the logical size of tensor. In the existing integration code, we are re-using those memory from input/output NDArray for computation and they are allocated according to the logical size during memory planning phase. So I don't think we can simply update mkl-dnn to 0.16 at this time. I have talked with @zheng-da and @eric-haibin-lin about that and we are also trying to figure out a work around before we can change the behavior of memory planning for mkldnn backend. @pengzhao-intel

**Comment by eric-haibin-lin** [comment]
@TaoLv thanks for the heads-up. It would be great if you can share the design/plan on how you want to change memory planning to achieve this

**Comment by kalyc** [comment]
Thanks for your contribution @azai91 
@mxnet-label-bot[pr-awaiting-response]

**Comment by azai91** [comment]
@TaoLv any plans to upgrade 0.16? a few people within amazon are inquiring.

**Pull request closed without merging**
