### PR TITLE
Comments formatting fix

### PR DESCRIPTION
**Pull request by DominikaJedynak**
## Description ##
This PR fixes the formatting of some comments so that they can be parsed by a documentation generator.

### CODE REVIEW

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-gpu, edge, windows-gpu]

**Review by bartekkuncer — APPROVED** [review]

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Comment by bgawrych** [comment]
@mxnet-bot run ci [centos-gpu, windows-gpu]

**Comment by DominikaJedynak** [comment]
@mxnet-bot run ci [windows-gpu]

**Review by bgawrych — APPROVED** [review]

**Pull request merged**
