### PR TITLE
[LICENSE] Update ps-lite LICENSE

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
A new file was added to ps-lite by ByteDance. I'm including the copyright in LICENSE. Is this the right way to fix it? @leezu @roywei 

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by leezu** [comment]
@eric-haibin-lin according to https://github.com/apache/incubator-mxnet/issues/17329 the problem is "file copyright Bytedance Inc [5] of unknown license". However, Bytedance has (supposedly?) licensed the code under Apache license by submitting the Pull Request on Github to the Apache Licensed repo ps-lite. To avoid such future issues, it would be best to require including the Apache License header in all files in ps-lite.

@eric-haibin-lin @roywei could you clarify why to include the copyright notice in LICENSE? Based on the Apache License and the Licensing Howto there doesn't seem to be such requirement? But I may have missed some point.
- http://www.apache.org/dev/licensing-howto.html#permissive-deps
- http://www.apache.org/dev/licensing-howto.html#alv2-dep

**Comment by roywei** [comment]
Hi @leezu , for 3rd party source files, we do not need to include the ASF license header, as it's not developed by ASF. We can depend on ps-lite as it's a permissive license (Apache 2.0). That specific file should already be covered by the apache-2.0 license, and we already acknowledged it in LICENSE file. So we just need to acknowledge additional copy right comes from ps-lite.  
 I think the mentor may made a mistake about the unknown license part.

From https://www.apache.org/legal/src-headers.html:
> Do not add the standard Apache License header to the top of third-party source files.

Our rat check already excluded 3rdparty directory. So we will only have problem if we added ASF header wrongly, any missing header will cause rat check to fail.

**Comment by leezu** [comment]
Thanks @roywei. In case you know, could you post a reference to why copyright notice needs to be included inside our LICENSE file?

**Comment by roywei** [comment]
@leezu I can't find any from ASF website. We started to add them in previous releases as mentors pointed out before. It seems to be the same issue this time.
https://github.com/apache/incubator-mxnet/pull/13851

**Pull request merged**
