### PR TITLE
[BUGFIX] Fix MKLDNN BatchNorm with even number of channels (#19150)

### PR DESCRIPTION
**Pull request by akarbown**
Even number of channels results in data reordering before batch
norm operation. Therefore, if BatchNorm data array is view of
another array and the data is stored in MKLDNN format, the data
needs to be converted to the default format.

It fixes: https://github.com/apache/incubator-mxnet/issues/19150.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### CODE REVIEW

**Comment by akarbown** [comment]
@mxnet-bot run ci [edge]

**Comment by akarbown** [comment]
@mxnet-bot run ci [edge]

**Comment by akarbown** [comment]
@mxnet-bot run ci [edge]

**Comment by akarbown** [comment]
@PatricZhao , @TaoLv could you please review it!
This review is for branch 1.7, but the issue seems to occur on the other branches as well. Thus, it'll need to be applied on them also.
[With reference to the job 'edge' tests - it seems to be not related to this change.]

**Comment by TaoLv** [comment]
@akarbown please add the issue link to the description of this PR. Also do you want to add a unit test?

@wkcn could you please help to review?

**Review by wkcn — COMMENTED** [review]
Thank you for the fix : )

Could you please update the test cases for MKLDNN-BatchNorm with even number of channels in [tests/python/mkl/test_mkldnn.py#L297](https://github.com/apache/incubator-mxnet/blob/v1.7.x/tests/python/mkl/test_mkldnn.py#L297) ?
```python
for shape in [(2, 3), (2, 4), (2, 3, 2, 2), (2, 4, 2, 2)]:
```

**Comment by akarbown** [comment]
> Thank you for the fix : )
> 
> Could you please update the test cases for MKLDNN-BatchNorm with even number of channels in [tests/python/mkl/test_mkldnn.py#L297](https://github.com/apache/incubator-mxnet/blob/v1.7.x/tests/python/mkl/test_mkldnn.py#L297) ?
> 
> ```python
> for shape in [(2, 3), (2, 4), (2, 3, 2, 2), (2, 4, 2, 2)]:
> ```

Done!
I've also added one more test similar to the one from the requested issue.

**Review by wkcn — APPROVED** [review]
LGTM. Thank you!

**Comment by szha** [comment]
thanks for the fix. please make sure to port to other branches (e.g. v1.x, v1.8.x, master) as appropriate.

**Pull request merged**
