### PR TITLE
v1.x website patch

### PR DESCRIPTION
**Pull request by ys2843**
## Description ##
Cherry pick latest website changes from master to v1.x branch, this ensure the website will be good for future 1.8, 1.9 release. 

> Note: this PR should be merged before creating new branch for v1.8, v1.9
 
### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Cherry pick website code changes to 1.x branch

## Comments ##
- Preview: pending

### CODE REVIEW

**Review by szha — APPROVED** [review]

**Comment by mseth10** [comment]
@samskalicky we need to cherry pick this PR to v1.8 branch. @ys2843 will be creating a PR for it shortly.

**Comment by ys2843** [comment]
> @samskalicky we need to cherry pick this PR to v1.8 branch. @ys2843 will be creating a PR for it shortly.

Cherry pick this PR to v1.8: https://github.com/apache/incubator-mxnet/pull/19212

**Comment by ciyongch** [comment]
@ys2843 Thanks for backport the news as well as the enhancement for the website from master to v1.x/v1.8.x, may I cherry pick this to v1.7.x branch, or can you help to do so?

**Comment by ys2843** [comment]
> @ys2843 Thanks for backport the news as well as the enhancement for the website from master to v1.x/v1.8.x, may I cherry pick this to v1.7.x branch, or can you help to do so?

@ciyongch the cherry pick to 1.7 is here: https://github.com/apache/incubator-mxnet/pull/19102. Once this PR got merged, v1.7 should be good

**Comment by ciyongch** [comment]
That's good, thanks for your kindly help @ys2843 !

**Pull request merged**
