### PR TITLE
[1.x] Revert Fix memory leaks in Gluon in 1.x branch

### PR DESCRIPTION
**Pull request by rondogency**
This reverts commit b523527df2aee4caa9275f9f1fa1668d5ae27cd6.

This is a continuation of 1.7 revert of the same PR: https://github.com/apache/incubator-mxnet/pull/18692

Since CD is built on top of 1.x, we should also unblock CD on top of 1.7 release

### CODE REVIEW

**Comment by szha** [comment]
@leezu are you patching it in master? That way @rondogency can pick it up here and validate 1.x again.

**Comment by leezu** [comment]
The issue does not apply to master.

**Comment by szha** [comment]
Oh right, I just realized that _BlockScope is gone.

**Comment by rondogency** [comment]
@mxnet-bot run ci [edge, unix-gpu]

**Comment by szha** [comment]
I think when enabling the branch protection, we accidentally turned on "Require branches to be up to date before merging". I'm requesting to disable it in https://issues.apache.org/jira/browse/INFRA-20616. Don't worry about updating the branch in this PR for now.

**Pull request closed without merging**
