### PR TITLE
[MXNET-1399] multiclass-mcc metric enhancements

### PR DESCRIPTION
**Pull request by tlby**
## Description ##
multiclass-mcc metric enhancements

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] Rename metric from "PCC" to "MMCC" because though the math is derived
   from Pearson CC, it's utility is as a multiclass extension of Mathews CC.
- [x] Harden mx.metric.MMCC.update to more variations of input format, similar to
   mx.metric.Accuracy.update.

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
The name change from `mx.metric.PCC()` to `mx.metric.MMCC()` for this metric has not yet been included in any releases or tagged branches, and for anyone following master the code update would be trivial.

### CODE REVIEW

**Comment by tlby** [comment]
verified that the additional checks in mx.metric.MMCC.update() are not a bottleneck.
[bench.py](https://github.com/apache/incubator-mxnet/files/3143902/bench.py.txt)

**Comment by tlby** [comment]
Oh, I should clarify this here; I discovered that use cases like the [fastText example from gluon-nlp](https://github.com/dmlc/gluon-nlp/blob/b079babf096e2a82bb901c7e16efe14183f7709f/scripts/text_classification/fasttext_word_ngram.py#L154) expect metrics to be comfortable taking predictions already `.argmax()` resolved.  `mx.metric.Accuracy` has a special case for that and this patch makes mx.metric.MMCC flexible in the same way.

**Comment by szha** [comment]
@tlby thanks for the patch! Since PCC has already been merged for almost a month, there might be people who already depend on PCC. If there is, then renaming PCC to MMCC will likely break them. Since PCC hasn't made into a release yet, it's technically not breaking a released API, but with that in mind, do you feel necessary to rename the class?

**Comment by tlby** [comment]
I don't think it's absolutely necessary, but I definitely regret the name choice because while the implementation came from a discrete derivation of the Pearson correlation coefficient, all a user cares about is that it's a multiclass extension of Matthews correlation coefficient.  When it comes to using these metrics Pearson is for continuous and Matthews is for discrete predictions.  This metric is discrete so I feel it was misnamed.  I later discovered that the formula I used is equivalent to one [mentioned in Wikipedia](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient#Multiclass_case) as an extension of Matthews.

Perhaps we should leave "pcc" as an alias for the sake of reverse compatibility?

**Comment by anirudhacharya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by karan6181** [comment]
@szha Could you please review it again? Thanks!

**Comment by piyushghai** [comment]
@szha Gentle ping...

**Comment by vandanavk** [comment]
Is this PR good to go?

**Comment by szha** [comment]
@karan6181 @piyushghai @vandanavk the class rename needs to be reverted

**Comment by karan6181** [comment]
@szha I think @tlby addressed your review comments by renaming the class. Could you please review it again? Thanks!

**Comment by szha** [comment]
Thanks @tlby! The only thing left is that we need test cases to cover both code paths.

**Comment by piyushghai** [comment]
@szha Is this PR good to merge now ?

**Pull request merged**
