### PR TITLE
Backport #16798, #16836 and #16838 to 1.6

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Backporting #16798, #16836 and #16838 to 1.6.x branch.

@haojin2 @DickJC123  FYI

### CODE REVIEW

**Comment by ptrendx** [comment]
@haojin2 Windows build failed with `fatal error C1002: compiler is out of heap space in pass 2` - did you do anything in the other PRs to reduce the memory usage during compilation?

**Comment by ptrendx** [comment]
Due to problems with compilation on Windows I removed #16791 from this bulk of cherry-picks. @haojin2 Please make a separate PR to bring #16791 to 1.6.x branch and work on fixing those issues there.

**Comment by haojin2** [comment]
@ptrendx There's a separate PR #16827 that is needed to fix such issues. #16827 made a major refactor to the np_elemwise_binary_broadcast part and reduced the pressure on windows vs compilers.

**Comment by ptrendx** [comment]
Ok, so @haojin2 please make a PR to 1.6.x branch with both #16827 and #16791.

**Pull request merged**
