### PR TITLE
[MXNET-397] remove unused rotateM_

### PR DESCRIPTION
**Pull request by nihui**
## Description ##
the actual rotate param is allocated on demand, the rotateM_ member is useless
remove it

### Essentials ###
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- [x] Code is well-documented: 
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by lupesko** [comment]
@nihui thanks for your contribution! can you please resolve branch conflicts?

**Comment by lupesko** [comment]
@mxnet-label-bot [pr-awaiting-review]

**Comment by lupesko** [comment]
Adding @nswamy to help review

**Comment by vandanavk** [comment]
@apeforest @haojin2 for review

**Comment by vrakesh** [comment]
@nswamy @apeforest Requesting an review on this PR.

**Comment by ankkhedia** [comment]
@nswamy @eric-haibin-lin  @apeforest @haojin2 
Could you please take a look into this PR?

**Comment by eric-haibin-lin** [comment]
@nihui thx for the contribution!

**Pull request merged**
