### PR TITLE
add mobilenet

### PR DESCRIPTION
**Pull request by qingzhouzhen**
This mobilenet implements article [MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications](https://arxiv.org/abs/1704.04861)
It speeds up training and scoring in ImageNet 2012 with CPU version but not GPU
I will try to implemented depth-wise conv using cuda kernel

### CODE REVIEW

**Comment by feiyulv** [comment]
How about the final acc compared with the original network?

**Comment by qingzhouzhen** [comment]
I am training on my machines,  I did not get the final accuacy file, but currently it is low than normal convulution.

**Comment by qingzhouzhen** [comment]
I got the current result as below
INFO:root:Epoch[35] Batch [2080]        Speed: 204.10 samples/sec       accuracy=0.745996
INFO:root:Epoch[35] Batch [2100]        Speed: 203.38 samples/sec       accuracy=0.753320
INFO:root:Epoch[35] Batch [2120]        Speed: 203.06 samples/sec       accuracy=0.743457
INFO:root:Epoch[35] Batch [2140]        Speed: 203.16 samples/sec       accuracy=0.747852
INFO:root:Epoch[35] Batch [2160]        Speed: 205.46 samples/sec       accuracy=0.743262
INFO:root:Epoch[35] Batch [2180]        Speed: 205.97 samples/sec       accuracy=0.749219
INFO:root:Epoch[35] Batch [2200]        Speed: 201.81 samples/sec       accuracy=0.748340
INFO:root:Epoch[35] Batch [2220]        Speed: 202.77 samples/sec       accuracy=0.757812
INFO:root:Epoch[35] Batch [2240]        Speed: 202.41 samples/sec       accuracy=0.747656
INFO:root:Epoch[35] Batch [2260]        Speed: 202.23 samples/sec       accuracy=0.752637
INFO:root:Epoch[35] Batch [2280]        Speed: 204.70 samples/sec       accuracy=0.758789
INFO:root:Epoch[35] Batch [2300]        Speed: 202.87 samples/sec       accuracy=0.760156
INFO:root:Epoch[35] Batch [2320]        Speed: 202.67 samples/sec       accuracy=0.760840
INFO:root:Epoch[35] Batch [2340]        Speed: 204.11 samples/sec       accuracy=0.762012
INFO:root:Epoch[35] Batch [2360]        Speed: 205.23 samples/sec       accuracy=0.753516
INFO:root:Epoch[35] Batch [2380]        Speed: 205.74 samples/sec       accuracy=0.771777
INFO:root:Epoch[35] Batch [2400]        Speed: 203.00 samples/sec       accuracy=0.769336
INFO:root:Epoch[35] Batch [2420]        Speed: 202.30 samples/sec       accuracy=0.762891
INFO:root:Epoch[35] Batch [2440]        Speed: 205.86 samples/sec       accuracy=0.759570
INFO:root:Epoch[35] Batch [2460]        Speed: 204.60 samples/sec       accuracy=0.761133
INFO:root:Epoch[35] Batch [2480]        Speed: 203.70 samples/sec       accuracy=0.771875
INFO:root:Epoch[35] Batch [2500]        Speed: 204.29 samples/sec       accuracy=0.740234

**Comment by qingzhouzhen** [comment]
I get current result as below @feiyulv :
INFO:root:Epoch[35] Batch [2080]        Speed: 204.10 samples/sec       accuracy=0.745996
INFO:root:Epoch[35] Batch [2100]        Speed: 203.38 samples/sec       accuracy=0.753320
INFO:root:Epoch[35] Batch [2120]        Speed: 203.06 samples/sec       accuracy=0.743457
INFO:root:Epoch[35] Batch [2140]        Speed: 203.16 samples/sec       accuracy=0.747852
INFO:root:Epoch[35] Batch [2160]        Speed: 205.46 samples/sec       accuracy=0.743262
INFO:root:Epoch[35] Batch [2180]        Speed: 205.97 samples/sec       accuracy=0.749219
INFO:root:Epoch[35] Batch [2200]        Speed: 201.81 samples/sec       accuracy=0.748340
INFO:root:Epoch[35] Batch [2220]        Speed: 202.77 samples/sec       accuracy=0.757812
INFO:root:Epoch[35] Batch [2240]        Speed: 202.41 samples/sec       accuracy=0.747656
INFO:root:Epoch[35] Batch [2260]        Speed: 202.23 samples/sec       accuracy=0.752637
INFO:root:Epoch[35] Batch [2280]        Speed: 204.70 samples/sec       accuracy=0.758789
INFO:root:Epoch[35] Batch [2300]        Speed: 202.87 samples/sec       accuracy=0.760156
INFO:root:Epoch[35] Batch [2320]        Speed: 202.67 samples/sec       accuracy=0.760840
INFO:root:Epoch[35] Batch [2340]        Speed: 204.11 samples/sec       accuracy=0.762012
INFO:root:Epoch[35] Batch [2360]        Speed: 205.23 samples/sec       accuracy=0.753516
INFO:root:Epoch[35] Batch [2380]        Speed: 205.74 samples/sec       accuracy=0.771777
INFO:root:Epoch[35] Batch [2400]        Speed: 203.00 samples/sec       accuracy=0.769336
INFO:root:Epoch[35] Batch [2420]        Speed: 202.30 samples/sec       accuracy=0.762891
INFO:root:Epoch[35] Batch [2440]        Speed: 205.86 samples/sec       accuracy=0.759570
INFO:root:Epoch[35] Batch [2460]        Speed: 204.60 samples/sec       accuracy=0.761133
INFO:root:Epoch[35] Batch [2480]        Speed: 203.70 samples/sec       accuracy=0.771875
INFO:root:Epoch[35] Batch [2500]        Speed: 204.29 samples/sec       accuracy=0.740234

**Pull request merged**
