### PR TITLE
fix bug, issue 12613

### PR DESCRIPTION
**Pull request by lovickie**
fix a bug
https://github.com/apache/incubator-mxnet/issues/12613

### CODE REVIEW

**Comment by stu1130** [comment]
Thanks for your contribution @
@mxnet-label-bot[pr-awaiting-review]

**Comment by arronhanson1024** [comment]
@eric-haibin-lin an expert in engine/executor related stuff.
@cjolivier01 fixed several related issues last year.

Could you guys help review this PR?

**Comment by junrushao1994** [comment]
@eric-haibin-lin who is an expert in engine/executor-related stuff.
@cjolivier01 who fixed several related bugs last year.

Could you guys help review this PR? Thanks a lot!

**Comment by vandanavk** [comment]
Adding @apeforest @haojin2 for review too

**Comment by eric-haibin-lin** [comment]
@lovickie thanks for the contribution!

**Pull request merged**
