### PR TITLE
Add embedding to print_summary

### LINKED ISSUE #12778: Cannot print parameter summary of embedding layer
## Description
0  parameter of Embedding layer, when print_summary() 

## Environment info (Required)

MXNet 1.3.0

Package used (Python/R/Scala/Julia):
I am using python

## Minimum reproducible example

```
class SentClassificationModel(gluon.HybridBlock):
    def __init__(self, vocab_size, num_embed, **kwargs):
        super(SentClassificationModel, self).__init__(**kwargs)
        with self.name_scope():
            self.embed = nn.Embedding(input_dim=vocab_size, output_dim=num_embed)
            self.drop = nn.Dropout(0.3)
            self.fc = nn.Dense(100, activation='relu')
            self.out = nn.Dense(2)  
    def hybrid_forward(self, F ,inputs):
        em_out = self.drop(self.embed(inputs))
        fc_out = self.fc(em_out) 
        return(self.out(fc_out))

ctx = mx.gpu()

model = SentClassificationModel(vocab_size = len(vocab.idx_to_token), num_embed=50)

model.initialize(mx.init.Xavier(),ctx=ctx)
model.hybridize()

mx.viz.print_summary(
    model(mx.sym.var('data')), 
    shape={'data':(1,30)}, #set your shape here
)
```

```
________________________________________________________________________________________________________________________
Layer (type)                                        Output Shape            Param #     Previous Layer                  
========================================================================================================================
data(null)                                          30                      0                                           
________________________________________________________________________________________________________________________
sentclassificationmodel0_embedding0_fwd(Embedding)  30x50                   0           data                            
________________________________________________________________________________________________________________________
sentclassificationmodel0_dropout0_fwd(Dropout)      30x50                   0           sentclassificationmodel0_embeddi
________________________________________________________________________________________________________________________
sentclassificationmodel0_dense0_fwd(FullyConnected) 100                     3100        sentclassificationmodel0_dropout
________________________________________________________________________________________________________________________
sentclassificationmodel0_dense0_relu_fwd(Activation)100                     0           sentclassificationmodel0_dense0_
________________________________________________________________________________________________________________________
sentclassificationmodel0_dense1_fwd(FullyConnected) 2                       202         sentclassificationmodel0_dense0_
========================================================================================================================
Total params: 3302
________________________________________________________________________________________________________________________
```

### PR DESCRIPTION
**Pull request by soeque1**
## Description ##
Fixes #12778

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by soeque1** [comment]
The Post (#12778) does not have enough information to run the code. 
So I added something to the sample code.

```
from mxnet import gluon
from mxnet.gluon import HybridBlock, nn
import mxnet as mx

vocab_size
```


```
from mxnet import gluon
from mxnet.gluon import HybridBlock, nn
import mxnet as mx

class SentClassificationModel(gluon.HybridBlock):
    def __init__(self, vocab_size, num_embed, **kwargs):
        super(SentClassificationModel, self).__init__(**kwargs)
        with self.name_scope():
            self.embed = nn.Embedding(input_dim=vocab_size, output_dim=num_embed)
            self.drop = nn.Dropout(0.3)
            self.fc = nn.Dense(100, activation='relu')
            self.out = nn.Dense(2)  
    def hybrid_forward(self, F ,inputs):
        em_out = self.drop(self.embed(inputs))
        fc_out = self.fc(em_out) 
        return(self.out(fc_out))

ctx = mx.gpu()

model = SentClassificationModel(vocab_size = 20, num_embed=50)

model.initialize(mx.init.Xavier(),ctx=ctx)
model.hybridize()

mx.viz.print_summary(
    model(mx.sym.var('data')), 
    shape={'data':(1,30)}, #set your shape here
)

```

The output is the below

```
________________________________________________________________________________________________________________________
Layer (type)                                        Output Shape            Param #     Previous Layer                  
========================================================================================================================
data(null)                                          30                      0                                           
________________________________________________________________________________________________________________________
sentclassificationmodel2_embedding0_fwd(Embedding)  30x50                   1000        data                            
________________________________________________________________________________________________________________________
sentclassificationmodel2_dropout0_fwd(Dropout)      30x50                   0           sentclassificationmodel2_embeddi
________________________________________________________________________________________________________________________
sentclassificationmodel2_dense0_fwd(FullyConnected) 100                     3100        sentclassificationmodel2_dropout
________________________________________________________________________________________________________________________
sentclassificationmodel2_dense0_relu_fwd(Activation)100                     0           sentclassificationmodel2_dense0_
________________________________________________________________________________________________________________________
sentclassificationmodel2_dense1_fwd(FullyConnected) 2                       202         sentclassificationmodel2_dense0_
========================================================================================================================
Total params: 4302
________________________________________________________________________________________________________________________
```

**Comment by marcoabreu** [comment]
Am I catching it wrong or is test_print_summary() actually not doing any validation?

**Comment by soeque1** [comment]
@marcoabreu The test_print_summary() just print the output that have a lot of model information. It seems to be no problem.

Another test may be required to verify the number of each layer's parameters or output sizes. It is related to the definition, print_layer_summary() in print_summary(). But, It is different from this issue(#12796).

**Comment by sandeep-krishnamurthy** [comment]
@marcoabreu - This is fixing one of the important user facing functionality. I would like to merge this changes in and track other case tests as an issue. Any concerns?

**Comment by marcoabreu** [comment]
Fine with me

**Pull request merged**
