### PR TITLE
fix a formula typo in doc

### PR DESCRIPTION
**Pull request by zjjxsjh**

### CODE REVIEW

**Comment by piiswrong** [comment]
It is num filter

**Comment by zjjxsjh** [comment]
num_channel is in the input dimension

num_filter is in the output dimension

the num_channel dimension should be summed up

**Comment by zjjxsjh** [comment]
num_channel is in the input dimension

num_filter is in the output dimension

the num_channel dimension should be summed up

**Comment by tqchen** [comment]
@piiswrong It is indeed should be num_filter?

**Comment by piiswrong** [comment]
Looks like should be channel instead of num_channel

**Pull request merged**
