### PR TITLE
Update contribute.md (Fix links to subscribe for users and contributors)

### PR DESCRIPTION
**Pull request by sad-**
## Description ##

This change is to update the contribute.md page to use the right references/links for the subscribing to the different mailing lists.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by marcoabreu** [comment]
Hello Soji, welcome to MXNet and thanks a lot for your first contribution!

**Comment by sandeep-krishnamurthy** [comment]
@sad- Can you please retrigger CI? (with empty commit)
Changes looks good, thanks for your contributions.

**Comment by eric-haibin-lin** [comment]
@marcoabreu why doesnt CI show any status?

**Comment by marcoabreu** [comment]
It seems like this particular PR is bugged and does not execute the ping to our ci server. I'd recommend reopening the PR

**Comment by sad-** [comment]
@marcoabreu i see you tried closing and reopening and that still did not trigger the ci. Any idea why that did not work? Did you mean closing out this one entirely and opening a different one?

**Comment by marcoabreu** [comment]
Exactly

**Comment by sad-** [comment]
https://github.com/apache/incubator-mxnet/pull/12183

**Pull request closed without merging**
