### PR TITLE
Refactor L2_normalization

### PR DESCRIPTION
**Pull request by ZhennanQin**
## Description ##
Refactor L2_normalization for speed up. Before this change, on skx-8180,  L2_normalization will take 8372 ms in ssd-vgg16 for bs=1, num_batch=1000. After adopting this change, L2_normalization only takes 372ms for same work load.

Current unit test can cover all changes in this PR.

@pengzhao-intel

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ankkhedia** [comment]
@ZhennanQin Thanks for the contrbution!
Request you to look into CI failures before the PR can be reviewed.

@mxnet-label-bot [pr-awaiting-review, performance, operator ]

**Comment by RogerChern** [comment]
The original version implemented in mshadow expression template works both for cpu and gpu; If you are only intereseted in an accelerated cpu version, please move your code to a cpu specialized template in the l2_normalization.cc file

**Comment by ZhennanQin** [comment]
> The original version implemented in mshadow expression template works both for cpu and gpu; If you are only intereseted in an accelerated cpu version, please move your code to a cpu specialized template in the l2_normalization.cc file

Thanks for review. The cpu optimization is moved to  l2_normalization.cc as your suggestion.

**Comment by leezu** [comment]
Thanks for your PR! Your current implementation will tend to underflow for small values and overflow for large values. How about using a stable algorithm for normalizing? You can take a look at https://github.com/apache/incubator-mxnet/blob/2899715921612ef4dd147004292b5b5d0f83320b/src/operator/mshadow_op.h#L892 or the BLAS nrm2 implementation. There is an open PR that changes L2_normalization Op to make use of the stable implementation, but it is currently abandoned https://github.com/apache/incubator-mxnet/pull/12440

**Comment by ZhennanQin** [comment]
@leezu Good suggestion, but it's better to be implemented by another PR. This PR is just a code refactoring to speed up current algorithm.

**Comment by anirudhacharya** [comment]
Also the current l2-normalization uses legacy implementation, it needs to be updated with nnvm operator registration

**Comment by eric-haibin-lin** [comment]
@lanking520 is scala test flaky or does this PR break sth?

**Comment by lanking520** [comment]
bug fixed... pull rebase master should resolve

**Comment by ZhennanQin** [comment]
@lanking520 scala can pass now, but travis failed instead. Shall I re-trigger again? Thanks.

**Comment by ankkhedia** [comment]
@ZhennanQin Thanks for retriggering the build. Travis build is not a blocker currently for merging the PR if they are approved.

**Comment by ankkhedia** [comment]
Hi @ZhennanQin Travis CI is not blocker for PR merge as I already mentioned in previous comment.
@leezu @anirudhacharya @apeforest  Could you please review the changes?

**Pull request merged**
