### PR TITLE
correct usage of bool arguments from command line

### PR DESCRIPTION
**Pull request by rahul003**
## Description ##
When trying to convert any non empty string to bool, python returns True. 
> bool('False') 
> True

This means if a bool argument (`--shuffle`) has a default value of True, then passing `--shuffle False` will not set it to False. 

Correcting this by converting the string argument given to bool with a custom function. 

This is a fix with minimal change on user's end. Alternative (and the proper way) would be `--shuffle` and `--no-shuffle`. But that would require significant changes to the examples.

### Essentials ###
- [x] Passed code style checking (`make lint`)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] For user-facing API changes, API doc string has been updated. For new C++ functions in header files, their functionalities and arguments are well-documented. 
- [x] To my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
- Refer description above
- Fixes issues people have raised like https://github.com/apache/incubator-mxnet/issues/8875

### CODE REVIEW

**Comment by piiswrong** [comment]
I think the right way to do this is to use action=store_true

**Comment by rahul003** [comment]
Updated

**Comment by rahul003** [comment]
Rebased

**Comment by rahul003** [comment]
Looks good to go in, right?

**Comment by rahul003** [comment]
Rebased with master now

**Comment by larroy** [comment]
https://github.com/apache/incubator-mxnet/pull/9457/commits/decb09751ea57ae873830ba165a2b16cb5b49dbe

**Comment by rahul003** [comment]
Thanks, I hadn't checked the docs!

**Comment by larroy** [comment]
@rahul003 did we by chance make the same change or you saw my PR first?

**Comment by rahul003** [comment]
Coincidence! I hadn't seen your PR for this

**Comment by sunyonggang** [comment]
Oh😕, it's my first time to use im2rec.py to get like this:
```
python ~/incubator-mxnet/tools/im2rec.py --list True --recursive True t_sss train/
usage: im2rec.py [-h] [--list] [--exts EXTS [EXTS ...]] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive] [--no-shuffle] [--pass-through]
                 [--resize RESIZE] [--center-crop] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label]
                 prefix root
im2rec.py: error: unrecognized arguments: t_sss train/
```
Yes, I should remove 'True', then it can work-- so why don't change the doc?

**Comment by larroy** [comment]
@sunyonggang @piiswrong my change fixes the doc: https://github.com/apache/incubator-mxnet/pull/9457

**Pull request merged**
